### ISSUE TITLE
Support version 16.15.0

### ISSUE THREAD

**Issue by SDAdham** [nexe/nexe#1003]
Hello, can you please support node `v16.15.0` in https://github.com/nexe/nexe/releases/tag/v3.3.3 ?

I need to build the project for linux, windows and mac...

**Comment by vuquanganhnguyen** [comment]
Hi @SDAdham Any update on this ? I have the same question for `v18.18.2`, I do not want to use to --build flag to build from scratch as it seems to take a lot of time to build. Or if someone can explain how to build it ?

**Comment by vuquanganhnguyen** [comment]
Hello @Armanio : Please refer to my anwsers in stackoverflow, hope it helps
https://stackoverflow.com/questions/57879150/how-can-i-solve-error-gypgyp-errerr-find-vsfind-vs-msvs-version-not-set-from-c/78157088#78157088
https://stackoverflow.com/questions/75851339/nexe-not-working-with-node-version-15-8-0/78191558#78191558

**Comment by Armanio** [comment]
@vuquanganhnguyen of course i could build node for any platform by self but what about build matrix like [this](https://github.com/nexe/nexe/releases/tag/v3.3.3)? I need build exe for windows 10/11 on my mac. I doesnt have windows machine. 

I found fork with 18 and 20 node version: https://github.com/bruce-one/nexe/releases or https://github.com/urbdyn/nexe_builds

**Comment by SDAdham** [comment]
Hello everyone,

Here is one https://github.com/microcodez/nexe_builds that includes macOS, windows and Linux. Node 20.10.0 and node 20.9.0.
