### ISSUE TITLE
node is 16.15 is available, but nexe has only 14? 

### ISSUE THREAD

**Issue by wzquyin** [nexe/nexe#1015]
I tired nexe -build ,
got a lot error ,fix one by one ,still can not work ,,,,

help me ,,,,update 16.15

**Comment by calebboyd** [comment]
You can cache your resulting binary and use it as an `asset` for subsequent builds. There is no need to build a node version more than once.

**Comment by fairbairn** [comment]
One of the limitations of this approach, vs having access to updated fixed assets, is the fact that it's harder to build within docker efficiently.  We use node 16 presently within docker builds, and now we're having to build the asset within each environment.  Just would be easier if nexe was up to date.
