### ISSUE TITLE
Support for python 3.11

### ISSUE THREAD

**Issue by collinmyers** [nexe/nexe#1017]
When trying to install to compile on my laptop that I use on the go I had to downgrade to python 3.10 when i was running 3.11

Python 3.11 brings a lot of enhancements, and would be great to be able to use 3.11 when trying to compile with nexe

**Comment by calebboyd** [comment]
I haven't had problems with that. What versions are you trying to build? 

Ref: https://github.com/nodejs/node/blob/main/BUILDING.md#building-nodejs-on-supported-platforms

**Comment by collinmyers** [comment]
> I haven't had problems with that. What versions are you trying to build?
> 
> Ref: https://github.com/nodejs/node/blob/main/BUILDING.md#building-nodejs-on-supported-platforms

Currently trying to build for windows and using node v18

**Comment by NiklasCODES** [comment]
I am also trying to bujild for windows right now. I am using node v19 and python 3.11
