### ISSUE TITLE
How can i ignore a file from being included?

### ISSUE THREAD

**Issue by Default-01** [nexe/nexe#1018]
I wanna ignore my config file from being included into the executable, how can I do this?

**Comment by calebboyd** [comment]
Something like this should work:

```javascript
const ConfigFile = './my-config-file'
const config = require(ConfigFile)
```

**Comment by Default-01** [comment]
sorry, I meant excluded. currently, my config gets included when it shouldn't be.

**Comment by calebboyd** [comment]
Yeah, If you dynamically require (`require(anyVariable)`)  The file at the path in `anyVariable` will NOT be included by nexe.
![CleanShot 2022-11-02 at 09 43 23](https://user-images.githubusercontent.com/5818726/199520211-e7d89e77-ebe2-4235-a4a4-25712d0b8f9b.gif)
