### ISSUE TITLE
platform-embedded-file-writer-aix.obj : error LNK200

### ISSUE THREAD

**Issue by AlphaCharry** [nexe/nexe#1034]
mksnapshot.obj : error LNK2001: An external symbol that cannot be parsed "public: class v8::internal::Object __cdecl v8::internal::FixedArray::get(int
)const " (?get@FixedArray@internal@v8@@QEBA?AVObject@23@H@Z) [C:\Users\Administrator\.nexe\18.12.1\tools\v8_gypfiles\mk
snapshot.vcxproj]
platform-embedded-file-writer-aix.obj : error LNK2001: An external symbol that cannot be parsed "public: class v8::internal::Object __cdecl v8::intern
al::FixedArray::get(int)const " (?get@FixedArray@internal@v8@@QEBA?AVObject@23@H@Z) [C:\Users\Administrator\.nexe\18.12
.1\tools\v8_gypfiles\mksnapshot.vcxproj]
platform-embedded-file-writer-generic.obj : error LNK2001: An external symbol that cannot be parsed "public: class v8::internal::Object __cdecl v8::in
ternal::FixedArray::get(int)const " (?get@FixedArray@internal@v8@@QEBA?AVObject@23@H@Z) [C:\Users\Administrator\.nexe\1
8.12.1\tools\v8_gypfiles\mksnapshot.vcxproj]
platform-embedded-file-writer-mac.obj : error LNK2001: An external symbol that cannot be parsed "public: class v8::internal::Object __cdecl v8::intern
al::FixedArray::get(int)const " (?get@FixedArray@internal@v8@@QEBA?AVObject@23@H@Z) [C:\Users\Administrator\.nexe\18.12
.1\tools\v8_gypfiles\mksnapshot.vcxproj]
platform-embedded-file-writer-win.obj : error LNK2001: An external symbol that cannot be parsed "public: class v8::internal::Object __cdecl v8::intern
al::FixedArray::get(int)const " (?get@FixedArray@internal@v8@@QEBA?AVObject@23@H@Z) [C:\Users\Administrator\.nexe\18.12
.1\tools\v8_gypfiles\mksnapshot.vcxproj]
..\..\out\Release\mksnapshot.exe : fatal error LNK1120: 1 An external symbol that cannot be parsed [C:\Users\Administrator\.nexe\18.12.1\tools\v8_gyp
files\mksnapshot.vcxproj]
√ Compiling Node with arguments: nosign,release,x64
√ Finished in 47.774s

Error: vcbuild.bat nosign release x64 exited with code: 1

**Environment**:
- Platform(OS/Version):Windows11
- Host Node Version:18
- Target Node Version:18
- Nexe version:4.0.0
- Python Version:3.10

**Comment by byyeesh** [comment]
The same problem when compiling
