### ISSUE TITLE
typing mistake maybe

### ISSUE THREAD

**Issue by AgentHackerYT** [nexe/nexe#1035]
Just Viewing The Code and saw a typing mistake file : lib/compiler.js line 140

**Comment by calebboyd** [comment]
Can you provide a link to the source?

**Comment by AgentHackerYT** [comment]
https://www.npmjs.com/package/nexe?activeTab=explore

**Comment by calebboyd** [comment]
I think what you're seeing is a bug in npmjs.com's syntax highlighting (currently in beta).
