### ISSUE TITLE
Failing when spaces in directory path.

### ISSUE THREAD

**Issue by wavded** [nexe/nexe#106]
Thanks for lib.  Found a quirk w/ patch resolution:

```
make[1]: *** No rule to make target `../%.c', needed by `/var/lib/jenkins/jobs/Extra'.  Stop.
```

The job is actually called `Extra ITG Proxy`.  When I renamed without spaces it worked.

Here was the command I ran:

``` sh
nexe -i index.js -o dist/proxy -r 0.10.37
```

**Comment by RainbowDashDC** [comment]
Will look into. Not sure what's causing it as of right now though.

**Comment by calebboyd** [comment]
Fixed in `nexe@beta`
