### ISSUE TITLE
Using NEXE with NodeJS v20?

### ISSUE THREAD

**Issue by bnbowman** [nexe/nexe#1071]
**What happened**:
When I tried to update my NEXE build from Node v18 to Node v20, NEXE stopped producing a binary of my code and started producing a binary of what appears to be just the Node binary/executable.

**What you expected to happen**:
I expected NEXE to work with Node v20 just like it did Node v18

**How to reproduce it (as minimally and precisely as possible)**:
Compile any project with Node v18, then upgrade to v20.

**Environment**:
- Platform(OS/Version): Multiple - MaxOSX + Linux EL8
- Host Node Version: v20.9.0
- Target Node Version: v20.9.0
- Nexe version: v4.0.0-rc2
- Python Version: 2.7.18

**Comment by bruce-one** [comment]
It can be done - you need to use the latest Git commit of nexe, and use the `build` flag :-)

**Comment by calebboyd** [comment]
Added updated packages to npm!
- `nexe@latest` has v20 support and is tracking [v4](https://github.com/nexe/nexe/tree/v4) branch
- `nexe@next` is tracking master
