### ISSUE TITLE
Meet 'ReferenceError: file is not defined' after build from source

### ISSUE THREAD

**Issue by RogerKang** [nexe/nexe#1075]
**What happened**:
I use nexe@4.0.0-rc.3 to build an executable binary using below command:
`nexe -t linux-x64-16.20.2 --build --make='-j4' -i hello.js`
Then run the generated binary:
`./hello`
It throw an error:
```
node:internal/bootstrap/pre_execution:31
{{ file("lib/fs/bootstrap.js") }}
   ^

ReferenceError: file is not defined
    at prepareMainThreadExecution (node:internal/bootstrap/pre_execution:31:4)
    at node:internal/main/run_main_module:9:1
```

**What you expected to happen**:
It should be succeed to run the binary.

**How to reproduce it (as minimally and precisely as possible)**:
Just run:
```
npm i -g nexe@4.0.0-rc.3
echo 'console.log("hello")' >> hello.js
nexe -t linux-x64-16.20.2 --build --make='-j4' -i hello.js
./hello
```

Ref: I build my build env according to nodejs build env document for node 16.x in docker image centos:7
https://github.com/nodejs/node/blob/v16.x/BUILDING.md
```
FROM centos:7
RUN yum install -y centos-release-scl
RUN yum install -y devtoolset-8
RUN scl enable devtoolset-8 bash
RUN yum install -y python3
RUN ln -s -f /usr/bin/python3 /usr/bin/python
```

**Anything else we need to know?**:
I suppose this issue is related to this part:
https://github.com/nexe/nexe/blob/master/src/patches/third-party-main.ts#L62
that where is the definition of file function on this line: `"'use strict';\n" + '{{ file("lib/fs/bootstrap.js") }}' + '\n'` ?

**Environment**:
- Platform(OS/Version): Centos 7
- Host Node Version: v16.20.2
- Target Node Version: v16.20.2
- Nexe version: 4.0.0-rc.3
- Python Version: 3.6.8

**Comment by calebboyd** [comment]
There was a bad rebase - A new version has been published!
