### ISSUE TITLE
Error: Cannot find module 'node:util'

### ISSUE THREAD

**Issue by ringo360** [nexe/nexe#1095]
**What happened**:

I created exe file using `nexe index.js --target windows-x64-14.15.3`. but when I run it, I get the following error:
```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'node:util'
Require stack:
- C:\Users\GPTP3\GitHub\test-uwu\node_modules\consola\dist\shared\consola.deac7d5a.cjs
- C:\Users\GPTP3\GitHub\test-uwu\node_modules\consola\dist\shared\consola.4bbae468.cjs
- C:\Users\GPTP3\GitHub\test-uwu\node_modules\consola\dist\index.cjs
- C:\Users\GPTP3\GitHub\test-uwu\node_modules\consola\lib\index.cjs
- C:\Users\GPTP3\GitHub\test-uwu\src\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\GPTP3\GitHub\test-uwu\node_modules\consola\dist\shared\consola.deac7d5a.cjs:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\GPTP3\\GitHub\\test-uwu\\node_modules\\consola\\dist\\shared\\consola.deac7d5a.cjs',
    'C:\\Users\\GPTP3\\GitHub\\test-uwu\\node_modules\\consola\\dist\\shared\\consola.4bbae468.cjs',
    'C:\\Users\\GPTP3\\GitHub\\test-uwu\\node_modules\\consola\\dist\\index.cjs',
    'C:\\Users\\GPTP3\\GitHub\\test-uwu\\node_modules\\consola\\lib\\index.cjs',
    'C:\\Users\\GPTP3\\GitHub\\test-uwu\\src\\index.js'
  ]
}
```

**What you expected to happen**:
Everything must work perfectly

**How to reproduce it (as minimally and precisely as possible)**:
1. Write code:
```ts
//index.ts
import { consola } from 'consola';

async function main() {
	let urname = await consola.prompt('What is your name?', {
		placeholder: 'John',
	});
	if (!urname) urname = 'John';
	consola.box(`Hello, ${urname}!`);
}

consola.info(`Hello Sekai!`);
main();
```
2. do `tsc index.ts`
3. do `nexe index.js --target windows-x64-14.15.3`
4. open generated exe file
5. you can see error log

**Anything else we need to know?**:

*nothing*

**Environment**:
- Platform(OS/Version): Windows 11 (AtlasOS v0.4.0)
- Host Node Version: v21.2.0
- Target Node Version: v21.2.0
- Nexe version: 4.0.0-rc.6
- Python Version: Not installed

**Comment by ringo360** [comment]
Nah, I can't find any solution 😢 
Probably, consola depends on `node:utils`.

**Comment by mikoto2000** [comment]
@ringo360 

The library's source code needs to be bundled, including its dependencies, into a single JavaScript file.

Example by esbuild:

```sh
esbuild index.ts --bundle --minify --platform=node --target=node14.17.0 --outdir=dist
nexe dist/index.js --target windows-x64-14.15.3
```

**Comment by ringo360** [comment]
Thanks, I'll try that!

**Comment by ringo360** [comment]
It works! thank you @mikoto2000 🩵

**Comment by bilgofall21** [comment]
Bonjour je suis confronté au meme problème sur un Mac avec val version 14.14.0 de node

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'node:util'
Require stack:
- /Users/admin/Documents/caramigo/app-ucm/node_modules/@nuxt/utils/node_modules/consola/dist/shared/consola.deac7d5a.cjs
- /Users/admin/Documents/caramigo/app-ucm/node_modules/@nuxt/utils/node_modules/consola/dist/shared/consola.4bbae468.cjs
- /Users/admin/Documents/caramigo/app-ucm/node_modules/@nuxt/utils/node_modules/consola/dist/index.cjs
- /Users/admin/Documents/caramigo/app-ucm/node_modules/@nuxt/utils/node_modules/consola/lib/index.cjs
- /Users/admin/Documents/caramigo/app-ucm/node_modules/@nuxt/utils/dist/utils.js
- /Users/admin/Documents/caramigo/app-ucm/node_modules/@nuxt/cli/dist/cli-index.js
- /Users/admin/Documents/caramigo/app-ucm/node_modules/@nuxt/cli/dist/cli.js
- /Users/admin/Documents/caramigo/app-ucm/node_modules/nuxt/bin/nuxt.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/admin/Documents/caramigo/app-ucm/node_modules/@nuxt/utils/node_modules/consola/dist/shared/consola.deac7d5a.cjs:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/admin/Documents/caramigo/app-ucm/node_modules/@nuxt/utils/node_modules/consola/dist/shared/consola.deac7d5a.cjs',
    '/Users/admin/Documents/caramigo/app-ucm/node_modules/@nuxt/utils/node_modules/consola/dist/shared/consola.4bbae468.cjs',
    '/Users/admin/Documents/caramigo/app-ucm/node_modules/@nuxt/utils/node_modules/consola/dist/index.cjs',
    '/Users/admin/Documents/caramigo/app-ucm/node_modules/@nuxt/utils/node_modules/consola/lib/index.cjs',
    '/Users/admin/Documents/caramigo/app-ucm/node_modules/@nuxt/utils/dist/utils.js',
    '/Users/admin/Documents/caramigo/app-ucm/node_modules/@nuxt/cli/dist/cli-index.js',
    '/Users/admin/Documents/caramigo/app-ucm/node_modules/@nuxt/cli/dist/cli.js',
    '/Users/admin/Documents/caramigo/app-ucm/node_modules/nuxt/bin/nuxt.js'
  ]
}

**Comment by bilgofall21** [comment]
qui peut m'aider

**Comment by mikoto2000** [comment]
@bilgofall21 
Je pourrai peut-être vous aider si vous me dites spécifiquement quel projet vous essayez de traiter avec nexe.

**Comment by mikoto2000** [comment]
@bilgofall21 
I tried build nuxtjs get started application.(https://nuxt.com/docs/getting-started/introduction)

```sh
# build nuxt application
npm run build
# -> output build result to `.output/server/index.mjs`

# bundle and minify by esbuild
npx esbuild .output/server/index.mjs --bundle --minify --platform=node --target=node14.17.0 --outdir=dist
# -> output bundled js file to `dist/index.js`

# build single binary by nexe
npx nexe -i dist/index.js -o firststep --target windows-x64-14.15.3
# -> output windows binary to `./firststep.exe`
```

if you need newly Node.js, then add `-b` option(but first time build is tooooo long build time...)

```sh
npx nexe -i dist/index.js -o firststep -b --target windows-x64-22.13.1
```

For more complex applications, this may result in build errors, but it appears that minimal applications can be built using this procedure.

See: 

- https://github.com/nexe/nexe/issues/1094#issuecomment-2155195784
- https://github.com/nexe/nexe/issues/1094#issuecomment-2285506171
