### ISSUE TITLE
Error while using the mailparser (depends on iconv-lite)

### ISSUE THREAD

**Issue by shivamadhavan** [nexe/nexe#113]
The compilation using nexe goes without any errors. However, the error below is shown upon executing the binary. 

The line shown in the error is from the iconv-lite library which is used by encoding and in turn by mailparser. You can browser the source from iconv-lite repo or from https://github.com/shivamadhavan/nexe-compat-testing/blob/master/mailparser/node_modules/mailparser/node_modules/encoding/node_modules/iconv-lite/lib/index.js

What would be the best solution for this problem, if is not something that can handled currently by nexe ?
## Error trace

``` js
nexe.js:1787
        require("./streams")(iconv);
                            ^
TypeError: object is not a function
    at Array.call.G:\work\node\nexe-compat\mailparser\node_modules\mailparser\node_modules\encoding\node_modules\iconv-lite\lib\index.js../extend-node (nexe.js:1787:29)
    at initModule (nexe.js:29:11)
    at nexe.js:31:64
    at Array.call.G:\work\node\nexe-compat\mailparser\node_modules\mailparser\node_modules\encoding\lib\encoding.js.iconv-lite (nexe.js:1554:17)
    at initModule (nexe.js:29:11)
    at nexe.js:31:64
    at Array.call.G:\work\node\nexe-compat\mailparser\node_modules\mailparser\node_modules\mimelib\lib\mimelib.js.addressparser (nexe.js:5034:15)
    at initModule (nexe.js:29:11)
    at nexe.js:31:64
    at Array.call.G:\work\node\nexe-compat\mailparser\node_modules\mailparser\node_modules\mimelib\index.js../lib/content-types (nexe.js:5029:18)
```

**Comment by RainbowDashDC** [comment]
Hm, interesting, will look into this.

**Comment by shivamadhavan** [comment]
The following changes (https://github.com/shivamadhavan/nexe-compat-testing/commit/49540ff9987122fc22b803e038a11b022b1c8b9a) to iconv-lite itself fixes the problem. However, for obvious reasons, I would much rather prefer a solution that involved handling this in nexe than change iconv-lite.

**Comment by shivamadhavan** [comment]
The issue seems to be because browser-resolve (https://github.com/defunctzombie/node-browser-resolve) used by module-deps, seems to ignore any file(or package package) specified within the browser field in package.json. 

The temporary workaround I am using at the moment is this 
https://github.com/shivamadhavan/nexe-compat-testing/commit/cac1f5bf66124e45cf25518ed16266f252d71fd4.

Removing those 2 lines as in the above commit from package.json fixes the issue.

However, a better solution could be;

1. nexe allowing the use of packageFilter option while invoking module-deps  when needed for node environments
2. the packageFilter function could then modify the browser field in package.json
3. if the broeser field is not present browser-resolve won't ignore these files

Suggestions welcome.
Thanks.

**Comment by RainbowDashDC** [comment]
I think we'll end up forking `browser-resolve` and use a custom version of it as development on it is slow.

**Comment by jaredallard** [comment]
Have you tried `nexe@1`?

**Comment by calebboyd** [comment]
This should be fixed in v2. If it is not please open a new issue
