### ISSUE TITLE
ability to embed native modules

### ISSUE THREAD

**Issue by crcn** [nexe/nexe#15]
perhaps compiling node.js modules, and copying the .node files into the node_modules directory.

**Comment by RainbowDashDC** [comment]
Update on this, this is currently being worked on.

**Comment by RainbowDashDC** [comment]
Going to start using this as an area for progress and if anyone wants to contrib on this:

Using http://www.jedi.be/blog/2013/05/14/Compiling%20-%20packaging%20a%20nodejs%20project%20as%20a%20single%20binary/ for the method, the work that needs to be done is finding an automatic method.

binding.gyp: `sources` array contains any relevant CC that would be used.

**Comment by jedi4ever** [comment]
iirc the problem automating it , is that you sometimes have to rename the functions init to make not conflicting. I abondonned this method in favor of packing local compiled versions and correctly set the ld_librarypaths . See the npm of bashpack /jedi4ever. I creates self executable bash archives.

**Comment by RainbowDashDC** [comment]
Sadly that's not a cross-platform solution. I'm going to keep trying this method because it's imo the most expandable one and very cross platform.

**Comment by jedi4ever** [comment]
related - http://jxcore.com/turn-node-applications-into-executables/

**Comment by jedi4ever** [comment]
and lastly - nar - https://www.npmjs.com/package/nar

**Comment by RainbowDashDC** [comment]
This is being worked on in the branch `native-modules`, and all of the relevant work shall be there.

**Comment by marcominetti** [comment]
:+1:

**Comment by tonytcb** [comment]
@jedi4ever The nar module works perfectly for this. Thanks.

**Comment by dekarguy** [comment]
I can't seem to find the `native-modules` branch, and nar doesn't support windows environments

**Comment by zhzehong** [comment]
where is the native-modules branch, @jedi4ever

**Comment by jaredallard** [comment]
@zhzehong Hi! I'm the guy who was going to be working on that. Native modules are a varried system, in terms of bundling, so it's a last todo. Anyone is free to attempt to work on that. Currently I'm working on removing the filesystem limitations, but at the speed of a "volunteer" due to being both in school, and working.

**Comment by calebboyd** [comment]
@jaredallard What can we do to help here?

**Comment by calebboyd** [comment]
this is initially working. windows example: examples/native-build

**Comment by fmoo** [comment]
examples/native-build was mentioned, but this file no longer exists.  The main README.md has a TODO on documentation.

Any links to recent docs or examples of how to use native modules?

**Comment by ashleydavis** [comment]
I'm interested in this as well. I've tried including a native module in a Nexe build and it doesn't seem to work.

**Comment by lrNas** [comment]
examples/native-build no loger exists on main. It was removed?
