### ISSUE TITLE
proxy error when downloading node framework

### ISSUE THREAD

**Issue by dafyddPrys** [nexe/nexe#160]
Is there a way to configure proxy settings for when I try and run this? I currently get an error when I run 

```
nexe -i app.js 
```

I get:

```
stream.js:74
throw er; //Unhandled stream error in pipe.

Error: connect ECONNREFUSED xxx.xx.xx.xx.443
at Object.exports._errnoException (util.js:849:11)
at exports._exceptionWithHostPort (util.js:872:20)
at TCPConnectWrap.afterConnect [as oncomplete] (new.js:1060:14)
```

Seems like it can't get out from behind my proxy. Can I use npm's proxy settings somehow or configure my own for this?

**Comment by jaredallard** [comment]
Yes, thanks to request. However, there is no command line way so far. Either; edit it or wait until I can implement it :) What type of proxy are we looking at? HTTP, HTTPS, SOCKSvX?

**Comment by jingovimes** [comment]
Ok! I have http and https proxies. I may have a look next week. Will it recognise it if the nodejs framework is already downloaded and placed in the file or does it always fetch it itself?

**Comment by jaredallard** [comment]
It will recognize the already downloaded node framework as long as you don't change the tmp variable

**Comment by calebboyd** [comment]
[downloadOptions](https://www.npmjs.com/package/download) can be passed in `nexe@beta`

**Comment by babuilyas** [comment]
> [downloadOptions](https://www.npmjs.com/package/download) can be passed in `nexe@beta`

i'm new to nexe and node, counting fingers how to do this!
