### ISSUE TITLE
Error no such native module

### ISSUE THREAD

**Issue by tresdin** [nexe/nexe#173]
I got this error when I run the compiled binary of my app.

```
node.js:932
      throw new Error('No such native module ' + id);
      ^

Error: No such native module /home/project/master/config/AppModules.master
    at NativeModule.require (node.js:932:13)
    at s (nexe.js:1:176)
    at nexe.js:1:367
    at Object.<anonymous> (nexe.js:122:1)
    at Object.__dirname.1.exports.include.cb2.watch.watch.cb2.getFiles.getFiles.fs.readdir.then.files.2.3.../Recursion (nexe.js:131:4)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.1.exports.include.cb2.watch.watch.cb2.getFiles.getFiles.fs.readdir.then.files.2.require.initialise.then.catch../master/Builder.master (nexe.js:100:2)
    at s (nexe.js:1:316)
    at e (nexe.js:1:487)
```

Here is the line in **/home/project/master/config/Builder.master** that produces the above error.

```
require(__dirname+'/config/AppModules.master.server');
```

I've rechecked the path and it is correct. I'm not sure about the reason behind this crash.

**Comment by jaredallard** [comment]
Can you give me some info about AppModules.master.server? What is it? Native module, js file, directory, json file?

**Comment by tresdin** [comment]
@jaredallard It contains a single line. No more, no less.
```
Object.defineProperty(global,'Project',{value : {}});
```

**Comment by tresdin** [comment]
@jaredallard FWIW, those files are executed in master's context, not the worker's one. And I think it might be related to this error.

**Comment by jaredallard** [comment]
Sorry to ask this, but I don't think I'll be able to solve this without the entire environment. If you can't provide that, understandable, I'll try other things! Thanks for your contributions so far though!

**Comment by jaredallard** [comment]
Aha! Confirmed reproduced!

**Comment by jaredallard** [comment]
Okay, so, using `./` instead of `_dirname` works. I'll look into why using dirname doesn't.

**Comment by jaredallard** [comment]
For some reason using `_dirname` really screws [browserify] up.

**Comment by tresdin** [comment]
Either way, it's just a work around. IMHO, `nexe` should provide an official method for preloading app's modules. I think using another flag would be fine. 
```
//load modules inside folder '/home/project/view'
modules : 'home/project/view'

//recursively load all modules inside folder '/home/project/view' and '/home/project/controller'
modules : ['/home/project/view/**','/home/project/controller/**']
```
About native nodejs modules, there is no reason to load them dynamically.

**Comment by CKarper** [comment]
Interesting thought.   Could probably do something with this idea.

**Comment by jaredallard** [comment]
@ckarper if you're up for it, assign yourself and I'll focus on other stuff! Actual native modules is my thing ATM and `--jsflags` command line opt, then finally working with the virtual fs layer you worked. In between semesters at the moment so my contribution "streak" is dampened.

**Comment by jaredallard** [comment]
So I was working on trying to get sourceMaps support as browserify can generate them, and I ran into how to get 'static' preloading of modules with browserify. It's as simple as adding it to .require of the browserify bundling API stage. Since source maps are iffy at the moment, I'll switch gears into making this possible!

**Comment by VLmja** [comment]
The new approach looks to be leaving Edge.js integration behind which worked before.  Using: 
var edgeNode = '../native/win32/ia32/4.1.1/edge.node';
var edge = require('bindings')(edgeNode);
Shows the full correct path in the error but still has runtime error of 'No such native module ' as does the formerly sufficient:
var edge = require('edge');
Edge.js is very useful for those of us working Windows integrations!

**Comment by mbroadst** [comment]
@jaredallard here is an example gist of an app structure that will result in this error being thrown: https://gist.github.com/mbroadst/f95baec0fbb6bec84806
