### ISSUE TITLE
Express 4 and body-parser module error

### ISSUE THREAD

**Issue by deguich** [nexe/nexe#177]
Hi,

This error always occur with fresh express project that use body-parser module middleware :

```
node.js:932
      throw new Error('No such native module ' + id);
      ^

Error: No such native module ...\node_modules\body-parser\lib\types\json.js
    at NativeModule.require (node.js:932:13)
    at s (nexe.js:1:176)
    at nexe.js:1:367
    at Function.load (nexe.js:207:18)
    at Object.<anonymous> (nexe.js:18:19)
    at Object.__dirname.1../routes/index (nexe.js:59:4)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.2.../app (nexe.js:67:11)
    at s (nexe.js:1:316)
```

Probably because of that part of body-parser code :

```
var parsersDir = path.join(__dirname, 'lib', 'types')

/**
 * Auto-load bundled parsers with getters.
 */

fs.readdirSync(parsersDir).forEach(function onfilename(filename) {
  if (!/\.js$/.test(filename)) return

  var loc = path.resolve(parsersDir, filename)
  var mod
  var name = path.basename(filename, '.js')

  function load() {
    if (mod) {
      return mod
    }

    return mod = require(loc)
  }

  Object.defineProperty(exports, name, {
    configurable: true,
    enumerable: true,
    get: load
  })
})
```

I try to add this code in index.js of body-parser but I still have the error :

```
var dummyToForceIncludeForBundle = false;
if (dummyToForceIncludeForBundle) {
    require("./lib/types/json.js");
    require("./lib/types/raw.js");
    require("./lib/types/text.js");
    require("./lib/types/urlencoded.js");
}
```

**Comment by jaredallard** [comment]
This is an issue with _dirname and browserify currently. I'm not sure how to solve it as of now.

**Comment by deguich** [comment]
Hi, It works with this very bad solution :
Add the "dummyToForceIncludeForBundle  ..." part to include the 4 js in nexe.js
and comment :
//var loc = path.resolve(parsersDir, filename)

Replace by :
var loc = "./lib/types/"+name+".js"


Next, I had a "require jade" error. I added this in "node_modules/express/lib/view.js" :
```
var dummyToForceIncludeForBundle = false;
if (dummyToForceIncludeForBundle) {
	require("jade");
} 
```

**Comment by jaredallard** [comment]
What I'm thinking of is a way to determine what is needed to be required dynamically, by evaluating require statements to a basic degree (match vars with local directories and take an include * approach to it).

However it seems like it could be complicated. I'll look into what might work.

**Comment by CKarper** [comment]
Look at ternjs/acorn.  You can build an AST, then walk it to figure out
what context you need.   It *is* complicated, but pretty thorough.   You
can at least identify which require statements you are going to exclude,
and why...

**Comment by calebboyd** [comment]
This has been resolved in the express stack

https://github.com/expressjs/body-parser/blob/master/index.js#L139
