### ISSUE TITLE
No such native module with winstonjs/winston

### ISSUE THREAD

**Issue by pinodex** [nexe/nexe#178]
I get this error when I run the compiled application.

```
nexe.js:1129
    var doParallelLimit = function(limit, fn) {
                            ^

Error: No such native module ./transports/console
    at NativeModule.require (node.js:932:13)
    at s (nexe.js:1:176)
    at nexe.js:1:367
    at Object.Console (nexe.js:66028:12)
    at new exports.Container (nexe.js:65162:29)
    at Object.__dirname.259../winston/common (nexe.js:64514:19)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.175.events (nexe.js:47558:15)
    at s (nexe.js:1:316)
```

The file that might be triggering the error is https://github.com/winstonjs/winston/blob/0.8.3/lib/winston/transports.js#L32

I tried the following to workaround the dynamic requires:

In the file where I call `nexe.compile()`, I added a code before that to create a file on the same directory as `transports.js`. The file contains:

```
require('./transports/console');
require('./transports/daily-rotate-file');
require('./transports/file');
require('./transports/http');
require('./transports/memory');
require('./transports/transport');
require('./transports/webhook');
```

Then that file is _required_ at my main file:

```
var _nexeDynamicBundle = false;

if (_nexeDynamicBundle) {
  require('winston/lib/winston/nexe-bundle');
}
```

And also, the generated binary file contains the _required_ files as what I saw in `output.exe/.rdata`:

```
},{"./common":260,"fs":undefined,"path":undefined}],270:[function(require,module,exports){
/*
 * console.js: Transport for outputting to the console
 *
 * (C) 2010 Charlie Robbins
 * MIT LICENCE
 *
 */
```

```
},{"./transports/console":270,"./transports/daily-rotate-file":271,"./transports/file":272,"./transports/http":273,"./transports/memory":274,"./transports/transport":275,"./transports/webhook":276}],269:[function(require,module,exports){
```

Any idea why the error occurs?

**Comment by jaredallard** [comment]
Hi! This is a common issue at the moment, I'd revert to `0.4.7` and see if that solves your problem for now-- if not, then you'll have to wait!

Browserify has some kinks at the moment, and solves some other ones. It's a bit off a difficult setup at the moment.

**Comment by jaredallard** [comment]
I'd have a go at `master` and see if the new package.json options:

```js
browserify.exclude
browserify.requires
browserify.paths
```

and see if any of those help you, specifically paths. (adds the the lookup array for require.resolve)

**Comment by gbaumgart** [comment]
got this too, winston is lazy loading its transport modules later. I usually fix this by placing such modules beside the binary in node_modules.

**Comment by Kurtas** [comment]
Same problem even I'm using ```master```
```
Cannot find module 'hiredis' from '/home/user/discovery/node_modules/ioredis/lib/parsers'
````
my package.json setting 
````
  "nexe": {
    "browserify": {
        "requires": [],
        "excludes": ["hiredis"],
        "paths": []
    }
  },
```
When I tried to use nexe verison ```0.4.1``` then it is compiled ok, but bin doesn't work (same problem as above with winston transports which are lazy loaded)
```
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/home/user/discovery/transports'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Array.__dirname.call./home/user/discovery/node_modules/winston/lib/winston/transports.js.fs (nexe.js:37081:4)
    at initModule (nexe.js:29:11)
    at nexe.js:31:64
    at Array.__dirname.call./home/user/discovery/node_modules/winston/lib/winston.js../winston/transports/transport (nexe.js:7851:22)
    at initModule (nexe.js:29:11)
    at nexe.js:31:64
    at Object.e.__esModule.default (nexe.js:47:3355)
    at t (nexe.js:47:107)
```

What about switch browserify to webpack, as I know webpack can handle a lazy loading modules.

**Comment by jaredallard** [comment]
I'll look into webpack!

**Comment by jaredallard** [comment]
@Kurtas I've been looking into webpack. It works for most of the tests, but for big projects it doesn't seem to work. Specifically express (test/express-test).

If it's just my configuration then please try it out and see if you can figure anything out, thanks!

```js
module.exports = {
    context: __dirname,
    target: 'node',
    entry: "./bin/www", //entry point
    exclude: ["fs", "net"],
    module: {
        loaders: [
            {
                test: /\.json$/,
                loader: "json-loader" 
            }
        ]
    }
}
```

**Comment by calvin** [comment]
@gbaumgart Can you elaborate your comment? What do you mean by:

>  I usually fix this by placing such modules beside the binary in node_modules.

**Comment by gbaumgart** [comment]
it means you can't really embed it, at least with the more safe 0.4.1 version. So that means you will have to deploy winston separate:

app\
app\myexe.exe
app\node_modules\
app\node_modules\winston

make sure you're installing those modules with npm3 otherwise you may run into path length limits on windows.

**Comment by gbaumgart** [comment]
@calvin you can also write a little script to get the dependencies of packages like winston and then embed those. that keeps your deployed node_modules folder quit small

**Comment by calvin** [comment]
@gbaumgart Thanks for your comments. I ended up writing a workaround which loads required transport files statically.

**Comment by thekiba** [comment]
@calvin Hello, i have a same issue. Can you talk about your solution?

**Comment by calvin** [comment]
@thekiba It was done in a quick-and-dirty manner hence not fully tested. 

https://gist.github.com/calvin/f72be59338ccbaefb5f9617d33fe2e3a

**Comment by thekiba** [comment]
@calvin aha, i see. So i found another solution. Check issue #243

**Comment by syarul** [comment]
@calvin  how do I use your transport.js?

**Comment by pofider** [comment]
The issue disappeared for me after upgrading to the latest winston.

**Comment by mreid-tt** [comment]
I ran a test of Jellyseerr v2.0.1 (https://github.com/SynoCommunity/spksrc/pull/6294) and I think I'm encountering a similar issue. The build completed successfully but when I try to run the package I get this:

```
$ ./jellyseerr 
node:internal/modules/cjs/loader:1250
  throw err;
  ^

Error: Cannot find module 'logform'
Require stack:
- /home/mreid/Documents/jellyseerr/node_modules/winston/lib/winston.js
- /home/mreid/Documents/jellyseerr/dist/logger.js
- /home/mreid/Documents/jellyseerr/dist/lib/settings/migrator.js
- /home/mreid/Documents/jellyseerr/dist/lib/settings/index.js
- /home/mreid/Documents/jellyseerr/dist/api/plexapi.js
- /home/mreid/Documents/jellyseerr/dist/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1247:15)
    at Module._load (node:internal/modules/cjs/loader:1073:27)
    at Module.require (node:internal/modules/cjs/loader:1333:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/mreid/Documents/jellyseerr/node_modules/winston/lib/winston.js:10:17)
    at Module._compile (node:internal/modules/cjs/loader:1491:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1570:10)
    at Module.load (node:internal/modules/cjs/loader:1310:32)
    at Module._load (node:internal/modules/cjs/loader:1126:12)
    at Module.require (node:internal/modules/cjs/loader:1333:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/mreid/Documents/jellyseerr/node_modules/winston/lib/winston.js',
    '/home/mreid/Documents/jellyseerr/dist/logger.js',
    '/home/mreid/Documents/jellyseerr/dist/lib/settings/migrator.js',
    '/home/mreid/Documents/jellyseerr/dist/lib/settings/index.js',
    '/home/mreid/Documents/jellyseerr/dist/api/plexapi.js',
    '/home/mreid/Documents/jellyseerr/dist/index.js'
  ]
}

Node.js v20.18.0
```
Any thoughts on resolving this?
