### ISSUE TITLE
Fails on requirejs projects

### ISSUE THREAD

**Issue by brollb** [nexe/nexe#183]
If the project uses requirejs, nexe fails to run and gives the error:

```
Cannot find module './process' from ...
```

It looks like nexe is currently incompatible with the build format of requires.

**Comment by jaredallard** [comment]
Browserify isn't perfect right now. Try using 0.x.x until I can implement fixes. I feel like I may have pushed this to soon.

**Comment by jaredallard** [comment]
Try the master branch, utilizing #188's new package.json method.

**Comment by gbaumgart** [comment]
+10
nothing works anymore with 1.0 release

**Comment by gbaumgart** [comment]
or can we disable browserify entirely ?

**Comment by calebboyd** [comment]
2.0 allows providing own bundle
