### ISSUE TITLE
Configure browserify optional dependencies.

### ISSUE THREAD

**Issue by jeff-blaisdell** [nexe/nexe#184]
I'm trying to build a CLI that leverages [chokidar](https://github.com/paulmillr/chokidar) for file watching.  Chokidar uses an optional require on fsevents that will not resolve on a Windows build.  By default Browserify will fail when it can't resolve a dependency, even if it is optional.  To get around this Browserify provides a couple different configuration options.

This may already exist, and I'm not seeing it; but is there a way to pass configuration options to Nexe's browserify instance?

I did some poking, and I think I could allow for these options to be passed through the nexe options down to the browserify bundler.  If this would be helpful; I'd be happy to make a PR.

**Comment by jaredallard** [comment]
I'll add something like this as soon as I can!

**Comment by jeff-blaisdell** [comment]
I made a PR for a simplistic method of just passing the excludes via options through compile down to browserify.  If you're looking to do something more elegant, feel free to close it.  Just thought I'd get something out for anyone else that might run into the issue until the real fix can be patched.  Made a tag on my for based on the PR for people to use if need be.
```
"nexe": "git@github.com:jeff-blaisdell/nexe.git#1.1.0-browserify"
```

**Comment by jaredallard** [comment]
It's not the most elegant thing but it works for now! Thanks! (nexe has no claim to elegance either, it's still in an odd state of my code style and @/crcn's from when he ran the project)

**Comment by JoelDapello** [comment]
sorry this is maybe a noob question but I'm having this exact issue.. How do I use this workaround?

**Comment by jaredallard** [comment]
@JoelDapello 

By using the package.json method of utilizing nexe!

i.e

```json
{
   "nexe": {
      "browserify": {
         "exclude": ["moduletoexclude"]
       }
   }
}
```

**Comment by JoelDapello** [comment]
ah! that was easy. thanks so much!

**Comment by incism** [comment]
Hello,
While using nexe to build an app, I get the error excerpted below.

----> executing browserify via API
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Cannot find module '../build/Release/canvas' from '/home/dev/app/node_modules/canvas/lib'
    at /usr/local/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/usr/local/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

The canvas module is being referenced by jsdom-- the application does not use the module directly. So I configured package.json file as follows:
"browserify": {
      "requires": [],
      "excludes": ["canvas"],
      "includes": [],
      "paths": []
    },
But that didn't help. Can someone help? Thanks

**Comment by calebboyd** [comment]
This issue is resolved with bundling configuration.

**Comment by calebboyd** [comment]
@incism see the native-build project in examples. and try `nexe@beta`
