### ISSUE TITLE
0.4.2 branch

### ISSUE THREAD

**Issue by sberan** [nexe/nexe#189]
The current version is completely broken for us, and 0.4.2 is the current version we are using. Is there a way we can create a branch for the 0.4.2 codeline until master is fully baked? It appears to be only in NPM right now.

**Comment by jaredallard** [comment]
https://github.com/jaredallard/nexe/commit/5dc698be9d674cd48bb4f87e5cae98272275989a is for 0.4.1 and might work until I get that working. Yea, I really regret pushing this into main. Should've held it in a branch for awhile (which I did, browserify for awhile, but not much input was given making it seem to be working)

If that doesn't work for you, I'll throw it on a branch. Tagging 0.4.2 in NPM should work for projects utilizing it.

**Comment by calebboyd** [comment]
0.4.2 is available in NPM but it doesn't have git history (very strange...) We built on 0.4.1 [here](https://github.com/telepharm/nexe/commit/75f0b809c1b8d2768d7d0bc18f8eb0e66d4d7145) based on the diff from NPM. If you want to create a new branch for 0.X.X. We can add a PR for that.

**Comment by jaredallard** [comment]
@calebboyd I'll do that right now, I'm actually working on looking at some of these bugs right now and might as well as create a 0.4.2 branch. Thinking about backporting the new build processes I added and removing browserify for now. To many issues, would be better to work on it on another branch for the time being.
