### ISSUE TITLE
Change the node's target_architecture to x64

### ISSUE THREAD

**Issue by nickich** [nexe/nexe#195]
I couldn't find a way to change the target_architecture to x64. It always builds node with 'ia32'.
What is the right way of setting it?

**Comment by nickich** [comment]
...it looks hardcoded in exe.js. Fo Win it is:
`
var vcbuild = spawn("vcbuild.bat", ["nosign", "release"], {
						cwd: dir,
						env: newEnv
					});
`

**Comment by jaredallard** [comment]
It's changable in the node.gyp. Aside from that I'll make the build opts in vc changeable.

**Comment by nickich** [comment]
Thanks.
For now as I need x64 Win always, I just modified the exe.js line to:
var vcbuild = spawn("vcbuild.bat", ["nosign", "release", "x64"], { cwd: dir, env: newEnv });
Do you have a plan for release of this option (in vc)?

**Comment by silviom** [comment]
I'm needing a way to change the target_architecture to x64, too
It will be great to have a new release with this feature.

**Comment by jaredallard** [comment]
I'll work on putting this in v2! :)

**Comment by calebboyd** [comment]
Supported in v2
