### ISSUE TITLE
Distributing native modules separate from executable.

### ISSUE THREAD

**Issue by rileymat** [nexe/nexe#205]
I know that you cannot package the native modules inside of the nexe executable at this point.  

I did notice that if I took the generated/browserified nexe.js file produced by the build and ran it with node.exe that I could launch the app as long as the native module .node files were in a "build" build directory next to the nexe.js file . This does not work with the compiled executable.  Is there some known load location that I could put the .node files so the .exe compiled with nexe could find those modules?

**Comment by jaredallard** [comment]
I've heard `global.require`may work in your case

**Comment by rileymat** [comment]
Thanks, I will try that out.  What I did in the mean time is build the module into the node executable. I thought about submitting a pull request with the FFI module built into node (as it is supremely useful for built exes, although that might be out of the scope of what you are trying to do with this project), but there is no way to do this in a version independent way like everything else.

**Comment by jaredallard** [comment]
Actually I'd agree that FFI might be actually pretty useful to at least support!

**Comment by calebboyd** [comment]
fixed in `nexe@beta` see examples/native-build
