### ISSUE TITLE
Failing when spaces in Python path

### ISSUE THREAD

**Issue by mattfabina** [nexe/nexe#210]
Probably not a high priority bug, but will effect users when they install Python to "C:\Program Files (x86)\Python27". Easily resolved by moving Python installation to "C:\Python27", which is probably recommended anyway. I'm partially posting for the benefit of future users as well.

The build fails with a failure to locate "C:\Program" in the above example.

**Comment by jaredallard** [comment]
Could you provide a full build log for this? It'll help me differentiate between it being from `nexe` or being from it replacing python in the various Makefiles & etc.

Thanks!

**Comment by calebboyd** [comment]
fixed in `nexe@beta`
