### ISSUE TITLE
TypeError: require.resolve is not a function

### ISSUE THREAD

**Issue by guanzhijie** [nexe/nexe#213]
I used nexe to wrap my node.js application with the following config in package.json: 
```json
"nexe": {
    "input": "/usr/local/bin/nexe",
    "output": "myApp.nexe^$",
    "temp": "temp",
    "runtime": {
        "framework": "node",
        "version": "5.5.0",
        "ignoreFlags": false
 }
```

The executable was generated but when I run it, it reported the following error:
```bash
$ ./myApp.nexe 
nexe.js:25933
var processPath = require.resolve('process/browser.js');
                          ^
TypeError: require.resolve is not a function
    at Object.__dirname.150.combine-source-map (nexe.js:25933:27)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.<anonymous> (nexe.js:11548:21)
    at Object.__dirname.34../lib/builtins.js (nexe.js:12350:4)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.2../log (nexe.js:140:21)
    at s (nexe.js:1:316)
    at nexe.js:1:367
```

[Google search](https://www.google.com/#q=%22TypeError:+require.resolve+is+not+a+function%22) suggested this error might be due to 
1) socket.io was used instead of socket.io-client; or
2) the used browserify doesn't support "require.resolve" while "require" should be used

My app doesn't use socket.io. And almost all of the libraries my app depends on use the same version of browserify as nexe uses (^13.0.0), except the [bluebird](https://github.com/petkaantonov/bluebird) library which uses [^8.1.1](https://github.com/petkaantonov/bluebird/blob/master/package.json). I am not sure if that is related. My app doesn't have any code using "require.resolve('process/browser.js')". It seems the error happens in the code generated by nexe. So hope I can get some help here.

**Comment by jaredallard** [comment]
A workaround for this is to use node's require via `global.require`. It looks like a module you're using is using it, this issue and others will be able to be worked around via nexe@2.0.0 which is being worked on!

**Comment by dekideian** [comment]
Another workaround that worked for me:
I removed all "nexe" references from both package.json and also from the .js file, however: I manually downloaded the latest node version in the tmp folder and i did no longer receive the require.resolve is not a function. Good luck!

**Comment by Thor19** [comment]
@jaredallard, could you elaborate a little bit on the workaround you mention in your comment?
I dont understand how I need to change my code to get it to work

**Comment by jaredallard** [comment]
@Thor19 so you can use `global.require` in place of `require()`, but this make it use the native node.js version of require. This means that it won't use the bundled version, and will instead use the one in `node_modules` (so that must be shipped as well).

**Comment by Thor19** [comment]
@jaredallard After replacing all require statements with global.require, nothing changed for me.

As an example (Just to make sure I am understanding the workaround correctly) i changed
`var args = require("./lib/argParser")();`
to 
`var args = global.require("./lib/argParser")();`

I still get the error:

`nexe.js:29901`
`var processPath = require.resolve('process/browser.js');`
`TypeError: require.resolve is not a function`

This workaround does not seem to work for me.

I dont know if my nexe configuration matters in this context because I dont fully understand the source of this issue. But Ill leave it here just in case.

`  "nexe": {
    "input": "./node_modules/nexe/bin/nexe",
    "output": "./build/output/test^$",
    "temp": "./build/tmp",
    "runtime": {
      "framework": "node",
      "version": "4.7.3"
    }`

**Comment by monspid** [comment]
```
[eval]:74
    }) : require.resolve(name_to_adapter(name));
                 ^

TypeError: require.resolve is not a function
    at resolve_engine_path ([eval]:74:18)
    at Object.exports.load ([eval]:34:19)
    at Object.123.accord ([eval]:29351:29)
    at s ([eval]:1:254)
    at [eval]:1:305
    at Object.393../bundle ([eval]:79345:12)
    at s ([eval]:1:254)
    at [eval]:1:305
    at Object.1../tasks/build_app ([eval]:4:1)
    at s ([eval]:1:254)
```

I changed the code in nexe.js in 74 line. From `require.resolve(name_to_adapter(name)); `to `global.require.resolve(name_to_adapter(name));` and it does not work. there is still the same error. I think i did not get @jaredallard instruction.

**Comment by calebboyd** [comment]
fixed in #308

**Comment by amilajack** [comment]
Should this be closed?

**Comment by rivetweb** [comment]
trying to use uglify-js

```
var uglifyjs = require('uglify-js');
var code = 'some code';
var result = uglifyjs.minify(code);

```
have

`TypeError: require.resolve is not a function`
