### ISSUE TITLE
v2.0.0 - redesign status

### ISSUE THREAD

**Issue by jaredallard** [nexe/nexe#218]
I've been redesigning nexe so that it's a lot more modular as well as plugin-able.

Here's a list of features planned, and done:
- [x] _nexe_: system to load new components to `nexe.libs[name]`
- [ ] _nexe_: allow hookins, i.e uglify
- [ ] _nexe_: allow hookins for monkey patching node source.
## lib/compile

Compile/extract node.js
- [x] _lib/compile_: can compile node.js
- [x] _lib/compile_: can extract node.js
- [x] _lib/compile_: can patch node to support python2 / etc.
## lib/download

Download node.js versions.
- [x] _lib/download_: can download node.js
- [x] _lib/download_: can defer latest->NODE_VERSION in directory structure.
## lib/embed

Embed files into an exe.
- [x] _lib/embed_: can embed files.
## lib/patch

Handles patching node.js source.
- [x] _lib/patch_: can patch node.js to load nexe bundle.
- [ ]  _lib/patch_: can patch node.js to take pre-set v8 flags.
- [ ]  _lib/patch_: can patch node.js to ignore initial args.
- [ ]  _lib/patch_: has a more efficient monkey patch.
## lib/package:

Module to handle packaging programs.
- [x] _lib/package_: can use nexe old bundle method.
- [x]  _lib/package_: can bundle with browserify
- [ ]  _lib/package_: can bundle with jspm
- [ ]  _lib/package_: can bundle with webpack
## lib/log

Handles debug/stdout.
- [ ] _lib/log_: use some sort of smart way of determining what to stdout and what to debug.
## package.json
- [ ] _package_: allow specifying the build type.
- [ ] _package_: use defaults efficiently.
## General Design
- [ ] _all_: map DOWNLOAD_DIR, NODE_DIR, and other constants for each module.
- [ ] _all_: setup gulp tasks to generate jsdoc
- [x] _all_: mocha is set back up
- [ ] _all_: mocha task to check eslint
- [ ] _proj_: make master develop branch, releases as tags. Use feature branches.

Want to contribute? The code is on branch v2.0.0, feel free to knock any of these out.

**Comment by jaredallard** [comment]
Don't worry, this is still being worked on! Hoping to have an RC by Sunday!

**Comment by anmonteiro** [comment]
I wonder why you're deprecating `nexe.compile`. Will there still be a way to programmatically use the Nexe API? In my use case, the resources I pass to nexe are computed as part of my build process, so using CLI or package.json is not an option..

**Comment by anmonteiro** [comment]
One other idea I had, which would be awesome for advanced users, would be to provide an extensible way to allow custom monkey-patching of Node's source. What do you think about this?

**Comment by rahul-dutt-sharma** [comment]
I am using nexe.compile and would very much want to keep doing so. :)

**Comment by jaredallard** [comment]
Sorry for the confusion everyone, `nexe.compile` is being deprecated accessed *that* way.

The new way of using `nexe` is to instance it, i.e

```js
'use strict'; 

const nexe = require('nexe');

let nexe      = new nexe({
  input:   'myfile.js',
  output: 'out',
  temp:   './temp'
});
```

Also, @anmonteiro Implementing a way of transforming the input using exts is in the works, but that's actually a really awesome idea, definitely will add to roadmap.

**Comment by rahul-dutt-sharma** [comment]
that's great! :) ty

**Comment by calebboyd** [comment]
superseded by current master
