### ISSUE TITLE
Is that possible to generate one binary file for phantom.js application? 

### ISSUE THREAD

**Issue by jzkunlun** [nexe/nexe#22]
I have phantom.js project. Is that possible to generate one binary deployable file? 

Thanks,

**Comment by calebboyd** [comment]
This is probably too little to late. Native modules [can now be  embedded](https://github.com/nexe/nexe/tree/v2.0.0-beta.2/examples/native-build). Though they're extracted at runtime due to limitations linking from in-memory.
