### ISSUE TITLE
Failing when spaces in working dir

### ISSUE THREAD

**Issue by lapsio** [nexe/nexe#221]
nexe is miserably failing if there are spaces in paths:

http://pastebin.com/zxmEiqh5

**Comment by jaredallard** [comment]
I don't see anything wrong here?

**Comment by multipia** [comment]
Guess nothing wrong but too many letters and alarms. 👍

**Comment by lapsio** [comment]
It created 2 directories in Documents - "custom" and "apps" and failed to compile. Whereas it's one directory ~/Documents/custom\ apps (with space). I had to move project to dir without spaces in name in order to make nexe compile node properly.

**Comment by jaredallard** [comment]
After looking at that more closely, the log seems to somewhat imply it's not actually nexe, but rather Makefile. Which is implying it's node.js' compiling having issues. Which isn't handled by nexe.

**Comment by calebboyd** [comment]
You need to be able to build node before nexe will work. 

See https://github.com/nodejs/node/blob/master/BUILDING.md#windows-1
and https://www.npmjs.com/package/windows-build-tools
