### ISSUE TITLE
Syntax error in node's configure file make compilation fails

### ISSUE THREAD

**Issue by mhcgolds** [nexe/nexe#223]
First time trying to use nexe. Running the following command:

`nexe -i server.js`

I get invalid syntax at "tmp\nexe\nodejs\latest\node-v6.2.0\configure" file. [Screenshot](https://imgur.com/5yBW8Fq).

Running over Win7 x64, installed nexe with -g flag

**Comment by jaredallard** [comment]
Hey! Thanks for the issue. What's your python version?

**Comment by mhcgolds** [comment]
Hi @jaredallard.
My python is `2.3.5`.

**Comment by mhcgolds** [comment]
I'm probably missing something. The first error I wasn't setting up any node version, so it was using the latest(6.2.0). So I tried other versions, 4.4.4, 0.12.14, 0.11.16. All bronken with the - almost - [same error.](http://imgur.com/Lb8jfw2). This error occurs with version 0.12.16 and 0.11.16.

**Comment by jaredallard** [comment]
For sure a python issue. I'd verify it's not python3 for sure (this error pops up only on python3) then try re-installing python.

**Comment by calebboyd** [comment]
Python 2.6 or 2.7 is required for building node -- see: https://github.com/nodejs/node/blob/master/BUILDING.md
