### ISSUE TITLE
SyntaxError: Unexpected character '

### ISSUE THREAD

**Issue by samueleforconi** [nexe/nexe#226]
Hi, I'm trying to compile a node.js app with nexe, but I get this error:

> ./nexe -i /home/pi/test.js -o /home/pi/test.bin
> ----> framework => nodejs
> ----> embedResources undefined
> ----> resource -> /home/pi/node_modules/nexe/bin/tmp/nexe/nodejs/latest/node-v6.2.0/lib/nexeres.js
> ----> bundle /home/pi/test.js
> ----> executing browserify via API
> 
> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> SyntaxError: Unexpected character '

I searched all the events.js files in the system and removed the '' in the comment line, but the error still remains, I can't even understand which file is reading given that the '' are not there anymore...

>  $ pwd
> /home/pi
> $ find . -name events.js
> ./node_modules/events/events.js
> ./node_modules/nexe/bin/tmp/nexe/nodejs/latest/node-v6.2.0/lib/events.js
> $ cat -n node_modules/events/events.js | grep 160
>    160        fired = true;
> $ cat -n node_modules/nexe/bin/tmp/nexe/nodejs/latest/node-v6.2.0/lib/events.js | grep 160
>    160        throw er; // Unhandled error event

**Comment by jaredallard** [comment]
This error is most likely misleading. Can you upload your source files somewhere?

**Comment by 0dividedby0** [comment]
I am getting the exact same error... the only difference is that mine says events.js:141 and the unexpected character is '�'. I tried reinstalling python and that did not work. Could this be some sort of issue with browserify? It fails while executing browserify via API...

**Comment by miparnisari** [comment]
@0dividedby0 i'm getting the same error as you, but I don't know how to apply the workaround. Any tips?

**Comment by PaulBGD** [comment]
This is 100% related to native modules. Is there no way to include them with Nexe? Is this planned for v2?

**Comment by MatheusNaldi** [comment]
@miparnisari I'm using this same module and getting the same error, but I think nexe call browserify before compile, and browserify is trying to parse this file that it seems binary...how to ignore these files in browserify? Did you solve that?

**Comment by miparnisari** [comment]
Hey @MatheusNaldi, sorry, I am no longer involved in the project and so I don't know what I did :(

**Comment by gsundin** [comment]
@MatheusNaldi have you found a solution to this?

**Comment by MatheusNaldi** [comment]
@gsundin I was here yesterday searching the solution again, but I don't find it

**Comment by soniagandhi** [comment]
Any update on this? I am facing the same issue. Trying to package the nodejs app using nexe and getting below error. I am stuck, please help !!
events.js:160
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Unexpected character '�'

**Comment by gsundin** [comment]
@soniaghandi I ended up using a Nodejs package called "pkg." It has support for native modules and worked well for my application.

**Comment by soniagandhi** [comment]
Thanks gsundin! I switched to pkg too.
exe is created and upon running it started the server (Listening to port..) - which is fine
When I browse localhost, it should load index.html as expected, but it throws error
Error processing request: File or directory 'C:\**\SwitchControllerService\node_modules\switchdesigner\dist\index.html' was not included into executable at compilation stage. Please recompile adding it as asset or script.

And the respective code is
app.get('/*', function (req, res) {
    res.sendFile('index.html', { root: path.join(__dirname, './../../node_modules/switchdesigner/dist/') });

I confirmed that it is due to the __dirname only. I replaced this with hardcoded path and it worked fine.
Tried using process.cwd() instead of __dirname , but it throws error while loading

Error processing request: ENOENT: no such file or directory, stat 'C:\projects\switchmanager\src\SwitchControllerService\dist\node_modules\switchdesigner\dist\index.html'

Can you please suggest how this can be resolved?

![error](https://user-images.githubusercontent.com/31244460/29653388-313eca28-88c7-11e7-931d-57b799def137.PNG)

**Comment by soniagandhi** [comment]
exe is created and upon running it started the server (Listening to port..) - which is fine
When I browse localhost, it should load index.html as expected, but it throws error
Error processing request: File or directory 'C:**\SwitchControllerService\node_modules\switchdesigner\dist\index.html' was not included into executable at compilation stage. Please recompile adding it as asset or script.

And the respective code is
app.get('/*', function (req, res) {
res.sendFile('index.html', { root: path.join(__dirname, './../../node_modules/switchdesigner/dist/') });

I know it should bundle the required files along with exe, but can someone help me with this?

package.json

 "pkg":{
    "scripts": [
      "dist/server/bin/www.js",
      "dist/server/app.js",
      "node_modules/body-parser/index.js",
      "node_modules/body-parser/lib/types/urlencoded.js",
      "node_modules/bufferutil/build/Release/bufferutil.node"
    ],
    "assets": [
      "./node_modules/switchdesigner/dist/index.html",
      "./node_modules/switchdesigner",
      "./dist/server/bin/www.js",
      "./dist/server/app.js",
      "./node_modules/body-parser/index.js",
      "node_modules/bufferutil/build/Release/bufferutil.node",
      "node_modules/switchdesigner/node_modules/bufferutil/build/Release/bufferutil.node"
    ]
  }
Warnings during packaging
PS C:\projects\switchmanager\src\SwitchControllerService> pkg ./dist/server/bin/www.js --output ./dist/service.exe

pkg@4.2.4
Targets not specified. Assuming:
node6-win-x64
Warning Cannot stat, ENOENT
C:\projects\switchmanager\src\SwitchControllerService\dist\client
The file was required from 'C:\projects\switchmanager\src\SwitchControllerService\dist\server\app.js'
Warning Cannot include addon %1 into executable.
The addon must be distributed with executable as %2.
C:\projects\switchmanager\src\SwitchControllerService\dist\SwitchControllerNode\Release\SwitchControllerNode.node
path-to-executable/SwitchControllerNode.node

![error](https://user-images.githubusercontent.com/31244460/29865829-2d355aba-8d94-11e7-8b47-c879770d5e7a.PNG)

**Comment by calebboyd** [comment]
If you have a specific issue with nexe please open a new issue
