### ISSUE TITLE
passing args provider on the command line

### ISSUE THREAD

**Issue by jedi4ever** [nexe/nexe#23]
Once the binary is compiled, the node binary swallows the commandline arguments.
They will need to be exposed again.

**Comment by gbaumgart** [comment]
same here, i am using the npm package 'commander' and it doesnt work anymore:
```js
commander
    .version('0.1.1')
    .option('-p, --profilePath <name>', 'path to profile',path.resolve(defaultProfile))
    .option('-s, --sourceRoot <name>', 'path to dojo source root',path.resolve(libRoot))
    .option('-c, --clientRoot <name>', 'path to client root',path.resolve(clientRoot))
    .option('-i, --info', 'return service profile')
    .option('-j, --jhelp', 'output options as json');

commander.parse(process.argv);
```

what do I now?

**Comment by jaredallard** [comment]
Have you tried enabling the flags option on compile time?

**Comment by gbaumgart** [comment]
hi, not yet but I put this here in my main file before anything:

process.argv = process.argv.slice(1);

which seems to work now, at least for me ;-)
