### ISSUE TITLE
Express App with path.join(__dirname...

### ISSUE THREAD

**Issue by vicatcu** [nexe/nexe#240]
I'm trying to package an Express .js app I wrote, and thought I'd give nexe a whirl. It built my project into an executable without complaint, but when I run it and load it in a browser, I get the message (in the browser):

```
Error: No such native module pug
   at NativeModule.require (bootstrap_node.js:393:13)
   at s (nexe.js:1:176)
   at nexe.js:1:367
   at new View (nexe.js:19973:30)
   at EventEmitter.render (nexe.js:16719:12)
   at ServerResponse.render (nexe.js:18450:7)
   at nexe.js:66:7
   at Layer.handle_error (nexe.js:19275:5)
   at trim_prefix (nexe.js:18867:13)
   at nexe.js:18837:7
```

I don't think pug (formerly jade) actually depends on native modules or qualifies as a native module itself (I could be wrong?), so I think this message is actually a red herring. I suspect what's actually happening has something to do with the __dirname directive.

In my application I do this sort of thing in my app.js (probably egregious in some fundamental way, but it works launching un-packaged):

```
...
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'pug');

app.use(express.static(path.join(__dirname, 'public')));
app.use(express.static(path.join(__dirname, 'node_modules/bootstrap/dist')));
...
```

I feel like that might have something to do with the real root cause of my trouble. Please can anyone offer me some guidance on how to sort out / fix what's going on with my construction.

**Comment by qlux** [comment]
Hi,
The parser looks for each 'require(package)' directive you might have in your code and view engines like pug or ejs are not declared with require. To force pug being bundled you have to add a require directive:
`...
require('pug');
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'pug');` 

In this case, it does not change the execution.

**Comment by calebboyd** [comment]
The static servers in this example will now work if those resources are bundled

03e2985c7a3af2be19f212ceedd36aa628b613f5
