### ISSUE TITLE
"No such native module ${id}" when required an excluded file

### ISSUE THREAD

**Issue by shaunxu** [nexe/nexe#241]
```
// ./index.js
"use strict";
var profile = require(process.cwd() + '/views/profile.js');
console.log(profile);

// ./views/profile.js
"use strict";
module.exports = "'profile.js' is ok";
```

Compile command was `nexe -i index.js -o a.out -f`
Then when I ran `./a.out` it gave me an error said

```
bootstrap_node.js:393
      throw new Error(`No such native module ${id}`);
      ^

Error: No such native module /Users/Shaun/try-nexe/views/profile.js
    at NativeModule.require (bootstrap_node.js:393:13)
    at s (nexe.js:1:176)
    at nexe.js:1:367
    at Object.__dirname.1 (nexe.js:7:15)
    at s (nexe.js:1:316)
    at e (nexe.js:1:487)
    at nexe.js:1:505
    at NativeModule.compile (bootstrap_node.js:460:7)
    at Function.NativeModule.require (bootstrap_node.js:401:18)
    at Function.Module._load (module.js:397:25)
```

**Comment by shaunxu** [comment]
After checked the source code I found in the source code and found a workaround. When we wanted to require a module which don't wanted to be bundled, we should use `global.require(process.cwd() + '/views/profile.js')` rather than `require(process.cwd() + '/views/profile.js')`.

This is because `nexe` will read the entry code and copied into a file named `nexe.js` located in the downloaded Node.js source code under `lib` folder. When compile our application, `nexe` will trigger Node.js build and it will put all files under `lib`, included our own `nexe.js` into Node.js binary as build-in modules. 

But Node.js will override `require` when processing build-in modules so that it only find build-in modules. This is the reason I got `No such native module` error if I tried to require an external module through `require`. Because in this case our `exec.js` is build-in module and Node.js tried to use altered `require` to find `/view/profile.js` in build-in modules, and it failed.

If changed the code to `global.require` we forced Node.js to use normal `require` to find module, so it can resolve the correct one we need.

Below is just my guess based on investigated `nexe` and Node.js source code. Please correct if anything wrong.

Hope this helps,

**Comment by moraisp** [comment]
I'm sorry to resurrect this issue, but global.require does not look to be available outside REPL context to me. Is there another workaround to this issue?

**Comment by calebboyd** [comment]
Please try to use v2 -- if you still have issues open a new issue.
