### ISSUE TITLE
The CJK literal string are stripped out.

### ISSUE THREAD

**Issue by chinlung-chang** [nexe/nexe#247]
I found a code in lib/bundle.js, line 118

`source = source.replace(/[^\x00-\x7F]/g, "");`

Which will strip Chinese Literal from strings of source codes.  Is there any reason for that !?

**Comment by woverton** [comment]
Please see this ticket: https://github.com/jaredallard/nexe/issues/206

**Comment by calebboyd** [comment]
fixed in `nexe@beta`
