### ISSUE TITLE
nexe task fails when on closed network

### ISSUE THREAD

**Issue by mikeyGlitz** [nexe/nexe#254]
when I run nexe on a closed system, I cannot build a package because nexe is trying to fetch the node tar from the Internet. I need to be able to specify a local node tar file to proceed with the install.
![error](https://cloud.githubusercontent.com/assets/606924/18636508/12891c3a-7e57-11e6-983e-49e9aa033e3e.png)

**Comment by gbaumgart** [comment]
when you specify your temp-directory, you only need to place the node source file that way: 

myTempDir/nodejs/4.4.7/nodejs-4.4.7.tar.gz

**Comment by mikeyGlitz** [comment]
is the nodejs.tar.gz dependent on which OS you're using? (I'm developing on Windows)

**Comment by calebboyd** [comment]
TODO --quick #308

**Comment by calebboyd** [comment]
Alternate download locations can be used with `nexe@beta` Please open a new issue if you have problems
