### ISSUE TITLE
Error: tunneling socket could not be established

### ISSUE THREAD

**Issue by creaux** [nexe/nexe#256]
Nodejs with npm is working, linux HTTP_PROXY, HTTPS_PROXY are seted up properly. Whne nexe trying to download nodejs version im getting following error.

```
{ [Error: tunneling socket could not be established, cause=connect EINVAL 0.0.12.56:80 - Local (0.0.0.0:0)] code: 'ECONNRESET' } 
```

What is nexe using as tool for downloading?

**Comment by jaredallard** [comment]
Hi, we use [request](https://github.com/request/request)
