### ISSUE TITLE
Compilation on windows take a long time even when compilation is run subsequently.

### ISSUE THREAD

**Issue by rahul-dutt-sharma** [nexe/nexe#258]
This does not happen on OSX the first compile is long but subsequent recompiles are fast. Not the same on windows. Anyway we can reuse the previous compiled state by passing some arguments to windows compiler

**Comment by jaredallard** [comment]
@rahul-dutt-sharma Will implement passing (if not already implemented) in v2.

**Comment by calebboyd** [comment]
fixed in #308

**Comment by rahul-dutt-sharma** [comment]
If this is fixed than great thanks, will try it out when I am back on using this in my project.
cheers

**Comment by borekb** [comment]
Just discovered next today and tried the simplest possible `console.log('hello world');` example (no `node_modules` etc.). The initial build took about half an hour I think and the second one didn't seem like it will be faster (it utilizes all my cores at 100% CPU so I had to kill it to be able to work).

Just some brief observation, I didn't look into all the possible parameters yet, this was a simple `nexe -i c:\temp\nexe\index.js -o test.exe` command.

**Comment by calebboyd** [comment]
Hi Borekb, Please take a look at `nexe@beta`. Working to get v2 released.

**Comment by borekb** [comment]
Tried the beta but had to kill it off again after a couple of minutes.

Could you give me an example of a `nexe@beta` command that should use binary Node builds on Windows 10 x64 and be relatively fast? What times should I expect for the simplest possible `console.log()` app?

My attempt was `nexe -o test --build --target win32-x64-8.0.0`.

**Comment by calebboyd** [comment]
While in beta targets won't build quickly. `--build` compiles node, just as you would using make or msbuild.
However, subsequent builds (the report in this issue) build fast.

![image](https://user-images.githubusercontent.com/5818726/28464428-c1cb36a0-6dea-11e7-9f08-ccb3146a6cd4.png)

**Comment by borekb** [comment]
Nice! I didn't have a chance to let the first long build finish so thanks for this info.

**Comment by calebboyd** [comment]
reclosing this as i think it has been clarified.
