### ISSUE TITLE
npm version is not in sync with github version ?

### ISSUE THREAD

**Issue by rahul-dutt-sharma** [nexe/nexe#262]
Although it says 1.1.2 in both places the code is different.
nodeVCBuildArgs is not present as a config object on npm.

**Comment by jaredallard** [comment]
This is because I haven't vbumped or published in a while.

**Comment by rahul-dutt-sharma** [comment]
Hey thanks for the reply!.

Okies so what I understand from this is that the npm version 1.1.2 which is old. The current git code is ahead of 1.1.2 and would soon be raised once it looks like its time for 1.2.0. Am I right or did I misread your reply.

**Comment by jaredallard** [comment]
That's exactly it! I'll publish 1.2.0 after manual review on my part, expect the release around Friday afternoon PST.

**Comment by rahul-dutt-sharma** [comment]
awesome. new to git new to collaborative development development so wanted to make sure I am getting the workflow understood. Again thanks a ton. Hoping to work with you in the future.
Cheers!

**Comment by calebboyd** [comment]
master is now tracking `nexe@beta` on npm
