### ISSUE TITLE
Error: could not load deps/icu-small...

### ISSUE THREAD

**Issue by juangl** [nexe/nexe#268]
When I run nexe I get the follow output:

```
$ nexe -i convertToBase64.js -o ./
----> framework => nodejs
----> embedResources undefined
----> resource -> /home/jn/js/2/pzj-server/src/bin/tmp/nexe/nodejs/latest/node-v6.9.1/lib/nexeres.js
----> bundle /home/jn/js/2/pzj-server/src/bin/convertToBase64.js
----> executing browserify via API
....> WARNING: src/node.js doesn't exist. Trying 'lib/internal/bootstrap_node.js'
----> make
creating  ./icu_config.gypi
* Using ICU in deps/icu-small
 Error: could not load deps/icu-small/source/common/unicode/uvernum.h - is ICU installed?
make: *** No rule to make target 'deps/http_parser/http_parser.gyp', needed by 'out/Makefile'.  Stop.
....> ERROR: The release executable has not been generated. This indicates a failure in the build process. There is likely additional information above.

```

I'm using Archlinux and I have python2-pyicu istalled.

**Comment by jaredallard** [comment]
So, that's a node problem which nexe *does not* provide support for. I'd verify you install deps for node, and verify they are installed. Sorry! :)

On Sat, Oct 22, 2016, 3:25 PM Juan García <notifications@github.com<mailto:notifications@github.com>> wrote:

When I run nexe I get the follow output:

$ nexe -i convertToBase64.js -o ./
----> framework => nodejs
----> embedResources undefined
----> resource -> /home/jn/js/2/pzj-server/src/bin/tmp/nexe/nodejs/latest/node-v6.9.1/lib/nexeres.js
----> bundle /home/jn/js/2/pzj-server/src/bin/convertToBase64.js
----> executing browserify via API
....> WARNING: src/node.js doesn't exist. Trying 'lib/internal/bootstrap_node.js'
----> make
creating  ./icu_config.gypi
* Using ICU in deps/icu-small
 Error: could not load deps/icu-small/source/common/unicode/uvernum.h - is ICU installed?
make: *** No rule to make target 'deps/http_parser/http_parser.gyp', needed by 'out/Makefile'.  Stop.
....> ERROR: The release executable has not been generated. This indicates a failure in the build process. There is likely additional information above.



I'm using Archlinux and I have python2-pyicu istalled.

**Comment by jaredallard** [comment]
Looking into this further, it may be a python problem.

**Comment by juangl** [comment]
That's okay. I'll take a look.

**Comment by xblox** [comment]
same here, can't build on OSX. and yes, its a nexe problem which doesn't deal with OSX Node.JS requirements correctly.

**Comment by nodejh** [comment]
+1, could't build on macOS sierra.

**Comment by McMerphy** [comment]
Have the same error on Windows 10, and Ubuntu 16.04. I have used python 2.6 an 2.7. Node version is 6.9.3

**Comment by jaredallard** [comment]
Not 100% sure why this is happening. I'll look into it a bit more.

**Comment by Eksrow** [comment]
So I had this error when using nexe inside virtualbox with a shared folder connected to a windows host.
The builtin unzip process wouldn't unzip everything correctly and resulted in a node/deps folder with missing files. Insynq was also connected to that folder(on windows). All in all a setup where many things can go wrong.

Setting the --temp folder to non-shared(like /home/rohan/blabla) folder completely solved the problem for me, nexe is building with great success.

**Comment by cunjieliu** [comment]
has same problem，already solve. 
Maybe you download the package is not complete.
so reinstall and try it again.
hope to help someone who has the same problem.

**Comment by fabifabi** [comment]
same issue, solved with -t tmp

**Comment by pereiradiogo** [comment]
same problem! 
nexe -t tmp doesn't work for me...

**Comment by calebboyd** [comment]
Please try the latest version 2.0.0-rc.1

**Comment by calebboyd** [comment]
@pereiradiogo Please open a new issue if you still have problems after trying the latest version
