### ISSUE TITLE
`nexe.compile` doesn't suppport platform specific extension

### ISSUE THREAD

**Issue by anmonteiro** [nexe/nexe#270]
As stated in the README for the `package.json` `"nexe"` entry:

    output: can use ^$ for platform specific file extension

however this is not supported when using `nexe.compile`.

Should make for a good first contribution, seems pretty easy to tackle.

**Comment by jaredallard** [comment]
It isn't? Hm. Odd, yeah that'd likely be a super easy implementation. But, the code is a little... interesting ;)

**Comment by anmonteiro** [comment]
doesn't seem to. It's only handled in `package` ([source](https://github.com/jaredallard/nexe/blob/b822f589731ed652a111d5e3104bdf186a29c37f/lib/exe.js#L1013-L1018)), not `compile`

**Comment by calebboyd** [comment]
fixed in #308

**Comment by calebboyd** [comment]
Nexe 2.0.0 Will add `.exe` if needed. Otherwise, whatever is passed will be the filename
