### ISSUE TITLE
will not patch node.js .cc files if working with git repo node source (on windows?)

### ISSUE THREAD

**Issue by btsimonh** [nexe/nexe#279]
in exe.js, nexe loads files and runs split('\n'), then compares lines.  If the node source used is the git repo (maybe only on windows), the line endings in the .cc files are \r\n, and the subsequent line comparisons fail.

replacing 
  let lines = mainC.split('\n');
with 
  let lines = mainC.replace(/\r\n/g,'\n').split('\n');

and
    var contentsSplit = contents.split('\n');
with
    var contentsSplit = contents.replace(/\r\n/g,'\n').split('\n');

will make it work in all cases?

**Comment by jaredallard** [comment]
Interesting, I haven't seen this yet. I'll check it out, and for now just throw it in v2 branch. Thanks!

**Comment by btsimonh** [comment]
i've modified my global git config ("core.autocrlf" is set to "input"), and will report if this helps.  In the end, the build of direct GIT 6.9.1 (with autocrlf=auto) did not work for some reason; i'm wondering if there is something else (maybe on node build itself) which is line ending sensitive.....

**Comment by calebboyd** [comment]
fixed in #308
