### ISSUE TITLE
Cannot determine current version of Node.js error

### ISSUE THREAD

**Issue by behroozshafiabadi** [nexe/nexe#280]
hi
i use nodeJs v 4.4.4, but when i try to use nexe whit command :
`nexe -i ./nexeApp.js -o ./output.bin -r 4.4.4` 
i get Cannot determine current version of Node.js error!
have any issue about this ?

**Comment by behroozshafiabadi** [comment]
![nexeerror](https://cloud.githubusercontent.com/assets/18419656/20836111/181efae8-b8b3-11e6-9280-bf95043b4cd3.jpg)

**Comment by ArcticZeroo** [comment]
I'm getting the same thing, using node v6.0.0 and v7.2.1 (and nexe 1.1.2)

**Comment by drahgon55** [comment]
I ran into this a while ago. I think it had something to do with stopping the build process midway through and trying to  restart it. I think the solution was to manually remove the build folder with the node.js source code that nexe downloads. That way it downloads it all again fresh and recompiles again from scratch.

**Comment by Rike-cz** [comment]
Same problem with error: 
`----> vcbuild [make stage]`
`File "C:\apps... ...tmp\nexe\node\7.2.1\node-v7.2.1\tools\getnodeversion.py", line 20`
`print '%<major>s.%<minor>s.%<patch>s'% locals()`
`Syntax Error: invalid syntax`
`Cannot determine current version of Node.js`

**Comment by kakkaroolari** [comment]
Apparently this is not Python 3 compatible. Print without parenthesis.

**Comment by haganbmj** [comment]
If you manually resolve the issue in `getnodeversion.py`, the build will fail a little later indicating `Please use either Python 2.6 or 2.7`

```
.................
Looking for Visual Studio 2015
Found Visual Studio 2015
configure  --dest-cpu=x86 --tag=
Please use either Python 2.6 or 2.7
Failed to create vc project files.
....> ERROR: The release executable has not been generated. This indicates a failure in the build process. There is likely additional information above.
```

**Comment by PDaily** [comment]
@Rike-cz  and others who have that particular issue: 

Uninstall any Python versions above 2.7 and re-download from the Python site.

[Python 2.6](https://www.python.org/download/releases/2.6/)

**Comment by calebboyd** [comment]
You can refer to the guide here: 
https://github.com/nodejs/node/blob/master/BUILDING.md#windows-1

Any necessary dependencies can be installed with: 
https://www.npmjs.com/package/windows-build-tools
