### ISSUE TITLE
Build Size

### ISSUE THREAD

**Issue by G047** [nexe/nexe#283]
A simple hello world application contains around 60MB, I know you have to include v8/node is required (maybe not node) but I know for a fact [npm](https://i.imgur.com/auo47xR.png) is not required. Also when trying to run on a different system `nexe.js` is making calls to `}).call(this,"/home/node_modules/bindings/bindings.js")` that obviously doesn't have that file on the other system.

**Comment by jaredallard** [comment]
Hey, can you post your example hello world?

**Comment by G047** [comment]
`console.log('Hello World!')`

**Comment by jaredallard** [comment]
@G047 Really? Wow, that's... odd.

**Comment by jaredallard** [comment]
Is there anything in the build directory? i.e a `node_modules` or anything else.

**Comment by CKarper** [comment]
![image](https://cloud.githubusercontent.com/assets/653156/21239726/20e9f0a6-c2d6-11e6-8f0d-cad952203613.png)

**Comment by G047** [comment]
Yes, if it helps using node `4.2.6` with the node module `ws` in the node_modules even so the size of the node_modules is under 1MB so it should only add that much to the build size.

**Comment by jaredallard** [comment]
@G047 Yeah, I see the binaries being about that size. Going to look into this. So far, from an initial examination of `lib/nexe[res].js` it seems the be that the final binary is unusually large. Not the actual source code.

**Comment by G047** [comment]
@jaredallard `lib/nexe.js` is about `300KB`, its smaller than the node_modules so I doubt thats the problem.

**Comment by jaredallard** [comment]
@G047 Yeah, the thing there is if it *isn't* `lib/nexe.js`, then it's likely something to do with node. Which would be out of this project's scope. But, as this is a critical issue it's something I'd work on. (compile opts? etc) Whatever it is.

**Comment by G047** [comment]
@jaredallard about the `deps/npm` that contains `12MB`

**Comment by jaredallard** [comment]
That's not nexe, that'd be node

**Comment by G047** [comment]
@jaredallard yes but can't you add a monkeypatch to remove it from the final build?

**Comment by jaredallard** [comment]
@G047 I can, currently seeing if it functions by just "removing it". Annoying part about this project is the need to build node to test a lot of things.

**Comment by G047** [comment]
@jaredallard It wouldn't be that bad if the build times where not 10-30 minutes.

**Comment by jaredallard** [comment]
@G047 Yeah, getting a way to not have to compile code was something I wanted to do but didn't seem feasible unfortunately. Maybe there was a way if I worked with C/C++ but, alas, I don't.

**Comment by G047** [comment]
@jaredallard If this doesn't want to work ill try and run the output through upx in a fork.

**Comment by jaredallard** [comment]
@G047 UPX reduces plain node binary from `16MB` -> `6MB`, so that may be something I implement. I'd suggest not investing anything in v1 nexe right now. Makes a lot of work for putting it into v2

**Comment by G047** [comment]
@jaredallard May I suggest a second repository for v2, or a git organisation.

**Comment by CKarper** [comment]
@jaredallard, I have some ideas on how to remove the compile step, we should chat sometime.

**Comment by calebboyd** [comment]
I'd join forces in a git org
prior work (with instant builds ala enclose) 

https://calebboyd.github.io/xbin
https://github.com/calebboyd/xbin

**Comment by jaredallard** [comment]
100% down for a git org

**Comment by G047** [comment]
that would be something i would love to help with

**Comment by jaredallard** [comment]
Removing `deps/npm` then re-compiling has no effect

**Comment by jaredallard** [comment]
Side note, I always found how you can `cat <nwjs binary> zipfile-of-app > newapp` pretty interesting with NW.js. Wonder if it's possible in this project scope.

**Comment by CKarper** [comment]
Not the way we currently do things, but we could definitely get there.

**Comment by G047** [comment]
EncloseJS gets around `16MB`, but it doesn't cross compile.

**Comment by calebboyd** [comment]
All the binaries for each project are going to be roughly the size of your bundle plus the size of the binary for that platform.. Its hard to say for enclose because its closed source. But the rough sizes of node

**For Node 6.9.2:**
macOS x64: 29mb
Windows x64: 18mb
Linux 32bit (--fully-static): 29mb

**Comment by G047** [comment]
@calebboyd enclose does the same thing (build node w js files)

**Comment by anmonteiro** [comment]
you need to pass dashes too. Here's an example: https://github.com/anmonteiro/lumo/blob/master/scripts/package.js#L48

**Comment by G047** [comment]
@anmonteiro thanks for your input, if it actually did anything it was not noticeable in the final output.

**Comment by G047** [comment]
`nexe.js` contains an awful lot of white space and code that you could minify, also if you minify the included files `fs, child_process etc` that may save a few bytes.

**Comment by jbackman** [comment]
In Unix/Linux run ```strip binaryname``` - reduces size of resulting binary by almost 30%

**Comment by calebboyd** [comment]
Nexe v2 (`nexe@beta`) has byob (bring your own bundler) so you can minify to your hearts content :)

Please open a new issue if there are other troubles
