### ISSUE TITLE
Transition to github org

### ISSUE THREAD

**Issue by CKarper** [nexe/nexe#284]
As per the discussion (#283), move nexe to a new organization.

I propose nexe/nexe.

**Comment by jaredallard** [comment]
@nexe seems to be taken, but I've contacted support about it, in case we decide to go this way.

**Comment by calebboyd** [comment]
`xbin` is up for grabs too 😜

**Comment by jaredallard** [comment]
Or, in spirit of this joint venture, a rename perhaps 😛

**Comment by jaredallard** [comment]
I'll keep you all updated when Github returns my email!

**Comment by G047** [comment]
@jaredallard thanks

**Comment by jaredallard** [comment]
https://GitHub.com/nexe is alive!
