### ISSUE TITLE
Configure download URL for node

### ISSUE THREAD

**Issue by thwint** [nexe/nexe#288]
In our company I am not allowed to download packages directly from Internet. There are some trusted packages available on an internal server.

Nexe always tries to download node from nodejs.org/dist which is absolutely correct for direct internet connections. But in my case I need to download from https://<ourinternalserver>/<nodelocation>/ 

something like 
nexe --baseurl=https://my.server.com/download/node/

would download from 
https://my.server.com/download/node/v[version]/[framework]-v[version].tar.gz";

Is there already a way to download node from custom locations?

**Comment by calebboyd** [comment]
fixed in #308
