### ISSUE TITLE
nexe compile only node source objects

### ISSUE THREAD

**Issue by TD-4242** [nexe/nexe#292]
I'm trying to speed up continuous delivery builds and would like an option to build all the node source objects and store them in a docker container under a directory sunch as /node, then I can build a node project in docker with a dockerfile something like:

```
FROM nexe-node:4.7.2
RUN mkdir /nodeapp
WORKDIR /nodeapp
COPY ./ /nodeapp/
RUN nexe -t /node
```

**Comment by calebboyd** [comment]
TODO --quick #308

**Comment by calebboyd** [comment]
`nexe@beta` has fast rebuilds
