### ISSUE TITLE
[Design] Cross Platform Support and Instant Builds

### ISSUE THREAD

**Issue by calebboyd** [nexe/nexe#295]
I'm going to attempt to outline a few methodologies for creating "instant" builds. These methods would also allow for cross platform builds (using an initial platform specific build)

1. Append to end.
   - Concatenate the bundle bytes to the end of the binary. The binary would be built with a static main module. Read them in at [runtime](https://github.com/calebboyd/xbin/blob/master/src/_third_party_main.js).
   - Easiest to implement, easiest to modify, 
   - Can't be signed. (file is truncated if signed)
   - Slow startup time (higher memory usage on boot)
   - This method is the one used in [xbin](https://github.com/calebboyd/xbin/blob/master/src/_third_party_main.js)

2. Replace contents
   - Replace the byte contents of the bundle out from the middle of the binary
   - Difficult to guess an appropriate size -- Bundle must have a correctly sized buffer such that subsequent user code additions and rebuilds fit into the "buffered binary". 
   - Could be simplified by hosting pre-built (CI) binaries with differing buffer sizes.
   - Fast startup time. Can be signed.

3. Append to end + Modify File Headers
   - Only (remotely) approachable (imo) on Windows. Not positive how the approach could work on Linux & Mac
   - Modifying the file headers to add data to a signed or unsigned binary. 
   - Easy to do insecurely 

I think option 2 is the obvious choice for robustness/security. I'd love to get more thoughts on this

/cc @CKarper, @jaredallard

**Comment by CKarper** [comment]
Osx is actually pretty straightforward, as an app there is a "bundle" and
works akin to a zip file basically.   Linux is the challenge, imo.  It can
be done, I just don't have the chops.

**Comment by calebboyd** [comment]
@jaredallard do you want to make a `next` branch I can PR against? Or give me perms for that?

**Comment by jaredallard** [comment]
@nexe/core should have permission now. Forgot to do that at the start.

**Comment by jaredallard** [comment]
I'm an advocate of 2, sounds the easiest to implement and the most interesting. Of course, I could be wrong, wouldn't the signing be nullified with 2 the second it's modified? Or are you referring to signing AFTER the creation of a new binary?

**Comment by calebboyd** [comment]
Yeah signing would happen as part of the userland build process.

**Comment by calebboyd** [comment]
TODO: #308

**Comment by calebboyd** [comment]
So, This is a major bummer, 2 is what is implemented in master, It turns out it doesn't work with every ELF binary.
