### ISSUE TITLE
Error: No such native module ./node-mongodb-native

### ISSUE THREAD

**Issue by bengiexd** [nexe/nexe#298]
I want to compile an app that uses the library mongoose, check this problem, I enter in the code but I always get this result.

$ ./out
Bootstrap_node.js: 435
      Throw new Error (`No such native module $ {id}`);
      ^
Error: No such native module ./node-mongodb-native
    At NativeModule.require (bootstrap_node.js: 435: 13)
    At s (nexe.js: 1: 176)
    At nexe.js: 1: 367
    At Object .__ dirname.290 ../ browser (nexe.js: 69798: 12)
    At s (nexe.js: 1: 316)
    At nexe.js: 1: 367
    At Object .__ dirname.311 ../ drivers (nexe.js: 79206: 36)
    At s (nexe.js: 1: 316)
    At nexe.js: 1: 367
    At Object .__ dirname.302 ... / package.json (nexe.js: 70349:14)

Please help me, give me a clue, or tell me if it is possible to solve it, thank you very much.

**Comment by qlux** [comment]
Mongoose has to be excluded and installed manually alongside your binary:
`
      "excludes": [
        "mongoose",
...]`

**Comment by calebboyd** [comment]
See also #287
