### ISSUE TITLE
nexe : "no such native module : midi.node"

### ISSUE THREAD

**Issue by ossandust** [nexe/nexe#300]
I would like to use nexe to build a small node project which requires midi (https://www.npmjs.com/package/midi) After building (on Windows10) the created exe crashes with error "No such native module [path\to\exe]\build\midi.node". nexe doesn't have a problem finding the midi module, located in node_modules\midi\midi.js, but file depends on the midi.node file which is created at node_modules\midi\midi.js\build\Release. I tried a few things with changing the package.json file, moving the midi.node file to the \build subfolder, etc. but no luck. Does anyone have any idea how to solve this issue ?

**Comment by calebboyd** [comment]
Please see the suggestion in #287
