### ISSUE TITLE
Cannot compile with --harmony-async-await

### ISSUE THREAD

**Issue by MatheusNaldi** [nexe/nexe#303]
My node program have some async awaits functions of node 7, but this functions is only enabled with --harmony-async-await flag, I tried to compile in several ways, but I got the same error `unexpected token` in async function declaration...

I've already tried:

- Run nexe with code, and put this flag in "jsFlags"
- Run nexe with package.json and put this flag in "js-flags"
- Typed "--harmony_async_await" and "--harmony-async-await"

Can someone help me?

**Comment by calebboyd** [comment]
Closing as this feature is no available without a flag.

**Comment by MatheusNaldi** [comment]
I know that this feature is no available without a flag, but where should I put this? I already tried the steps mentioned above and it did not work... could you help me?

**Comment by calebboyd** [comment]
Can you share your configuration? I had no issues using the following
```javascript
//build.js
var nexe = require('exe');
nexe.compile({
	input: 'input.js',
	output: 'out.exe',
	nodeVersion: '7.5.0',
	flags: true,
	jsFlags: "--harmony-async-await",
	framework: "node"
}, function(err) {
	if(err) {
		return console.log(err);
	}
});
```
and 
```javascript
//input.js
async function main () {
  const hello = await Promise.resolve('hello world')
  console.log(hello)
}
```
```
> node build
...
> ./out.exe
hello world
```

**Comment by MatheusNaldi** [comment]
I just tried the way you did and I got another error. (fresh folder Ctrl+C/Ctrl+V plus package.json with fresh require nexe)

```
➜  nexe-test node build
----> framework => node
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at _downloadNode (/var/www/html/teste/node_modules/nexe/lib/exe.js:283:39)
    at downloadNode (/var/www/html/teste/node_modules/nexe/lib/exe.js:129:7)
    at fn (/var/www/html/teste/node_modules/async/lib/async.js:746:34)
    at /var/www/html/teste/node_modules/async/lib/async.js:1213:16
    at /var/www/html/teste/node_modules/async/lib/async.js:166:37
    at /var/www/html/teste/node_modules/async/lib/async.js:706:43
    at /var/www/html/teste/node_modules/async/lib/async.js:167:37
    at Immediate.<anonymous> (/var/www/html/teste/node_modules/async/lib/async.js:1206:34)
```

PS: You typed "require('exe')", I fixed this before run `node build`

**Comment by calebboyd** [comment]
Could you send this info?

OS/Version:
Nexe Version:
Node Version:
Target Node Version:
Python version:

**Comment by MatheusNaldi** [comment]
OS/Version: Linux Mint 17.3 Cinnamon 64-bit
Nexe Version: 1.1.2
Node Version: 7.8.0
Target Node Version: 7.8.0 (tried 7.5.0)
Python version: 2.7.6

**Comment by calebboyd** [comment]
Sorry, I missed a config var, I updated that message

**Comment by MatheusNaldi** [comment]
It seems that node have been updated and I don't need anymore to use this flag to run async/await functions...that's why it works, thank you!

**Comment by MatheusNaldi** [comment]
Now I saw that you edited the comment from "No available" to "Now available", now it makes sense :laughing:
