### ISSUE TITLE
Just a heads up regarding compiling on Windows

### ISSUE THREAD

**Issue by Metric** [nexe/nexe#306]
I was experiencing a weird stall in the build process at v8_base3.vc projects part. It would seem the latest version of Avast when enabled causes the Microsoft linker to crash at that part. It is most likely due to a file read conflict. Simply disabling Avast before building fixes this issue.  

I also noticed that after compiling quite a few MSBuild.exe are never terminated properly (Around 7 are still lingering around). I have to manually close them via end process.

**Comment by bgao** [comment]
This doesn't seem to be an issue with nexe. According to [this](http://stackoverflow.com/questions/12174877/visual-studio-2012-rtm-has-msbuild-exe-in-memory-after-close), "MSBuild processes are kept running for a period of time (fifteen minutes, I believe) after Visual Studio is closed. This is an attempt to improve performance,..."
And the solution is to set environment variable MSBUILDDISABLENODEREUSE=1 (before starting VS) or specifying /nodeReuse:false (or /nr:false) if building from the command line.

**Comment by Metric** [comment]
Good to know about that. I did not realize Microsoft had it set that way.
