### ISSUE TITLE
__dirname hardcoded after compile

### ISSUE THREAD

**Issue by Metric** [nexe/nexe#307]
Is this intended? I thought, according to the docs it was to where the exe is currently located at?

Building with Node Version: 7.5.0, Windows 10 x64
Can replicate with a simple hello world style script: console.log(__dirname).

E.g. Build in directory \test\build. Move built exe to another directory. Run exe from new directory. Console still outputs the original \test\build directory, instead of the current directory.

It also seems to mess up the directory separator:
Ex: \test\build on Windows becomes /test\build when output in console.

Here is actual output from the test.exe with the above console.log print:
E:\VaariaMultiServers\test>test.exe
/VaariaMultiServers\test

//file moved via Windows Explorer to E:\VaariaMultiServers\Server1\

E:\VaariaMultiServers\test>cd ..

E:\VaariaMultiServers>cd Server1

E:\VaariaMultiServers\Server1>test.exe
/VaariaMultiServers\test

**Comment by klausgao** [comment]
yes it is hardcoded.
finally I find process.execPath is still working, but process.cwd is undefined.

**Comment by calebboyd** [comment]
This is intentional. You should use other methods for finding the current working directory, like `process.cwd()` or `process.execPath` for the hosting executable.
