### ISSUE TITLE
 My program runs on the linux platform, is there any way to keep this program running?

### ISSUE THREAD

**Issue by milu2003** [nexe/nexe#310]
Similar to nodejs pm2

**Comment by calebboyd** [comment]
Use systemd or systemv. A project that does this (I don't know its compatibility with nexe) is node-linux. You can reference the [templates](https://github.com/coreybutler/node-linux/tree/master/lib/templates) there

**Comment by milu2003** [comment]
thanks

**Comment by chintan1891** [comment]
PM2 will also work with Nexe executable.
