### ISSUE TITLE
What should I do if I want to package the entire project folder

### ISSUE THREAD

**Issue by milu2003** [nexe/nexe#311]
```
Options:
    -i, --input    The entry javascript files         [default: cwd]
    -o, --output   The output binary                  [default: out.nex]
    -r, --runtime  The node.js runtime to use         [default: "latest"]
    -t, --temp     The path to store node.js sources  [default: ./tmp/nexe]
    -f, --flags    Don't parse node and v8 flags, pass through app flags  [default: false]
    -v, --version  Display version number
    -p, --python   Set path of python to use.         [default: "python"]
    -F, --framework Set the framework to use.          [default: "nodejs"]
```
-i   Does it support folders?

What should I do if I want to package the entire project folder? I looked at the document carefully and did not find it. Thank you

**Comment by calebboyd** [comment]
Nexe has a naive bundler built in. However, if you want more advanced bundling I would look at a project like webpack. Once you have a bundle targeting node you can provide that as input to nexe.

**Comment by milu2003** [comment]
My project is based on electron, now want to port to linux platform. Is there any good idea? Now find nexe very good, but whether to meet my needs, still in the study
