### ISSUE TITLE
Failed to find Visual Studio installation.

### ISSUE THREAD

**Issue by mdhtr** [nexe/nexe#313]
On Windows10 I get the following error:

```
d:\my-project>nexe -i server.js
----> framework => nodejs
----> embedResources undefined
----> resource -> d:\my-project\tmp\nexe\nodejs\latest\node-v7.7.2\lib\nexeres.js
----> bundle d:\my-project\server.js
----> executing browserify via API
....> WARNING: src/node.js doesn't exist. Trying 'lib/internal/bootstrap_node.js'
----> vcbuild [make stage]
Looking for Visual Studio 2015
Failed to find Visual Studio installation.
....> ERROR: The release executable has not been generated. This indicates a failure in the build process. There is likely additional information above.
```
I found out that C++ support is needed for VS from issues #265, #227, #193, #138.  
So I have Visual Studio Community 2017 installed with [Universal Windows Platform Development and Desktop development with C++ Workloads](https://blogs.msdn.microsoft.com/vcblog/2017/03/06/finding-the-visual-c-compiler-tools-in-visual-studio-2017/) selected.

What should I do? What am I missing?

**Comment by levidobson** [comment]
It seems like the vcbuild.bat packaged with the latest nodejs version is hard-coded to handle VS 2015 only. Unfortunately installing VS 2015 doesn't seem like a straightforward process as it is not any more available for download with a direct link. I tried to update the vcbuild.bat with the correct paths but apparently you would also need to update platform toolset version and maybe other env variables, and I just didn't want to go down that path.

**Comment by calebboyd** [comment]
You can get the correct build environment by installing `windows-build-tools` from npm
