### ISSUE TITLE
Bundle static assets with nexe app

### ISSUE THREAD

**Issue by tonyalaribe** [nexe/nexe#314]
How do you bundle static html and css files alongside a nexe app, to serve as a browser based fronted for the app? I saw something about nexeres, but there is almost no documentation on it.

**Comment by JamesMGreene** [comment]
See the `resourceFiles` and `resourceRoot` configuration properties: [README.md#code-usage](https://github.com/nexe/nexe/tree/ad83cf769f19bb87f8d4e54313a6188f5fb4b3a8/README.md#code-usage)

Example usage: [test/embeded-files/](https://github.com/nexe/nexe/tree/ad83cf769f19bb87f8d4e54313a6188f5fb4b3a8/test/embeded-files)

**Comment by calebboyd** [comment]
https://github.com/nexe/nexe#resources-string
