### ISSUE TITLE
is there resourceDirectory?

### ISSUE THREAD

**Issue by kingmayko** [nexe/nexe#316]
Is there a method to write directory into binary and use by third modules
like koa-static, koa

**Comment by JamesMGreene** [comment]
See the `resourceFiles` and `resourceRoot` configuration properties: [README.md#code-usage](https://github.com/nexe/nexe/tree/ad83cf769f19bb87f8d4e54313a6188f5fb4b3a8/README.md#code-usage)

Example usage: [test/embeded-files/](https://github.com/nexe/nexe/tree/ad83cf769f19bb87f8d4e54313a6188f5fb4b3a8/test/embeded-files)

**Comment by kingmayko** [comment]
Thanks your response,
In my case, i except the below effect
  test/hw.txt                              in folder
  resourceRoot: [ 'test/' ]          in  package.json

 // read file in directory which we shouldn't declared to resourceFiles
 process.stdout.write(nexeres.get('test/hw.txt').toString('ascii'));

 // something third lib use the directory
 const statics = koa()
 statics.use(serve("test/"))

I already search implementation of nexe and test the Example
It's seems couldn't do this,

**Comment by kingmayko** [comment]
By test, resourceRoot is not work which always not empty in the embed.js 
       which test by add resourceRoot: [ 'test/' ] in package.json
and see the details
https://github.com/nexe/nexe/blob/master/lib/embed.js
It is not use for the embed directory.
