### ISSUE TITLE
nexe + opbeat, strage error in nexe.js

### ISSUE THREAD

**Issue by garrylachman** [nexe/nexe#319]
I distribute my exe and add Opbeat client (like nagios).
And i see strange errors in most of the users.

Type ReferenceError
Value
requestOptions is not defined
Location nexe.js, _execute:28196
Occurred (UTC) 2017-04-10T04:23:27.333000+00:00

11 library frames
nexe.js in _execute at line 28196
nexe.js in tasks.http-head at line 69462
nexe.js in listener at line 12393
nexe.js in <anonymous> at line 12347
native array.js in forEach at line 1
nexe.js in _each at line 11960
nexe.js in taskComplete at line 12346
nexe.js in instrumented at line 57045
timers.js in runCallback at line 672
timers.js in tryOnImmediate at line 645
timers.js in processImmediate at line 617

**Comment by calebboyd** [comment]
`requestOptions` looks like user code. You can look at it in context of the bundle at <tempDir>/<NodeVersion>/lib/nexe.js

**Comment by garrylachman** [comment]
yup.. its was user code.... thnx
