### ISSUE TITLE
Why Compile Node.js?

### ISSUE THREAD

**Issue by nprail** [nexe/nexe#321]
Why compile Node.js? Why not just download the binaries? Compiling Node.js takes quite a while and simply downloading it would be much quicker. Is there a reason that Nexe compiles instead of downloads?

**Comment by CKarper** [comment]
I don't think you understand what nexe does.   It compiles your source
*into* a custom node build.

**Comment by jbackman** [comment]
There are times when distribution of a singular binary is preferable to a bundle of nod.js + script + something to run it all together

**Comment by nprail** [comment]
Oh, I see. I definitely missed the point of Nexe!
