### ISSUE TITLE
Build as windows app

### ISSUE THREAD

**Issue by jbackman** [nexe/nexe#322]
This is a
 - [ ] Bug Report
 - [x] Feature Request
 - [ ] Other

Looking for a flag when building using MS Visual Studio to build the resulting binary as a windows app vs. console app. This would allow for running the resulting binary in the background easily

**Comment by Akaza-Akari** [comment]
![image](https://cloud.githubusercontent.com/assets/21969938/25309472/28a33288-2809-11e7-8a25-3ab71bc0932d.png)
is this miss?

**Comment by calebboyd** [comment]
@jbackman I think this is a good idea, It can be handled in userland though. I'll see if I can come up with an example!

**Comment by rioanns** [comment]
@calebboyd did you make any progress already?

**Comment by calebboyd** [comment]
Closing -- tracking in #374
