### ISSUE TITLE
Problem "Release|X86"

### ISSUE THREAD

**Issue by ydubois-fr** [nexe/nexe#323]
Hi,
I'am Yannick and i'm newbie
I'm trying to compile a JS file with NEXE.
I have and error:

D:\test\nexe\test\src\node\5.7.0\node-v5.7.0\node.sln.metaproj : error MSB4126: La configuration de solution spécifiée "Release|X86" n'est pas valide. Spécifiez une configuration de solution valide à l'aide des propriétés Configuration et Platform (exemple�: MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") ou laissez ces propriétés vides si vous voulez utiliser la configuration de solution par défaut. [D:\test\nexe\test\src\node\5.7.0\node-v5.7.0\node.sln]
....> ERROR: The release executable has not been generated. This indicates a failure in the build process. There is likely additional information above.

i don't understand how switch msbuild from "X86" to "any CPU"
Thanks for your help

- Platform(OS/Version): windows 10 64bits
- Host Node Version: V 7.9.0
- Target Node Version: 5.7.0
- Nexe version: 1.1.2
- Python Version: 2.7

**Comment by calebboyd** [comment]
Hi Yannick, You might want to go through this to make sure it works with node out of the box
https://github.com/nodejs/node/blob/master/BUILDING.md
