### ISSUE TITLE
module.exports = X = function() does not work

### ISSUE THREAD

**Issue by lophygor** [nexe/nexe#327]
This is a
 - [x] Bug Report

<br/>
The following code will fail after compile into binary with nexe. 

```javascript
module.exports = test = function() {
    console.log('hello world');
}
test();
```

Output error.
```
nexe.js:3
module.exports = test = function() {
                      ^

ReferenceError: test is not defined
    at Object.__dirname.1 (nexe.js:3:23)
    at s (nexe.js:1:316)
    at e (nexe.js:1:487)
    at nexe.js:1:505
    at NativeModule.compile (node.js:964:5)
    at Function.NativeModule.require (node.js:909:18)
    at Function.Module._load (module.js:285:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at [eval]:1:1
```

<br/><br/>
Please also provide: 

- Platform(OS/Version): mac os 10.12.4
- Host Node Version: 4.5.0
- Target Node Version: 4.4.7
- Nexe version: 1.1.2
- Python Version: 2.7.10

**Comment by calebboyd** [comment]
Test is not declared anywhere so its failing in strict mode.

Do
```javascript
const test = module.exports = function () {...}
test()
//or
module.exports = function test () {...}
test()
```

**Comment by lophygor** [comment]
The thing is I depend on an external node module that exports module in `module.exports = X = function()` style. Modifying the external node module is hacky and not scalable in my case. 

Is there any way I can turn off the strict mode?

**Comment by calebboyd** [comment]
Hmm I don't think so, Is the node module open source?

**Comment by lophygor** [comment]
We compile our app into binary, the app will dynamically load some external node modules (I was able to bypass the dynamic require issue using global.require) bases on the request. We may not have full control of what node modules are being loaded into the app.

**Comment by calebboyd** [comment]
Oh interesting, I don't think strict mode would have an effect outside of the bundle then... Odd

**Comment by lophygor** [comment]
The error can be reproduced with the following sample code. main.js and test.js are in the same working directory. Main.js will load test.js and execute it.

1. Compile main.js into a binary. Ouput file name `main`.
2. Run command `./main ./test.js`
3. Error: `ReferenceError: test is not defined`.

// main.js
```javascript
var inputModule = process.argv.slice(2)[0];
var f = global.require(inputModule);
f();
```

// test.js
```javascript
module.exports = test = function() {
    console.log('hello world');
}
```

// Error output
```
/Users/lophygor/test.js:3
module.exports = test = function() {
                      ^

ReferenceError: test is not defined
    at Object.<anonymous> (/Users/lophygor/test.js:3:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.__dirname.1 (nexe.js:4:16)
    at s (nexe.js:1:316)
    at e (nexe.js:1:487)
```

**Comment by jaredallard** [comment]
I've seen this before, strict mode appears to apply for the entire bundle, not sure why.

**Comment by calebboyd** [comment]
Yeah thats what I thought, but he's not bundling test.js

**Comment by calebboyd** [comment]
Very strange. Perhaps your build was inadvertently configured for global --use-strict. I don't have my mac to test the versions. But I can't replicate this on Windows. I'd try removing tmp directory (node source) and building again if you haven't already.

**Comment by lophygor** [comment]
It works after I clean up the tmp!!!

The problem is I enable `--use_strict` flag in the package.json the first time I built it. The strict mode flag applies strict mode globally. The strict mode can not be disabled even I remove the `--use_strict` flag from the package.json and the rebuild. I have to clean up the tmp directory, remove the `--use_strict` flag, then rebuild.


```
"nexe": {
    "input": "./bin/nexe",
    "output": "nexe^$",
    "temp": "src",
    "browserify": {
        "requires": [],
        "excludes": [],
        "paths": []
    },
    "runtime": {
        "framework": "node",
        "version": "5.6.0",
        "js-flags": "--use_strict",  // <--- once this flag is turn on, it can't be turned off unless you clean up the temp as well.
        "ignoreFlags": true
    }
}
```

**Comment by jaredallard** [comment]
Yep it's what's I thought -- the patch stays applied.

**Comment by calebboyd** [comment]
Glad you figured it out!

**Comment by jaredallard** [comment]
We should create a separate issue about this, should be addressed. Although, arguably, all of these patches may not be easily reverted. Not sure.

**Comment by calebboyd** [comment]
#308 has a workaround for this. I'm hanging out in gitter if you want me to show you how/where

**Comment by jaredallard** [comment]
I can't join gutter right now but I'll look through it, also, we should chat about the project at some point.
