### ISSUE TITLE
debug log file output

### ISSUE THREAD

**Issue by Shawn-ye** [nexe/nexe#328]
This is a
 - [ ] Bug Report
 - [x] Feature Request
 - [ ] Other

Hi,
Is there anyways to enable debugging using debug module? I've tried console.log , console.error and also debug module. console.log & console.error work fine but debug module does not work.
I'm not sure if #155 describes the same problem, so I create a new issue.
With my package.json below.
Thanks.

`
{
    "name": "embededfiles-test",
    "version": "0.0.0",
    "private": true,
    "scripts": {
        "start": "NODE_ENV=production DEBUG='*,MainErr' node main.js"
    },
    "dependencies": {
    },
    "nexe": {
        "input": "../main.js",
        "output": "release.o",
        "resourceFiles": [
            "config.json"
        ],
        "browserify": {
            "excludes": [],
            "requires": []
        },
        "temp": "nexe_tempfiles",
        "debug": true,
        "runtime": {
            "nodeConfigureOpts": ["--fully-static"],
            "framework": "node",
            "version": "7.8.0"
        }
    }
}
`

**Comment by calebboyd** [comment]
There should be no issues using this module in v2. If you still have problems open a new issue. Thanks!
