### ISSUE TITLE
Can't excute compiled binary

### ISSUE THREAD

**Issue by karimo255** [nexe/nexe#331]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
If this is a bug report, What are the steps to reproduce?

```js
bootstrap_node.js:469
      throw new Error(`No such native module ${id}`);
      ^

Error: No such native module ./middleware/errorHandler
    at NativeModule.require (bootstrap_node.js:469:13)
    at s (compiled.js:1:176)
    at compiled.js:1:367
    at Function.load [as errorHandler] (compiled.js:8928:27)
    at Object.__dirname.104../application (compiled.js:22454:8)
    at s (compiled.js:1:316)
    at compiled.js:1:367
    at Object.__dirname.102../lib/express (compiled.js:21778:18)
    at s (compiled.js:1:316)
    at compiled.js:1:367
```

<br/><br/>
Please also provide: 

- Platform(OS/Version):Linux (Debian Jessie)
- Host Node Version:
- Target Node Version:
- Nexe version:
- Python Version:

**Comment by jaredallard** [comment]
Does `./middleware/errorHandler` exist ...? Can you provide more information? What is requiring this?

**Comment by karimo255** [comment]
@jaredallard 
Those are the requires Modules :

var express = require('express'),
    app = express(),
    http = require('http'),
    server = http.createServer(app),
    io = require('socket.io').listen(server),
    conf = require('./config.json'),
    jwt = require('jsonwebtoken'),
    bodyParser = require('body-parser'),
    socketioJwt = require('socketio-jwt'),
    async = require('async'),
    moment = require('moment'),
    sqlite3 = require('sqlite3').verbose();

    var reload = require('require-reload')(require);

    var bonPrinter = require('node-thermal-printer');
    var ordersPrinter = reload('node-thermal-printer');

**Comment by calebboyd** [comment]
`require-reload`  uses undocumented and unsupported apis. The suggested method for reloading or rerunning a module is to export a function.

See https://nodejs.org/dist/latest-v6.x/docs/api/modules.html#modules_caching
