### ISSUE TITLE
Use an installed version of 'node' to build the executable

### ISSUE THREAD

**Issue by hanu-jayaram** [nexe/nexe#332]
This is a
 - [x] Other

Is there a way to use the already installed version of 'node' instead of compiling? I have a situation where the compilation required some tweaks and need nexe to not go through with the compilation process. How to achieve this? 

Much thanks and great tool!

**Comment by calebboyd** [comment]
Hi @hanu-jayaram There is actually a feature coming in [v2](https://github.com/nexe/nexe/tree/next#example) that was put in there for the express purpose of applying "tweaks" to the build (beta in the next few days). 

Does that look like it would solve for your use case?

**Comment by hanu-jayaram** [comment]
That sounds perfect, thanks for the quick response @calebboyd, appreciate it.

**Comment by calebboyd** [comment]
No Problem! I'll post here when released. It'd be great to get your feedback

**Comment by calebboyd** [comment]
This is now available `npm i -g nexe@beta`
