### ISSUE TITLE
Error: SyntaxError: Unexpected string in JSON at positio

### ISSUE THREAD

**Issue by shopsoy** [nexe/nexe#333]
Hi,

When running the command 
`nexe -i server.js -o server.bin`

it return this error
`----> framework => nodejs
----> embedResources undefined
----> resource -> /opt/dashboard/tmp/nexe/nodejs/latest/node-v8.1.0/lib/nexeres.js
----> bundle /opt/dashboard/server.js
----> executing browserify via API
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: SyntaxError: Unexpected string in JSON at position 101 while parsing json file /opt/dashboard/package.json
    at /usr/lib/node_modules/nexe/node_modules/module-deps/index.js:522:30
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)`

T
my **package.json** already with the **nexe option**s:
{
  "name": "AnalyticsDashboard",
  "version": "1.0.0",
  "description": "",
  "main": "server.js"
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "bcrypt": "^1.0.2",
    "body-parser": "^1.16.1",
    "connect-flash": "^0.1.1",
    "connect-mongo": "^1.3.2",
    "cookie-parser": "^1.4.3",
    "ejs": "^2.5.5",
    "express": "^4.14.1",
    "express-session": "^1.15.1",
    "ini": "^1.3.4",
    "mongoose": "^4.8.3",
    "morgan": "^1.8.1",
    "mysql": "^2.12.0",
    "passport": "^0.3.2",
    "passport-local": "^1.0.0",
    "redis": "^2.6.5",
    "redis-server": "^1.1.0",
    "socket.io": "^1.7.2"
  },
  "nexe": {
	"input": "./bin/nexe",
	"output": "nexe^$",
	"temp": "src",
	"browserify": {
		"requires": [],
		"excludes": [],
		"paths": []
	},
	"runtime": {
		"framework": "node",
		"version": "6.9.4",
		"js-flags": "--use_strict",
		"ignoreFlags": true
	}
  }
}

**Comment by calebboyd** [comment]
The JSON you posted is not valid...

Missing comma after `"main": "server.js"`
Unescaped double quotes in the test script `"test": "echo "Error: no test specified" && exit 1"`

**Comment by shopsoy** [comment]
Hi,

Thanks so much for the help. Some times we need to fresh eyes to validate.

Best regards

**Comment by unsama** [comment]
{
"name": "sp-main",
"version": "0.0.0",
"private": true,
"scripts": {
"start": "nodemon ./bin/www",
"watchify": "watchify -vd -e src/Pages/Setting/main.js -o public/Modules/Setting/build.js",
"watchifypurchase": "watchify -vd -e src/Pages/Purchase/main.js -o public/Modules/Purchase/build.js",
"dev": "npm-run-all --parallel watchify start",
"build": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Setting/build.css ] -e src/Pages/Setting/main.js | uglifyjs -c warnings=false -m > public/Modules/Setting/build.js",
"build_accounting": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Accounting/build.css ] -e src/Pages/Accounting/main.js | uglifyjs -c warnings=false -m > public/Modules/Accounting/build.js",
"build_attendance": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Attendance/build.css ] -e src/Pages/Attendance/main.js | uglifyjs -c warnings=false -m > public/Modules/Attendance/build.js",
"build_calendar": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Calendar/build.css ] -e src/Pages/Calendar/main.js | uglifyjs -c warnings=false -m > public/Modules/Calendar/build.js",
"build_dashboards": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Dashboards/build.css ] -e src/Pages/Dashboards/main.js | uglifyjs -c warnings=false -m > public/Modules/Dashboards/build.js",
"build_discuess": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Discuess/build.css ] -e src/Pages/Discuess/main.js | uglifyjs -c warnings=false -m > public/Modules/Discuess/build.js",
"build_employees": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Employees/build.css ] -e src/Pages/Employees/main.js | uglifyjs -c warnings=false -m > public/Modules/Employees/build.js",
"build_expenses": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Expenses/build.css ] -e src/Pages/Expenses/main.js | uglifyjs -c warnings=false -m > public/Modules/Expenses/build.js",
"build_inventory": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Inventory/build.css ] -e src/Pages/Inventory/main.js | uglifyjs -c warnings=false -m > public/Modules/Inventory/build.js",
"build_leaves": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Leaves/build.css ] -e src/Pages/Leaves/main.js | uglifyjs -c warnings=false -m > public/Modules/Leaves/build.js",
"build_maintenance": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Maintenance/build.css ] -e src/Pages/Maintenance/main.js | uglifyjs -c warnings=false -m > public/Modules/Maintenance/build.js",
"build_manufacturing": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Manufacturing/build.css ] -e src/Pages/Manufacturing/main.js | uglifyjs -c warnings=false -m > public/Modules/Manufacturing/build.js",
"build_notes": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Notes/build.css ] -e src/Pages/Notes/main.js | uglifyjs -c warnings=false -m > public/Modules/Notes/build.js",
"build_pointofsale": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Pointofsale/build.css ] -e src/Pages/Pointofsale/main.js | uglifyjs -c warnings=false -m > public/Modules/Pointofsale/build.js",
"build_projects": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Projects/build.css ] -e src/Pages/Projects/main.js | uglifyjs -c warnings=false -m > public/Modules/Projects/build.js",
"build_purchase": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Purchase/build.css ] -e src/Pages/Purchase/main.js | uglifyjs -c warnings=false -m > public/Modules/Purchase/build.js",
"build_recruitment": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Recruitment/build.css ] -e src/Pages/Recruitment/main.js | uglifyjs -c warnings=false -m > public/Modules/Recruitment/build.js",
"build_repairs": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Repairs/build.css ] -e src/Pages/Repairs/main.js | uglifyjs -c warnings=false -m > public/Modules/Repairs/build.js",
"build_sales": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Sales/build.css ] -e src/Pages/Sales/main.js | uglifyjs -c warnings=false -m > public/Modules/Sales/build.js",
"build_testing": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Testing/build.css ] -e src/Pages/Testing/main.js | uglifyjs -c warnings=false -m > public/Modules/Testing/build.js",
"build_timesheet": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Timesheet/build.css ] -e src/Pages/Timesheet/main.js | uglifyjs -c warnings=false -m > public/Modules/Timesheet/build.js"
"build_contacts": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Timesheet/build.css ] -e src/Pages/Timesheet/main.js | uglifyjs -c warnings=false -m > public/Modules/Timesheet/build.js"
},
"browserify": {
"transform": [
"babelify",
"vueify"
]
},
"browser": {
"vue": "vue/dist/vue.common.js"
},
"dependencies": {
"babel-core": "^6.25.0",
"bcrypt-nodejs": "0.0.3",
"body-parser": "~1.15.2",
"chart.js": "^2.6.0",
"connect-flash": "^0.1.1",
"connect-history-api-fallback": "^1.3.0",
"cookie-parser": "~1.4.3",
"csurf": "^1.9.0",
"debug": "~2.2.0",
"envify": "^4.1.0",
"express": "~4.14.0",
"express-session": "^1.15.0",
"express-validator": "^3.2.1",
"jade": "~1.11.0",
"lodash": "^4.17.4",
"mongoose": "^4.11.1",
"morgan": "~1.7.0",
"multer": "^1.3.0",
"mysql": "^2.13.0",
"nodemailer": "^3.0.2",
"passport": "^0.3.2",
"passport-local": "^1.0.0",
"plotly": "^1.0.6",
"randomstring": "^1.1.5",
"serve-favicon": "~2.3.0",
"simple-ssh": "^0.9.0",
"uglify-js": "^2.8.29",
"vee-validate": "^2.0.0-rc.7",
"vue": "^2.3.4",
"vue-resource": "^1.3.4",
"vue-router": "^2.7.0",
"vue-sortable": "^0.1.3",
"vueify": "^9.4.1"
},
"devDependencies": {
"babel-core": "^6.23.1",
"babel-plugin-transform-runtime": "^6.0.0",
"babel-preset-es2015": "^6.22.0",
"babel-preset-stage-2": "^6.0.0",
"babel-runtime": "^6.0.0",
"babelify": "^7.3.0",
"browserify": "^14.1.0",
"browserify-hmr": "^0.3.1",
"browserify-middleware": "^7.1.0",
"cross-env": "^4.0.0",
"nodemon": "^1.11.0",
"npm-run-all": "^2.3.0",
"uglify-js": "^2.5.0",
"vueify": "^9.4.0",
"watchify": "^3.4.0"
}
}
: Unexpected string in JSON at position 5534

I dont know whats the error, can you help me out this?

**Comment by AbiltonDias** [comment]
O que aconteceu comigo, foi somente no inicio do projeto (package.json), 

"name":"Desafio" ,
...

E não pode tem que ser com letra minuscula,
CORRETO
"name": "desafio" ,
...

Espero ter ajudado alguém...
_________________________________________________________________________________________
What happened to me was only at the beginning of the project (package.json),

"name": "Challenge",
...

And it can't be in lower case,
RIGHT
"name": "challenge",
...

I hope I helped someone ...
