### ISSUE TITLE
Feature: Override PRODUCTVERSION and maybe FILEVERSION

### ISSUE THREAD

**Issue by JamesMGreene** [nexe/nexe#337]
This is a
 - [x] Feature Request

I would like the ability to override the [`PRODUCTVERSION` and maybe `FILEVERSION` in the "node.rc" file](https://github.com/nodejs/node/blob/v4.8.3/src/res/node.rc#L9-L12) during the build process, just as the nexe mainline currently allows us to [override various string values today using `options.rc`](https://github.com/nexe/nexe/blob/cac2759d3a0f672e38676c61618176e7703e6f41/src/patches/node-rc.js#L9-L14).

I would be fine with not being allowed access to the `FILEVERSION` value if that's preferable since I personally intend to leave that as the Node.js engine version.  However, I would like the `PRODUCTVERSION` value to reflect **my** product's version (which **is** the [intent of that field](https://msdn.microsoft.com/en-us/library/windows/desktop/aa381058.aspx)).  I can already update the string-based value for product version, e.g. `options.rc.ProductVersion = "17.3.0.0";`, but I cannot update the actual binary product version.

I'm guessing I would be able to implement my own using the new `patches` option but I would suggest that this is more of a core functionality as product versioning is a pretty important concept.

If I'm understanding all the new options correctly, I would be able to do the following with a `patches` item (based on ["src/patches/node-rc.js"](https://github.com/nexe/nexe/blob/cac2759d3a0f672e38676c61618176e7703e6f41/src/patches/node-rc.js)):

```js
export default async function nodeRcProductVersion(compiler, next) {
  const options = compiler.options.version
  if (!options || !(options.product || options.file)) {
    return next()
  }

  const file = await compiler.readFileAsync('src/res/node.rc')

  let productVersion = options.product
  if (productVersion) {
    file.contents = file.contents.replace(/PRODUCTVERSION .*$/m, `PRODUCTVERSION ${productVersion}`)
  }

  let fileVersion = options.file
  if (fileVersion) {
    file.contents = file.contents.replace(/FILEVERSION .*$/m, `FILEVERSION ${fileVersion}`)
  }

  return next()
}
```

Where `options` would look like:

```json
{
  "version": {
    "product": "17,3,0,0",
    "file": "1,2,3,4"
  },
  "rc": {
    "ProductVersion": "17.3.0.0",
    "FileVersion": "1.2.3.4"
  }
}
```

**Comment by calebboyd** [comment]
I need to get some unit tests around the individual patches. (and then integration tests)
You copied an embarrassing  error that I made in that file (clearly untested 😬 )

`file.contents` is a string that needs to be reset if something is replaced.
e.g. `file.contents = file.contents.replace(...)`

**Comment by JamesMGreene** [comment]
Good point.

**Comment by calebboyd** [comment]
Sorry for the delay on this one. Its in master and will land soon

**Comment by JamesMGreene** [comment]
🎉

**Comment by JamesMGreene** [comment]
Added in https://github.com/nexe/nexe/commit/04fdd165a411a30eb386b331acd99ddd78a74111

**Comment by JamesMGreene** [comment]
Looks like the implemented options would be as such:

```js
{
  "rc": {
    "ProductVersion": "17.3.0.0",
    "FileVersion": "1.2.3.4",
    "PRODUCTVERSION": "17,3,0,0",
    "FILEVERSION": "1,2,3,4"
  }
}
```

**Comment by calebboyd** [comment]
Righto!

**Comment by JamesMGreene** [comment]
By the way, this still needs to be documented in the README. :smile:

**Comment by calebboyd** [comment]
Docs added
