### ISSUE TITLE
.nexerc

### ISSUE THREAD

**Issue by calebboyd** [nexe/nexe#339]
Add a `.nexerc` config file option

**Comment by JamesMGreene** [comment]
Would it be treated as JSON or JS?

**Comment by calebboyd** [comment]
JSON.

If you're thinking about patches -- i plan to add support for resolving module paths too

**Comment by JamesMGreene** [comment]
\*shrugs\*

At this point, I've resigned myself to just needing to make it a JS build script to handle some dynamic things (e.g. fetching and parsing some info from another file), so I would imagine leaving it as just normal JSON should be fine.

There are a handful of well-known projects that would let you use either, though, e.g. eslint's rc files can be either JSON or JS.  Just food for thought.

**Comment by calebboyd** [comment]
Pull requests and suggestions are always welcome :)

**Comment by JamesMGreene** [comment]
In fact, ESLint actually also supports YAML as well: http://eslint.org/docs/user-guide/configuring#configuration-file-formats

**Comment by calebboyd** [comment]
Do you know if they have a parser?

**Comment by JamesMGreene** [comment]
For YAML parsing, they appear to use [js-yaml](https://www.npmjs.com/package/js-yaml)

All their config file prioritization and loading seems be to taken care of in [lib/config/config-file.js](https://github.com/eslint/eslint/blob/f307aa0bd4a21bd9e6147a067b30564f85c9a4df/lib/config/config-file.js)

**Comment by calebboyd** [comment]
Hey @JamesMGreene what do you think of [cosmiconfig](https://www.npmjs.com/package/cosmiconfig)?

**Comment by JamesMGreene** [comment]
I've never heard of it before but, looking at it now, I like its concept but I feel that it gives the exact **opposite** precedence order that I would expect. :confused:

**Comment by anchnk** [comment]
Has this feature landed ? Just curious about the state of this 

Reading cosmiconfig documentation today and it seems that the default precedence order would match what you would expect now (and can be overridden with a custom array).
