### ISSUE TITLE
ERROR: trying to use package.json variables, but not setup to do so!

### ISSUE THREAD

**Issue by defusiondev** [nexe/nexe#347]
This is a
 - [*] Other

<br/>
I've installed nexe and inside a basic command line app I've built I'm running nexe -o file.exe and it's giving me the error:

```
....> ERROR: trying to use package.json variables, but not setup to do so!
```

I've seen a stackoverflow article that said I need to add a nexe entry to my package.json which I've done but it makes no difference. I have not included it programmatically at all in my index.js file. 

package.json
```
{
  "name": "scanner",
  "version": "1.0.0",
  "description": "Scanner",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "node-localstorage": "^1.3.0",
    "request": "^2.81.0",
    "serialport": "^5.0.0-beta8"
  },
  "nexe": {
    "input": "./bin/nexe",
    "output": "nexe^$",
    "temp": "src",
    "browserify": {
        "requires": [],
        "excludes": [],
        "paths": []
    },
    "runtime": {
        "framework": "node",
        "version": "5.6.0",
        "js-flags": "--use_strict",
        "ignoreFlags": true
    }
}
}

```

<br/><br/>
Please also provide: 

- Platform(OS/Version): Windows 10 / MacOS Sierra
- Host Node Version: 6.11.1 / 6.9.1
- Target Node Version: ?
- Nexe version:  1.1.3 
- Python Version: 2.7.10  (Mac)

**Comment by calebboyd** [comment]
`package.json` was a feature in 1.0. Please take a look at configuration for 2.0.0 -- If you have questions or feature requests please open a new issue
