### ISSUE TITLE
Configuration for NativeModulesPlugin

### ISSUE THREAD

**Issue by jcrountree** [nexe/nexe#349]
This is a
 - [ ] Bug Report
 - [ ] Feature Request
 - [ X] Other

<br/>
I'm having trouble using the new NativeModulesPlugin for fuse.  I have a locally build ".node" add on.  
The build works, but I get a runtime error.  The feature doesn't seem to documented outside of  the example linked from the readme, so it's very possible that I simply don't have it configured correctly.

Here is my build script, which I run with 
```
node build.js
``` 

```javascript
var FuseBox = require('fuse-box').FuseBox;
var nexe = require('nexe');
var NativeModulePlugin  = require('nexe/lib/bundling/fuse').NativeModulePlugin;
var fuse = FuseBox.init({
  homeDir: './',
  cache: true,
  log: false,
  debug: false,
  output: 'build/$name.js',
  plugins: [
    new NativeModulePlugin({
      NativeBindings: {
        additionalFiles: [
          './bin/NativeBindings.node'
        ]
      }
    })
  ]
});
fuse.bundle('app')
    .target('electron')
    .instructions(`> app.js`);
fuse.run().then(function(){
  console.log('fuse succeeds');
  return nexe.compile({
      input: 'build/app.js',
      output: './app.exe',
      vcBuild: ["x64"],
      resources: [
        "public/**/*",
        "views/**/*.jade"
      ],
      verbose: true
    });
  }).then(function() {
    console.log('success');
  }).catch(function(e) {
    console.log('Unexpected error: ' + e);
  });

```
The exe successfully builds

```
√ Downloading Node: 100%...
√ Extracting Node...
√ Compiling result
√ Scanning existing binary...
√ Configuring node build: 
√ Compiling Node with arguments: x64
√ Writing result to file
√ Executable written to: ./app.exe
√ Finsihed in 1105.07s
```

But when I try to run it, this is my stacktrace:
```
TypeError: Cannot read property 'filename' of undefined
    at c (app.js:115274:3145)
    at Function.r.import (app.js:115274:3747)
    at d (app.js:115271:15)
    at app.js:115274:1
    at NativeModule.compile (bootstrap_node.js:563:7)
    at NativeModule.require (bootstrap_node.js:506:18)
    at _third_party_main.js:73:1
    at NativeModule.compile (bootstrap_node.js:563:7)
    at Function.NativeModule.require (bootstrap_node.js:506:18)
    at bootstrap_node.js:92:22
```

<br/><br/>
Please also provide: 

- Platform(OS/Version): Windows 10
- Host Node Version: 8.2.0
- Target Node Version: 8.2.0
- Nexe version: 2.0.0-beta.2
- Python Version: 2.7.13

**Comment by calebboyd** [comment]
Hmm yes, I may not have accounted for this case. Try passing an empty object to the plugin

Like so `new NativeModulePlugin({})`.  It does not require any configuration if all that is being bundled is a `.node` file

**Comment by jcrountree** [comment]
If I just did  `new NativeModulePlugin({})`, then how would it know where my .node file is?  As of right now, the .node is in ./bin/, and my .js files require it with relative paths (eg. `require ('../../bin/NativeBindings')`).

**Comment by jcrountree** [comment]
Thanks for the help, by the way :).

I moved my `NativeBindings.node` file to my `node_modules/` folder, and I changed all of my require statements to `require('NativeBindings');`.  Then I ran script above, except with `new NativeModulePlugin({})`. I'm sill getting the runtime error:

```
TypeError: Cannot read property 'filename' of undefined
    at c (app.js:829:3145)
    at Function.r.import (app.js:829:3747)
    at d (app.js:826:15)
    at app.js:829:1
    at NativeModule.compile (bootstrap_node.js:563:7)
    at NativeModule.require (bootstrap_node.js:506:18)
    at _third_party_main.js:73:1
    at NativeModule.compile (bootstrap_node.js:563:7)
    at Function.NativeModule.require (bootstrap_node.js:506:18)
    at bootstrap_node.js:92:22
```

**Comment by calebboyd** [comment]
Hi @jcrountree I think you might need to update fusebox to >=2.2.1

**Comment by jcrountree** [comment]
```
    "fuse-box": "^2.2.1"
    "nexe": "^2.0.0-beta.3"
```

I just tried again, and I got 

```
.\app.exe
app.js:12089
    throw new TypeError('argument fn must be a function')
    ^

TypeError: argument fn must be a function
    at Function.wrapfunction [as function] (app.js:12089:11)
    at populateConstructorExports (app.js:15299:45)
    at Number.<anonymous> (app.js:15081:1)
    at c (app.js:114619:3281)
    at w.require (app.js:114619:3065)
    at Number.<anonymous> (app.js:13986:19)
    at c (app.js:114619:3281)
    at w.require (app.js:114619:3065)
    at Number.<anonymous> (app.js:2982:12)
    at c (app.js:114619:3281)
```

I had hoped to use nexe to have an easy way to share my node.js based Windows app with some people at my company, but I ended up just writing a grunt task to zip everything thing.  I don't think I'll be spending more time with nexe for this particular project, so I will close this issue.  I still think nexe is a great idea, and very helpful in a lot of cases, so thanks for making it!
