### ISSUE TITLE
Not Working (Windows 10 x64)

### ISSUE THREAD

**Issue by gpresland** [nexe/nexe#350]
This is a
 - [x ] Bug Report
 - [ ] Feature Request
 - [ ] Other

- Platform(OS/Version):
- Host Node Version: 8.1.4
- Target Node Version: 8.1.4
- Nexe version: 1.1.3
- Python Version: 
Tried:
- Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)] on win32
- Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32

Running:

```bash
nexe -i ./dist/index.js -o ./app.exe
```

Produces:

```
 √ Using the cwd's main file as the main module
√ Source already downloaded
√ Node binary compiled
- Writing result to fileevents.js:182
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'D:\Dev\node\MyProject\.nexe\8.1.4\Release\node.exe'
```

Installing Nexe locally with 2.7 Python yield blank output and nothing happens.

**Comment by gpresland** [comment]
Appears to be working when used programmatically using a build script like:

```js
const nexe = require("nexe");

nexe.compile({
    flags: true,
    input: INPUT,
    output: EXECUTABLE_NAME,
    nodeVersion: NODE_VERSION,
    nodeTempDir: "nexe_node",
    framework: "node",
    resourceFiles: []
  },
  (error) => console.error(error.message)
);
```

**Comment by calebboyd** [comment]
@gpresland Which version are you using? You stated 1.1.3, but the output is from 2, and the programmatic config is for 1.1.3

**Comment by dlech** [comment]
I just hit the same issue with 2.0.0-beta6 using node 6.11.0.

> √ Node binary compiled

is shown after 1 or 2 seconds, so obviously, it is not actually compiling.

**Comment by dlech** [comment]
Running `vcbuild.bat` manually, it looks like it requires Visual Studio 2015, whereas I only have Visual Studio 2017 installed.

**Comment by calebboyd** [comment]
Please try the latest version! (2.0.0-rc.2)

**Comment by dlech** [comment]
What exactly was fixed? 

I fixed my issue locally by install VS 2015. But, it seems to me that the real problem is that `vcbuild.bat` always returns a successful exit code even when it fails, which throws you off track because you are looking in the wrong place for an error.

**Comment by calebboyd** [comment]
Windows targets are no longer required to be built -- they're hosted in github releases.
