### ISSUE TITLE
Is it possible for someone to retrieve the source script from an exe packed by nexe

### ISSUE THREAD

**Issue by capstar** [nexe/nexe#351]
This is a 
 - [ ] Bug Report
 - [ ] Feature Request
 - [x] Other

<br/>

I created an executable test2 on Ubuntu by running command
```
nexe -i test2.js -o test2
```
Wonder if it's possible for someone to retrieve the source script test2.js from the executable.  

Thanks.

**Comment by calebboyd** [comment]
Yes, Nexe just embeds your code, like it is a core module
