### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by satanch** [nexe/nexe#352]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [x] Other

<br/>

I was trying to build with:
```
/* jshint esversion: 6 */
/* jshint node: true */

const nexe = require("nexe");

nexe.compile({
    build: false,
    flags: true,
    input: 'D:/speech-emote/index.js',
    output: 'D:/speech-emote/sstg.exe',
    nodeTempDir: "nexe_node",
    framework: "nodejs",
    resourceFiles: [],
    python: 'C:/Python27'
  },
  (error) => {
    if (error) {
      return console.error(error.message);
    }
  }
);

```

But I'm getting this:

```
PS D:\speech-emote> node compile
openssl config failed: error:02001003:system library:fopen:No such process
√ Using input file as the main module: D:/speech-emote/index.js
√ Node source extracted to: D:\speech-emote\.nexe\6.11.1
√ Node binary compiled
- Writing result to fileevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'D:\speech-emote\.nexe\6.11.1\Release\node.exe'
    at Error (native)
```

If I trying to put binary by myself I'm getting:

```
PS D:\speech-emote> node compile
openssl config failed: error:02001003:system library:fopen:No such process
√ Using input file as the main module: D:/speech-emote/index.js
√ Source already downloaded
- Compiling resultBinary: D:\speech-emote\.nexe\6.11.1\Release\node.exe is not compatible with nexe
(node:9336) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Binary: D:\speech-em
ote\.nexe\6.11.1\Release\node.exe is not compatible with nexe
/ Scanning existing binary...PS D:\speech-emote>
```

Whan am I doing wrong? Should I compile node, what software installed do I need?

<br/>

- Windows 8.1 x64
- v6.11.1
- v6.11.1
- Nexe version: beta
- Python Version: 2.7

**Comment by gerard2p** [comment]
I have the same error, seems like the VS project is not generated/compiled.
I ran ./vcbuild.bat inside **.nexe/NODE_VERSION/** making sure Python2.7 is the default version in my environment.

I did build the binary, but I whe I tried to run the app bundled with the compiled node version I just sent and error that can not be traced.

**Comment by skicean** [comment]
I have the same error . Is show 'Node binary compiled', but I cannot find the node.exe.

**Comment by calebboyd** [comment]
@gerard2p and @skicean You both have 
`openssl config failed: error:02001003:system library:fopen:No such process`?

@satanch This error looks like node and npm might not be installed correctly.

Also, you indicated you're using the beta version but the usage matches v1.

**Comment by skicean** [comment]
@gerard2p 
my error:
D:\dev\naxe>nexe -i logtext.js -o app.exe
√ Using input file as the main module: logtext.js
- Downloading Node.js source from: https://nodejs.org/dist/v6.10.2/node-v6.10.2.
√ Source already downloaded
√ Node binary compiled
- Writing result to fileevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'D:\dev\naxe\.nexe\6.10.2\Release
\node.exe'
    at Error (native)

**Comment by linslin** [comment]
Same error for me. Any help what be appreciated. Thanks

**Comment by satanch** [comment]
@calebboyd NPM working fine, still same error.

**Comment by iSkore** [comment]
+1

**Comment by aurothic** [comment]
I'm also experiencing this issue.

```
PS C:\node\yacag> nexe -i ./yacag.js -o ./yacag.exe
√ Using input file as the main module: ./yacag.js
√ Node source extracted to: C:\node\yacag\.nexe\6.11.2
√ Node binary compiled
- Writing result to fileevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\node\yacag\.nexe\6.11.2\Release\node.exe'
    at Error (native)
```

**Comment by systemmind** [comment]
I have the same problem. nexe is working for me on simple project but it throws the same error on my large project. I am using some es6 features like classes and I guess nexe does not support es6 yet, so it can be the reason why error appears. [Here](https://github.com/nexe/nexe/issues/293) people says that the es6 code should be run through babel transpiler and then compiled using nexe.

**Comment by calebboyd** [comment]
@systemmind what version are you using?

**Comment by calebboyd** [comment]
You will need to ensure you can build node see #364

**Comment by systemmind** [comment]
I have 6.11.1 node installed. I have created some test project with 2 js files and nexe runs well and node.js is building without issues. But the same is not working for another project.
The manual building of node is working well as well.

But, I have updated the node to 8.4.0 and it looks the upgrading fixes issue.

**Comment by calebboyd** [comment]
@skicean Great!
Note: 
Node 6 requires visual studio 2015
Only starting with Node 8 can VS2017 be used.

**Comment by calebboyd** [comment]
Please try V2. If you continue to have problems, please open a new issue
