### ISSUE TITLE
Using nexe@beta on Manjaro Linux errors on checking compiled node binary

### ISSUE THREAD

**Issue by reinaldorauch** [nexe/nexe#354]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

Steps to reproduce:
- Create a folder, initialize it with npm init and use default settings.
- Create a index.js file with this content:
  ```
  console.log("Hello World");
  ```
- Install nexe@beta in project with ```npm i -D nexe@beta```
- Run ```npx nexe -i index.js -o index```
- Output would be:
```
✔ Using input file as the main module: index.js
✔ Node source extracted to: /home/reinaldoacr/projetos/nexe-test/.nexe/8.1.4
✔ Node binary compiled
⠋ Writing result to fileevents.js:182
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/home/reinaldoacr/projetos/nexe-test/.nexe/8.1.4/out/Release/node'
```

<br/><br/>
Please also provide: 

- Platform(OS/Version): 
```
lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	17.0.2
Codename:	Gellivara
```
```
uname -a
Linux reinaldo-note-manjaro 4.9.38-1-MANJARO #1 SMP PREEMPT Sat Jul 15 12:04:06 UTC 2017 x86_64 GNU/Linux
```
- Host Node Version: v8.1.4
- Target Node Version: v8.1.4
- Nexe version: 2.0.0-beta.2
- Python Version: python 3.6.1, python2 2.7.13

**Comment by Tchoumi** [comment]
i think perhaps you should add the version of nexe you  are using .some thing like that : ```nexe -i indexe.js -o logging.exe --version 8.0.0. ``

**Comment by calebboyd** [comment]
Did you try setting `-p`? Since `python` is occupied by python 3?

**Comment by calebboyd** [comment]
I might see if that can be detected...

**Comment by reinaldorauch** [comment]
Yeah, used that and it didn't worked at all. It made the check if I was using python 3 instead python 2 and I had to switch to python2 to be able to get this. Sorry for the late reply.

**Comment by calebboyd** [comment]
I think this is just a classic node build problem. GYP doesn't always use $PYTHON...
You can probably fix it temporarily by doing the following in the session you're running nexe in.

```
mkdir -p ~/bin/
ln -s $(which python2) ~/bin/python
export PATH=~/bin/:$PATH
```

**Comment by reinaldorauch** [comment]
Oh, I see, will try with that. Thanks :D

**Comment by calebboyd** [comment]
I don't think its appropriate for nexe to create a symlink anywhere. So, Instead I'll just make a note of this in the readme
