### ISSUE TITLE
executable can't be run, access denied (windows 10)

### ISSUE THREAD

**Issue by tswaters** [nexe/nexe#355]
Found this module in a reddit thread and figured I would try it out.

This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
If this is a bug report, What are the steps to reproduce?

```
c:\users\tyler>type logtest.js

console.log("test")

C:\Users\tyler>node -v
v8.2.1

C:\Users\tyler>npm -v
5.3.0

C:\Users\tyler>python --version
Python 2.7.11

C:\Users\tyler>nexe -i logtest.js -o logtest.exe
√ Using input file as the main module: logtest.js
- Downloading Node.js source from: https://nodejs.org/dist/v8.2.1/node-v8.2.1.ta
√ Source already downloaded
√ Node binary compiled
√ Executable written to: logtest.exe
√ Finsihed in 1676.911s  ### whoa, it really did take 27 minutes... I guess that's compiling node for ya

C:\Users\tyler>dir | find "logtest"
2017-07-30  18:59        24,785,922 logtest.exe   ### yikes, i suppose this is expected
2017-07-30  18:15                23 logtest.js

c:\Users\tyler> logtest.exe
Access is denied.
```

After the last command was entered, a windows 10 prompt showed:

>This app can't be run on your PC
>To find a version for your PC, check with the software publisher

```
- Platform(OS/Version):  Windows 10 Version 1703 (OS Build 15063.483)
- Host Node Version: v8.2.1
- Target Node Version: v8.2.1
- Nexe version:  2.0.0-beta.2
- Python Version: v2.7.11
```

 Please let me know if there's any other information I can provide to help diagnose this.

**Comment by FloMaetschke** [comment]
I have got the same error with "nexe": "^2.0.0-beta.2".
It worked before with the old 1.x version,
The reason i needed to update was to get a build agent on linux working to compile for windows.
I would love to see a simple sample on how to do that.

**Comment by FloMaetschke** [comment]
I tried the console.log("test"); example code to compile.

inside an index.js it worked for me with:  
`nexe -o test.exe --build`

Now trying on linux and also on linux for win.

My real project is defect at the moment.

**Comment by FloMaetschke** [comment]
linux worked, too. i was able to change the hello world output and compile in no time. - nice.
I tried a fresh compile with --target windows-x64-7.0.0 but it was just a linux binary. (which worked).

I can't get my old program to work, I will open an seperate issue for it.

**Comment by calebboyd** [comment]
Thanks. Just returning from a trip I will look at this soon.

@FloMaetschke The --target option is not yet supported while in beta

**Comment by calebboyd** [comment]
@tswaters What version of visual studio do you have? I don't have any problems with that configuration... (im assuming you have a typo and meant `logtest.js`)

**Comment by tswaters** [comment]
Correct.  I did mean `logtest.js` I've updated that.

I have `Microsoft Visual Studio Community 2015 Version 14.0.25123.00 Update 2`

I've also followed option 1 from here https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules to get native modules to compile.... i.e.,  I've installed [ Visual C++ Build Tools](http://go.microsoft.com/fwlink/?LinkId=691126)

**Comment by calebboyd** [comment]
Thanks for the detail @tswaters. Is this all you were compiling? `console.log('test')` ? Or did you try to include native modules as well

**Comment by tswaters** [comment]
Correct, just the one line:  `console.log("test')`

I tried it again with `--build` flag, as @FloMaetschke did, also tried renaming to `index.js` and omitting the `-i` flag... same results each time. 

I can probably upload the generated executable somewhere if that would help.

**Comment by calebboyd** [comment]
Hmm Okay, This looks like it might be on my end. Can you drop the file somewhere?

**Comment by calebboyd** [comment]
Both would be most helpful

**Comment by tswaters** [comment]
@calebboyd I've zipped them, here https://file.io/TtS26G

**Comment by calebboyd** [comment]
Hmm 404

**Comment by tswaters** [comment]
well.. what a shoddy service haha.  give me a second,

**Comment by tswaters** [comment]
https://file.io/cRaOaP ?

**Comment by calebboyd** [comment]
Something is unfurling the link, just give me the ending it should stick around then

**Comment by tswaters** [comment]
try this one?  https://dropfile.to/GqOXJJj
that's all that service gave me...

**Comment by calebboyd** [comment]
Just published 2.0.0-beta.3 It should hopefully resolve the problem!

**Comment by tswaters** [comment]
it works!  thanks

**Comment by calebboyd** [comment]
So nexe will use the existing/already built executable if it can (in this case it uses Release\node.exe. 
It performs a streaming copy, layering in your new code. -- So your "rebuild" is super fast. The problem you were having was it was layering in an extra line ending.. `\r\n` and had an extra byte

Release\node.exe will always be the base build. It specifically won't work well if you expect to use resources, because the embedded files won't have the correct offsets

Every nexe executable will have some amount of buffer, If you want to remove the buffer you can pass `--padding 0` (i don't have much documentation around that yet, but thats the gist), If you do remove all padding though, the feedback cycle will be -- that initial 27 minute compile.

**Comment by calebboyd** [comment]
When beta hits rc nexe will be hosting "base builds" on github releases. So 99% of scenarios won't require actually building node
