### ISSUE TITLE
Memory access problems when running compiled artifact. - not working

### ISSUE THREAD

**Issue by FloMaetschke** [nexe/nexe#356]
This is a
 - [ x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>

```
nexe -i myapp -o server.exe --build
```

<br/><br/>
Please also provide: 

- Platform(OS/Version): Windows 10
- Host Node Version: 7.0.0
- Target Node Version: 7.0.0
- Nexe version: 2 beta
- Python Version: 2.7
I am able to compile a simple hello world without any problems.

I am unable to execute my real nodejs program.
I guess its because of its dependencys:
```
var net = require('net');
var cookieSession = require('cookie-session')
var fs = require('fs');
var path = require('path');
var bodyParser = require('body-parser');
var _ = require('lodash');
var express = require('express');
var https = require('https');
var mkdirp = require('mkdirp');
```
Do i have to define native bindings?

I tried bundling my source files (backend) with webpack but execution is without any success, too.
Compilation is successful.

I get memory access errors on linux, 
Windows says error like 0x00..0017 or or 0x000...005 which seems to be memory related, too.

I was able to compile my code with the old version of nexe, the new version does not work yet.

Any idea, what i am doing wrong, or is there something missing in the new version ?

**Comment by calebboyd** [comment]
You will have to make changes for native modules. What native modules are you using?

**Comment by FloMaetschke** [comment]
Please have a look at my require statements. I dont know if i require any further definitions.
I tried latest beta6 without success.

**Comment by FloMaetschke** [comment]
I assume i don't have any native modules in use.
Please have a look here for further bug-hunting. 
https://github.com/nexe/nexe/issues/362
