### ISSUE TITLE
Segmentation fault on Linux Ubuntu and OS X

### ISSUE THREAD

**Issue by StamKaly** [nexe/nexe#358]
I find `nexe` to be poorly documented. I am on Ubuntu 16.04, using node 8.2, python 2.7 and nexe beta. I am trying to make a standalone binary from `bin.js` included in package `srt-to-vtt`. 
After having `srt-to-vtt` installed with `npm`, I edited `bin.js` to import the module as `srt-to-vtt` rather than `./`. Then I ran:
`nexe -i node_modules/srt-to-vtt/bin.js -o srt-to-vtt`, but the binary created gave me error `No such built-in module: srt-to-vtt`. After that I went to the directory srt-to-vtt was installed in, and tried compiling it again, same error. I then edited `package.json` that was in there, and added an `nexe` field with `requires` which had the file `index.js`(`srt-to-vtt`) exported as `srt-to-vtt`. Trying recompiling again, and the resulted binary, gave the same error. How do you `require` normal modules? Can there be added any examples? Thanks

**Comment by calebboyd** [comment]
Please take a look at the template you removed. Can you provide:

- Platform(OS/Version):
- Host Node Version:
- Target Node Version:
- Nexe version:
- Python Version:

Thanks!

**Comment by StamKaly** [comment]
- Platform(OS/Version): Linux Ubuntu 16.04 LTS
- Host Node Version: 8.2.1
- Target Node Version: 8.2.1
- Nexe version: beta
- Python Version: 2.7.12

**Comment by calebboyd** [comment]
The beta doesn't support bundling (yet)
The usage example indicates you should use a bundle

>
>Existing application bundle:
>- `nexe -i ./my-app-bundle.js -o ./my-app.exe`


If you need an example on how to bundle your application you can find one in the [examples directory](https://github.com/nexe/nexe/blob/master/examples/native-build/build.js)

Let me know if you have other questions

**Comment by StamKaly** [comment]
Having cloned this repo, and changed directory into the examples, I am getting error `Cannot find module '../../lib/bundling/fuse'` when I run `node build.js`.

**Comment by calebboyd** [comment]
You don't need that plugin unless you're planning on bundling native modules. And even then you can just require it with `require('nexe/lib/bundling/fuse')`

**Comment by calebboyd** [comment]
The example just demonstrates a fusebox configuration

**Comment by StamKaly** [comment]
What I need is bundling some table `json` files that `iconv-lite` needs in order to work, I saw that you used it to add additional files for zmq, so I guessed that would also work for me...

**Comment by StamKaly** [comment]
Is there another way to provide those files?
Here is one of the warning I am getting, they are all similar:
`WARNING The contents of /root/nexe/node_modules/iconv-lite/encodings/tables/shiftjis.json weren't loaded. Missing a plugin?`

**Comment by calebboyd** [comment]
Ahh, You can use the JSONPlugin from fuse-box

```
const JSONPlugin = require('fuse-box').JSONPlugin

FuseBox.init({
    ...
    plugins : [
         JSONPlugin()
    ]
});
```

Hopefully when we're out of beta this will be supported ootb

**Comment by StamKaly** [comment]
Bundling works now! Unfortunately, though, after I compiled with `nexe`, the executable returned `Segmentation fault (core dumped)`. What is the problem in this case? Running the bundle with `node` works fine. Thanks

**Comment by calebboyd** [comment]
weird!
can you zip up the bundle + executable here?

https://dropfile.to/

**Comment by calebboyd** [comment]
What version of the beta are you using `nexe version`?

**Comment by StamKaly** [comment]
The latest one, probably, `nexe@2.0.0-beta.3`

**Comment by calebboyd** [comment]
@StamKaly, Thanks for bringing this issue to my attention. It looks like this is linux specific (ELF binaries) 
Where the encoding is not consistent, So the way nexe rebuilds the binary isn't going to work in its current form. I have a workaround that I plan on applying.

**Comment by MythicManiac** [comment]
Also receiving `Segmentation fault: 11` here

Same issue from what I can tell, started happening when attempted to build from a bundle. Running on OS X.

**Comment by astefanutti** [comment]
I also face `Segmentation fault: 11` on Mac OS X.

**Comment by calebboyd** [comment]
This should be fixed in the latest beta, Please clear the temp files!

**Comment by astefanutti** [comment]
I confirm I don't have the error on Mac OS X with Nexe 2.0.0-beta.7.
