### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '../src/node_version.h'

### ISSUE THREAD

**Issue by monkeysuffrage** [nexe/nexe#359]
----> framework => node
----> embedResources undefined
----> resource -> C:\cygwin\home\owner\node\phantom\src\node\8.2.1\node-v8.2.1\lib\nexeres.js
----> bundle phantom.js
----> executing browserify via API
....> WARNING: src/node.js doesn't exist. Trying 'lib/internal/bootstrap_node.js'
----> re-injecting v8 args
----> vcbuild [make stage]
Note: vcbuild no longer signs by default. "nosign" is redundant.
Traceback (most recent call last):
  File "tools\getnodeversion.py", line 10, in <module>
    f = open(node_version_h)
IOError: [Errno 2] No such file or directory: '../src/node_version.h'
Traceback (most recent call last):
  File "tools\getnodeversion.py", line 10, in <module>
    f = open(node_version_h)
IOError: [Errno 2] No such file or directory: '../src/node_version.h'
Cannot determine current version of Node.js
....> ERROR: The release executable has not been generated. This indicates a failure in the build process. There is likely additional information above.

This is a
 - [x ] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
If this is a bug report, What are the steps to reproduce?
Here is the script I ran:
var nexe = require('nexe');

nexe.compile({
	input: 'phantom.js', // where the input file is
	output: '.', // where to output the compiled binary
	nodeVersion: '8.2.1', // node version
	nodeTempDir: 'src', // where to store node source.
	nodeConfigureArgs: ['opt', 'val'], // for all your configure arg needs.
	nodeMakeArgs: ["-j", "4"], // when you want to control the make process.
	nodeVCBuildArgs: ["nosign", "x64"], // when you want to control the make process for windows.
										// By default "nosign" option will be specified
										// You can check all available options and its default values here:
										// https://github.com/nodejs/node/blob/master/vcbuild.bat
	//python: 'path/to/python', // for non-standard python setups. Or python 3.x forced ones.
	//resourceFiles: [ 'path/to/a/file' ], // array of files to embed.
	//resourceRoot: [ 'path/' ], // where to embed the resourceFiles.
	//flags: true, // use this for applications that need command line flags.
	jsFlags: "--use_strict", // v8 flags
	//startupSnapshot: 'path/to/snapshot.js', // when you want to specify a script to be
											// added to V8's startup snapshot. This V8
											// feature deserializes a heap to save startup time.
											// More information in this blog post:
											// http://v8project.blogspot.de/2015/09/custom-startup-snapshots.html
	framework: "node" // node, nodejs, or iojs
}, function(err) {
	if(err) {
		return console.log(err);
	}

	 // do whatever
});

```
//provide configuration here
```

<br/><br/>
Please also provide: 

- Platform(OS/Version):
Windows 10
- Host Node Version:
8.2.1
- Target Node Version:
8.2.1
- Nexe version:
1.1.3
- Python Version:
2.7.10

**Comment by calebboyd** [comment]
Building node is no longer required in the latest rc
