### ISSUE TITLE
the application is unable to start correctly 0xc0000005

### ISSUE THREAD

**Issue by FloMaetschke** [nexe/nexe#362]
This is a
 - [x ] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
nexe -i  myapp.bundle.js -o myapp.exe
or
nexe -i  myapp.bundle.js -o myapp.exe --target win32-x64-7.0.0
or
nexe -i  myapp.bundle.js -o myapp.exe --target win32-x64-7.0.0 --vcBuild x64

Please also provide: 

- Platform(OS/Version):Windows 10
- Host Node Version: 7.0.0
- Target Node Version: 7.0.0
- Nexe version: 2.0.0-beta.6
- Python Version: 2.7.6

Compile successfully.
Crashes on start withot any message when run from commandline.
When run from explorer, the following message appears:

 the application is unable to start correctly 0xc0000005

![image](https://user-images.githubusercontent.com/7500948/29464987-fa28d882-8437-11e7-9af2-156c29e52370.png) 
(German Windows Error)

I have no clue how to solve this.

**Comment by FloMaetschke** [comment]
![image](https://user-images.githubusercontent.com/7500948/29465571-0a8a35c0-843a-11e7-9f90-67677910fb0f.png)

This is whats in my windows events application log:
Application Error:
Exceptioncode: 0xc0000005
Erroroffset: 0x000729b3
[backend-compile.zip](https://github.com/nexe/nexe/files/1234823/backend-compile.zip)

**Comment by calebboyd** [comment]
Are you able to execute your bundle as expected using `node myapp.bundle.js`?

**Comment by calebboyd** [comment]
Please try the latest version!

**Comment by FloMaetschke** [comment]
```
PS C:\Projekte\mde2\build> nexe -v
2.0.0-rc.2
PS C:\Projekte\mde2\build> nexe backend.js -o mde2-server
i nexe 2.0.0-rc.2
Acorn error: Invalid number (15433:15)
File: C:\Projekte\mde2\build\backend.js

15431
15432      if (mode === undefined) {
15433          mode = 0777 & (~process.umask());
15434      }
15435      if (!made) made = null;
15436
15437      var cb = f || function () {};


\ Fetching prebuilt binaryError: windows-x64-7.0.0 not available, create one using --build --empty
    at NexeCompiler.<anonymous> (C:\Users\mt\AppData\Roaming\npm\node_modules\nexe\lib\compiler.js:206:35)
    at step (C:\Users\mt\AppData\Roaming\npm\node_modules\nexe\lib\compiler.js:40:23)
    at Object.next (C:\Users\mt\AppData\Roaming\npm\node_modules\nexe\lib\compiler.js:21:53)
    at fulfilled (C:\Users\mt\AppData\Roaming\npm\node_modules\nexe\lib\compiler.js:12:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)PS C:\Projekte\mde2\build>
PS C:\Projekte\mde2\build> nexe backend.js -o mde2-server --build --empty
i nexe 2.0.0-rc.2
√ Node source extracted to: C:\Projekte\mde2\build\.nexe\7.0.0
√ Node binary compiled
√ Executable written to: mde2-server.exe
√ Finsihed in 703.7s


PS C:\Projekte\mde2\build> .\mde2-server.exe

_third_party_main.js:12
  throw 'Invalid Nexe binary'
  ^
Invalid Nexe binary
```

Its still not working.
Any idea what i am doing wrong?

Win10 x64.

**Comment by FloMaetschke** [comment]
I also tested setting a valid target:
```

PS C:\Projekte\mde2\build> nexe backend.js -o mde2-server --build --empty --target win32-x64-7.0.0
i nexe 2.0.0-rc.2
√ Source already downloaded
√ Node binary compiled
√ Executable written to: mde2-server.exe
√ Finsihed in 108.709s
PS C:\Projekte\mde2\build> .\mde2-server.exe

_third_party_main.js:12
  throw 'Invalid Nexe binary'
  ^
Invalid Nexe binary
```

**Comment by FloMaetschke** [comment]
I got the same result, when specifying node version 6.10.3:

```
PS C:\Projekte\mde2\build> nexe backend.js -o mde2-server --build --empty --target win32-x64-6.10.3 --version 6.10.3
i nexe 2.0.0-rc.2

√ Node source extracted to: C:\Projekte\mde2\build\.nexe\6.10.3
√ Node binary compiled
√ Executable written to: mde2-server.exe
√ Finsihed in 663.08s
PS C:\Projekte\mde2\build>
PS C:\Projekte\mde2\build> .\mde2-server.exe

_third_party_main.js:12
  throw 'Invalid Nexe binary'
  ^
Invalid Nexe binary
```

btw. the error message "unable to start correctly 0xc0000005" is gone.

**Comment by calebboyd** [comment]
Thanks for giving it a try: 
>Its still not working.
>Any idea what i am doing wrong?
>Win10 x64.

Right now the code is parsed in module mode (es6), which is not configurable at the moment, 

However you can just use an octal literal `0o777` or parseInt('0777', 8) instead of that other non-portable code

-----

For your last two you just need to remove the `--empty` flag... That ignores your input

**Comment by FloMaetschke** [comment]
Compiled and running. YES!
I had to fix 2 octal literal values with the method you mentioned. Thx alot.

This code is from an other library. I just have a small express application with cookies and sockets.
Is it already possible to build just my code without the need to bundle it before?
