### ISSUE TITLE
Writing result to fileevents.js:182       throw er; // Unhandled 'error' event       ^  Error: ENOENT: no such file or directory, open 'node.exe'

### ISSUE THREAD

**Issue by iseriousnoob** [nexe/nexe#363]
This is a
 - [X] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>

calling nexe.compile (input is a small file) inside a node script
results in a 0 Byte exe

`Looking for Visual Studio 2017
calling: "D:\Saved Games\Visual Studio 2017\VC\\Auxiliary\Build\vcvarsall.bat" amd64
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26730.10
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Found MSVS version 15.0
"C:\Users\*********\.windows-build-tools\python27\python.exe" configure  --dest-cpu=x64 --tag=
creating icu_config.gypi
* Using ICU in deps/icu-small
creating icu_config.gypi
{ 'target_defaults': { 'cflags': [],
                       'default_configuration': 'Release',
                       'defines': [],
                       'include_dirs': [],
                       'libraries': []},
  'variables': { 'asan': 0,
                 'coverage': 'false',
                 'debug_devtools': 'node',
                 'debug_http2': 'false',
                 'debug_nghttp2': 'false',
                 'force_dynamic_crt': 0,
                 'host_arch': 'x64',
                 'icu_data_file': 'icudt59l.dat',
                 'icu_data_in': '..\\..\\deps/icu-small\\source/data/in\\icudt59l.dat',
                 'icu_endianness': 'l',
                 'icu_gyp_path': 'tools/icu/icu-generic.gyp',
                 'icu_locales': 'en,root',
                 'icu_path': 'deps/icu-small',
                 'icu_small': 'true',
                 'icu_ver_major': '59',
                 'node_byteorder': 'little',
                 'node_enable_d8': 'false',
                 'node_enable_v8_vtunejit': 'false',
                 'node_install_npm': 'true',
                 'node_module_version': 57,
                 'node_no_browser_globals': 'false',
                 'node_prefix': '/usr/local',
                 'node_release_urlbase': '',
                 'node_shared': 'false',
                 'node_shared_cares': 'false',
                 'node_shared_http_parser': 'false',
                 'node_shared_libuv': 'false',
                 'node_shared_openssl': 'false',
                 'node_shared_zlib': 'false',
                 'node_tag': '',
                 'node_use_bundled_v8': 'true',
                 'node_use_dtrace': 'false',
                 'node_use_etw': 'true',
                 'node_use_lttng': 'false',
                 'node_use_openssl': 'true',
                 'node_use_perfctr': 'true',
                 'node_use_v8_platform': 'true',
                 'node_without_node_options': 'false',
                 'openssl_fips': '',
                 'openssl_no_asm': 0,
                 'shlib_suffix': 'so.57',
                 'target_arch': 'x64',
                 'v8_enable_gdbjit': 0,
                 'v8_enable_i18n_support': 1,
                 'v8_enable_inspector': 1,
                 'v8_no_strict_aliasing': 1,
                 'v8_optimized_debug': 0,
                 'v8_promise_internal_field_count': 1,
                 'v8_random_seed': 0,
                 'v8_trace_maps': 0,
                 'v8_use_snapshot': 'false',
                 'want_separate_host_toolset': 0,
                 'want_separate_host_toolset_mkpeephole': 0}}
creating config.gypi
creating config.mk
Traceback (most recent call last):
  File "configure", line 1439, in <module>
    run_gyp(gyp_args)
  File "tools\gyp_node.py", line 53, in run_gyp
    rc = gyp.main(args)
  File "tools\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "tools\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "tools\gyp\pylib\gyp\generator\msvs.py", line 2032, in GenerateOutput
    generator_flags))
  File "tools\gyp\pylib\gyp\generator\msvs.py", line 953, in _GenerateProject
    return _GenerateMSBuildProject(project, options, version, generator_flags)
  File "tools\gyp\pylib\gyp\generator\msvs.py", line 3378, in _GenerateMSBuildProject
    project_file_name)
  File "tools\gyp\pylib\gyp\generator\msvs.py", line 2714, in _GetMSBuildGlobalProperties
    _ConfigWindowsTargetPlatformVersion(configuration, version))
  File "tools\gyp\pylib\gyp\generator\msvs.py", line 311, in _ConfigWindowsTargetPlatformVersion
    return names[0]
IndexError: list index out of range
Failed to create vc project files.`

<br/><br/>
Please also provide: 

- Platform(OS/Version): win32-x64 (Windows 10)
- Host Node Version: 8.4.0
- Target Node Version: 8.4.0
- Nexe version: 2.0.0-beta.6
- Python Version: 2.7.13

**Comment by calebboyd** [comment]
See troubleshooting from #364

**Comment by calebboyd** [comment]
Building node is no longer required with the latest rc
