### ISSUE TITLE
Nexe can't find node.exe

### ISSUE THREAD

**Issue by atn832** [nexe/nexe#364]
This is a
 - [X] Bug Report
 - [ ] Feature Request
 - [ ] Other

If this is a bug report, What are the steps to reproduce?

- Install nexe beta. I got nexe@2.0.0-beta.6
- create a file called test.js, with a simple console.log("hello");
- run nexe -i test.js
- nexe crashes with the following error

```
C:\test>nexe -i test.js
√ Using input file as the main module: test.js
√ Node source extracted to: C:\test\.nexe\6.11.2
√ Node binary compiled
- Writing result to fileevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\test\.nexe\6.11.2\Release\node.exe'
    at Error (native)
```

And indeed, the folder does not contain a folder called Release:

```
C:\test>dir .nexe\6.11.2
 Volume in drive C has no label.
 Volume Serial Number is [redacted]

 Directory of C:\test\.nexe\6.11.2

08/23/2017  04:37 PM    <DIR>          .
08/23/2017  04:37 PM    <DIR>          ..
07/31/2017  10:39 PM             2,158 .remarkrc
07/31/2017  10:39 PM             1,944 android-configure
07/31/2017  10:39 PM            53,138 AUTHORS
08/23/2017  04:37 PM    <DIR>          benchmark
07/31/2017  10:39 PM               263 BSDmakefile
07/31/2017  10:39 PM            11,754 BUILDING.md
07/31/2017  10:39 PM            55,990 CHANGELOG.md
07/31/2017  10:39 PM               181 CODE_OF_CONDUCT.md
07/31/2017  10:39 PM            27,682 COLLABORATOR_GUIDE.md
07/31/2017  10:39 PM            13,695 common.gypi
07/31/2017  10:39 PM            46,748 configure
07/31/2017  10:39 PM            12,624 CONTRIBUTING.md
07/31/2017  10:39 PM    <DIR>          deps
08/23/2017  04:37 PM    <DIR>          doc
07/31/2017  10:39 PM             7,579 GOVERNANCE.md
08/23/2017  04:37 PM    <DIR>          lib
07/31/2017  10:39 PM            60,255 LICENSE
07/31/2017  10:39 PM            25,708 Makefile
08/23/2017  04:37 PM    <DIR>          nexe
08/23/2017  04:37 PM            21,277 node.gyp
07/31/2017  10:39 PM            10,217 node.gypi
07/31/2017  10:39 PM            20,452 README.md
08/23/2017  04:37 PM    <DIR>          src
08/23/2017  04:37 PM    <DIR>          test
08/23/2017  04:37 PM    <DIR>          tools
07/31/2017  10:39 PM            17,216 vcbuild.bat
              18 File(s)        388,881 bytes
              10 Dir(s)
```

Please also provide: 

- Platform(OS/Version): Windows 10
- Host Node Version: v6.11.2
- Target Node Version: ?
- Nexe version: 2.0.0-beta.6
- Python Version: Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32

**Comment by calebboyd** [comment]
See [Building Node](https://github.com/nodejs/node/blob/master/BUILDING.md) -- Python 3 is not supported

**Comment by danieldecsi** [comment]
I'm trying to do the same, getting the same error but my Python version just looks fine: 

- Platform(OS/Version): Windows 10
- Host Node Version: 8.4.0
- Target Node Version: 8.4.0
- Nexe version: 2.0.0-beta.6
- Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32 

Any idea?

**Comment by calebboyd** [comment]
Are you able to build node on its own?

eg. 
```
git clone git@github.com:nodejs/node.git
cd node
.\vcbuild release nosign
```

**Comment by danieldecsi** [comment]
I guess I just missed Visual Studio 2015 build tools. Now it's working. Thanks.

**Comment by jsammarco** [comment]
I have the build tools already installed and I still have this error. I am running win10 64bit. Any other tips? I'd like to compile without creating a bloated exe like nwjs and electron.

**Comment by calebboyd** [comment]
Did you try building node alone?
What happens when you:

```
git clone git@github.com:nodejs/node.git
cd node
.\vcbuild release nosign
```

**Comment by eiymba** [comment]
I've fixed this issue by reinstalling the build tools in a path without spaces; i.e. instead of:
`C:\Program Files(86)\Visual Studio 2017\`

I installed in `C:\BuildTools`

But I would not suggest using VS 2017, as you'll run into another error: 

`The build tools for v140 (Platform Toolset = 'v140') cannot be found.`

**Comment by AlexisAnzieu** [comment]
Hello, 

I'm on win10 64bit too and I got this message (run under admin so access rights are OK)

```
Cloning into 'node'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by calebboyd** [comment]
You can use the https endpoint, updated
