### ISSUE TITLE
nexe "Scanning existing binary...Binary [...] is not compatible with nexe"

### ISSUE THREAD

**Issue by plunkettscott** [nexe/nexe#365]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

If this is a bug report, What are the steps to reproduce?
 1. `npm -i nexe@beta`
 2. Run `nexe -i bundle.js -o pilot`
 3. nexe will compile the executable and then the executable runs just fine.
 4. Run `nexe -i bundle.js -o pilot` again, this time you receive an error (below).
 5. Delete `.nexe` directory and start at step 2 again...it works, but I had to compile Node all over again, which takes about 15 minutes each time.

```
$ nexe -i ./tmp/build.js -o pilot --verbose
✔ Using input file as the main module: ./tmp/build.js
✔ Downloading Node.js source from: https://nodejs.org/dist/v8.4.0/node-v8.4.0.tar.gz
✔ Source already downloaded
✔ Compiling result
⠙ Scanning existing binary...Binary: /Users/scott/RApps/runr-mid/.nexe/8.4.0/out/Release/node is not compatible with nexe
```

- Platform(OS/Version): Mac OSX 10.12.6
- Host Node Version: v8.4.0
- Target Node Version: v8.4.0
- Nexe version: nexe@2.0.0-beta.6
- Python Version: Python 2.7.10

**Comment by calebboyd** [comment]
Hi @plunkettscott This should be fixed -- Try the latest beta (7)

**Comment by calebboyd** [comment]
This is fixed in the latest version
