### ISSUE TITLE
UPX compressed invalid Nexe binary error

### ISSUE THREAD

**Issue by astefanutti** [nexe/nexe#366]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

Compress a Nexe binary with UPX and execute it prints the following error:

```
_third_party_main.js:11
  throw new Error('Invalid Nexe binary')
  ^

Error: Invalid Nexe binary
    at _third_party_main.js:11:9
    at NativeModule.compile (bootstrap_node.js:586:7)
    at Function.NativeModule.require (bootstrap_node.js:531:18)
    at bootstrap_node.js:92:22
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

It used to be working with Nexe v1. I could get my binary size reduced from 35MB to 11MB, so that would be awesome to get the same support for v2.

Environment: 

- Platform(OS/Version): Mac OS Sierra 10.12.6
- Host Node Version: 8.4.0
- Target Node Version: 8.4.0
- Nexe version: 2.0.0-beta.7
- Python Version: 2.7.7
- UPX version: 3.94

**Comment by calebboyd** [comment]
Interesting! How can I install UPX on macOS i don't see that it is a supported OS

**Comment by calebboyd** [comment]
And to give some context -- I wanted to support this -- it would have worked in beta.6 but the approach being taken to achieve fast builds (arguably a better feature) Didn't work well with ELF binaries and so I had to change the way code was bundled with the binary... However - I think I should be able to provide a solution for this.

**Comment by calebboyd** [comment]
A temporary workaround is to run upx on
`.nexe/8.4.0/out/Release/node`

And then rerun your build

**Comment by calebboyd** [comment]
A similar workaround will be provided in the future -- whereas you provide an already compressed nexe binary path via `--target`

**Comment by astefanutti** [comment]
Compressing `.nexe/8.4.0/out/Release/node` indeed works. Nice! It's slightly less effective than compressing the whole binary (+1MB) but I can still compress from 35MB to 12MB 👍

**Comment by calebboyd** [comment]
Well, Compressing the whole binary deleted your code ;)

**Comment by astefanutti** [comment]
I meant compared to v1 :) My understanding is it was compressing the app code as well.

**Comment by calebboyd** [comment]
ahh, You can minify your bundle that you provide --- or -- in the next rc it will be supported out of the box hopefully

**Comment by astefanutti** [comment]
awesome. thanks!

**Comment by jgoux** [comment]
Hello,

in the end, what are the recommanded steps/ commands to compress a binary created with nexe as of version 2.0.0-rc.9 ?

It would be great to document it. 👍

**Comment by calebboyd** [comment]
First, run nexe with `--empty`

If you use `--build`:
 - compress `./.nexe/<VERSION>/out/Release/node` (or windows equivalent

else 

 - compress `./.nexe/<TARGET>`
