### ISSUE TITLE
Compiling resultspawn python ENOENT

### ISSUE THREAD

**Issue by dpeter99** [nexe/nexe#368]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

steps to reproduce:
I run ```nexe -o test --build```
I got: 
```
√ Using the cwd's main file as the main module
√ Source already downloaded
- Compiling resultspawn python ENOENT
```
```
{
  "name": "proj",
  "version": "0.0.0",
  "main": "app.js",
  "dependencies": {
    "express-formidable": "^1.0.0",
    "express": "^4.15.2",
    "formidable": "^1.1.1",
    "jsdom": "^11.1.0",
    "material-components-web": "^0.17.0",
    "mkdirp": "^0.5.1",
    "mustache": "^2.3.0",
    "nodemailer": "^3.1.8",
    "rimraf": "^2.6.1",
    "spdy": "^3.4.7"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "GD.SourceMakers",
  "license": "ISC",
  "description": ""
}
```
Please also provide: 

- Platform(OS/Version):Win 10
- Host Node Version:latest
- Target Node Version:latest
- Nexe version:latest
- Python Version:latest

**Comment by eiymba** [comment]
I reinstalled my python to the latest 3.x and this issue was resolved for me. I also made sure that python was added to the path.

Lucky I guess. Sorry if that was of no help 😞 .

**Comment by calebboyd** [comment]
Thats Odd! `python.exe` should be available on the path and should be version 2.6 or 2.7 as per [building node](https://github.com/nodejs/node/blob/master/BUILDING.md)

**Comment by eiymba** [comment]
@calebboyd haha yeah, I just followed the exact same link through another issue after I overcame this one. I'm changing versions now 😄 .

**Comment by calebboyd** [comment]
Just published a new version (2.0.0-rc.2)
@dpeter99, @eiymba 
This should be resolved! Let me know if it is not

**Comment by eiymba** [comment]
@calebboyd thanks for the update!

I actually managed to get nexe working the following day doing a fresh install of VS2015 and python 2.7.

My issue was that I was using VS 2017 and node 6.x. My apologies, I misunderstood the compilation instructions. I would have mentioned something if I thought it was something you were concerned about.

**Comment by calebboyd** [comment]
Neat!. If you're interested -- The new version will used pre-built binaries hosted in a github release. So building node for the base-case won't be needed
