### ISSUE TITLE
Node compile failure (ARM, v8.4)

### ISSUE THREAD

**Issue by jonnyt886** [nexe/nexe#373]
This is a
 - [x] Bug Report

<br/>
If this is a bug report, What are the steps to reproduce?

`nexe --build --empty --target linux-armv6-8.4.0 --version 8.4.0 --input app.js`

System is a RaspberryPi 3 running Linux 4.4.39.
```
# python --version
Python 2.7.13
# node --version
v6.9.2
# nexe --version
2.0.0-rc.2
```

I get this output:
```
# nexe --build --empty --target linux-armv6-8.4.0 --version 8.4.0 --input app.js
ℹ nexe 2.0.0-rc.2
✔ Node source extracted to: /usr/share/shepd-app/.nexe/8.4.0
✔ Node binary compiled
⠋ Writing result to fileevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/usr/share/shepd-app/.nexe/8.4.0/out/Release/node'
    at Error (native)
# nexe --build --empty --target linux-armv6-8.4.0 --version 8.4.0 --input app.js
```
There is no Python 3 installed on the system so that is definitely not the issue. I got exactly the same results with node v7.10.1 and v6.9.2, though those failed much faster. v8.4 took a couple of hours to compile before it failed.

In case it's any use, here are the contents of the `out` and `Release` folders:
```
# ls .nexe/8.4.0/out/
Makefile                                     node_dtrace_ustack.target.mk
Release                                      node_etw.target.mk
cctest.target.mk                             node_js2c.host.mk
deps                                         node_perfctr.target.mk
mkssldef.target.mk                           specialize_node_d.target.mk
node.target.mk                               tools
node_dtrace_header.target.mk                 v8_inspector_compress_protocol_json.host.mk
node_dtrace_provider.target.mk
# ls .nexe/8.4.0/out/Release/
genccode     genrb        iculslocs    icupkg       obj          obj.host     obj.target   openssl-cli
```

**Comment by jonnyt886** [comment]
When I ran `make` from the `.nexe/v8.4.0` directory I discovered that `linux-headers` was not installed on the system. It would be helpful if `nexe` could be a bit more helpful with its error reporting? I was initially thinking the build process was to blame, since it told me the compilation was successful when it wasn't. At least nexe should be looking at the exit code of make?

**Comment by calebboyd** [comment]
You're right. It should make those more transparent. The goal run all those "base-builds" in CI. And then `--build` will be more of a secondary feature.

Can I ask why you're using `--empty`?

Also --- I need to add this to the docs, but `--target` with `--build` does nothing
You need to be operating on the platform you want to target if you're going to use `--build`

**Comment by calebboyd** [comment]
In addition to correctly checking the exit code. I think I will add an additional log level that will pipe the output from the child process building node.

**Comment by jonnyt886** [comment]
Sorry for the slow response! I am not entirely clear on all the options and what they do and I saw `--empty` in some examples and it appeared to work. I think the options docs might generally benefit from a review as `--empty` doesn't appear in the `--help` output at all.

**Comment by jonnyt886** [comment]
...and yes the logs from the child process would be very handy :-)

**Comment by calebboyd** [comment]
I shouldn't have had it in an example. That was a mistake. it's an undocumented (purposefully) flag.

**Comment by calebboyd** [comment]
Logging had been added (in master rn)
