### ISSUE TITLE
Option to preserve argv[1]

### ISSUE THREAD

**Issue by Chinafreak** [nexe/nexe#375]
Looks like that process.argv.slice(2) is not working when the app was compiled.

index.js code:
```console.log(process.argv.slice(2));```

"**node index.js one two three --four -five six seven --eight -nine**" print:
[ 'one',  'two',  'three',  '--four',  '-five',  'six',  'seven',  '--eight',  '-nine' ]

"**index.exe one two three --four -five six seven --eight -nine**" print:
[]

-     Platform(OS/Version): Windows 10
-     Host Node Version: v7.9.0
-     Target Node Version: v7.9.0
-     Nexe version: 2.0.0-rc.2
-     Python Version: 2.7.13

**Comment by calebboyd** [comment]
Can you give any more information? I can't seem to replicate this..
Here is what I did:
![image](https://user-images.githubusercontent.com/5818726/30213173-83d7e39e-946d-11e7-8215-1ef226299b19.png)

**Comment by Chinafreak** [comment]
Strange, now it's working. I just got "[ ]" before. Maybe after restarting Visual Studio Code fixed that? Anyways, it's now solved. 

Yeah, it would be better that "one" would appear at out.exe too.

**Comment by Chinafreak** [comment]
Looks like that this feature is added? :)

**Comment by calebboyd** [comment]
Yep, fakeArgv, or --fake-argv






On Tue, Sep 12, 2017 at 2:08 AM -0500, "Chinafreak" <notifications@github.com> wrote:












Looks like that this feature is added? :)
