### ISSUE TITLE
ENOENT: no such file or directory, open [...]\Release\node.exe

### ISSUE THREAD

**Issue by Grewamor** [nexe/nexe#377]
This is a
 - [x] Bug Report
<br/>

```
nexe
i nexe 2.0.0-rc.4
\ Fetching prebuilt binaryError: windows-x64-8.1.4 not available, create it using the --build flag
```

```
nexe --build
i nexe 2.0.0-rc.4
√ Source already downloaded
√ Node binary compiled
- Writing result to fileevents.js:182
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '[...]\.nexe\8.1.4\Release\node.exe'
```

<br/><br/>

- Platform(OS/Version): Win10 64
- Host Node Version: 8.1.4
- Target Node Version: 8.1.4
- Nexe version: 2.0.0-rc.4
- Python Version: 2.7.13

**Comment by calebboyd** [comment]
Make sure you're environment is setup correctly, see https://github.com/nexe/nexe/blob/master/README.md#compiling-node

**Comment by Grewamor** [comment]
On another PC it works. Thanks 4 the info.
