### ISSUE TITLE
TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by Grewamor** [nexe/nexe#378]
This is a
 - [x] Bug Report

<br/>
I get the following error while executing the file. Does anybody has an idea?

```
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.dirname (path.js:716:5)
    at Configuration.loadAppenderModule (C:\xampp\htdocs\Transaktionsserver2\nexe_1505232869321.exe:69962:38)
```

- Platform(OS/Version): Win10 64
- Host Node Version: 8.2.1
- Target Node Version: 8.2.1
- Nexe version: 2.0.0-rc.4
- Python Version: 2.7.13

**Comment by calebboyd** [comment]
pass `--debugBundle ./debug-bundle.js` and look at line 69962

**Comment by Grewamor** [comment]
Thx 4 the quick help.
The Problem is log4js.

```
console.log('log1');
const log4js = require('log4js');
console.log('log2');
```
Error:
```
log1
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^......
```
Are there any problems known?

**Comment by calebboyd** [comment]
See
https://github.com/nexe/nexe/issues/344#issuecomment-327031041

**Comment by calebboyd** [comment]
@Grewamor Any luck?

**Comment by Grewamor** [comment]
Thank you @calebboyd, it helped. ;-)
