### ISSUE TITLE
Windows support, extended OS X support, binary addons

### ISSUE THREAD

**Issue by IngwiePhoenix** [nexe/nexe#38]
Hey hey. Instead of making it three seperate issues, I thought i'd make one.

_Windows support_
So, when is this coming? i am getting to a point where I have about six extensions, that all need to reside inside the actual nodejs binary. But, the main userbase is on Windows...

_Extended OS X support_
I saw an issue about OS X .app packages? They're hillariously easy. You'll just need an actual Info.plist file, and that can be looked up from across the internet. But to create a base .app package:

``` bash
# Assuming we're inside the release folder and $APPNAME is the file of the executable, application, whatever...
mkdir -p $APPNAME.app/Contents/MacOS
cp $APPNAME $APPNAME.app/Contents/MacOS/$(basename $APPNAME) #no extension!
cp Info.plist $APPNAME.app/Contents/Info.plist
```

The most important keys for the Info.plist file would be the executable name, application name, application display name, version, copyright and idendifyer. As long as you do not use Cocoa in any way, you won't need it...but if you do, then you need to also `mkdir $APPNAME.app/Contents/Resources`.
Thats it, app bundle. :)

_Binary addons_
Binary addons are something very important - especially as I am making an FLTK wrapper - so I need to link in the library file. A usual invocation of such is:
`g++ myApp.cpp -lfltk` ...obviously I shortened that a bit.
But, when creating a nodejs executable with a binary addon, there are two things to consider:
- Adding the library and its objects - or adding just a link to the shared library.
- Adding the actual addon.node binary.

I think that especialyl the second is not ultra-easy. But one method I can think about is: Unpack the extension in memory thru another module. Like, serialize the module in memory, and tell nodejs to use it from there. That'd make it a simple .js file again. Buuuut, the next problem then is that you'll need to compile the addon before compiling a "nexe".
A bit complicated, but think about that - it may actually work.

``` js
// this is pseudo-code.
var bin = [...binary content...],
binInMemory = putIntoMemory(bin);
module.exports = require(binInMemory);
```

Kind regards, Ingwie.

**Comment by RainbowDashDC** [comment]
Extended Mac OSX Support is definetly something I'd like to include, however I don't own a Mac machine currently and I'm not sure how much help a `.app` would because they are almost all command line apps, but hey it's a good idea irregardless. `indevelopment` label added because native modules is my top priority right now.

**Comment by Penagwin** [comment]
I'm a little confused. Is it possible to make a .exe ?

**Comment by RainbowDashDC** [comment]
@Penagwin Yes! It supports building an exe right now if you build from Windows!

**Comment by Penagwin** [comment]
I know it isn't the right place to ask, but just in case. When I try to install anything with npm on windows it just hangs. Here is a log.
https://gist.github.com/Penagwin/43f36fe98387ccdaca39

**Comment by Penagwin** [comment]
Is cross compiling possible? (I have need to compile a windows binary from linux)

**Comment by CKarper** [comment]
No, cross compiling is not possible.  You will need to build from the
environment you want the resultant executable to run in.

**Comment by calebboyd** [comment]
Added cross "compiling" (more like assembling) in `nexe@beta` examples/native-build` also has an example of including native addons. 

These aren't baked into the node build but shipped alongside -- written to disk at runtime. Perhaps a future iteration will merge the build file to accommodate actual integrated native modules.

**Comment by calebboyd** [comment]
closing for now! re-open if there is something that doesn't meet your needs
