### ISSUE TITLE
Is there a way to execute .exe / script inside of nexe's exe?

### ISSUE THREAD

**Issue by Chinafreak** [nexe/nexe#381]
Let's say we have a .exe file as resources which it's included at nexe's exe, is there an way to execute this .exe with child_process.exec/spawn?

I've already tried but somehow child_process.exec couldn't find this file.

[Edit]

It's because the exe doesnt "exists" since this exe is inside of nexe's exit

**Comment by calebboyd** [comment]
Right, you can write out the bundled binary though and execute it with a child_process method

**Comment by Chinafreak** [comment]
Is there any documentation/examples? It would be good to know. :)
Thanks!

**Comment by calebboyd** [comment]
I'll lump it in with #322
