### ISSUE TITLE
node --max_old_space_size=5000

### ISSUE THREAD

**Issue by Greg-openface** [nexe/nexe#383]
Ok so basically how do you set the max old space size for a exe you create with nexe ? I need to set this variable before i package the js file so it uses the max old space user defined. thanks

**Comment by calebboyd** [comment]
You can use the flag/option `enableNodeCli`
https://github.com/nexe/nexe#enablenodecli-boolean

If you use this flag you also have to use `--build`. 

See `nexe --help` for all the options

**Comment by Greg-openface** [comment]
ok , does that mean that the exe i make will still just run without any cmd node being typed ? i currently am doing this ... nexe -i csv-to-json.js -o 100th-frame-Downsampling.exe -t v8.4.0-win-x86

**Comment by calebboyd** [comment]
Do `nexe csv-to-json.js -o 100th-frame-Downsampling.exe -t x86-8.4.0 --enableNodeCli --build`

The resulting `100th-frame-Downsampling.exe` can then be executed with `--max_old_space_size=5000` This overrides the cli back to nodes, which blocks unknown cli arguments

**Comment by Greg-openface** [comment]
so build the exe using your first line ... then when i execute the exe add the --max_old_space_size=5000  to a shortcut ? ..... i am hopeful that the exe will run without any additional commands

**Comment by calebboyd** [comment]
Right.

**Comment by Greg-openface** [comment]
Awesome !! your a legend !
