### ISSUE TITLE
Error: spawn C:\Python27\ ENOENT

### ISSUE THREAD

**Issue by tobeedelafuente** [nexe/nexe#386]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>

I ran the command:

```
 nexe index.js --build
```

The code inside `index.js` is just a simple `console.log("hello world");`

And got the following output:

```
i nexe 2.0.0-rc.6
√ Node source extracted to: C:\Users\TACDF\Documents\projects\trial\.nexe\8.5.0
- Compiling result
Error: spawn C:\Python27\ ENOENT
    at _errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

- Platform(OS/Version): Running Windows 10 on Mac
- Host Node Version: 8.5.0
- Target Node Version: 8.5.0
- Nexe version: 2.0.0-rc.6
- Python Version: 2.7.14

I tried to set my environment variables correctly (added the python folder to `PATH` and created another environment variable for the python folder called `PYTHON`) but the issue still persists. Could you enlighten me on how to fix this issue?

**Comment by calebboyd** [comment]
Do you have visual studio build tools installed?

See https://github.com/nexe/nexe#compiling-node

**Comment by FloMaetschke** [comment]
I think i got the same problem a day ago.
Check that your python27 is set up correctly.
Its often installed at this path: `C:\Python27.`

So you have to set your enviroment PATH variable correctly.

I fixed it by specifying the option python, to set the path manually:

These are my current options:

```
{
  input: './build/app.js',
  output: './publish/myapp.exe',
  target: 'win32-x64-6.11.3',
  build: false, //builds node
  logLevel: 'verbose',
  python: 'C:/Python27/',
  bundle: false,
  fakeArgv: true
}
```

**Comment by tobeedelafuente** [comment]
I am not familiar with "options" you did. Do I add this to the .js file I made or do I have to created another one? Could you give me some pointers on how to go about in applying the options?

**Comment by calebboyd** [comment]
If you're using nexe programmatically, pass python like shown above. Otherwise use `--python`

For example, `nexe myapp.js --build --python C:/Python27`

It sounds like you probably don't really want/ need to build node though. So just leave that out and run `nexe index.js`
