### ISSUE TITLE
No prebuilt binary for linux-x64-6.11.3

### ISSUE THREAD

**Issue by nloomans** [nexe/nexe#387]
This is a
 - [ ] Bug Report
 - [ ] Feature Request
 - [X] Other

<br/>

Simply running `nexe` says that there are no prebuild binaries for `linux-x64-6.11.3`. I find this quite strange, as this is the Linux kernel that is shipped with Ubuntu 16.04.

I did some digging myself and noticed that https://api.github.com/repos/nexe/nexe/releases/latest does not return **any** assets, even tho the program looks for that here: https://github.com/nexe/nexe/blob/master/src/compiler.ts#L151

Here is a Vagrantfile to reproduce this error:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provision "shell", inline: <<-SHELL
    curl -sL https://deb.nodesource.com/setup_6.x | bash -
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
    apt-get update
    apt-get install -y nodejs yarn
  SHELL
  
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    echo 'export PATH=$PATH:$(yarn global bin)' >> /home/vagrant/.bashrc
    yarn global add nexe
  SHELL
end
```

**Comment by calebboyd** [comment]
Hi @nloomans, pending the full 2.0 release there aren't very many prebuilt binaries right now. Its a new feature for 2.0 and we're attempting to minimize the churn on changes that would require a rebuild. Sorry for the inconvenience! 

However if you build one once and cache it `.nexe/6.11.3/out/Release/node`. Your rebuilds will be really quick.

**Comment by nloomans** [comment]
Thanks, how long can I expect a build to take? Because it's taking a really long time...

**Comment by nloomans** [comment]
> Sorry for the inconvenience!

Why are you sorry? It's note like i'm paying you for this. It's open-source work and you should be proud!

**Comment by calebboyd** [comment]
Probably around 45-65 minutes in a VM... depending on CPUs
