### ISSUE TITLE
Build documentation unclear

### ISSUE THREAD

**Issue by nloomans** [nexe/nexe#388]
This is a
 - [ ] Bug Report
 - [ ] Feature Request
 - [X] Other

<br/>

The output is pretty self explanatory:

```
➜  ~/tmp/nexe nexe --build
ℹ nexe 2.0.0-rc.6
✔ Node source extracted to: /home/cyborg/tmp/nexe/.nexe/6.11.3
✔ Node binary compiled
✔ Executable written to: nexe
✔ Finsihed in 1033.303s
➜  ~/tmp/nexe nexe
ℹ nexe 2.0.0-rc.6
⠋ Fetching prebuilt binary
Error: linux-x64-6.11.3 not available, create it using the --build flag
    at NexeCompiler.<anonymous> (/home/cyborg/.config/yarn/global/node_modules/nexe/lib/compiler.js:208:35)
    at step (/home/cyborg/.config/yarn/global/node_modules/nexe/lib/compiler.js:40:23)
    at Object.next (/home/cyborg/.config/yarn/global/node_modules/nexe/lib/compiler.js:21:53)
    at fulfilled (/home/cyborg/.config/yarn/global/node_modules/nexe/lib/compiler.js:12:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

<br/><br/>

- Platform(OS/Version): Ubuntu GNOME 17.04
- Host Node Version: v6.11.3
- Target Node Version: N/A
- Nexe version: nexe 2.0.0-rc.6
- Python Version: 2.7.13 and 3.5.3

**Comment by nloomans** [comment]
I figured it out, apparently you always need to use the `--build` flag, and not just on the initial build. The documentation could be expanded to clarify this.

**Comment by nloomans** [comment]
I **actually** figured it out, turns out it already compiled the code in the first command. It just assumed I wanned to compile `index.js` when I'm not giving it a file as argument. This wasn't clear to me...

**Comment by calebboyd** [comment]
Right, `--build` tells it to use downloaded/built source.
If you don't provide an entry file eg `nexe <entry-file>` it will choose the pkg#main file. Or index.js

**Comment by calebboyd** [comment]
I should update the logging to make the clear once its finished what was used as input

**Comment by nloomans** [comment]
BTW, I didn't actually use 2 hours to figure this out, if you're worried about that. It's more like 10 minutes with a lot of breaks in between.
