### ISSUE TITLE
Error: Cannot find module 'index.js'

### ISSUE THREAD

**Issue by palavrov** [nexe/nexe#389]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
If this is a bug report, What are the steps to reproduce?

```sh
$ mkdir test
$ cd test
$ npm init
$ npm i --save-dev nexe@v1.1.3
$ touch index.js
$ ./node_modules/.bin/nexe -i index.js -o app
module.js:529
    throw err;
    ^

Error: Cannot find module 'index.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/Users/palavrov/codigi/ttk/test/node_modules/nexe/bin/nexe:101:22)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
```
The problem is introduced with this commit: https://github.com/nexe/nexe/commit/8f96b2bca9913a3712020501de05843f8ec765ad

`require.resolve(toAbsolute(argv.i))` doesn't work for relative paths when nexe is local dev dependency. Rolling back to v1.1.2 solves the problem.

Latest v2.0.0 RC works as expected but this issue is pain in the ass for v1.x installations.

<br/><br/>
Please also provide:

- Platform(OS/Version): macOS 10.13
- Host Node Version: 8.6.0
- Target Node Version:
- Nexe version: 1.1.3
- Python Version: 2.7.10

**Comment by calebboyd** [comment]
Hmm, If you know what the issue might be I'd accept a PR against the V1-EOL branch

**Comment by palavrov** [comment]
Just rollback the mentioned commit and it should be fine.

```sh
git revert  8f96b2b
```

I would expect `toAbsolute()` to return always absolute path but with that change it doesn't which first introduces that bug and second makes the function name non self explanatory and wrong.

The issue happen because `require.resolve()` builds a list with all `node_modules/` paths to look for the specified file i.e. the fact that the file exists in current directory doesn't mean that `process.cwd()` will be included in the require.resolve paths i.e. we really need absolute path.

**Comment by calebboyd** [comment]
This should solve your issue.
e516681a803bf072627ffc732eb2e628aca61da9

Also, I highly suggest updating to v2 :)
