### ISSUE TITLE
max old size attached to shortcut problem

### ISSUE THREAD

**Issue by Greg-openface** [nexe/nexe#390]
This is a
 - [ ] Bug Report
 - [ ] Feature Request
 - [x ] Other

<br/>
If this is a bug report, What are the steps to reproduce?

```
//provide configuration here
```

<br/><br/>
Please also provide:

- Platform(OS/Version):
- Host Node Version:
- Target Node Version:
- Nexe version:
- Python Version:

i have built an exe using the following line ....
nexe csv-to-json.js -o No-Downsampling.exe -t x86-8.4.0 --enableNodeCli --build

and have created a shortcut to the exe including cmd prompt remain active so i can see whats happening...
C:\Windows\System32\cmd.exe /K node "No-Downsampling.exe" --max_old_space_size=4000

i cant seem to figure out how to get the max old space to be applied.... what am i doing wrong ? 
sorry for the persistnat bother.
Cheer,
Greg.

**Comment by calebboyd** [comment]
Why do you have `node` in there?

Looks like you're also using /K wrong

`C:\Windows\System32\cmd.exe /K "path\to\No-Downsampling.exe --max_old_space_size=4000"`

**Comment by Greg-openface** [comment]
Thanks for th response, I tried it even with C:\Windows\System32\cmd.exe /K "No-Downsampling.exe" --max_old_space_size=6500   but still getting this kind of error ....

<--- Last few GCs --->

[12020:00D57290]   210323 ms: Mark-sweep 1478.7 (1537.1) -> 1477.5 (1535.6) MB, 2572.3 / 0.0 ms  allocation failure GC in old space requested
[12020:00D57290]   213355 ms: Mark-sweep 1477.5 (1535.6) -> 1477.2 (1538.1) MB, 3032.0 / 0.0 ms  allocation failure GC in old space requested
[12020:00D57290]   216119 ms: Mark-sweep 1477.2 (1538.1) -> 1477.2 (1523.1) MB, 2762.9 / 0.0 ms  last resort
[12020:00D57290]   219001 ms: Mark-sweep 1477.2 (1523.1) -> 1477.2 (1523.1) MB, 2882.0 / 0.0 ms  last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 3A896095 <JSObject>
    1: addIndexes(aka addIndexes) [F:\VIBE-EXE\LATEST VERSION\Openface-Data-Converter\No-Downsampling.exe:~122] [pc=3F60E3C9](this=3A884125 <undefined>,jsonData=59E1DC8D <Object map = 0BF3CEE9>)
    2: /* anonymous */(aka /* anonymous */) [F:\VIBE-EXE\LATEST VERSION\Openface-Data-Converter\No-Downsampling.exe:~157] [pc=3F616EB6](this=3A884125 <undefined>,week=0855F6F9 <String[8]: Overview>)
    3: arg...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Comment by calebboyd** [comment]
Please look at my previous post for how to use the quotations with `/K`

**Comment by calebboyd** [comment]
@Greg-openface Closing since there isn't much I can do. I hope you get it figured out

![image](https://user-images.githubusercontent.com/5818726/31042244-1173ce64-a569-11e7-861e-1a23e59ae741.png)

**Comment by Greg-openface** [comment]
Hi Calebboyd thanks for the message, sorry i haven't been online past coupl of days . I am trying another build now ... the issue i have is that from a cmd prompt i get how you would just put --max-old-space-size-6500 but not sure if it is working with a windows shortcut for the exe.  im going to try puting it in the same way in the right click properties shortcut option... or maybe i just put it in the commands field of a windows shortcut properties im not sure.

**Comment by Greg-openface** [comment]
..... ok so some good news , when i run the exe fro a cmd prompt with the --max-old-space-size-6500 it works !! however when i create a windows shortcut and in target put the same code in "Downsampling.exe" ---max_old_space_size=6500 .... clicking the shortcut triggers what looks like the exe (loads in a cmd window) and then disappears .. not sure what i am doing wrong here

**Comment by Greg-openface** [comment]
ok .. im an idiot i had 3 --- at the beggining , works now !
