### ISSUE TITLE
Nexe does work when executed in build pipelines

### ISSUE THREAD

**Issue by FloMaetschke** [nexe/nexe#391]
This is a
 - [x ] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
Run nexe compile in build batch.

```
//provide configuration here
```

<br/><br/>
Please also provide:

- Platform(OS/Version): Windows 10 (Build Agent from VSTS)
- Host Node Version: 7
- Target Node Version: 7
- Nexe version: 2.0.0-rc.6
- Python Version: 2.7.x

When i run nexe from node (webpack build), then it works fine on my local shell:
e.g. i type npm run publish (which calls a webpack build including nexe compilation) 

When i do the same inside a VSTS build, it starts nexe and then the output / operation hangs.

I only get this output:
> i nexe 2.0.0-rc.6
> The operation was canceled.

The operation is canceled after a long time.

Any idea why this happens inside vsts builds ?

I guess its the same in other tools like TeamCity Builds, or any other build chain.

This is my simple plugin for webpack:
```

const { compile } = require('nexe')


var nexe_plugin_options;
function WebpackNexePlugin(options) {
  // Setup the plugin instance with options...
  if (options === undefined) {
    throw "WebpackNexePlugin: Nexe options need to be set."
  }
  else {
    nexe_plugin_options = options;
  }
}

WebpackNexePlugin.prototype.apply = function (compiler) {
  compiler.plugin('done', function () {
    compile(nexe_plugin_options).then(() => {
      console.log('success')
    });
  });
};

module.exports = WebpackNexePlugin;
```

**Comment by calebboyd** [comment]
What is the configuration being used? ( Nexe plugin options)

**Comment by calebboyd** [comment]
Also, you should update to `nexe@latest`

**Comment by calebboyd** [comment]
>I guess its the same in other tools like TeamCity Builds, or any other build chain.

What makes you say that? I'm running nexe programmatically just fine in Appveyor.

I'm not very familiar with VSTS. What is the environment like where you execute your script? (npm publish it sounds like)

I'm wondering if it has to do with stdin

**Comment by calebboyd** [comment]
try the latest version `nexe@latest`

**Comment by FloMaetschke** [comment]
Hi caleb!

Thx for the fast responses!

I updated to latest which seems to be 2.0.0-rc.11 ?
There is now an error with python.

> 
> 2017-09-30T07:03:08.8231914Z i nexe 2.0.0-rc.11
> 2017-09-30T07:03:43.3305610Z Error: spawn python ENOENT
> 2017-09-30T07:03:43.3305610Z     at exports._errnoException (util.js:1026:11)
> 2017-09-30T07:03:43.3305610Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
> 2017-09-30T07:03:43.3305610Z     at onErrorNT (internal/child_process.js:359:16)
> 2017-09-30T07:03:43.3305610Z     at _combinedTickCallback (internal/process/next_tick.js:74:11)
> 2017-09-30T07:03:43.3305610Z     at process._tickCallback (internal/process/next_tick.js:98:9)
> 

I googled for Error: spawn python ENOENT which let me to check the env is set up correctly.

Further inspection showed me, that i have set an env variable PYTHON=C:\Python27.
But it is not added to the path. :(

Since i am at home and not at work, i am unable to update the env variables right now :(
I will try it the next days and inform you again what happened.

**Comment by FloMaetschke** [comment]
I found that there is a python parameter in the config. I will try that now.. :)

Nether the less, i noticed that the output of nexe  seems to be incorrect in the log of the build pipeline. 
I guess it has something to do with the updating line replacements when building?

There is only the line
`  i nexe 2.0.0-rc.11`

and the rest is missing.

**Comment by FloMaetschke** [comment]
And there is another one:

> 2017-09-30T08:37:50.7307070Z Error: python configure exited with code: 1
> 2017-09-30T08:37:50.7307070Z     at ChildProcess.<anonymous> (C:\VSTS-Buildserver\agent\_work\1\s\node_modules\nexe\lib\compiler.js:192:28)
> 2017-09-30T08:37:50.7307070Z     at ChildProcess.g (events.js:291:16)
> 2017-09-30T08:37:50.7307070Z     at emitTwo (events.js:106:13)
> 2017-09-30T08:37:50.7307070Z     at ChildProcess.emit (events.js:191:7)
> 2017-09-30T08:37:50.7307070Z     at maybeClose (internal/child_process.js:877:16)
> 2017-09-30T08:37:50.7307070Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)


My options:
```
plugins.push(new WebpackNexePlugin({
  input: './build/backend.js',
  output: './publish/mde2-server.exe',
  target: 'win32-x64-7.0.0',
  build: true, //builds node
  version: '7.0.0',
  logLevel: 'verbose',
  python: 'C:/Python27'
}));
```

**Comment by calebboyd** [comment]
Hmm Okay,

I have a couple tips

- add `bundle: false` since you're using webpack.
  - If you want to try, the latest version will bundle by default, you might not need to use webpack
- remove `version`  It uses the version from `target`
- Use a supported node target. You won't need to compile at all if you use a version in the 6/8 line, and it will go really fast.

I think the problem with logging is that its in a CI environment
Internally it is using https://npmjs.com/ora which doesn't run in CI

In nexe's own build process we use:
https://github.com/nexe/nexe/blob/fe5aa0be0941183dbcce40ec7932916924b5d07b/tasks/asset-compile.ts#L92-L95

https://github.com/nexe/nexe/blob/fe5aa0be0941183dbcce40ec7932916924b5d07b/tasks/asset-compile.ts#L67-L73

Maybe a different logger interface for those environments... PRs and Ideas welcome :)

**Comment by FloMaetschke** [comment]
Wow it works nice now and really fast without the build flag turned on.

Its also helpful to mention this file for a version:
https://nodejs.org/download/release/index.json

I am now on stable win-x64-6.11.3

**Comment by calebboyd** [comment]
That json is the source, but the build cluster might not always be caught up.

I added some more info here

https://github.com/nexe/nexe/blob/master/README.md#target-string--object

**Comment by FloMaetschke** [comment]
is it already possible with this feature to do a target like win-x64-6.11.3  on a linux machine (cross platform)?

**Comment by calebboyd** [comment]
Yes, but take note of native modules (see section in readme)

**Comment by calebboyd** [comment]
Closing re:  https://github.com/nexe/nexe/issues/374#issuecomment-333396521
