### ISSUE TITLE
Contents of `process.argv` different when compiled through nexe.

### ISSUE THREAD

**Issue by nloomans** [nexe/nexe#392]
This is a
 - [X] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>

`index.js`:

```
#!/usr/bin/env node
console.log(process.argv);
```

```
$ node index.js --foo
[ '/home/cyborg/.nvm/versions/node/v6.11.3/bin/node',
  '/home/cyborg/Code/nloomans-ev3dev/index.js',
  '--foo' ]
```

```
$ ./index.js --foo
[ '/home/cyborg/.nvm/versions/node/v6.11.3/bin/node',
  '/home/cyborg/Code/nloomans-ev3dev/index.js',
  '--foo' ]
```

```
$ nexe --build && ./nloomans-ev3dev --foo # removed #!/usr/bin/env node
[ '/home/cyborg/Code/nloomans-ev3dev/nloomans-ev3dev', '--foo' ]
```

The arguments passed to node are moved from the 3th position to the 2nd position when compiled through `nexe`. This causes tools like https://github.com/75lb/command-line-commands to dysfunction.

<br/><br/>
Please also provide:

- Platform(OS/Version): Ubuntu 17.04
- Host Node Version: v6.11.3
- Target Node Version: v6.11.3?
- Nexe version: 2.0.0-rc.6
- Python Version: 2.7.13 + 3.5.3

**Comment by calebboyd** [comment]
I don't see an issue here.
argv is simply different when you don't use `node` to execute your script.

With `nexe@latest` you can use https://github.com/nexe/nexe#fakeargv-boolean

**Comment by nloomans** [comment]
Thanks! `fakeArgv` did the trick.
