### ISSUE TITLE
Documenation of available build targets

### ISSUE THREAD

**Issue by kwisatz** [nexe/nexe#395]
This is a
 - [ ] Bug Report
 - [x] Feature Request
 - [ ] Other

Would it be possible to include a list of available targets in the README file?
It's not obvious which targets are available or where to look for them.
It's also confusing that win32 can actually be a 64bit arch, but maybe that's an upstream or even Windows issue?

I figured out some available target by trial and error:

```
~ $ ./node_modules/nexe/index.js -t win64-amd64-8.5
ℹ nexe 2.0.0-rc.11
⠦ Fetching prebuilt binary
Error: linux-x64-8.5 not available, create it using the --build flag
~ $ ./node_modules/nexe/index.js -t win32-amd64-8.5
ℹ nexe 2.0.0-rc.11
⠦ Fetching prebuilt binary
Error: windows-x64-8.5 not available, create it using the --build flag
```

But I'm not sure I'm using this correctly. Specifying e.g. `windows-x64-8.6.0` as a target still produces a Linux ELF binary:

compile script:
```
const { compile } = require('nexe')

compile({
  input: './cutter-simple.js',
  output: './simplecutter.exe',
  build: true,
  fakeArgv: true,
  target: 'windows-x64-8.6.0',
  name: 'simplecutter'
}).then(() => {
  console.log('success')
})
```

Output:
```
~ $ file simplecutter.exe 
simplecutter.exe: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=66de492a03b8b30ab4cc4ea254a01144f2579a5d, not stripped
```

**Comment by calebboyd** [comment]
Since you're passing `build:true` it will negate any target but the current platform. 

The `windows` portion of the target is being ignored. (looks like you're on linux?)

This is a case where a better warning could be produced. (`build` with explicit `target` conflict)

**Comment by calebboyd** [comment]
The available targets are a bit hidden rn.. This note has a link to the github releases
https://github.com/nexe/nexe#compiling-node

**Comment by kwisatz** [comment]
On 30/09/17 20:52, calebboyd wrote:
>
> The available targets are a bit hidden rn.. This note has a link to
> the github releases
> https://github.com/nexe/nexe#compiling-node
>

OK, thanks. Maybe explaining that `target` maps to nodejs releases and
repeat the link in the `target` explanation in the README would be
enough already?

**Comment by kwisatz** [comment]
> Since you're passing build:true it will negate any target but the current platform.
> The windows portion of the target is being ignored. (looks like you're on linux?)

Yes, that's much better ;)

```
~ $ node compile-simplecutter.js 
ℹ nexe 2.0.0-rc.11

-- cache cleared ---
✔ Compiling result
✔ Entry: './cutter-simple.js' written to: ./simplecutter.exe
✔ Finished in 1.635s
success
~ $ file simplecutter.exe 
simplecutter.exe: PE32+ executable (console) x86-64, for MS Windows
```

**Comment by calebboyd** [comment]
Added, I also added a note about native modules... 

Sorry for the bummer wrt cross compilation of native modules. It is possible but the binaries would have to be distributed with the package -- and for a specific node version for each platform. And then they would need to be conditionally loaded.

eg. 
```javascript
let binding
if (platform === 'linux' && arch === 'x64') {
    binding = require('./build/out/linux-x64.node')
}

if (platform === 'win32' && arch === 'ia32' {
    binding = require('./build/out/win32-x86.node') 
}
//... so on and so on
```
