### ISSUE TITLE
Correct options to get cli to work with my app?

### ISSUE THREAD

**Issue by FloMaetschke** [nexe/nexe#397]
This is a
 - [ ] Bug Report
 - [ ] Feature Request
 - [ x] Other

<br/>
What are the correct options to get my cli parameters to work i would use like:

`node myapp.js --hello-world value1 --second --parameter3 1234`

I am using this package for this at the moment:
command-line-args

**Comment by vickylance** [comment]
@FloMaetschke  I think you would just bundle it normally and while running it you would use the cli parameters to run it.

Eg: To bundle

`nexe myApp.js -o myApp`

To run the bundled app from cmd

./myApp.exe  --hello-world value1 --second --parameter3 1234

**Comment by calebboyd** [comment]
There is also the [`fakeArgv`](https://github.com/nexe/nexe/blob/master/README.md#fakeargv-boolean) option, it might be required for some cli parsers

**Comment by FloMaetschke** [comment]
Actually doing this:

> myApp.exe --hello-world value1 --second --parameter3 1234

behaves like this:

> node myApp.js

And the cli parameters are dropped.

Using 

> fakeArgv: true

 in my options, it works now. Thx alot caleb!
