### ISSUE TITLE
Cannot require with a substitution-free template string

### ISSUE THREAD

**Issue by jaubourg** [nexe/nexe#399]
In the project I'm trying to compile, I have files with require statements like this:

```js
const program = require( `commander` );
```

Which give me the following runtime error:

```
Error: Cannot find module 'commander'
```

Of course, the following works:

```js
const program = require( "commander" );
```

Sadly, the project is pretty big with lots of dependencies and the style guide covering them all requires the usage of backtick strings wherever possible... which includes require statements.

I've also tried pkg and it suffers from the same problem.

I suspect fuse-box doesn't recognize substution-free template strings as litterals and thus ignores require statements that use them. I just wanted to confirm this with you before opening an issue there.

**Comment by calebboyd** [comment]
Oh. Oh my. I will say that is a strange style guide, if for nothing else other than
it is not forward compatible... eg. You can't/won't be able to do in the future
```
import { resolve } from `path`
```
I'd strongly suggest lobbying for a change to that styleguide...

In the meantime. Webpack offers partial require expression evaluation.
You can achieve a webpack build by doing something like this:

`nexe entry-file.js --bundle ./nexe-bundle.js`

nexe-bundle.js
```
const webpack = require('pify')(require("webpack"))
const fs = require('fs')

module.exports.createBundle = function (options) {
    return webpack({
        entry: options.input,
        target: 'node',
        output: { filename: 'tmp.js' }
    }).then(() => {
        const result = fs.readFileSync('./tmp.js').toString()
        fs.unlinkSync('./tmp.js')
        return result
    })
}
```

I would like to add partial expression evaluation to fuse-box...So we can have it outof the box.. If you want to explore its anything that falls outside of [this block](https://github.com/fuse-box/fuse-box/blob/0646063d6f55d47b254582c90282d03925d13351/src/analysis/plugins/ImportDeclaration.ts#L24)


I already have an issue open, and may provide a PR... eventually.

**Comment by jaubourg** [comment]
Fact is eslint does properly handle the situation for imports so the style guide is still good.

Anyway, I tried your workaround and it works like a charm. Got a problem with a native module but I used [node-loader](https://github.com/webpack-contrib/node-loader) and it worked like a charm.

One thing I noted since it's a command-line tool is that `process.argv` is not properly populated. Instead of:

````json
[ "path/to/node.exe", "script_name.js", "param1", "param2", ... ]
````

I get

```json
[ "path/to/generated.exe", "param1", "param2", ... ]
```

Dunno if it's a known issue but it's probably worth mentioning (makes `commander` choke). Any way to know the script is running in nexe so that the script can work in both node and nexe? I can unshift a blank string into `process.argv` but I still need the script to work properly in vanilla node :/

FYI, I'm using version `2.0.0-rc.11` of nexe.

As for partial expression evaluation, I'd need to have a deeper look into the ESTree structure for template strings. I already had a quick look but the documentation is... let's say sparse. Shouldn't be a big change to detect template strings "litterals" for my case but I dunno if handling more complex, invariant expressions is in my ballpark. Have you located the code responsible for this black magic in webpack?

Anyway, thanks a __ton__ for your quick and so on-point answer! You saved me from 3 days of hell toying around with lots of different, all non-working, options for the project I'm on.

**Comment by jaubourg** [comment]
Just saw the `--fake-argv` command-line option and feel very stupid right now ;)

**Comment by calebboyd** [comment]
Was just going to mention that. 

If you're interested in not having to ship/send your node_modules folder for native modules you can use `xbin-loader` in place of node-loader.

**Comment by calebboyd** [comment]
https://github.com/calebboyd/xbin/tree/master/xbin-loader

**Comment by jaubourg** [comment]
Damn, you're a well of information! Can't thank you enough for all the pointers!

**Comment by calebboyd** [comment]
>Have you located the code responsible for this black magic in webpack?

I have, its... quite elaborate and It makes me sad its [so embedded...](https://github.com/webpack/webpack/blob/master/lib/Parser.js#L50)

**Comment by jaubourg** [comment]
Wow! One would have expected some kind of pattern matching for this... I had toyed with something like that when I wanted to modify some JavaScript but scrapped the code since I managed to get around the issue I was having at the time by heavily refactoring the code to make in Closure-compatible. Basically I would define structure templates of the AST tree that would be called automagically by a tree runner. Worked well but AST analysis / modification is so involved and messy :/

Dunno if webpack goes that far, but you would need a complete scope analysis to catch `const` declarations so that you could properly compute expressions. I remember building the scope structure was the worst.

Anyway, can't do this without some kind of abstraction but I admit those lines of code make my eyes bleed ;)

**Comment by calebboyd** [comment]
Is this still an issue or shall it be closed?

**Comment by jaubourg** [comment]
Well, it is an issue in the sense I need to use webpack as a workaround but it's working so as far as I'm concerned, I'm good. Dunno if you have an opened issue to support partial expression evaluation but it surely belongs to `fuse-box` rather than here I suppose.

**Comment by jaubourg** [comment]
And thanks again for you help. Very deeply appreciated :)

**Comment by calebboyd** [comment]
No problem, and yeah, im tracking it there :)

**Comment by calebboyd** [comment]
Linking: https://github.com/fuse-box/fuse-box/issues/804
