### ISSUE TITLE
Native addon support - aka, faking dlopen?

### ISSUE THREAD

**Issue by IngwiePhoenix** [nexe/nexe#40]
Hey.

So since a while now, I have tried my luck with nodejs modules - especially native addons. It turns out that those are nothing but dynamic libraries (well lol, who would have guessed?).

In order to implement support for these in nexe, one would have to either fake the dlopen function and point it BACK at the executable. Buuuut, that may be no good idea entirely... So I got another idea.

Since nodejs does not offer a real way to do manual memory management, and hence can not read binary data off memory, or require() it from there, there is the option to dynamicaly extract the shared objects, and then require them. That is, if we have no other choice.
But if you find a way to place the .node file into meory and trick require in reading it, then you would get what you want.

In PHP, one can use stream wrappers to do that. I dont know is there is such a way for nodejs though.

But I thought I would share my opinion and thought on this, as I am needing this functionality myself currently o.o

Kind regards, Ingwie

**Comment by pkoretic** [comment]
:+1:

**Comment by calebboyd** [comment]
Implemented with `nexe@beta` 

Native modules (.node) and friends (.dll) can be bundled and will be written at runtime. alongside the  binary. Doing this from memory was impractical as it would require forking node and performing some shady stuff with the filesystem to get in memory linking. 

see examples/native-build

**Comment by modeswitch** [comment]
@calebboyd What happened to native module support and the native-build example?
