### ISSUE TITLE
[Feature] - Source map support

### ISSUE THREAD

**Issue by mika-fischer** [nexe/nexe#402]
It would be nice to be able to generate proper stack traces. Maybe passing through the relevant fuse-box options and packaging the .map file alongside the bundle would be sufficient?

**Comment by calebboyd** [comment]
Good idea, this would be helpful.
Does node natively pick up source maps now? Or would we have to use `source-map-support`?

I worked on adding it briefly, but then stopped

**Comment by mika-fischer** [comment]
No, `source-map-support` is still needed...

**Comment by calebboyd** [comment]
This is no longer needed in 3 (nexe@next)

**Comment by EvanBoyle** [comment]
I believe I have need for source map support. I'll explain my scenario:

1. I use `ncc build index.ts -m -s` to build my typescript into a single javascript file with source maps
2. I use `nexe dist/index.js` to compile to an executable

What I really want is error messages to point to typescript line numbers via the source map file created in step 1. Is this supported in any way?

**Comment by weilbith** [comment]
@EvanBoyle I tried to do the same, but I always get issues that the build executable can't find the `prebuilds` sources of `ncc` as soon as I move it. How do you solve this issue? I have the same with `pkg` which can't handle the imports in `ncc`'s `index.js` to the `prebuils` and `build/Release`.
