### ISSUE TITLE
--ico option does not seem to work?

### ISSUE THREAD

**Issue by vickylance** [nexe/nexe#404]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
steps to reproduce?

Here is my build script.

```
const { compile } = require('nexe')

const inputAppName = './gen.js'
const outputAppName = 'generator'

compile({
  input: inputAppName,
  output: outputAppName,
  build: false,
  ico: './icon.ico'
}).then((err) => {
  if (err) throw err
  console.log('success')
})
```

here is the output of it.

```
C:\Projects\web-technology\generator
> node buildScript.js

i nexe 2.0.0-rc.11

-- cache cleared ---
√ Compiling result
√ Entry: './gen.js' written to: generator.exe
√ Finished in 10.432s
success
```

But I dont the custom icon being displayed.

![error](https://user-images.githubusercontent.com/5861833/31234521-b7c71e72-aa0c-11e7-8837-c55f1ead914a.PNG)

The ico file does contain all the png for various icon sizes.
Here is the output from the ImageMagick

```
PS C:\Projects\web-technology\generator> magick convert 16.png 24.png 32.png 48.png 256.png icon.ico
PS C:\Projects\web-technology\generator> identify icon.ico
icon.ico[0] ICO 16x16 16x16+0+0 8-bit sRGB 22678B 0.000u 0:00.002
icon.ico[1] ICO 24x24 24x24+0+0 8-bit sRGB 22678B 0.000u 0:00.005
icon.ico[2] ICO 32x32 32x32+0+0 8-bit sRGB 22678B 0.000u 0:00.006
icon.ico[3] ICO 48x48 48x48+0+0 8-bit sRGB 22678B 0.000u 0:00.008
icon.ico[1] PNG 256x256 256x256+0+0 8-bit sRGB 22678B 0.000u 0:00.007
```

```
//provide configuration here
```

<br/><br/>
Please also provide:

- Platform(OS/Version): Windows 10 x64bit
- Host Node Version: 8.6.0
- Target Node Version: 8.6.0
- Nexe version: 2.0.0-rc.11
- Python Version: 2.7.13

**Comment by calebboyd** [comment]
See --help, `ico` option requires `build: true`

**Comment by vickylance** [comment]
@calebboyd Does that mean everytime I make a change to the code I have to build it again. Because building from source takes ~1hr to 1hr 30 mins.

**Comment by calebboyd** [comment]
Nope, they're reused. If you change your icon though you'll have to rebuild.

>Subsequently using this flag will cause nexe to use the previously built binary.
https://github.com/nexe/nexe#build-boolean

**Comment by vickylance** [comment]
@calebboyd  Sorry I read that earlier but was not able to quite understand it. But now I checked how it works and now I get it thanks.
Its awesome and yeah it works :)

![capture](https://user-images.githubusercontent.com/5861833/31245790-09164eda-aa29-11e7-87f5-5ac3342792ec.PNG)

**Comment by calebboyd** [comment]
I should make it easier to understand. Thanks for the feedback :)

**Comment by 07sainishanth** [comment]
> @calebboyd Does that mean everytime I make a change to the code I have to build it again. Because building from source takes ~1hr to 1hr 30 mins.



> @calebboyd Sorry I read that earlier but was not able to quite understand it. But now I checked how it works and now I get it thanks.
> Its awesome and yeah it works :)
> 
> ![capture](https://user-images.githubusercontent.com/5861833/31245790-09164eda-aa29-11e7-87f5-5ac3342792ec.PNG)

Excuse Me .Could you tell me what did you change other then build:true to change the icon

**Comment by vickylance** [comment]
@07sainishanth I think build:true is fine if you need a complete rebuild then use --clean
