### ISSUE TITLE
__dirname is not an absolute path

### ISSUE THREAD

**Issue by Arlen22** [nexe/nexe#405]
This is a
 - [X] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
If this is a bug report, What are the steps to reproduce?

`__dirname` only specifies the folder name instead of the full absolute path like Node would provide. It should provide the full directory path of the executable.

<br/><br/>
Please also provide:

- Platform(OS/Version): Windows 7
- Host Node Version: v6.10
- Target Node Version: none specified
- Nexe version: nexe 2.0.0-rc.11
- Python Version:

**Comment by calebboyd** [comment]
Hmm. Yes, It looks like this is something [fuse-box](https://github.com/fuse-box/fuse-box) is doing. Perhaps pose the question there?

A harmless workaround is to use `path.resolve(__dirname)`.

Although, I'd suggest not using __dirname at all. What is your usecase?

`path.dirname(process.execPath)` would get you the current directory of the executable.

**Comment by Arlen22** [comment]
Just curious, why should I not use __dirname? Is there another way to get the path of the current file that is better? `path.resolve` is dependant on the CWD, isn't it? One way I found is `path.dirname(module.filename || process.execPath)`. The reason I need this is because I have both packaged and unpackaged distributions of my project.

**Comment by calebboyd** [comment]
Its just a non standard api, see my note:
>Edit: to give some context around this --- import.meta is in Stage 3 to replace the non standardized __filename properties etc

Glad you found a workaround

**Comment by Arlen22** [comment]
It's listed in https://nodejs.org/api/modules.html#modules_dirname as being around since Node v0.1.27. How do you mean it is not standard?

**Comment by calebboyd** [comment]
I just mean its an arbitrary nodejs module global. Its not part of commonjs specification or an ecmascript specification.

You can use `path.resolve(__dirname)`. When dirname is absolute it will just pass through, otherwise it will resolve it against the cwd which is what you want in the bundle.

**Comment by Arlen22** [comment]
But it *is* part of the NodeJS documentation. I don't understand what you mean. Isn't nexe meant for Node? I mean, if we don't follow the NodeJS specification, how can it dependably "compile your Node.js application into a single executable file." 

https://nodejs.org/dist/latest-v6.x/docs/api/globals.html#globals_dirname

> The file name of the current module. This is the resolved absolute path of the current module file.

The problem is that if I wanted the cwd, I would use the cwd, but that is not what I am after. Because the cwd could be anywhere, and if a user types out the absolute path to the executable from another cwd, I don't want to start trying to read and write files to that other directory, I want the files in the executable directory. 

P.S. What is the CommonJS specification. I've never heard about it, and all I can find is the Wikipedia article, which says that NodeJS does not follow the CommonJS spec.

**Comment by calebboyd** [comment]
You can use the combination of examples from my first response.

`path.resolve(path.dirname(process.execPath), __dirname)`

As I also mentioned, this is a bug in fuse-box. All I can do right now is provide you with a workaround. 

Nexe is slightly different from regular node. Its more like the `node` repl or `node -e` eval environments (where __dirname and __filename don't exist) **because there are no modules** for those globals to exist in. And as you found, there is a bug in fusebox that fakes their existence by providing a value for __dirname

**Comment by calebboyd** [comment]
@Arlen22 Did that workaround work for you?

**Comment by Arlen22** [comment]
Basically, because depending on where I require the module from, it might contain an actual folder name. What I ended up using was `__dirname = path.dirname(module.filename || process.execPath)`, and so far it seems like it's working fine. 

If process.execPath is not set, I don't think we should fallback to the CWD, though. That would be an application decision. Node also exhibits this behavior, since you could call node.exe from a batch file that uses the absolute path to the script (`%~dp0/node %~dp0/server.js`) if the application is on PATH. __dirname would then presumably be set based on process.argv[1], which would be an absolute path. 

Where is the fuse-box repo? Is there an issue open currently? If not, I would be happy to open one.

**Comment by calebboyd** [comment]
Application decision for sure. Here is the repo, I don't think an issue has been raised.
https://github.com/fuse-box/fuse-box
