### ISSUE TITLE
update to ES2017

### ISSUE THREAD

**Issue by xileftenurb** [nexe/nexe#409]
It would be nice to be able to use ES2017 in compilation.

I got an "Acorn error" when trying to use feature enabled by Node 8.

I searched Acorn and there is an option to enable ES2017.
is it possible to send the option from nexe to acorn? if yes, how? if now, I make it a feature request.

thank you

**Comment by calebboyd** [comment]
I agree! pending https://github.com/fuse-box/fuse-box/pull/862

**Comment by calebboyd** [comment]
Now pending https://github.com/fuse-box/fuse-box/pull/864 😃

**Comment by calebboyd** [comment]
Try updating this is fixed :)
