### ISSUE TITLE
Can an included resource be an executable?

### ISSUE THREAD

**Issue by momocow** [nexe/nexe#411]
This is a
 - [ ] Bug Report
 - [ ] Feature Request
 - [x] Other

My project is using [`windows-shortcuts`](https://github.com/j201/windows-shortcuts) a dependency; however, this module is actually using `child_process.execFile` to call an prebuilt executable [`Shortcut.exe`](https://github.com/j201/windows-shortcuts/tree/master/lib/shortcut). I am wondering a way to make it work as expected.

Here is the code that `windows-shortcuts` try to run the `Shortcut.exe`.
I have found that `__dirname =='lib/'`, so the nexe-compiled executable of my project try to find an executable located at `lib/shortcut/Shortcut.exe`. (and ENOENT is thrown)
```
execFile(__dirname + '/shortcut/Shortcut.exe',
		['args'],
		function(error, stdout, stderr) {
			...
		});
```

It seems that the resources cannot be executables, then how can I solve the problem?
(I am thinking about manually placing the Shortcut.exe at the `process.cwd()+'/lib/shortcut'` as an alternative way)

btw, another question, do the resources remain the same structure as my project structure?
e.g. I have an image under `<project-root>/assets/img/target.png`, then I can access the image at `process.env.NODE_PATH+'/assets/img/target.png'`. Just like what [`asar` (by electron)](https://github.com/electron/asar) does.

**Comment by calebboyd** [comment]
Since you can't execute the file as it exists you'll have to write it out before using that library.

eg. `nexe -r node_modules/windows-shortcuts/lib/shortcut/Shortcut.exe`

and somewhere in your app before you run it.. 
```javascript
fs.writeFileSync(
  'lib/shortcut/Shortcut.exe', 
  fs.readFileSync('node_modules/windows-shortcuts/lib/shortcut/Shortcut.exe'
)
```

The assets will have the same (relative) path as when they are bundled. (as shown above). It will also capture the absolute path (of the executable's working directory)

**Comment by calebboyd** [comment]
For your image example.
`nexe -r ./assets/img/target.png`
````
const png = fs.readFileSync('./assets/img/target.png')
const png2 = fs.readFileSync(path.resolve('./assets/img/target.png'))
png.equals(png2) // true
```

**Comment by momocow** [comment]
Thanks for your examples.

However, is it weird that I have to package and extract the executable for my dependencies? I can totally accept that it is a workaround. But should those modules like `windows-shortcuts` who utilizes an external prebuilt executable be handled by Nexe (or Fuse-box)? 
e.g. walking through dependencies, finding all `child_process#execFile(...)`'s, collecting all executables as resources and extracting them out (even handling their lifetime in the runtime environment).

It seems to be kind of difficult. Modules like `windows-shortcuts` are not like a standard Node.js module, it's more likely an interface of the executable for Node.js. 

It's just a suggestion which is figured out after I read the [native module issue](https://github.com/nexe/nexe/issues/335#issuecomment-311423892) for nexe.

**Comment by calebboyd** [comment]
> is it weird that I have to package and extract the executable for my dependencies?

Hmm... for native modules, the set of possibilities is finite and well defined (small interface). They all ultimately work by requiring a `.node` file. 

With child_process the interface is too broad to be generalized... (unless you know of a way?...). All sorts of modules execute and ship binaries in different ways.

I think also, once you are using external executable it becomes increasingly important you know what is packaged in the binary. I don't really see a path to generalize that behavior.

**Comment by momocow** [comment]
Uh, I got it. That's truth. Binary shipping has no standard spec compared with native modules, so it's difficult to handle which executable  should be included.

I was thinking about parsing all dependent scripts with the help of [esprima](http://esprima.org), and check if the child process (spawn by spawn, execFile, exec) is a local executable (the cmd is a path starting with './' or '../'). It is only feasible if all scripts of dependencies can be parsing as strings (through `<string> fs.readFile('path-to-dep-script')`). But I found out that it is still a complicated work with little benefit. (may hugely increase the loading to build an executable with nexe)

Anyway, thanks for your help. Nice work with nexe. 👍

**Comment by momocow** [comment]
FYI: I found that `electron builder` automatically detects which dependent modules contain executable files and unpacks those modules.
[electron builder configuration #asar](https://www.electron.build/configuration/configuration#PlatformSpecificBuildOptions-asar)

Hope this is useful for this issue.

**Comment by calebboyd** [comment]
Hmm Okay. Interesting. Might be something that can be done alongside #401
