### ISSUE TITLE
Package.json vars do not exist on process.env

### ISSUE THREAD

**Issue by momocow** [nexe/nexe#413]
This is a
 - [x] Bug Report

Please also provide:

- Platform(OS/Version): Window10
- Host Node Version: 8.5.0
- Target Node Version: 8.5.0
- Nexe version: 2.0.0-rc.11
- Python Version: 2.7.13

Hi, I am coming again.

As the [spec](https://docs.npmjs.com/misc/scripts#packagejson-vars) of `npm` tells us 

> The package.json fields are tacked onto the npm_package_ prefix. So, for instance, if you had {"name":"foo", "version":"1.2.5"} in your package.json file, then your package scripts would have the npm_package_name environment variable set to "foo", and the npm_package_version set to "1.2.5"

In my script I wrote `console.log(process.env.npm_package_name)`.
When I try `npm start` it work as expected, but when I try to compile it with nexe and run, `undefined` is shown.
I think this is a bug, right?

**Comment by momocow** [comment]
Just wanna make sure if it is a bug or not, I've read it myself with `require('./package.json').name` as a workaround.

**Comment by calebboyd** [comment]
That solution isn't a "workaround". npm scripts is a feature of the `npm` package and has nothing to do with node or nexe the "spec" you referenced is npm's documentation.
