### ISSUE TITLE
Using helmet with nexe

### ISSUE THREAD

**Issue by kingmayko** [nexe/nexe#415]
This is a  Bug Report
Add test.js
`let helmet = require('helmet')
`
Node.js API:
```
const { compile } = require('nexe')
compile({
  input: './test.js',
  output: './app.bin',
  build: false,
  flags: false,
  target: 'linux-x64-6.9.2',
}).then(() => {
  console.log('success')
})
```
Results errors:
```
var notAllowed = ['self', "'self'"].concat(config.unsafes)
TypeError: Cannot read property 'unsafes' of null
```
And it's code in
 helmet-csp/lib/check-options/check-directive/plugin-types.js

 

- Platform(OS/Version): ubuntu16.04
- Host Node Version: 6.9.2
- Target Node Version: 6.9.2
- Nexe version: 2.0.0-rc.17
- Python Version: 2.7.12

**Comment by calebboyd** [comment]
There is a strange issue with the [bundler](github.com/fuse-box/fuse-box) not being able to require json...
Issue 904

**Comment by calebboyd** [comment]
As a workaround you can take a look at https://github.com/nexe/nexe/issues/399#issuecomment-333687985 where I give an example webpack configuration to use as an alternate bundler

**Comment by kingmayko** [comment]
Thanks a lot !! It's work. 
It's really strange.
