### ISSUE TITLE
Bundle Issues [Tracking Issue]

### ISSUE THREAD

**Issue by calebboyd** [nexe/nexe#418]
This is a collection of issues that will be fixed when the bundler is fixed (in progress)

#417
#414
#408
#405
#398 
#419 
#420 
#423 
#428 
#429
#430 
#432 
#433
#436
#435

**Comment by SheetJSDev** [comment]
Another issue to add to the pile: `require` does not handle "directories" with `package.json` entries (e.g. `require("./")`):

```bash
$ echo 'module.exports = "Hello world!";' > foo.js
$ echo 'console.log(require("./"));' > t.js
$ echo '{ "main": "./foo" }' > package.json
$ node t.js 
Hello world!
$ nexe t.js && ./t
ℹ nexe 2.0.0-rc.22
✔ Compiling result
✔ Entry: 't.js' written to: t
✔ Finished in 0.475s
{}
```

**Comment by calebboyd** [comment]
yeah... Fusebox implicitly requires a `name` and `version` :( -- (it does work if you have those in the package.json -- any installed package has these)

**Comment by SheetJSDev** [comment]
It still fails even if you specify both name and version in package.json:

```bash
$ echo 'module.exports = "Hello world!";' > foo.js
$ echo 'console.log(require("./"));' > t.js
$ echo '{ "name": "foobar", "version": "1.0.0", "main": "./foo" }' > package.json
$ node t.js 
Hello world!
$ nexe t.js && ./t
ℹ nexe 2.0.0-rc.22
✔ Compiling result
✔ Entry: 't.js' written to: t
✔ Finished in 0.428s
{}
```

**Comment by calebboyd** [comment]
Hmm. That's fun (not). I'm working on replacing that dependency with this https://github.com/nexe/resolve-dependencies

**Comment by Deilan** [comment]
@calebboyd Is there a temporary workaround until the issues is fixed?

**Comment by calebboyd** [comment]
@Deilan Do you have a specific issue in particular you were encountering (can you reply there?)? This is more of a triage issue for bundling in general.
