### ISSUE TITLE
zip-folder module bundling error

### ISSUE THREAD

**Issue by HarelAshwal** [nexe/nexe#423]
`var zipfolder=require('zip-folder');`

causing the following error when try to bunde:

i nexe 2.0.0-rc.20
Acorn error: Invalid number (104:17)
File: C:\projects_node\xlsx_test\node_modules\archiver\lib\modules\core\index.js

102
103    if (typeof data.mode === 'number') {
104      data.mode &= 0777;
105    } else if (stats) {
106      data.mode = stats.mode & 0777;
107    } else {
108      data.mode = isDir ? 0755 : 0644;

Acorn error: Invalid number (104:17)
File: C:\projects_node\xlsx_test\node_modules\archiver\lib\modules\core\index.js

102
103    if (typeof data.mode === 'number') {
104      data.mode &= 0777;
105    } else if (stats) {
106      data.mode = stats.mode & 0777;
107    } else {
108      data.mode = isDir ? 0755 : 0644;

- nexe 2.0.0-rc.20undefined
√ Compiling result
√ Entry: 'app.js' written to: app.exe
√ Finished in 0.625s

**Comment by calebboyd** [comment]
the module `zip-folder` is locking you into an `archiver` version that is 3 years old. 

Maybe just use `archiver` directly? -- `zip-folder` is like 10 LOC
