### ISSUE TITLE
[Bug] - 403 Forbidden in CI

### ISSUE THREAD

**Issue by calebboyd** [nexe/nexe#425]
@enko via gitter

>I'm trying to build an executeable with nexe on travis, but it seems to fail to download something: https://travis-ci.org/datenknoten/restic-orchestrator/jobs/307289153

**Comment by calebboyd** [comment]
Closed via https://github.com/nexe/nexe/commit/5ac0afb0dd71a3686d3d7249d1740ae8e514ceaa

**Comment by enko** [comment]
@calebboyd thanks for opening a ticket!

As a side note, it would be better from the terms of usability to catch the exception, print a useful error message and point to the github token.
