### ISSUE TITLE
Cannot read property 'version' of null

### ISSUE THREAD

**Issue by antony** [nexe/nexe#428]
This is a
 - [X] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
1. Build an application with nexe.
2. When trying to run windows executable:

```
exports.version = require('./package').version;

TypeError: Cannot read property 'version' of null
```

It looks like this line should be corrected to `require('./package.json').version` or loading of json files as js files explicitly enabled in rollup/webpack

<br/><br/>

- Platform(OS/Version): Ubuntu 17.04
- Host Node Version: 9.2.0
- Target Node Version: 9.2.0
- Nexe version: 2.0.0-rc.22
- Python Version: 2.7.12+

**Comment by calebboyd** [comment]
Sorry, Working on resolving this -- #418

To clarify, it works if you use `require("./package.json")`?

**Comment by antony** [comment]
Heya - it's not actually something I'm doing. Appears to be nexe.

I tried creating package.js to fool it and just exporting the contents of package.json `module.exports = require('package.json')` but to no avail.

**Comment by calebboyd** [comment]
Okay, Here is a workaround to bypass the bundler

`nexe entry-file.js --bundle ./nexe-bundle.js`

and `nexe-bundle.js` (requires two dependencies `pify` and `webpack`

```javascript
const webpack = require('pify')(require("webpack"))
const fs = require('fs')

module.exports.createBundle = function (options) {
    return webpack({
        entry: options.input,
        target: 'node',
        output: { filename: 'tmp.js' }
    }).then(() => {
        const result = fs.readFileSync('./tmp.js').toString()
        fs.unlinkSync('./tmp.js')
        return result
    })
}
```

**Comment by antony** [comment]
Thanks for that :)
