### ISSUE TITLE
`nexe -i` generates empty app on nonstandard script extensions

### ISSUE THREAD

**Issue by SheetJSDev** [nexe/nexe#429]
We use the nonstandard extension `.njs` to distinguish scripts meant for node consumption from universal scripts.  Using a nonstandard file extension `.njs`:

```bash
$ echo 'console.log("hello world");' > t.js 
$ echo 'console.log("hello world");' > t.njs
```

Running `nexe filename` will fail for the nonstandard extensions:

```bash
$ nexe t.njs 

Error: No entry file found
    at resolveEntry (/usr/local/lib/node_modules/nexe/lib/options.js:131:15)
```

However, `nexe -i filename` will pass but generates an empty app:

```bash
$ nexe -i t.njs --debugBundle app.bundle.js &>/dev/null; rm -f t
$ nexe -i t.njs --debugBundle app.bundle.njs; echo $?; ./t
ℹ nexe 2.0.0-rc.22
✔ Compiling result
✔ Entry: 't.njs' written to: t
✔ Finished in 0.418s
0
```

Inspecting the bundles shows the code is not added in the nonstandard case:

```diff
--- app.bundle.js
+++ app.bundle.njs
@@ -2,8 +2,3 @@
 FuseBox.pkg("default", {}, function(___scope___){
-___scope___.file("t.js", function(exports, require, module, __filename, __dirname){
-
-console.log("hello world");
-
-});
-return ___scope___.entry = "t.js";
+return ___scope___.entry = "t.njs";
 });
@@ -11,4 +6,4 @@
 
-FuseBox.import("default/t.js");
-FuseBox.main("default/t.js");
+FuseBox.import("default/t.njs");
+FuseBox.main("default/t.njs");
 })
```

**Comment by calebboyd** [comment]
Hmm Yeah, Looks like fusebox can't handle that extension... I'm adding it to #418...

**Comment by calebboyd** [comment]
You may be able to use webpack and provide necessary configuration to resolve .njs files
see my comment [here](https://github.com/nexe/nexe/issues/428#issuecomment-348553688)

**Comment by SheetJSDev** [comment]
Renaming to `.js` is fine, and we have to do some munging to strip the shebang anyway.  To be clear, this issue is specifically about inconsistent handling of the normal entry spec (`nexe filename`) versus the option form (`nexe -i filename`).

Digging into the code, the issue is in [`resolveEntry`](https://github.com/nexe/nexe/blob/master/src/options.ts#L195-L210).  The `isEntryFile` is guarding against bad extensions, but that check is bypassed when specifying an input with `-i`.  Would it make sense to additionally apply the `isEntryFile` check in the option case?  The code would look something like:

```typescript
export function resolveEntry(input: string, cwd: string, maybeEntry?: string) {
  const entry: string = input || maybeEntry || "";
  if (entry && isEntryFile(entry)) {
    return resolve(cwd, entry)
  }
  if (!process.stdin.isTTY) {
    return ''
  }
  try {
    return require.resolve(cwd)
  } catch (e) {
    throw new Error('No entry file found')
  }
}
```
