### ISSUE TITLE
Question about publishing cross-platform binaries generated be nexe as an npm module

### ISSUE THREAD

**Issue by dandean** [nexe/nexe#431]
This is a Question

I'd like to publish a nexe binary as an npm module which will, when installed, run on both mac and linux. How do I configure my module to install the correct binary, based on the current platform?

**Comment by calebboyd** [comment]
I'd host it somewhere, github releases maybe and publish a package consisting only of a postinstall script and a bin entry. The post install script can just download the correct binary to the location referenced by the bin entry.

**Comment by dandean** [comment]
@calebboyd Thank you for the pointers! 👍
