### ISSUE TITLE
Requiring Puppeteer returns null

### ISSUE THREAD

**Issue by CelesterSpencer** [nexe/nexe#432]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
So i want to create a small test application using puppeteer. When requiring puppeteer and logging it, it happens to be null.

<br/>

**index.js**
```
const puppeteer = require('puppeteer');
console.log(puppeteer);
```

**terminal output**
```
null
```

Does it have to do something with native modules? And if yes, is there any possibility to provided puppeteer alongside the binary?

<br/><br/>
Please also provide:

- Platform(OS/Version): Win 7 SP1
- Host Node Version: 8.9.3
- Target Node Version: 8.9.3
- Nexe version: 8.9.3
- Python Version: 8.9.3

**Comment by calebboyd** [comment]
I'm working on this as well. Its an issue with the bundler at the moment.. #418 
https://github.com/GoogleChrome/puppeteer/commit/42fd41c4996878e4836aeb9602de23054953b9cb

**Comment by CelesterSpencer** [comment]
Thank you for the quick reply calebboyd, i got a bit sick around Christmas. Anyway, waiting patiently for it getting fixed. Nexe is my favourite node build tool. :)
