### ISSUE TITLE
Unable to process .js that starts with #!/usr/bin/env node

### ISSUE THREAD

**Issue by pjbgf** [nexe/nexe#433]
This is a
 - [ X ] Bug Report
 - [ ] Feature Request
 - [ ] Other

NEXE seems to be unable to process [a file](https://github.com/snyk/snyk/blob/master/cli/index.js) that starts with `#!/usr/bin/env node`.

<br/>
Steps to reproduce:

1. Clone repo https://github.com/snyk/snyk
2. cd snyk
3. npm install
4. cd cli
5. Execute cat index.js | nexe -o test && ./test

```
cat index.js | nexe -o test && ./test
ℹ nexe 2.0.0-rc.22
✔ Compiling result
✔ Entry: '[stdin]' written to: test
✔ Finished in 0.195s
/Users/paulo.gomes/git/snyk/snyk/cli/test:9
      process.argv.splice(1,0, '[stdin]');})();;#!/usr/bin/env node
                                                ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at _third_party_main.js:45:20
    at NativeModule.compile (bootstrap_node.js:596:7)
    at Function.NativeModule.require (bootstrap_node.js:541:18)
    at bootstrap_node.js:116:22
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

<br/><br/>
Please also provide:

- Platform(OS/Version): MacOS High Sierra 10.13.1
- Host Node Version: v8.9.3
- Target Node Version: -
- Nexe version: 2.0.0-rc.22
- Python Version: Python 2.7.10

**Comment by calebboyd** [comment]
You're right, currently tracking the issue in #398 and #418
