### ISSUE TITLE
Cannot find modules that exist on node_modules

### ISSUE THREAD

**Issue by pjbgf** [nexe/nexe#434]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>

For some reason nexe is not being able to find modules that exist on the node_modules folder.

Steps to reproduce:

1. Clone repo https://github.com/snyk/snyk
2. cd snyk
3. npm install
4. cd cli
5. nexe index.js --no-bundle --build --resources "../node_modules/**/*.js" --resources "../lib/**/*.js" -o snyk && ./snyk

```js
cat index.js | tail -n+3 | nexe --no-bundle --build --resources "../node_modules/**/*.js" --resources "../lib/**/*.js" -o snyk && ./snyk
✔ Included 28872 file(s). 86.520 MB
✔ Source already downloaded
✔ Compiling result
✔ Entry: '[stdin]' written to: snyk
✔ Finished in 738.087s
module.js:538
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/paulo.gomes/git/snyk/snyk/cli/snyk:179:13)
    at Module._compile (module.js:635:30)
    at _third_party_main.js:45:20
    at NativeModule.compile (bootstrap_node.js:596:7)
    at Function.NativeModule.require (bootstrap_node.js:541:18)
    at bootstrap_node.js:116:22
```

<br/><br/>
Please also provide:

- Platform(OS/Version): MacOS High Sierra 10.13.1
- Host Node Version: v8.9.3
- Target Node Version: -
- Nexe version: 2.0.0-rc.22
- Python Version: Python 2.7.10

**Comment by pjbgf** [comment]
@calebboyd good to hear that. Is there anything you would suggest to work around the problem in the mean time?

**Comment by calebboyd** [comment]
You can try bundling with webpack...Though, I think it would also choke on hotload.js

see https://github.com/nexe/nexe/issues/428#issuecomment-348553688

**Comment by calebboyd** [comment]
@pjbgf this appears to be working in `nexe@next`

using the following command `nexe cli/index.js --build -o synk -r "{cli,dist,lib,help}/**/*" -r *.json`
