### ISSUE TITLE
Error: Cannot find module 'got'

### ISSUE THREAD

**Issue by RobertDiebels** [nexe/nexe#439]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
If this is a bug report, What are the steps to reproduce?

1. Create a new NodeJS project.
2. Execute `npm install nexe --save-dev`
3. Define a run-script which uses this file: `scripts: { build: 'node ./build/production.js' }`
4. The file production.js is provided below.
5. Execute `npm run build`
6. The process will fail reporting: `Cannot find module 'got' `.

**production.js**
```
const { compile } = require('nexe'); 

// Application fails before executing compile
compile({
    name: 'my-app',
    input: './index.js'
}).then(() => {
    console.log('success')
});
```

**Versions**
- Platform(OS/Version): Windows 10
- Host Node Version: v8.9.3
- Target Node Version: null
- Nexe version: ^2.0.0-rc.22
- Python Version: null

**Additional information**
I checked the package.json and `got` is listed in `devDependencies` so it is not retrieved from NPM. I believe adding `got` to `dependencies` will fix this.

**Work-around**
`npm install got`

**Comment by calebboyd** [comment]
What version of npm did you use to install nexe?

**Comment by RobertDiebels** [comment]
@calebboyd I used `npm 5.5.1` to install nexe.
