### ISSUE TITLE
Just a big thanks

### ISSUE THREAD

**Issue by fgreinus** [nexe/nexe#443]
Hey guys, I just wanted to let you know, that I really appreciate what you are working on here! Your project helped me achieve what would've cost me months when building myself. Thanks!

(I hope it's not a big deal to post this as an issue, but I just wanted to leave a quick thanks and did not know how to do, but post here 😁 )

**Comment by jaredallard** [comment]
Might as well as throw in huge props to @calebboyd for all of his hard work on this project! ❤️

**Comment by Rirbeiro** [comment]
Is it possible run the exe from PHP server?
Thanks

**Comment by calebboyd** [comment]
Thanks!
