### ISSUE TITLE
"Writing result to file" is never-ending

### ISSUE THREAD

**Issue by martinjoubert** [nexe/nexe#444]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
Steps to reproduce:

 - Install Zenbot: https://github.com/DeviaVir/zenbot
 - run nexe in Zenbot's root directory: nexe index.js -p /usr/bin/python2.7
 - The task called "Writing result to file" is never-ending

<br/><br/>
- Platform(OS/Version): MacOS 10.13.1
- Host Node Version: v8.9.1
- Target Node Version: v8.9.1
- Nexe version: 2.0.0-rc.22
- Python Version: 2.7

**Comment by jaredallard** [comment]
Can you provide a log?

**Comment by martinjoubert** [comment]
Hmm, I think I was not in the good directory :/
But I still get an error when I run nexe in the good directory:

$ nexe index.js -p /usr/bin/python2.7 --verbose
ℹ nexe 2.0.0-rc.22
Acorn error: Octal literal in strict mode (53:60)
File: /Users/admin/Documents/blockchain/zenbot/node_modules/eyes/lib/eyes.js

51          return this.print(stringify(obj, options), label, options);
52      } else {
53          return stringify(obj, options) + (options.styles ? '\033[39m' : '');
54      }
55  };
56  
57  // Output using the 'stream', and an optional label

Acorn error: Octal literal in strict mode (53:60)
File: /Users/admin/Documents/blockchain/zenbot/node_modules/eyes/lib/eyes.js

51          return this.print(stringify(obj, options), label, options);
52      } else {
53          return stringify(obj, options) + (options.styles ? '\033[39m' : '');
54      }
55  };
56  
57  // Output using the 'stream', and an optional label


⠋ nexe 2.0.0-rc.22undefined
✔ Compiling result
✔ Writing result to file
✔ Entry: 'index.js' written to: zenbot
✔ Finished in 2.07s

-------------

$ ./zenbot
module.js:538
    throw err;
    ^

Error: Cannot find module 'codemap@1.3.1'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at u (/Users/admin/Documents/blockchain/zenbot/zenbot:3575:1092)
    at f (/Users/admin/Documents/blockchain/zenbot/zenbot:3575:1430)
    at c (/Users/admin/Documents/blockchain/zenbot/zenbot:3575:2520)
    at y.require (/Users/admin/Documents/blockchain/zenbot/zenbot:3575:3117)
    at Number.<anonymous> (/Users/admin/Documents/blockchain/zenbot/zenbot:13:15)
    at c (/Users/admin/Documents/blockchain/zenbot/zenbot:3575:3333)

-------------------

index.js:
var codemap = require('codemap')

module.exports = function () {
  var rootMap = {
    _maps: [require('./_codemap')],

    'get': function container (get, set) {
      return get
    },
    'set': function container (get, set) {
      return set
    },
    'use': function container (get, set) {
      return function use () {
        ;[].slice.call(arguments).forEach(function (arg) {
          instance.parseMap(arg)
        })
        instance.validatePathCache()
      }
    }
  }
  var instance = codemap(rootMap)
  return instance.export()
}

module.exports.version = require('./package.json').version

**Comment by jaredallard** [comment]
@calebboyd is this something to do with previous issues about how strict mode is interpreted (I know that used to be an issue)

**Comment by calebboyd** [comment]
Yeah... It is.. I Don't have a easy solution yet. The New "bundler" is almost ready...It doesn't really bundle, but will enable require-ing from nexe resources. It should solve this and all of the other issues in #418
