### ISSUE TITLE
Request to upgrade fuse-box version

### ISSUE THREAD

**Issue by lizardruss** [nexe/nexe#449]
This is a
 - [ ] Bug Report
 - [x] Feature Request
 - [ ] Other

When trying to package a nest.js application using nexe, I ran into an issue where `this` was interpreted incorrectly. I traced it back to a [`fuse-box` issue which has since been fixed](https://github.com/fuse-box/fuse-box/issues/1030).

I was able to work around the issue by installing the new version of `fuse-box` locally and overriding the `bundle` step with nearly the same bundle code contained in nexe. I'm creating this issue in hopes that a new release can be made that'll make it possible to remove the override.

Please also provide:

- Platform(OS/Version): OSX High Sierra
- Host Node Version: 8.9.0
- Target Node Version: 8.9.0
- Nexe version: v2.0.0-rc.22
- Python Version:

**Comment by calebboyd** [comment]
That's doable, updated.
