### ISSUE TITLE
Bundling non-strict code

### ISSUE THREAD

**Issue by 0xbitcoin** [nexe/nexe#450]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
If this is a bug report, What are the steps to reproduce?

index.js contains:

 
var Web3 = require('web3') 

run nexe . 

run the file with ./indextest   

- error occurs !

Acorn error: Invalid number (108:10)
File: /..../node_modules/tar/tar.js

106  // values for the mode field
107  var modes =
108    { suid: 04000 // set uid on extraction
109    , sgid: 02000 // set gid on extraction
110    , svtx: 01000 // set restricted deletion flag on dirs on extraction
111    , uread:  0400
112    , uwrite: 0200

Cannot find module 'web3@1.0.0-beta.29'

```
//provide configuration here
Nodejs 7.6

Add these to package.json: 
 
    "web3": "^1.0.0-beta.29",
 

```

<br/><br/>
Please also provide:

- Platform(OS/Version): Linux 
- Host Node Version:  7.6
- Target Node Version: 7.6
- Nexe version: 
- Python Version:

**Comment by calebboyd** [comment]
Looks like an old dependency in [swarm-js#](https://github.com/MaiaVictor/swarm-js)10 ([tar.gz](https://github.com/alanhoff/node-tar.gz))

I'd advocate for that to be fixed..

In the meantime, the overall issue is being addressed by work being done for #418
