### ISSUE TITLE
Cannot find module 'any-promise'

### ISSUE THREAD

**Issue by felix307253927** [nexe/nexe#452]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
If this is a bug report, What are the steps to reproduce?

```
"dependencies": {
    "koa": "^2.4.1",
    "koa-router": "^7.4.0",
    "koa-static": "^4.0.2",
    "any-promise": "^1.3.0"
  }
```
![image](https://user-images.githubusercontent.com/9459249/35892948-a9d6a6ca-0be6-11e8-8386-e2e3b72c7165.png)
![image](https://user-images.githubusercontent.com/9459249/35893366-b1d854fc-0be8-11e8-8a80-63f9ad17a196.png)

<br/><br/>
Please also provide:

- Platform(OS/Version): ubuntu 16.04
- Host Node Version: 8.9.0
- Target Node Version:8.9.4
- Nexe version:2.0.0-rc.22
- Python Version:2.7.12

**Comment by calebboyd** [comment]
This will be fixed with along with the issues in #418

And...

That library appears to be abandoned.
The description says "NOTE: You probably want native promises now"
