### ISSUE TITLE
Add pify, source-map and uglify-es to package.json dependencies field

### ISSUE THREAD

**Issue by foxever** [nexe/nexe#462]
This is a
 - [ ] Bug Report

<br/>
If this is a bug report, What are the steps to reproduce?

```
//provide configuration here
```

<br/><br/>
Please also provide:

- Platform(OS/Version):
- Host Node Version:
- Target Node Version:
- Nexe version: 2.0.0-rc.25
- Python Version:

**Comment by jaredallard** [comment]
#461 and this would probably be better as PRs.
