### ISSUE TITLE
nexe --help Black font at the black background.

### ISSUE THREAD

**Issue by KonradLinkowski** [nexe/nexe#464]
This is a
 - [ ] Bug Report
 - [ ] Feature Request
 - [X] Other
<br/>
I'm using Cmder as a command line program. And when I'm trying to list --help I'm getting black font on black background. Everything is invisible unless I highlight it.

![image](https://user-images.githubusercontent.com/26126510/37260315-1880037c-2592-11e8-9d33-a2a82df16e83.png)

<br/><br/>
Please also provide:

- Platform(OS/Version): Windows Cmder
- Host Node Version: ?
- Target Node Version: v8.4.0
- Nexe version: nexe@2.0.0-rc.26
- Python Version: 3.6.2

**Comment by calebboyd** [comment]
Fixed in `nexe@next`
