### ISSUE TITLE
Compiled app fails to find top-level dependencies' child dependencies that are installed at at the top-level

### ISSUE THREAD

**Issue by JamesMGreene** [nexe/nexe#466]
This is a
 - [x] Bug Report

<br/>
If this is a bug report, what are the steps to reproduce?

* Repro repo with steps in `README.md`: [JamesMGreene/nexe-test](https://github.com/JamesMGreene/nexe-test)

<br/>
Please also provide:

- **Platform(OS/Version):** Windows 10 Enterprise (64-bit)
- **Host Node Version:** `8.10.0`
- **Target Node Version:** `8.10.0`
- **Nexe version:** `2.0.0-next.5`
- **Python Version:** `2.7.11`

### NPM folder structure concept

- https://docs.npmjs.com/cli/install#algorithm
- https://docs.npmjs.com/files/folders#cycles-conflicts-and-folder-parsimony

### Execution

```shell
$ cd ..
$ NexeTest.exe

module.js:327
    throw err;
    ^

Error: Cannot find module 'swagger-schema-official/schema.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\git\node_modules\swagger-parser\lib\validators\schema.js:6:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

But both dependencies (and many more) are indeed installed in `node_modules` at the top-level:

![image](https://user-images.githubusercontent.com/417751/37425363-17dca7d0-2791-11e8-83a3-78c2b4fb94b6.png)

**Comment by calebboyd** [comment]
I found the bug in [resolve-dependencies](https://github.com/nexe/resolve-dependencies)

An incorrect assumption was made that a commonjs package had to have an entrypoint that could be resolved from its name... In this case it is `swagger-schema-official`.  e.g. `node -e "require('swagger-schema-official')"` throws an error, so it doesn't get resolved

**Comment by JamesMGreene** [comment]
That certainly is the norm but it’s true that is not a strict requirement of modules. Understandable oversight, though, given these type of modules are relatively uncommon.

**Comment by calebboyd** [comment]
Yeah, It was a performance optimization (to pull the dependencies right out of the package.json instead of traversing the ast). The resolver works fine, but i'm rethinking that shortcut.

**Comment by calebboyd** [comment]
This should be fixed! via https://github.com/nexe/resolve-dependencies/commit/fecfebc36b985cc53554308792c5caceae21cdb6

`nexe@next`

**Comment by JamesMGreene** [comment]
Cool, I’ll try it out tomorrow!

**Comment by calebboyd** [comment]
Might have closed this prematurely, The parser I switched to isn't quite as mature as babylon
