### ISSUE TITLE
OS X: unable to code sign executable

### ISSUE THREAD

**Issue by weevilgenius** [nexe/nexe#470]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
Steps to reproduce:

```
$ echo 'console.log("hello world");' | nexe -t 9.8.0 -o test
ℹ nexe 2.0.0-rc.26
✔ Compiling result
✔ Entry: '[stdin]' written to: test
✔ Finished in 0.105s

$ codesign -vvv -s "<signing identity>" test
test: main executable failed strict validation
```

<br/>
Please also provide:

- Platform(OS/Version): OS X 10.11.6
- Host Node Version: 9.8.0
- Target Node Version: 9.8.0
- Nexe version: 2.0.0-rc.26
- Python Version: 2.7.14

**Comment by calebboyd** [comment]
Use the `build` and `patches` options noted here https://github.com/nexe/nexe/issues/446#issuecomment-360386260

Also note that resources (`-r` `--resource`) won't work in this configuration

**Comment by calebboyd** [comment]
@weevilgenius Did this answer your question?
