### ISSUE TITLE
Compiled binary is broken using pre-compiled node source from nexe

### ISSUE THREAD

**Issue by chrstew** [nexe/nexe#472]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>

2 issues in one day, sorry for this

If this is a bug report, What are the steps to reproduce?

It is worth noting that using nexe 1.1.2 with the same file / compilation process succeeds

1. create a simple hello.js file of `console.log('hello world');`
2. run the command line: `nexe -i hello.js -o hello -t 8.9.1`

```
nexe -i hello.js -o hello -t 8.9.1
ℹ nexe 2.0.0-rc.26
✔ Compiling result
✔ Entry: 'hello.js' written to: hello
✔ Finished in 0.507s
```

Upon running the resulting binary:
```
./hello
./hello: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./hello)
./hello: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./hello)
./hello: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by ./hello)
./hello: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ./hello)
./hello: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by ./hello)
./hello: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./hello)
```

Again to note compiling this under 1.1.2 works without these GLIBC errors

<br/><br/>
Please also provide:

- Platform(OS/Version): CentOS 6
- Host Node Version: 8.11.1
- Target Node Version: 8.9.1
- Nexe version: 2.0.0-rc.26
- Python Version: 2.6.6

**Comment by calebboyd** [comment]
Looks like your glibc is too old or not present. A static version is available, 

try `nexe hello.js -t static-8.9.1`

**Comment by chrstew** [comment]
This worked, thank you very much
