### ISSUE TITLE
Executables built by Gitlab Runner using Docker are broken.

### ISSUE THREAD

**Issue by JoonasC** [nexe/nexe#477]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
If this is a bug report, What are the steps to reproduce?
<br/><br/>

1. Setup a Gitlab CI environment, with Gitlab runner.
2. Register a new runner that uses Docker as it's executor, and use the image `node:latest`.
3. Try build an executable with Nexe using Gitlab Runner.
4. Try to run the produced executable

**Note**: I have tested that this issue is caused because of Gitlab Runner, since an executable built manually using this docker image works. I have posted an issue on the Gitlab forums, but they don't seem to be answering, so i thought i might as well post this here. As for how the executables are broken, when i try to run them, they just exit instantly and don't output anything to the console.

<br/><br/>
Please also provide:

- Platform(OS/Version): Centos 7
- Host Node Version: 9.11.1(since using the `node:latest` Docker image)
- Target Node Version: 9.9.0
- Nexe version: 2.0.0-rc.27
- Python Version: 2.7.9 is the version currently used in `node:latest`

**Comment by calebboyd** [comment]
How are you running nexe, what are the arguments/configuration being used

**Comment by JoonasC** [comment]
This the script i run to build with nexe:
```
nexe main.js --target linux-x64-9.5.0 -o node_linux
retcode=$?
if [ $retcode != 0 ];then
    exit 1
fi
nexe main.js --target mac-x64-9.9.0 -o node_macos
retcode=$?
if [ $retcode != 0 ];then
    exit 1
fi
nexe main.js --target windows-x64-9.9.0 -o node.exe
retcode=$?
if [ $retcode != 0 ];then
    exit 1
fi
mkdir dist
mv node_linux dist/node_linux
mv node_macos dist/node_macos
mv node.exe dist/node.exe
```

**Comment by JoonasC** [comment]
Adding `-i` did not help, still same problem. And i am using Gitlab not GitHub, so i don't see why i should set that token.

**Comment by calebboyd** [comment]
Because nexe uses the GitHub releases API to download prebuilt executables. This is fine locally, but often ci installations will be blocked

**Comment by JoonasC** [comment]
Ok i'm trying with the token now

**Comment by JoonasC** [comment]
One interesting thing, is that i'm not seeing much output from nexe in my CI logs.
I just see RUN a three times.
```
Running with gitlab-runner 10.7.1 (b9bba623)
  on Node test runner 3bc2c7a6
Using Docker executor with image node:latest ...
Pulling docker image node:latest ...
Using docker image sha256:1c1272350058db55158ae07e6fb9ac0de9ce6b3e5dea8b3e1c687e8708cba4a1 for node:latest ...
Running on runner-3bc2c7a6-project-30-concurrent-0 via localhost.localdomain...
Fetching changes...
Removing dist/
Removing node_modules/
HEAD is now at a5bd3af Progress:
From https://dyndev.dynavio.com/selko/selko-node
   a5bd3af..a93efa4  dev        -> origin/dev
Checking out a93efa40 as dev...
Skipping Git submodules setup
$ npm install -g nexe
/usr/local/bin/nexe -> /usr/local/lib/node_modules/nexe/index.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/nexe/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ nexe@2.0.0-rc.27
added 443 packages in 13.34s
$ npm install
npm WARN selko-node@0.0.1 scripts['server'] should probably be scripts['start'].
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 244 packages in 3.737s
$ sh build.sh
RUN
RUN
RUN
Uploading artifacts...
dist/node_linux: found 1 matching files            
dist/node_macos: found 1 matching files            
dist/node.exe: found 1 matching files              
Uploading artifacts to coordinator... ok            id=175 responseStatus=201 Created token=m_bnGvnH
Job succeeded
```

**Comment by JoonasC** [comment]
Nope, adding the token did not help...

**Comment by JoonasC** [comment]
Whoops i accidentally added the token to the wrong CI job. Trying again..

**Comment by JoonasC** [comment]
Ok it actually didn't help...
