### ISSUE TITLE
Doesn't work with "websocket" package

### ISSUE THREAD

**Issue by jeffrson** [nexe/nexe#478]
I'm working on Windows 10, Python 2.7.14.

Given this package.json:
```
{
  "name": "nexe_test",
  "version": "1.0.0",
  "description": "nexe_test",
  "main": "src/test.js",
  "license": "ISC",
  "dependencies": {
    "websocket": "^1.0.26"
  }
}

```
and this `test.js` in subfolder `src`:
```
console.log("1")
const webSocket = require("websocket");
console.log("2")

```
I build `test.exe` with `nexe --verbose -t 9.11.1`, which outputs
```
i nexe 2.0.0-rc.27
RUN
√ Compiling result
√ Writing result to file
√ Entry: 'src\test.js' written to: test.exe
√ Finished in 1.236s

```
Running `test.exe` results in:
```
1
...\test.exe:2704
var bufferUtil = require('./BufferUtil').BufferUtil;
                                        ^
TypeError: Cannot read property 'BufferUtil' of null
    at Object.<anonymous> (...\test.exe:2704:41)
    at c (...\test.exe:4408:3565)
    at b.require (...\test.exe:4408:3327)
    at Object.<anonymous> (...\test.exe:1809:22)
    at c (...\test.exe:4408:3565)
    at b.require (...\test.exe:4408:3327)
    at Object.<anonymous> (...\test.exe:1282:27)
    at c (...\test.exe:4408:3565)
    at b.require (...\test.exe:4408:3327)
    at Object.<anonymous> (...\test.exe:970:24)
```

A simple `node src\test.js` works as expected:
```
1
2

```

**Comment by MatthewSH** [comment]
I'm also experiencing this issue. I would love to use Nexe for releasing some of my stuff...but this makes it impossible because websocket is required for my project.

**Comment by MatthewSH** [comment]
@jaredallard I'll be honest, I just started using Nexe tonight so I don't know enough to diagnose the issue. Just trying to add onto the issue that there's more than just one person experiencing it.

**Comment by elewin** [comment]
Will it work with a framework like socket.io ? Or does this affect all websocket connections in general?

**Comment by calebboyd** [comment]
You can try using webpack to bundle. As it will properly allow the absence of native modules

https://github.com/nexe/nexe/issues/428#issuecomment-348553688

**Comment by purefan** [comment]
Just going back to this since I still can't get nexe to work with `ws`, wondering if its a network limitation in nexe or if anyone has successfully built a ws client with nexe

**Comment by calebboyd** [comment]
Did you try https://github.com/nexe/nexe/issues/428#issuecomment-348553688
