### ISSUE TITLE
Is there a way to pass Node executable flags when targeting Node < 8?

### ISSUE THREAD

**Issue by JamesMGreene** [nexe/nexe#488]
This is a
 - [ ] Bug Report
 - [ ] Feature Request
 - [x] Other

<br/>

Question: Is it possible to pass Node executable flags when targeting a version of Node < 8 for the runtime? With Node >= 8, we can use the `NODE_OPTIONS` environment variable as specified in the README to pass certain flags, e.g. `--inspect`. I would love to be able to do the same conceptually for runtimes of Node < 8, e.g. for `--debug`, but I'm unsure on if nexe can support that without changing Node.js core source code.

Could you please clarify?  Thank you!

Please also provide:

- Platform(OS/Version): Windows 10 Enterprise x64
- Host Node Version: `8.x`
- Target Node Version: `4.8.4`
- Nexe version: `2.0.0-next.12`
- Python Version: `2.7.11`

**Comment by calebboyd** [comment]
The `--enableNodeCli` option will do this in conjunction with `--build` 

Though, if enabled, it will cause node to yell about options it doesn't recognize (such as your application's options). But if your application doesn't have a CLI then it would be fine

**Comment by JamesMGreene** [comment]
Thanks for clarifying! :+1:
