### ISSUE TITLE
Nexe do not work using git-bash for window (MINGW32)

### ISSUE THREAD

**Issue by xileftenurb** [nexe/nexe#489]
This is a
 - [X] Bug Report
 - [ ] Feature Request
 - [ ] Other

I use `nexe test.js` in git bash
where test.js contain a single line : `console.log("test")`

nexe show : 
```
$ nexe test.js
RUN
(node:4476) ExperimentalWarning: The fs.promises API is experimental
```

- Platform(OS/Version): window 10
- Host Node Version: 10.0.1
- Target Node Version: ?
- Nexe version: 2.0.0-rc.28
- Python Version: 2.7.13

I used it 5 month ago without problem (was rc.17 at the time). I don't know what changed.

**Comment by calebboyd** [comment]
try targeting a version less than 10. The remote builds are backed up.

**Comment by xileftenurb** [comment]
Thank you for the help,

I tried 
```
nexe test.js --target 8.0.0
nexe test.js --target 6.11.2
nexe test.js --target windows-x64-8.0.0
next test.js -t x64-8.0.0
```

and many other, without any changes
