### ISSUE TITLE
Baking in node CLI options

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [nexe/nexe#491]
This is a
 - [ ] Bug Report
 - [X] Feature Request
 - [ ] Other

It would be great if this could be done, see also [zeit/pkg](https://github.com/zeit/pkg#options).

**Comment by calebboyd** [comment]
https://github.com/nexe/nexe#flags-string

**Comment by s-h-a-d-o-w** [comment]
Whoops... missed that, sorry... :pensive:

**Comment by s-h-a-d-o-w** [comment]
At the risk of further embarrassment... does it work though? :wink:

Because I've tried the following with nexe 2.0.0-rc.28:
```
// Also tried '--expose_gc', 'expose_gc' and 'expose-gc'
flags: ['--expose-gc'],
```

Simply doing...
```
global.gc();
```

... always leads to:
```
18:19:40.458: TypeError: global.gc is not a function
```

**Comment by calebboyd** [comment]
I'm guessing you found `--help`. The `-f` option requires that `--build` be set.

They should probably set it automatically...

**Comment by s-h-a-d-o-w** [comment]
I didn't want to write about this here but it seems you guys haven't been active on gitter for a while so...
I've constructed this little example which doesn't work:

build.js
```
const {compile} = require('nexe');

compile({
	input: './bla.js',
    
	build: true, //required to use patches
	loglevel: 'verbose',
    
	flags: ['--expose_gc'],
}).then(() => {
	console.log('SUCCESS')
});
```

bla.js
```
global.gc();

console.log("DONE");
```

package.json
```
{
  "devDependencies": {
    "nexe": "^2.0.0-rc.28"
  }
}
```

Output is:
```
global.gc();
       ^

TypeError: global.gc is not a function
    at Object.<anonymous> (D:\development\node playground\dummy\bla.exe:14:8)
    at c (D:\development\node playground\dummy\bla.exe:25:3565)
    at Function.r.import (D:\development\node playground\dummy\bla.exe:25:4171)
    at p (D:\development\node playground\dummy\bla.exe:22:15)
    at Object.<anonymous> (D:\development\node playground\dummy\bla.exe:25:1)
    at Module._compile (module.js:652:30)
    at _third_party_main.js:45:20
    at NativeModule.compile (bootstrap_node.js:600:7)
    at Function.NativeModule.require (bootstrap_node.js:545:18)
    at bootstrap_node.js:120:22
```

**Comment by s-h-a-d-o-w** [comment]
8.11.2

**Comment by calebboyd** [comment]
Hmm. I can't replicate. Try running it once with `--clean`
![image](https://user-images.githubusercontent.com/5818726/40877408-fdc8017a-6645-11e8-8331-c536fc2e528c.png)

**Comment by s-h-a-d-o-w** [comment]
Appears to work at least with 2.0.0-rc.29... :+1:
