### ISSUE TITLE
ARMv6 and ARMv7 Builds Exit 0 but Do Not Run

### ISSUE THREAD

**Issue by xcjs** [nexe/nexe#492]
This is a
 - [X ] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
If this is a bug report, What are the steps to reproduce?

I'm using Nexe to compile a binary for Raspberry Pi devices. I've attempted to compile a CLI utility written in Node.js on a Raspberry Pi, and  while it compiles, it does not run. I get no output and a stdout result of 0.

The command to invoke the build is as follows: 
`nexe --build index.js -o bin/app`

No additional resources are bundled in. There are a few native modules. Everything appears to compile just fine with no error codes or messages.

<br/><br/>
Please also provide:

- Platform(OS/Version): Raspbian/Debian Stretch 9
- Host Node Version: v8.11.2
- Target Node Version: v8.11.2
- Nexe version: 2.0.0rc19
- Python Version: 2.7.13

**Comment by calebboyd** [comment]
Nexe with `--build` is just a wrapper around nodes build scripts. You may want to investigate what is needed for `--configure` and `--make` options on your platform, then pass these to nexe.

**Comment by xcjs** [comment]
Thanks, I'll take a look!
