### ISSUE TITLE
Loading modules after building fails.

### ISSUE THREAD

**Issue by MatthewSH** [nexe/nexe#497]
This is a
 - [x] Bug Report
------

In a [chatbot framework](https://github.com/MarkedBots/ChatBot-CE) I'm using Nexe to bundle it up for end users and other products. We use a [bundle script](https://github.com/MarkedBots/ChatBot-CE/blob/master/nexe-bundle.js) (which actually was gotten from another issue to solve my WebSocket issue). As you can see [here](https://github.com/MarkedBots/ChatBot-CE/blob/master/src/lib/Parser.ts#L83) we're dynamically loading addons (example [here](https://github.com/BultApp/Addon-Ping/) and [here](https://github.com/MarkedBots/CoinBot)) from an addons folder. When running any built script (using TypeScript, after it's compiled) it all runs fine. However, after I build it with Nexe...it fails. Anyone else experience this? It fails with the error:
```
Cannot find module '/home/matthew/ChatBotCE/addons/ping'
```

------

- Platform(OS/Version): Linux/Ubuntu (Pop! OS)
- Host Node Version: v10.4.0
- Target Node Version: v9.5.0
- Nexe version: 2.0.0-rc.29 (haven't tried on candidate 30 yet)
- Python Version: 2.7.15rc1

**Comment by calebboyd** [comment]
Could it be that `addons/ping ` isn't included in the bundle you're creating?

**Comment by calebboyd** [comment]
Looks like this was resolved in the linked repo

**Comment by MatthewSH** [comment]
@calebboyd it's not supposed to be included as addons can be installed or removed without rebundling. The program loads them all in at runtime. I resolved it by getting rid of Nexe and moving to Pkg because Pkg allows that.
