### ISSUE TITLE
Not work in win10

### ISSUE THREAD

**Issue by keyiis** [nexe/nexe#498]
This is a
 - [ ] Bug Report
 - [ ] Feature Request
 - [ *] Other

<br/>

Please also provide:

- Platform(OS/Version):win10 x64
- Host Node Version:8.9.3
- Target Node Version:win-x64-9.4.0
- Nexe version:2.0.0-rc.30
- Python Version:

I used nexe to package express app
`nexe .\bin\www`
```
RUN
√ Compiling result
√ Entry: 'main.js' written to: main.exe
√ Finished in 1.8s
```
when i run main.exe
```
.\main.exe
程序“main.exe”无法运行: 指定的可执行文件不是此操作系统平台的有效应用程序。所在位置 行:1 字符: 1
+ .\main.exe
+ ~~~~~~~~~~。
所在位置 行:1 字符: 1
+ .\main.exe
+ ~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed 

```

**Comment by ReturnToTheYouth** [comment]
请问你是怎么生成这个exe文件的啊？

**Comment by keyiis** [comment]
@ReturnToTheYouth `nexe .\bin\www`

**Comment by jinweizhiyuan** [comment]
@keyiis 这个问题解决了吗

**Comment by ReturnToTheYouth** [comment]
没有解决:( 使用的electron生成exe


发自我的iPhone

------------------ Original ------------------
