### ISSUE TITLE
Latest LTS not supported

### ISSUE THREAD

**Issue by DayBr3ak** [nexe/nexe#503]
This is a
 - [x ] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>

- Platform(OS/Version): win10 x64
- Host Node Version: 8.11.3
- Target Node Version: 8.11.3
- Nexe version: 2.0.0-rc.31
- Python Version: 2.7

    (node:18952) UnhandledPromiseRejectionWarning: Error: windows-x64-8.11.3 not available, create it 
    using the --build flag

using the build flag just compile for ever, pretty sure it just won't compile

**Comment by calebboyd** [comment]
The build system was broken but its fixed now and this should be up within a few days.

And yeah. The build takes _forever_ 😂
