### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by filips123** [nexe/nexe#504]
Add support for building with Python 3.
Python 2 is very old and it will not be supported in 2020 anymore (https://pythonclock.org/).

**Comment by calebboyd** [comment]
Python 2 is required to [build node](https://github.com/nodejs/node/blob/master/BUILDING.md). The requirement for it will not be removed until it is removed from node itself.

**Comment by calebboyd** [comment]
https://bugs.chromium.org/p/gyp/issues/detail?id=36#c44

**Comment by Artoria2e5** [comment]
Node supports Python 3 builds since a few days ago (nodejs/node#30091). The GYP blocker is gone too (nodejs/node-gyp#1903). Please consider reopening as new binaries become available.

Python 2 is dead, long live Python 3!

**Comment by filips123** [comment]
@calebboyd Can you please reopen issue and start working on Python 3 support?

**Comment by kmirojo** [comment]
Hi,
@calebboyd  Is support for Python 3 still unavailable? I updated to Python 3.5 and my building process is crashing, I'm pretty sure it is because of that.

**Comment by kmirojo** [comment]
Hello there, 
does anyone know if this issue has been fixed? 
Do we still required `python 2` to build `nexe binary`?

**Comment by Artoria2e5** [comment]
I am pretty... sure we need to open a new issue now.
