### ISSUE TITLE
Cannot execute binary if the script uses Terminal-Kit library

### ISSUE THREAD

**Issue by domingosl** [nexe/nexe#509]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>

Just require terminal-kit in your script ([https://github.com/cronvel/terminal-kit](https://github.com/cronvel/terminal-kit)), compile and run.

```
Error: Cannot find module './termconfig/xterm.generic.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)

```

<br/><br/>

- Platform(OS/Version): MacOS
- Host Node Version: 9.5.0
- Target Node Version: 9.5.0
- Nexe version: 2.0.0-rc.31
- Python Version: 2.7.10

**Comment by wanghc78** [comment]
The problem happens in pkg package, too. The reason is Terminal-Kit has `require(variable)` statement.

In ode_modules\terminal-kit\lib\Terminal.js:163:18
```js
			try {
				// No generic config exists, try a specific config
				term.termconfigFile = term.generic + '.js' ;
				termconfig = require( './termconfig/' + term.termconfigFile ) ;
			}
			catch ( error_ ) {
				// Nothing found, fallback to the most common terminal generic
				term.termconfigFile = 'xterm.generic.js' ;
				termconfig = require( './termconfig/' + term.termconfigFile ) ;
			}
```
Neither nexe nor pkg can do the precise dependence analysis for such a non-literal require. You need to add those resources (js files under _termconfig_) explicitly.

**Comment by calebboyd** [comment]
`npm i nexe@next` (nexe 3.0) will do a best effort to glob these variable dependencies.

**Comment by innersuit** [comment]
The below package.json configuration worked for me, once I remembered to call pkg with package.json instead of filename:

{
  ....
  "main": "index.js",
  "bin": "bin.js",
  "pkg": {
    "scripts": "node_modules/terminal-kit/lib/**/*.js",
    "assets": "node_modules/terminal-kit/lib/**/*.json"
  },
  "scripts": {
    "build-cli": "./node_modules/.bin/pkg package.json --out-path ./bin"
  }
  ... 
}

**Comment by kyung-lee-official** [comment]
> 

How do I do this exactly?
