### ISSUE TITLE
windows-x64-8.11.3 not available, create it using the --build flag

### ISSUE THREAD

**Issue by ReturnToTheYouth** [nexe/nexe#511]
This is a
 - [ ●] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
windows-x64-8.11.3 not available, create it using the --build flag
```

<br/><br/>
Please also provide:

- Platform(OS/Version):windows
- Host Node Version:v8.11.3
- Target Node Version:
- Nexe version:2.0.0-rc.31
- Python Version:2.7.12

**Comment by calebboyd** [comment]
The build cluster broke down but is up again. This build should be arriving soon
