### ISSUE TITLE
ES6 Modules Support

### ISSUE THREAD

**Issue by rahbari** [nexe/nexe#512]
Does nexe support native es6 modules activated using --experimental-modules, or it must be transpiled to CommonsJS modules using babel?

**Comment by jaredallard** [comment]
Hi, does this answer your question? https://github.com/nexe/nexe#flags-string

**Comment by rahbari** [comment]
I added --experimental-modules, the compiled version (10.7.0) doesn't recognize this flag. In the node source files node.cc is replaced with a custom version. So short answer nexe doesn't support ES6 modules yet.

**Comment by calebboyd** [comment]
This should be supported after #455 is done. (not sure on ETA)

**Comment by calebboyd** [comment]
The flag isn't supported. But isn't needed with the current version, since the code is bundled.
