### ISSUE TITLE
Unable to compile node app with nexe 2.0.0-rc-31

### ISSUE THREAD

**Issue by SgtBreadStick** [nexe/nexe#515]
**BUG REPORT** 

**What happened:**
Tried compiling with compiling script but shows errors like these
"python.exe configure exited with code: 1"
"windows-x64-10.7.0 not available, create it using --build flag"
I also used --clean & --build but still shows both errors.

**What you expected to happen:**
Successful compiling of node app.

**Anything else we need to know?:**
The previous version of nexe worked normally with npm 6.1.0, now with latest nexe & npm it refuses to work.
Images: https://i.imgur.com/AlVGRRm.png https://i.imgur.com/7Jf4mfJ.png

**Environment**

- Platform(OS/Version): Windows 10 1803 (17713.1002)
- Host Node Version: 10.7.0
- Nexe version: 2.0.0-rc.31
- Python Version: 2.7.15

**Comment by calebboyd** [comment]
Re: #527 The version from your original issue is 10.7.0 which is available now.

8.6.0 from the image in #527 hasn't been built yet, but should be available as soon as the build system gets to it.
