### ISSUE TITLE
Error: python configure exited with code: 1

### ISSUE THREAD

**Issue by zwhitchcox** [nexe/nexe#516]
**Is this a BUG or a FEATURE REQUEST?:** 
BUG
**What happened:**
I'm trying to compile a simple hello world program, but it won't run
**What you expected to happen:**
it to run

**How to reproduce it (as minimally and precisely as possible):**
in a file `console.log('hello world')`, `nexe --build hello.js`
**Anything else we need to know?:**
I don't know
**Environment**
?
- Platform(OS/Version):
Windows
- Host Node Version:
10.7.1
- Target Node Version:
default
- Nexe version:
2.0.0-rc.31
- Python Version:
3.7.0

**Comment by calebboyd** [comment]
Use `--verbose` will lead you to https://github.com/nodejs/node/blob/v10.7.0/BUILDING.md

You probably need NASM.

**Comment by calebboyd** [comment]
Please refer to the above doc It looks like you'll also need Python 2
