### ISSUE TITLE
fs.existsSync( fileName ) seems to always fail for bundled-in files

### ISSUE THREAD

**Issue by chrstew** [nexe/nexe#517]
Using nexe rc31

If I call `fs.existsSync( fileName )` for a file I have bundled into a nexe executable, the return will always be false.

If I remove my `fs.existsSync()` check, my code is able to read my file via `fs.readFileSync( fileName )` without issue.

Am I doing something wrong or is this a bug with reading bundled files within nexe?

**Comment by calebboyd** [comment]
Thanks, This is fixed in 32.
