### ISSUE TITLE
off-by-1 error in bundled files

### ISSUE THREAD

**Issue by chrstew** [nexe/nexe#518]
Thanks for being so quick on solving my last bug.

I'm serving a large amount of bundled files in a nexe executable via `express`. Files that I serve from endpoints with a simple `fs.readFileSync( fileName )` and those work perfectly.

However I also use the express.static function like so:
```
// files referrenced from within the html are served up below:
var sPublicDir 	=  __dirname + 'public';
app.use( new RegExp( '/corp\\d*/table.html' ), express.static( sPublicDir ) );	// required
app.use( new RegExp( '/corp\\d*' ), express.static( sPublicDir ) );
```

and the files that are served via these endpoints seem to have an off-by-one error with the file reads.

Whenever I recieve a js file from my express app from those endpoints the last character (usually on a new line) is either a `v`, `'` or `/`.

I believe this is because the start of most of my files is either `var`, `'use strict';` or `//comment`

Again I am not sure if I am doing something in an unintended way or if this is an issue with nexe. I am curious if the error has to do with the huge amount of files I am bundling (about 1800 files in total)

**Comment by calebboyd** [comment]
Can you provide a minimal reproduction?

**Comment by chrstew** [comment]
I will see if I am able to reproduce in a simple way

**Comment by calebboyd** [comment]
closed via https://github.com/nexe/nexe/commit/bf65477ca3b5dbff78d7dff8c0260cba1960b135

available via `nexe@latest`
