### ISSUE TITLE
Dependencies installation leading to Error: Cannot find module

### ISSUE THREAD

**Issue by iesrbt** [nexe/nexe#519]
Hi there,
I stumble about this problem:

==code=====
const mqtt = require('mqtt');
const autobahn = require('autobahn');
console.log('!OK');

==package.json=====
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "test.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "autobahn": "^18.3.2",
    "mqtt": "^2.18.3"
  }
}

==install======
> npm i
Then inside node_modules/mqtt remove the first line: #!/usr/bin/env node
for files: mqtt.js ; bin/pub.js ; bin/sub.js
else at compile time: Acorn error: Unexpected character '#' (1:0)
But I guess this is expected.

Then:
==compile=====
> nexe -i test.js
i nexe 2.0.0-rc.34
√ Compiling result
√ Entry: 'test.js' written to: test.exe
√ Finished in 1.503s

==run=====
> node test.js
!OK
> test
module.js:540
    throw err;
    ^
Error: Cannot find module 'readable-stream/duplex'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at f (D:\DEVZ\NODE\test.exe:17175:1092)
    at u (D:\DEVZ\NODE\test.exe:17175:1430)
    at c (D:\DEVZ\NODE\test.exe:17175:2750)
    at b.require (D:\DEVZ\NODE\test.exe:17175:3346)
    at Object.<anonymous> (D:\DEVZ\NODE\test.exe:94:20)
    at c (D:\DEVZ\NODE\test.exe:17175:3584)

==more=====
A) if you comment the require('mqtt') line and rebuild, the error disappears.
B) when used alone (only there dependencies installed) both modules compile and works ok

A mystery to me!
Thanks for your help & work :-)

**Comment by calebboyd** [comment]
Try `nexe@next` you may have native modules that will need to be shipped alongside the binary nexe produces.

Also, the build pipeline is currently rebuilding so only a few versions are available https://github.com/nexe/nexe/releases/latest

**Comment by rraallvv** [comment]
Thanks. I'll give it a try.

**Comment by BVSPHari** [comment]
The issue is still persist for me. #534 .
