### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by ItalyPaleAle** [nexe/nexe#521]
Nexe sounds like the exact thing that I need to solve a problem I have.... if only it supported FreeBSD!  I searched the issues but couldn't find anything mentioning FreeBSD.

What would it take to add the support?

**Comment by calebboyd** [comment]
Nexe builds are currently produced using oss friendly tools TravisCI (Linux), CircleCI (Mac) and AppVeyor (Windows). 

I don't know of a FreeBSD tool that is similar to these. If you do please suggest it.

You can always produce your own though using `--build` 

Note: When `--build` is used nexe just invokes the regular node build process. So you can pass the appropriate values to `--make` and `--configure` You only need to cache the artifact for subsequent builds to be instant.
