### ISSUE TITLE
"Invalid Nexe binary" error after using "strip"

### ISSUE THREAD

**Issue by borisovg** [nexe/nexe#523]
**Is this a BUG or a FEATURE REQUEST?:** 
BUG

**What happened:**
Running binary through strip breaks it.

**How to reproduce it (as minimally and precisely as possible):**
Build binary:
```
$ nexe index.js --build
ℹ nexe 2.0.0-rc.34
✔ Source already downloaded
✔ Compiling result
✔ Entry: 'index.js' written to: test
✔ Finished in 0.42s
```

It works:
```
$ ./test 
Hello world
```

Now it doesn't work:
```
$ strip test
$ ./test 

_third_party_main.js:8
    throw 'Invalid Nexe binary';
    ^
Invalid Nexe binary
```

**Environment**

- Platform(OS/Version): Debian Sid
- Host Node Version: v8.12.0
- Target Node Version: v8.12.0
- Nexe version: 2.0.0-rc.34
- Python Version: 2.7.15+ and 3.6.6+

**Comment by borisovg** [comment]
same problem when trying to use "upx"

**Comment by borisovg** [comment]
Filed as "BUG" because #283 mentions using "strip" but maybe it was never supposed to work - no idea.

**Comment by calebboyd** [comment]
You can apply upx or strip to the main artifact in your case with this version its located at `~/.nexe/8.12.0/out/Release/node`.

**Comment by borisovg** [comment]
That works - thanks!

**Comment by cris691** [comment]
> That works - thanks!

This is awesome. That's a great workaround 😃
