### ISSUE TITLE
Running a packaged executable creates directories in the current directory (Linux)

### ISSUE THREAD

**Issue by happybeing** [nexe/nexe#524]
I've packaged my own test cli application and can create a single packaged executable for different operating systems. So far I've only tested that generated for Linux x64, node v8.11.3, and when I run the packaged executable, it works as expected, but in the process three unexpected directories are created:

```
08a575c6:
total 48
-rw-rw-r-- 1 me me 47080 Sep 18 16:28 binding.node

3ad8934c:
total 80
-rw-rw-r-- 1 me me 80624 Sep 18 16:28 ffi_bindings.node

af571553:
total 40
-rw-rw-r-- 1 me me 37456 Sep 18 16:28 weakref.node
```
These correspond to some of the dependencies of my app. 

- Assuming this is expected behaviour, is there a way to direct where they are created?
- Is there a way to avoid this / is that worth submitting as a feature request?

I don't like that the packaged executable creates unexpected files like this.

**Comment by eliot-akira** [comment]
I see the same behavior on macOS with latest node. For me it creates one folder with `binding.node`, every time the packaged executable is run.
