### ISSUE TITLE
No native build was found for runtime=node

### ISSUE THREAD

**Issue by theWebalyst** [nexe/nexe#525]
On running my packaged executable I get the above error which I think indicates I need to explicitly include the files under `node_modules/fuse-bindings/prebuilds`, but I'm having difficulty getting that to happen. So I'm assuming this is my bad rather than a bug.

The reason I think this is because the error is thrown at the following line, and I needed to include those files explicitly to solve a similar problem when using `pkg`:
```
const Fuse = require('fuse-bindings')
```
Firstly if I use `nexe --verbose -r <some-glob-path>` the console output shows it only includes one file, even though there are two files that I'd expect to be packaged with `nexe --verbose -r node_modules/@maidsafe/safe-node-app/src/native/prod/*.*` and I expect a tree of files to be packaged with `nexe --verbose -r node_modules/fuse-bindings/prebuilds/**/*.*`. For example:

```
$ nexe --verbose -r node_modules/fuse-bindings/prebuilds/**/*.*
ℹ nexe 2.0.0-rc.34
✔ Bundling Resources...
✔ Including file: node_modules/fuse-bindings/prebuilds/linux-x64/electron-47.node
✔ Included 1 file(s). 0.060 MB
✔ Compiling result
✔ Writing result to file
✔ Entry: 'bin.js' written to: bin
✔ Finished in 1.091s
```

Secondly, I tried using the `nexe` options object in my `package.json` file, but that doesn't get picked up at all. For example, with this in `package.json`:

```
{
  "name": "safenetwork-fuse",
  "version": "0.1.0",
  "description": "Mount SAFE Network as a FUSE volume",
  "main": "bin.js",
  "scripts": {
    "start": "node bin",
    "build": "mkdirp ./dist && nexe bin.js -o ./dist/mount-safe"
  },
  "nexe": {
    "input": "rubbish",
    "output": "dist/junk",
    "resources": [
      "node_modules/@maidsafe/safe-node-app/src/native/prod/*.*",
      "node_modules/@maidsafe/safe-node-app/src/native/mock/*.*",
      "node_modules/fuse-bindings/prebuilds/**/*.*"
    ]
  },
...
```
When I type `nexe --verbose` I get the following output:

```
ℹ nexe 2.0.0-rc.34
✔ Compiling result
✔ Writing result to file
✔ Entry: 'bin.js' written to: bin
✔ Finished in 1.078s
```
I tried the options  initially with only `"resources":` but when that had no effect I added the garbage entries for 'input' and 'output' to see if I could make it error, but it seems not to pick any of the `package.json` options up at all.

**Environment**

- Platform(OS/Version): Ubuntu 18
Linux version 4.15.0-33-generic (buildd@lcy01-amd64-024) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018

- Host Node Version: v8.11.3
- Target Node Version: v8.11.3
- Nexe version: 2.0.0-rc.34
- Python Version: Python 2.7.15rc1

**Comment by theWebalyst** [comment]
Any chance [v3.0 / #455](https://github.com/nexe/nexe/pull/455) would help here (I see the note about bundling missing binaries as resources):

**Comment by calebboyd** [comment]
Anything that runs that isn't javascript that has to be run by the operating system (not node) is effectively a native module. Eg. a dll (`.node`, `.dll`, `.so`). Or a `.sh`, `.exe` etc.

These files can be bundled with nexe (3) but will have to be written out to the appropriate paths before the are used by your application.
