### ISSUE TITLE
nexe appears to only package one file for a 'glob' path

### ISSUE THREAD

**Issue by theWebalyst** [nexe/nexe#526]
**Is this a BUG or a FEATURE REQUEST?:** 
BUG report

**What happened:**
Using `-r node_modules/@maidsafe/safe-node-app/src/native/prod/*.*` should package two files, but `nexe` reports only one being added:
```
ℹ nexe 2.0.0-rc.34
✔ Bundling Resources...
✔ Including file: node_modules/@maidsafe/safe-node-app/src/native/prod/libsafe_app.so
✔ Included 1 file(s). 20.811 MB
✔ Compiling result
✔ Writing result to file
✔ Entry: 'safecmd.js' written to: dist/safecmd-nexe
✔ Finished in 1.227s
```

**What you expected to happen:**
`nexe` should report adding `libsafe_app.so` as well.

**How to reproduce it (as minimally and precisely as possible):**

```
git clone https://github.com/theWebalyst/safe-cli-boilerplate
cd safe-cli-boilerplate
git checkout dev-nexe-packager
npm install
ls node_modules/@maidsafe/safe-node-app/src/native/prod/*.*
npm run test
```

**Anything else we need to know?:**
Nope.

**Environment**

- Platform(OS/Version): Ubuntu 18
- Host Node Version: v8.11.3
- Target Node Version: v8.11.3
- Nexe version: 2.0.0-next.14
- Python Version: Python 2.7.15rc1

**Comment by jontore** [comment]
I had the same issue, until I found out that the glob pattern has to be a string.  ```-r node_modules/@maidsafe/safe-node-app/src/native/prod/*.*```

otherwise it fill pick the first one and pass ```node_modules/@maidsafe/safe-node-app/src/native/prod/libsafe_app.so``` as the resource file

**Comment by theWebalyst** [comment]
Ah, well figured out. Just a documentation and --help usage issue then.

**Comment by calebboyd** [comment]
Great!, Closing for now
