### ISSUE TITLE
No more prebuilt binary?

### ISSUE THREAD

**Issue by Bacto** [nexe/nexe#527]
Hi,

It seems that the prebuilt binaries are not available anymore:
`Error: alpine-x64-8.9.4 not available, create it using the --build flag`

I can't find any version of the in releases.
Is it possible to push them again?

**Comment by SgtBreadStick** [comment]
I'm having this exact same issue but with windows, i submitted an issue 3 months ago with no reply still. this issue is occuring once again.

**Comment by SgtBreadStick** [comment]
It works when running nexe --build but when doing nexe index.js or npm run compile (compile script), it errors out with the "not available" thing.

**Comment by SgtBreadStick** [comment]
An example
![image](https://user-images.githubusercontent.com/21985403/46301864-6c2a8d00-c59f-11e8-96a4-fe3ec6387aba.png)

**Comment by calebboyd** [comment]
@Bacto I triggered a build specifically with alpine 8.9.4 -- We'll see if it finishes.

https://travis-ci.org/nexe/nexe/builds/436176992

**Comment by calebboyd** [comment]
Its up!

**Comment by Bacto** [comment]
It works! Thanks @calebboyd :)
