### ISSUE TITLE
nexe don't package modules rosurces

### ISSUE THREAD

**Issue by rahbari** [nexe/nexe#530]
After running app I get 4 unhandled promise rejection:

```
 { [Error: ENOENT: no such file or directory, open 'lib/mappings.wasm']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'lib/mappings.wasm' }
```
Unpackaged app has no problem.

-------------- EDIT ----------------
I found out the problem, I'm using source-map package which has lib/mappings.wasm in it but nexe doesn't include it. 
Is this correct behaviour?
Is there any work around?

**Comment by calebboyd** [comment]
Can you provide a minimal reproduction?

**Comment by calebboyd** [comment]
@rahbari, the increased size is due to nexe loading the additional files it previously was not loading.
