### ISSUE TITLE
Problem with app-module-path

### ISSUE THREAD

**Issue by elliotpj** [nexe/nexe#531]
**Is this a BUG or a FEATURE REQUEST?:** Request

**What happened:** I have a small application with nodejs at server side. i want an executable file for my nodejs code.  Problem is with app-module-path if i don't use app-module-path it works fine, but if i don't use this module i have to change entire code whereever i am requiring file. so to avoid this problem of changing code. i want nexe to work fine with app-module-path, m sure there must be some solution to this problem. 

Thanks

**What you expected to happen:** I want an executable file to work fine with app-module-path. Changing Path in every files is time consuming.

**How to reproduce it (as minimally and precisely as possible):** [https://github.com/elliotpj/nexe-example.git](https://github.com/elliotpj/nexe-example.git)

**Anything else we need to know?:**
Entry Point index.js

```
const express = require('express')
const path = require('path')
const app = express();
require('app-module-path').addPath(__dirname);
app.use('/', express.static(path.join(__dirname, 'public')))
var test = require('test/utility.js');
console.log(test);
test.test();

app.listen(8888)
console.log('Listen on Port :8888');
```

Nexe config is as shown below :

```
var nexe = require('nexe');
nexe.compile({
    input: './index.js', // where the input file is
    output: './nexe-example.exe', // where to output the compiled binary
    targets:['windows-x64-8.9.0'],
    nodeVersion: '8.9.0', // node version
    nodeTempDir: 'src', // where to store node source.
    nodeConfigureArgs: ['opt', 'val'], // for all your configure arg needs.
    nodeMakeArgs: ["-j", "4"], // when you want to control the make process.
    resource: [ './public/**/*' ], // array of files to embed.
    verbose:true,
    build:false,
    flags: false, // use this for applications that need command line flags.
    jsFlags: "--use_strict", // v8 flags
    framework: "node" // node, nodejs, or iojs
}, function(err) {
    if (err) {
        return console.log(err);
    } else {
        return console.log('Nexe Compiled Successfully')
    }
});

```

To Create Exe :

`node nexe.js`

Error occur while executing exe :

> E:\>nexe-example.exe
> module.js:538
>     throw err;
>     ^
> 

> Error: Cannot find module 'test/utility.js'
>     at Function.Module._resolveFilename (module.js:536:15)
>     at Function.Module._load (module.js:466:25)
>     at Module.require (module.js:579:17)
>     at require (internal/module.js:11:18)
>     at f (E:\nexe-example.exe:29515:1092)
>     at u (E:\nexe-example.exe:29515:1430)
>     at c (E:\nexe-example.exe:29515:2750)
>     at b.require (E:\nexe-example.exe:29515:3346)
>     at Object.<anonymous> (E:\nexe-example.exe:249:12)
>     at c (E:\nexe-example.exe:29515:3584)
> 

**Environment**

- Platform(OS/Version): **Windows 10 Pro**
- Host Node Version: **8.9.0**
- Target Node Version: **8.9.0**
- Nexe version: **2.0.0-rc.34**
- Python Version: **2.7.0**

**Comment by calebboyd** [comment]
Try `nexe@next` and let me know if it works for you!

**Comment by elliotpj** [comment]
I already did that but still getting same error.

And i have changed options now.

**Comment by calebboyd** [comment]
'test/utility.js' doesn't exist.. unless you're referring to [this file](https://github.com/Gozala/test-commonjs/blob/master/utils.js) in the npm package called `test`


I think you need `'./test/utility'`

**Comment by elliotpj** [comment]
I cannot change all the files. 

I have created bundle with `webpack `for my server side code and it resolve my problem.

Thanks
