### ISSUE TITLE
Unable to bundle scoped packages

### ISSUE THREAD

**Issue by chrstew** [nexe/nexe#532]
It appears scoped packages are unable to be bundled into a nexe binary.

Take for example the popular package `@google/maps`

Upon requiring it within a project and then compiling with nexe, at run time we get the error:

`Error: Cannot find module '@google/maps'`

Is there a way to properly bundle scoped packages into a binary?

**Comment by calebboyd** [comment]
Can you try nexe@next and let me know if it works for you?

**Comment by chrstew** [comment]
Trying to compile several of our applications under `nexe@next` gives this at runtime:

```
    var patches = process.nexe.patches || {};
                               ^

TypeError: Cannot read property 'patches' of undefined
```

However I doubt this is related to the scoped package issue

**Comment by calebboyd** [comment]
Run the builds with the `clean` option once. You'll need the new binaries.

**Comment by chrstew** [comment]
It looks like after doing a clean I was able to run my binary with a scoped package included successfully.

Thank you for your help, much appreciated!

**Comment by Nautigsam** [comment]
I reopen it because even with clean binaries I get an error about a scope package not being found.
I use version `3.0.0-beta.15`.
