### ISSUE TITLE
nexe@next doesn't load modules from package

### ISSUE THREAD

**Issue by rahbari** [nexe/nexe#534]
The packaged file is working on development server which has node installed.
But when it is uploaded to a server without node.js I get this error:

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/node_modules/require_optional/index.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)

this package exists in project node_modules prior to packaging.
I didn't have this problem with v2.

---- UPDATE ----
I installed node on production server but the problem remained, then I found out that in development server node_modules directory is beside packaged file and the it's reading modules from that directory.

**So for now I created the node_modules folder beside the packaged version in production server and installed required modules and now it's working.**

**Actually packaged version is loading some modules from node_modules directory beside it instead of package contents and some from package. for example it loads semver from node_modules.**

I tried nexe command and node nexe.js, none of them works.

**Comment by calebboyd** [comment]
Can you provide a minimal reproduction?

For example, if I run the following commands:
```bash
mkdir example
cd example
npm init -y && npm i semver -S
echo "console.log(require('semver'))" >> index.js
npx nexe@next
rm -rf node_modules
./example

# contents of semver package are logged to stdout
```

**Comment by rahbari** [comment]
I run exactly this code.
For me it works as long as node_modules exists, after removing I get `Error: Cannot find module 'semver'`
I'm using latest node on centos 7.

![nexe](https://user-images.githubusercontent.com/163890/47030604-dd129d00-d17a-11e8-9008-76553a5896a2.png)

**Comment by calebboyd** [comment]
Closed via e6a416cc4f0831b28a1360853e41a07ccc51f71c

**Comment by ZQun** [comment]
@calebboyd Can nexe package the package developed by node.js into an executable file? Do not rely on other files to execute! For example, I developed the node.js program using the koa.js framework, can I pack it? If no entry document is provided.

**Comment by calebboyd** [comment]
@ZQun Yes, thats the premise of this library If you have a specific issue open a new issue!
