### ISSUE TITLE
Acorn error: Identifier 'parse' has already been declared (5110:9)

### ISSUE THREAD

**Issue by iraviteja** [nexe/nexe#536]
ℹ nexe 2.0.0-rc.34
Acorn error: Identifier 'parse' has already been declared (5110:9)
File: /media/teja/Teja/Projects/Abhigamya/report-generation-abhigamya/node_modules/cssstyle/lib/properties.js

5108  var width_export_definition;
5109  
5110  function parse(v) {
5111    if (String(v).toLowerCase() === 'auto') {
5112      return 'auto';
5113    }
5114  

Acorn error: Identifier 'parse' has already been declared (5110:9)
File: /media/teja/Teja/Projects/Abhigamya/report-generation-abhigamya/node_modules/cssstyle/lib/properties.js

5108  var width_export_definition;
5109  
5110  function parse(v) {
5111    if (String(v).toLowerCase() === 'auto') {
5112      return 'auto';
5113    }
5114  

⠋ nexe 2.0.0-rc.34undefined
✔ Compiling result
✔ Entry: 'server.js' written to: server
✔ Finished in 8.192s

**Comment by calebboyd** [comment]
Try `npm i nexe@next`
