### ISSUE TITLE
Nexe mixes `vcBuild` and `make` together

### ISSUE THREAD

**Issue by anmonteiro** [nexe/nexe#537]
**Is this a BUG or a FEATURE REQUEST?:** 
Bug

**What happened:**
This line: 
https://github.com/nexe/nexe/blob/e6a416cc4f0831b28a1360853e41a07ccc51f71c/src/options.ts#L247
is mixing `vcBuild` arguments with `make` arguments.

**What you expected to happen:**
Shouldn't be mixed. Use `make` arguments on non-Windows, and `vcBuild` arguments on Windows.

Maybe my understanding is wrong here, but I thought that Nexe would handle the cross-platform thing for me and I wouldn't need to dispatch on the OS.

**Comment by calebboyd** [comment]
closed via https://github.com/nexe/nexe/commit/db766e283229d76fa19d98d5abad3c004ba85e8d

available via `npm i nexe@next`

**Comment by anmonteiro** [comment]
Thanks!
