### ISSUE TITLE
Invalidate Cache when snapshot file changes

### ISSUE THREAD

**Issue by anmonteiro** [nexe/nexe#540]
I'm not sure how the cache is handled, but it seems like currently the binary is not rebuilt from source if the snapshot file changes.

Can you advise?

**Comment by calebboyd** [comment]
There really isn't a cache for changes requiring a re-`--build`

I'm open to suggestions or PRs

**Comment by anmonteiro** [comment]
I'm probably misunderstanding what the `--build` flag does then. When does it choose to build the binary vs using the one it has?

**Comment by calebboyd** [comment]
It is very naive, It just is just checking for the presence of a build artifact

https://github.com/nexe/nexe/blob/e3f1d6fc7460dd1bd6f7f7038c369ccf6e550798/src/compiler.ts#L271-L285

This is so, once you have the build as you like you can iterate quickly for regular JS changes. Or cache it in CI. But it isn't conducive to build changes...
