### ISSUE TITLE
Security in my code - INFORMATION

### ISSUE THREAD

**Issue by thiagoanselmo** [nexe/nexe#545]
Can I get a commercial version of my APP without source code? so that they can not reverse engineer and pick up source codes?

**Comment by calebboyd** [comment]
Code obfuscation is not currently a goal of this project

**Comment by tbhaxor** [comment]
@calebboyd  you guys can use some approaches to obfuscate the code

Steps you can use
1. Use webpack to bundle all the files in one `*.bundle.js` (here i am assuming code wont break)
2. Then use http://www.jsfuck.com/ to obfuscate the code

PS: after successful PR with reference to this issue please delete this issue
