### ISSUE TITLE
Dynamic "require" statements

### ISSUE THREAD

**Issue by lghamie** [nexe/nexe#546]
Hi.

I'm currently using nexe to create a binary that has a dependency to simple-git. This library uses "var r = require(someRelativePath)" inside the function calls. This results in r having an undefined value. I assume this happens because nexe doesn't detect this kind of dependencies. 

I'm using the following command for building "nexe  --target linux-x64-8.12.0  -o output"

How can I overcome this?

Thanks!

**Comment by calebboyd** [comment]
try `npm i nexe@next`

**Comment by calebboyd** [comment]
Anything you require dynamically you'll want to include in the the binary

you can do this with the `-r` flag

**Comment by kylecarbs** [comment]
Using nexe `^2.0.0-rc.34` I'm experiencing this issue. I've attempted to use `nexe@next` and it doesn't seem like resources are included (or at least accessible) via fs calls anymore.

Is there a specific commit that fixed the dynamic requires? The version I'm on right now seems to work perfectly for everything apart from that.

**Comment by calebboyd** [comment]
@kylecarbs What errror do you get? Can you open a new issue with a reproduction?

**Comment by DSigmund** [comment]
Hi,  

Same issue here:

The Files are included in the binary and i can use fs to find them.
But they wont require...

I am using 2.0.0-rc.34

Unforntunatelly i cant upgrade:

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/nexe/globby.git
npm ERR!
npm ERR! fatal: unable to connect to github.com

... Any Ideas?

**Comment by kaysersoze** [comment]
I'm running into this issue as well with `3.0.0-beta.15`, with a library (`axios`) that is required within another dynamically required module. 

The dynamically required modules are for organization-specific features that can be enabled at runtime via a configuration file.

I have included the files as resources within my build script, but that doesn't seem to help. In the meantime, I can work around it by including the child dependencies statically.

If I can do anything to help with the issue, I'd be happy to contribute a PR back if I could get a clue to where this might be occurring, as I'm not familiar with the nexe codebase yet.

**Comment by calebboyd** [comment]
@kaysersoze 

I think your explanation clearly outlines some of the current inadequacies in the supporting library (or usage of it) I made to solve this. Thanks!

If a dynamic resource is added with `-r` and also contains a reference to another dependency that wasn't found in the statically analyzable dependency tree of the main entry point.. It will be missing and cause a bug.

Some possible fixes
 - [ ] [Pass script resources (-r)](https://github.com/nexe/nexe/blob/c5cdbd93805532868421d86657b1f1a48401c9ca/src/steps/bundle.ts#L46) as additional "entrypoints" to [resolve-dependencies](https://github.com/nexe/resolve-dependencies)
 - [ ] Include an entrypoint's own package.json dependencies in expansion scenarios.

**Comment by calebboyd** [comment]
@kaysersoze This should be fixed now, Resources that are added with `-r` are now analyzed for additional dependencies.

**Comment by kaysersoze** [comment]
@calebboyd Thanks! I'll give this a test in the next week or so as I put together a new build of my project. I really appreciate your help on this issue (and apologies I didn't have time to take a look at fixing it myself yet).

**Comment by kamesh95** [comment]
@calebboyd Should this work in case when I have a dynamic node module required in my script and I am including that node_module in my bundle with `-r "node_modules/[[name]]/**"` ? So all dependencies of that node module should be automatically included.
