### ISSUE TITLE
Nexe 3.0.0-beta.7 not catching syntax errors in files required by a module

### ISSUE THREAD

**Issue by chrstew** [nexe/nexe#547]
Hi there, I am unsure if this is a bug, or intended or otherwise. I am using `nexe 3.0.0-beta.7`. 

Let's say I have an entry file (ex `index.js`) that includes an in-house module, ex:
`var x = require('customModule');`

And that `customModule` calls `require` for other files, ex:
`extendedRoutes['ReportingStock2_view'] = require("../custom/clsReportingStock2.js");` 

Normally if `index.js` has a syntax error in it nexe will catch it when bundling, but it seems it will not catch errors for files that are required by modules (ex `../custom/clsReportingStock2.js`)

Is this indended? Does nexe only catch syntax errors for the entry input file, or is it supposed to catch syntax errors in all bundled files?

**Comment by calebboyd** [comment]
This is an issue currently. 

This call passes `warnings` but they're currently being ignored.
https://github.com/nexe/nexe/blob/c681a62566b6a348271a84f42e410301beaf70de/src/steps/bundle.ts#L17
