### ISSUE TITLE
nexe build fail inside docker, error no such file or directory, open __nexe_stdin.js

### ISSUE THREAD

**Issue by xshadowlegendx** [nexe/nexe#548]
**Is this a BUG or a FEATURE REQUEST?:**  Not sure

**What happened:** ``Error: ENOENT: no such file or directory, open '/opt/app/__nexe_stdin.js'``

**What you expected to happen:** nexe to successfully build the executable inside Dockerfile

**How to reproduce it (as minimally and precisely as possible):** ``docker image build -t node_server:latest .``

**Anything else we need to know?:**
    
Package.json

    ...,
    "dependencies": {
    "@babel/runtime": "^7.1.2",
    "apollo-server-express": "^2.1.0",
    "argon2": "^0.19.3",
    "bluebird": "^3.5.1",
    "compression": "^1.7.3",
    "connect": "^3.6.6",
    "cors": "^2.8.4",
    "csurf": "^1.9.0",
    "dataloader": "^1.4.0",
    "ejs": "^2.6.1",
    "email-templates": "^5.0.2",
    "graphql": "^14.0.2",
    "graphql-fields": "^1.2.1",
    "graphql-redis-subscriptions": "^2.0.0",
    "helmet": "^3.14.0",
    "ioredis": "^4.2.0",
    "jsonwebtoken": "^8.3.0",
    "merge-graphql-schemas": "^1.5.7",
    "morgan": "^1.9.1",
    "nodemailer": "^4.6.8",
    "pg": "^7.6.0",
    "pg-hstore": "^2.3.2",
    "qs-middleware": "^1.0.3",
    "sequelize": "^4.41.0",
    "uuid": "^3.3.2"
    },
    "devDependencies": {
    "@babel/cli": "^7.1.2",
    "@babel/core": "^7.1.2",
    "@babel/node": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "@babel/register": "^7.0.0",
    "babel-eslint": "^9.0.0",
    "babel-plugin-import-graphql": "^2.6.2",
    "babel-plugin-module-resolver": "^3.1.1",
    "chai": "^4.2.0",
    "eslint": "^5.8.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-node": "^7.0.1",
    "eslint-plugin-promise": "^4.0.0",
    "eslint-plugin-standard": "^4.0.0",
    "faker": "^4.1.0",
    "graphql-tools": "^4.0.3",
    "grunt": "^1.0.3",
    "grunt-contrib-uglify": "^4.0.0",
    "mocha": "^5.2.0",
    "nexe": "^3.0.0-beta.7",
    "nodemon": "^1.18.5",
    "nyc": "^13.1.0",
    "pkg": "^4.3.4",
    "rimraf": "^2.6.2",
    "rollup": "^0.66.6",
    "rollup-plugin-babel": "^4.0.3",
    "rollup-plugin-commonjs": "^9.2.0",
    "rollup-plugin-multi-entry": "^2.0.2",
    "rollup-plugin-node-resolve": "^3.4.0"
    }

Scripts inside package.json
   
    ..,
    "scripts": {
      "build:rollup": "npm run rollup && npm run minify",
      "exec:nexe": "nexe --enableStdIn='' -i dist/app-server.min.js -p /usr/bin/python -o dist/app-server -r \"dist/**/*.graphql\" -r \"dist/**/*.ejs\"",
      "pack:rollup:nexe": "npm run lint && npm run clean:before && npm run mkdist && npm run copy-assets && npm run build:rollup && npm run exec:nexe && npm run clean:after && npm run clean:asset",
    },
    ...

Dockerfile

    FROM alpine:3.8 as builder
    WORKDIR /opt/app/
    RUN sed -i -e 's/v[[:digit:]]\.[[:digit:]]/edge/g' /etc/apk/repositories && \
      apk update && apk upgrade && \
      apk --update add \
      nodejs \
      nodejs-npm \
      python \
      build-base \
      bash

    ADD . /opt/app/

    RUN npm install && npm run pack:rollup:nexe

    FROM alpine:3.8
    LABEL maintainer="xxx@xxx.com"

    WORKDIR /opt/app/
    COPY --from=builder /opt/app/dist/ /opt/app/

    RUN apk update && apk upgrade && \
      apk add --no-cache bash && \
      addgroup sguard && \
      adduser -D -G sguard sguard-alpha && \
      chown -R sguard-alpha:sguard /opt/app/

    USER sguard-alpha

    CMD ["/opt/app/app-server"]

The error

![error](https://user-images.githubusercontent.com/21999889/47931646-fd27b780-df01-11e8-823f-e36c1a221dad.png)

The build error only happens inside docker

**Environment**

- Platform(OS/Version): Docker/Alpine 3.8
- Host Node Version: Node10
- Target Node Version: Node10
- Nexe version: 3.0.0beta.7
- Python Version: 2.7

**Comment by brilvio** [comment]
the same error happens with using Gitlab CI using shell instead of docker.

```shell
$ call nexe server/server.js -r "client/**/*" -o build/dist/xp-pagamentos.exe -t windows-x64-10.0.0
- Starting...
ℹ nexe 3.0.0-beta.7
- nexe 3.0.0-beta.7
- Included 431 file(s). 3.722 MB
- Downloading...100%
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'c:\multirunner\builds\79bd9abc\0\utilitarios\xppagamentos\__nexe_stdin.js'
Emitted 'error' event at:
    at MultiStream.destroy (C:\Users\XPert\AppData\Roaming\npm\node_modules\nexe\node_modules\multistream\index.js:64:17)
    at MultiStream.onError (C:\Users\XPert\AppData\Roaming\npm\node_modules\nexe\node_modules\multistream\index.js:132:10)
    at Object.onceWrapper (events.js:273:13)
    at MultiStream.emit (events.js:182:13)
    at MultiStream.destroy (C:\Users\XPert\AppData\Roaming\npm\node_modules\nexe\node_modules\multistream\index.js:64:17)
    at ReadStream.onError (C:\Users\XPert\AppData\Roaming\npm\node_modules\nexe\node_modules\multistream\index.js:132:10)
    at Object.onceWrapper (events.js:273:13)
    at ReadStream.emit (events.js:182:13)
    at fs.js:2096:12
    at FSReqWrap.oncomplete (fs.js:171:20)
```

**Comment by jlelse** [comment]
I experience this same error with the same log.

```
- Starting...
ℹ nexe 3.0.0-beta.9
- nexe 3.0.0-beta.9
- Included 3 file(s). 0.256 MB
- Downloading...100%
events.js:167
      throw er; // Unhandled 'error' event
      ^
Error: ENOENT: no such file or directory, open '/app/__nexe_stdin.js'
Emitted 'error' event at:
    at MultiStream.destroy (/app/node_modules/multistream/index.js:64:17)
    at MultiStream.onError (/app/node_modules/multistream/index.js:132:10)
    at Object.onceWrapper (events.js:273:13)
    at MultiStream.emit (events.js:182:13)
    at MultiStream.destroy (/app/node_modules/multistream/index.js:64:17)
    at ReadStream.onError (/app/node_modules/multistream/index.js:132:10)
    at Object.onceWrapper (events.js:273:13)
    at ReadStream.emit (events.js:182:13)
    at lazyFs.open (internal/fs/streams.js:115:12)
    at FSReqWrap.oncomplete (fs.js:141:20)
```

**Comment by xshadowlegendx** [comment]
This issue is back, I also tried to create simple script to test this out:

The script

    // index.js
    console.log('hi');

Dockerfile

    FROM alpine:3.8 as builder

    ENV HOME=/opt/app.
    WORKDIR $HOME

    RUN sed -i -e 's/v[[:digit:]]\.[[:digit:]]/edge/g' /etc/apk/repositories &&\
      apk update && apk upgrade &&\
      apk --update add\
      git\
      nodejs-current\
      nodejs-npm\
      python2\
      build-base\
      bash

    ADD . $HOME

    RUN npm install && npm run build

    FROM alpine:3.8
    LABEL maintainer="legend@shadowlegend.me"

    ENV HOME=/opt/app
    WORKDIR $HOME

    COPY --from=builder $HOME/dist/ $HOME

    RUN apk update && apk upgrade &&\
      apk add --no-cache bash &&\
      mkdir /opt/build &&\
      mv $HOME/native_addons/* /opt/build/ &&\
      rm -rf $HOME/native_addons &&\
      addgroup genx &&\
      adduser -D -G genx xuser &&\
      chown -R xuser:genx $HOME

    USER xuser

    CMD ["/opt/app/dist"]

The packing works as normal outside of docker and here is the error:

    - Starting...
    ℹ nexe 3.0.0-beta.15
    - nexe 3.0.0-beta.15
    - Downloading...100%
    events.js:173
      throw er; // Unhandled 'error' event
      ^

    Error: ENOENT: no such file or directory, open '/opt/app/__nexe_stdin.js'
    Emitted 'error' event at:
      at MultiStream.destroy (/opt/app/node_modules/multistream/index.js:64:17)
      at MultiStream.onError (/opt/app/node_modules/multistream/index.js:132:10)
      at Object.onceWrapper (events.js:285:13)
      at MultiStream.emit (events.js:197:13)
      at MultiStream.destroy (/opt/app/node_modules/multistream/index.js:64:17)
      at ReadStream.onError (/opt/app/node_modules/multistream/index.js:132:10)
      at Object.onceWrapper (events.js:285:13)
      at ReadStream.emit (events.js:197:13)
      at /opt/app/node_modules/graceful-fs/graceful-fs.js:207:14
      at /opt/app/node_modules/graceful-fs/graceful-fs.js:258:16

**Comment by calebboyd** [comment]
What is the command you are using to run nexe?

**Comment by yuta1024** [comment]
I have a same issue.
Maybe, some option (i.e. `-o`, `-r?`) caused this issue.

The following is the sample.
- index.js
```
'use strict';

console.log('Hello, world!');
```

- Dockerfile
```
FROM node:10.15.1-alpine

COPY index.js index.js

RUN set -x && \
    apk add git && \
    npm install nexe@next typescript -g && \
    nexe -o test
```

- logs
```
$ docker build -t nexe-test .
Sending build context to Docker daemon  65.54kB
Step 1/4 : FROM node:10.15.1-alpine
 ---> fe6ff768f798
Step 2/4 : COPY hoge hoge
 ---> 2dfc0b2d06c3
Step 3/4 : COPY index.js index.js
 ---> f7fac8489eec
Step 4/4 : RUN set -x &&     apk add git &&     npm install nexe@next typescript -g &&     nexe -r hoge
 ---> Running in 465e16162757
+ apk add git
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/7) Installing ca-certificates (20171114-r3)
(2/7) Installing nghttp2-libs (1.32.0-r0)
(3/7) Installing libssh2 (1.8.0-r3)
(4/7) Installing libcurl (7.61.1-r1)
(5/7) Installing expat (2.2.5-r0)
(6/7) Installing pcre2 (10.31-r0)
(7/7) Installing git (2.18.1-r0)
Executing busybox-1.28.4-r3.trigger
Executing ca-certificates-20171114-r3.trigger
OK: 21 MiB in 22 packages
+ npm install nexe@next typescript -g
/usr/local/bin/nexe -> /usr/local/lib/node_modules/nexe/index.js
/usr/local/bin/tsc -> /usr/local/lib/node_modules/typescript/bin/tsc
/usr/local/bin/tsserver -> /usr/local/lib/node_modules/typescript/bin/tsserver
+ nexe@3.0.0-beta.15
+ typescript@3.3.3333
added 305 packages from 177 contributors in 19.115s
+ nexe -r hoge
- Starting...
ℹ nexe 3.0.0-beta.15
- nexe 3.0.0-beta.15
- Included 1 file(s). 0.000 MB
- Downloading...100%
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/__nexe_stdin.js'
Emitted 'error' event at:
    at MultiStream.destroy (/usr/local/lib/node_modules/nexe/node_modules/multistream/index.js:64:17)
    at MultiStream.onError (/usr/local/lib/node_modules/nexe/node_modules/multistream/index.js:132:10)
    at Object.onceWrapper (events.js:277:13)
    at MultiStream.emit (events.js:189:13)
    at MultiStream.destroy (/usr/local/lib/node_modules/nexe/node_modules/multistream/index.js:64:17)
    at ReadStream.onError (/usr/local/lib/node_modules/nexe/node_modules/multistream/index.js:132:10)
    at Object.onceWrapper (events.js:277:13)
    at ReadStream.emit (events.js:189:13)
    at lazyFs.open (internal/fs/streams.js:115:12)
    at FSReqWrap.oncomplete (fs.js:141:20)
The command '/bin/sh -c set -x &&     apk add git &&     npm install nexe@next typescript -g &&     nexe -r hoge' returned a non-zero code: 1
```

- docker
```
$ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by yuta1024** [comment]
I found a workaround for this issue. 
**If you explicitly specify `-i` option, the build succeeds.**
However, the build fails if you define the `main` field of package.json.

### use `-i` option (build succeeds) 
- index.js
```
'use strict';

console.log('Hello, world!');
```

- Dockefile
```
FROM node:10.15.1-alpine

COPY index.js index.js

RUN set -x && \
    apk add git && \
    npm install nexe@next typescript -g && \
    nexe -i index.js -o test
```

- logs
```
$ docker build -t nexe-test .
Sending build context to Docker daemon  65.02kB
Step 1/3 : FROM node:10.15.1-alpine
 ---> fe6ff768f798
Step 2/3 : COPY index.js index.js
 ---> Using cache
 ---> 187acfb45938
Step 3/3 : RUN set -x &&     apk add git &&     npm install nexe@next typescript -g &&     nexe -i index.js -o test
 ---> Running in 92a23ec3c78e
+ apk add git
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/7) Installing ca-certificates (20171114-r3)
(2/7) Installing nghttp2-libs (1.32.0-r0)
(3/7) Installing libssh2 (1.8.0-r3)
(4/7) Installing libcurl (7.61.1-r1)
(5/7) Installing expat (2.2.5-r0)
(6/7) Installing pcre2 (10.31-r0)
(7/7) Installing git (2.18.1-r0)
Executing busybox-1.28.4-r3.trigger
Executing ca-certificates-20171114-r3.trigger
OK: 21 MiB in 22 packages
+ npm install nexe@next typescript -g
/usr/local/bin/nexe -> /usr/local/lib/node_modules/nexe/index.js
/usr/local/bin/tsc -> /usr/local/lib/node_modules/typescript/bin/tsc
/usr/local/bin/tsserver -> /usr/local/lib/node_modules/typescript/bin/tsserver
+ typescript@3.3.3333
+ nexe@3.0.0-beta.15
added 305 packages from 177 contributors in 20.224s
+ nexe -i index.js -o test
- Starting...
ℹ nexe 3.0.0-beta.15
- nexe 3.0.0-beta.15
- Downloading...100%
✔ Entry: 'index.js' written to: test
- Finished in 17.005s
✔ Finished in 17.005s
Removing intermediate container 92a23ec3c78e
 ---> 4bc9de61f7e9
Successfully built 4bc9de61f7e9
Successfully tagged nexe-test:latest
```

### define the main field of pacakge.json (build fails)
- index.js
```
'use strict';

console.log('Hello, world!');
```

- package.json
```
{
  "name": "nexe-test",
  "main": "index.js"
}
```

- Dockefile
```
FROM node:10.15.1-alpine

COPY package.json package.json
COPY package-lock.json package-lock.json
COPY index.js index.js

RUN set -x && \
    apk add git && \
    npm install nexe@next typescript -g && \
    nexe -o test
```

- logs
```
$ docker build -t nexe-test .
Sending build context to Docker daemon  67.07kB
Step 1/5 : FROM node:10.15.1-alpine
 ---> fe6ff768f798
Step 2/5 : COPY package.json package.json
 ---> Using cache
 ---> 87caa9e9eb4f
Step 3/5 : COPY package-lock.json package-lock.json
 ---> Using cache
 ---> 4febce03c56e
Step 4/5 : COPY index.js index.js
 ---> Using cache
 ---> 6c9d92cc8a7c
Step 5/5 : RUN set -x &&     apk add git &&     npm install nexe@next typescript -g &&     nexe -o test
 ---> Running in 5a07dd36e00c
+ apk add git
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/7) Installing ca-certificates (20171114-r3)
(2/7) Installing nghttp2-libs (1.32.0-r0)
(3/7) Installing libssh2 (1.8.0-r3)
(4/7) Installing libcurl (7.61.1-r1)
(5/7) Installing expat (2.2.5-r0)
(6/7) Installing pcre2 (10.31-r0)
(7/7) Installing git (2.18.1-r0)
Executing busybox-1.28.4-r3.trigger
Executing ca-certificates-20171114-r3.trigger
OK: 21 MiB in 22 packages
+ npm install nexe@next typescript -g
/usr/local/bin/nexe -> /usr/local/lib/node_modules/nexe/index.js
/usr/local/bin/tsc -> /usr/local/lib/node_modules/typescript/bin/tsc
/usr/local/bin/tsserver -> /usr/local/lib/node_modules/typescript/bin/tsserver
+ nexe@3.0.0-beta.15
+ typescript@3.3.3333
added 305 packages from 177 contributors in 16.978s
+ nexe -o test
- Starting...
ℹ nexe 3.0.0-beta.15
- nexe 3.0.0-beta.15
- Downloading...100%
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/__nexe_stdin.js'
Emitted 'error' event at:
    at MultiStream.destroy (/usr/local/lib/node_modules/nexe/node_modules/multistream/index.js:64:17)
    at MultiStream.onError (/usr/local/lib/node_modules/nexe/node_modules/multistream/index.js:132:10)
    at Object.onceWrapper (events.js:277:13)
    at MultiStream.emit (events.js:189:13)
    at MultiStream.destroy (/usr/local/lib/node_modules/nexe/node_modules/multistream/index.js:64:17)
    at ReadStream.onError (/usr/local/lib/node_modules/nexe/node_modules/multistream/index.js:132:10)
    at Object.onceWrapper (events.js:277:13)
    at ReadStream.emit (events.js:189:13)
    at lazyFs.open (internal/fs/streams.js:115:12)
    at FSReqWrap.oncomplete (fs.js:141:20)
The command '/bin/sh -c set -x &&     apk add git &&     npm install nexe@next typescript -g &&     nexe -o test' returned a non-zero code: 1
```

**Comment by xshadowlegendx** [comment]
Hello @calebboyd  and @yuta1024  sorry for late reply.

The command I run with is `nexe --resources \"dist/**/*.ejs\" --output dist/app-server`

When changed to `nexe --input dist/app-server.js ...` the error is gone but it back to this issue where nexe does not continue and stop at this

    - Starting...
    ℹ nexe 3.0.0-beta.15
    - nexe 3.0.0-beta.15

So the packaging was not success and did not have any error message, and here is running the command with `--loglevel verbose`

    - Starting...
    ℹ nexe 3.0.0-beta.15
    - nexe 3.0.0-beta.15
    ✔ Bundling Resources...
    - Including file: dist/emails/email_verify/html.ejs
    ✔ Including file: dist/emails/email_verify/html.ejs
    - Including file: dist/emails/password_reset/html.ejs
    ✔ Including file: dist/emails/password_reset/html.ejs
    - Included 2 file(s). 0.003 MB

However, when running outside of docker it works as expected:

    ℹ nexe 3.0.0-beta.15
    ✔ Bundling Resources...
    ✔ Including file: dist/emails/email_verify/html.ejs
    ✔ Including file: dist/emails/password_reset/html.ejs
    ✔ Included 2 file(s). 0.003 MB
    ✔ Compiling result
    ✔ Writing result to file
    ✔ Entry: 'dist/app-server.js' written to: dist/app-server
    ✔ Finished in 116.339s

**Comment by calebboyd** [comment]
This should be resolved in 3.0.3

**Comment by xshadowlegendx** [comment]
@calebboyd Hello, the issue is fixed but it still not package the app inside docker

**Comment by calebboyd** [comment]
@xshadowlegendx What is the command you're using to run the docker image. 
Where are you running this?

**Comment by xshadowlegendx** [comment]
@calebboyd I am running it on my local mac machine. Inside gitlab CI also have the same result as my local machine.

The command I am running was `nexe --logLevel verbose --input index.js --output dist/app`

Those file content are:

index.js

    console.log('hi');

package.json

    {
      "name": "nexe-test",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
        "scripts": {
        "pack": "rm -rf dist && nexe --logLevel verbose --input index.js --output dist/app"
       },
      "author": "",
      "license": "ISC",
      "devDependencies": {
        "nexe": "^3.0.3"
      }
    }

Dockerfile

    FROM alpine:3.9 as builder

    ENV HOME=/opt/app
    WORKDIR $HOME

    RUN sed -i -e 's/v[[:digit:]]\.[[:digit:]]/edge/g' /etc/apk/repositories &&\
      apk update && apk upgrade &&\
      apk --update add\
      git\
      nodejs-current\
      nodejs-npm\
      python2\
      build-base\
      bash

    ADD . $HOME

    RUN npm install && npm run pack && ls .

    FROM alpine:3.9
    LABEL maintainer="legend@shadowlegend.me"

    ENV HOME=/opt/app
    WORKDIR $HOME

    COPY --from=builder $HOME/dist/ $HOME

    RUN apk update && apk upgrade &&\
      apk add --no-cache bash &&\
      mkdir /opt/build &&\
      mv $HOME/native_addons/* /opt/build/ &&\
      rm -rf $HOME/native_addons &&\
      addgroup genx &&\
      adduser -D -G genx xuser &&\
      chown -R xuser:genx $HOME

    USER xuser

    CMD ["/opt/app/dist"]

Some part of docker build output

    > nexe-test@1.0.0 pack /opt/app
    > rm -rf dist && nexe --logLevel verbose --input index.js --output dist/app

    - Starting...
    ℹ nexe 3.0.3.     <-------- it ends here ---------
    <--------- i did ls ./ to see if it has dist folder but it not ----------
    Dockerfile. 
    index.js
    node_modules
    package-lock.json
    package.json
    Removing intermediate container 1243d9c7bcff
     ---> 9308f827923f
    Step 7/14 : FROM alpine:3.9

**Comment by calebboyd** [comment]
3.0.5 should work. Let me know if you still have issues.

Full example:
```
FROM alpine:3.9

ENV HOME=/opt/app
WORKDIR $HOME

RUN sed -i -e 's/v[[:digit:]]\.[[:digit:]]/edge/g' /etc/apk/repositories &&\
  apk update && apk upgrade &&\
  apk --update add\
  nodejs-current\
  nodejs-npm\
  bash

RUN echo "console.log('hello world')" \
    >> index.js && \
  echo "{\"scripts\": { \"pack\": \"rm -rf dist && nexe -t alpine-10.15.3 --logLevel verbose --output dist/app\"},\"dependencies\":{\"nexe\":\"^3.0.5\" }}" \
    >> package.json

RUN npm i && npm run pack && ./dist/app
```

**Comment by xshadowlegendx** [comment]
@calebboyd I copy pasted it from you to a new `Dockerfile`, but the image build still fail.

Here is the error output:

    // packges install and npm ...

    - Starting...
    ℹ nexe 3.1.0
    /bin/sh: ./dist/app: not found
    ...

**Comment by calebboyd** [comment]
I can't replicate this at all :(

**Comment by xshadowlegendx** [comment]
@calebboyd The `hello-world` example are already the simplest. I am not sure what is wrong with me. Could you please tell me how to help u to reproduce this?

**Comment by calebboyd** [comment]
I've been able to build that image (and log `hello world`) on both windows and mac with `docker build .` 

Does your environment have internet access? Are you behind a proxy that would prevent you from accessing the pre-built binaries (hosted in github release)? Maybe try adding them to your image. (-t) option controls the nexe temp directory.

**Comment by xshadowlegendx** [comment]
@calebboyd I also used the copy paste `Dockerfile` of yours and try it on gitlab ci, it also didnt work

**Comment by StevenACoffman** [comment]
Hmm... Maybe a different issue, but with globally installed nexe and local:
```
FROM node:11.14.0-alpine as nexe

ENV HOME=/opt/app
WORKDIR $HOME

RUN apk add --update --no-cache python make g++ bash \
      alpine-sdk ca-certificates \
      libressl \
      git openssh openssl build-base coreutils upx

RUN echo "console.log('hello world')" \
    >> index.js && \
  echo "{\"main\": \"index.js\", \"scripts\": { \"pack\": \"rm -rf dist && nexe --build --logLevel verbose --output dist/app\"}}" \
    >> package.json
RUN npm install nexe -g && npm run pack
```
I got:
```
- Starting...
ℹ nexe 3.1.0
- nexe 3.1.0
- Node source extracted to: /opt/app/.nexe/11.14.0
✔ Compiling Node...
- Finished in 65.023s
✔ Finished in 65.023s

Error: make  exited with code: 2

See nexe -h for usage..

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ pack: `rm -rf dist && nexe --build --logLevel verbose --output dist/app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ pack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

**Comment by calebboyd** [comment]
Closing since the original post's issue is solved

Please open a new issue if you have a different nexe issue.
