### ISSUE TITLE
Absolute path of the application built with nexe 

### ISSUE THREAD

**Issue by giacomoratta** [nexe/nexe#549]
I would like to know how I could get the absolute path inside the app in a way which works also when I build the app with nexe.

I tried with the following solutions found online:
console.log( process.cwd() );
console.log( __dirname );
console.log( path.dirname(require.main.filename) );
console.log( path.dirname(process.mainModule.filename) );

1) When I run '**node ./app.js**' I get this ('/Workspace/nxvpl' is the correct absolute path):
/Workspace/nxvpl
/Workspace/nxvpl
/Workspace/nxvpl
/Workspace/nxvpl

2) When I run '**node ./nxvpl/app.js**' I get this ('/Workspace/nxvpl' is the correct absolute path):
/Workspace
/Workspace/nxvpl
/Workspace/nxvpl
/Workspace/nxvpl

3) When I run '**./my_app**' (built with nexe) I get this:
/Workspace/nxvpl
./
.
/Workspace/nxvpl/my_app:20 (error output...)

4) When I run '**./nxvpl/my_app**' (built with nexe) I get this:
/Workspace
./
.
/Workspace/nxvpl/my_app:20 (error output...)

____
In another issue I read that __dirname should not be used. However, what are the alternatives to get the real absolute path inside the app built with nexe?

**Comment by calebboyd** [comment]
What Version of Nexe is this?

**Comment by giacomoratta** [comment]
> What Version of Nexe is this?

I think the latest one... 2.0.0-rc.34

**Comment by calebboyd** [comment]
Go ahead and try `npm i nexe@next` I'm thinking it will fix your issue

**Comment by giacomoratta** [comment]
Almost fixed my specific problems.
I still have the wrong absolute path when I execute the app built with nexe from an external directory.

1) When I run 'node ./app.js' I get this ('/Workspace/nxvpl' is the correct absolute path):
/Workspace/nxvpl
/Workspace/nxvpl
/Workspace/nxvpl
/Workspace/nxvpl

2) When I run 'node ./nxvpl/app.js' I get this ('/Workspace/nxvpl' is the correct absolute path):
/Workspace
/Workspace/nxvpl
/Workspace/nxvpl
/Workspace/nxvpl

3) When I run './my_app' (built with nexe) I get this:
/Workspace/nxvpl
/Workspace/nxvpl
/Workspace/nxvpl
/Workspace/nxvpl

4) When I run './nxvpl/my_app' (built with nexe) I get this:
/Workspace
/Workspace
/Workspace
/Workspace

**Comment by giacomoratta** [comment]
I think I found a way to get the absolute path from the object 'process'.
I'm focusing on:
console.log(process.argv);
console.log(process.mainModule);

When I run 'node ./nxvpl/app.js', I see these values:
[ '/usr/local/bin/node', '**/Workspace/nxvpl/app.js**' ]
Module {
  id: '.',
  exports: {},
  parent: null,
  **filename: '/Workspace/nxvpl/app.js',**
  loaded: false,
  children:  [ ... ],
  paths: 
   [ '**/Workspace/nxvpl/node_modules**',   <--not present in the next output
     '/Workspace/node_modules',
     '/node_modules' ] }


When I run the app built with nexe from an external directory, I see some invalid values:
[ '/Workspace/nxvpl/my_app', **'/Workspace/app.js'** ]
Module {
  id: '.',
  exports: {},
  parent: null,
  **filename: '/Workspace/app.js',**
  loaded: false,
  children: [ ... ],
  paths: [ '/Workspace/node_modules', '/node_modules' ] }

Of course, I can manage this situation.
I just want to show you these different outputs. Maybe it's something you want to fix...

**Comment by calebboyd** [comment]
Yeah it is likely a bug in how i'm setting up the virtual file system. Thanks for info

**Comment by giacomoratta** [comment]
Thanks for your help and for your great job with nexe!

**Comment by simonbuchan** [comment]
Regardless of the FS, `__dirname` and `__filename` should be set to the exe path. This is biting me with native-ext-loader, which emits `const filePath = path.resolve(__dirname, "foo.node"); try { global.process.dlopen(module, filePath); } catch ...`, and this is a context where you absolutely don't want to be using the CWD.

**Comment by simonbuchan** [comment]
Current workaround is the following loader:

```js
const path = require("path");

module.exports = function(content) {
  const fileName = path.basename(this.resourcePath);

  this.emitFile(fileName, content, false);

  this.addDependency(this.resourcePath);

  return `\
const path = require('path');
const dirname = path.dirname(global.process.argv[0]);
const filePath = path.resolve(dirname, ${JSON.stringify(fileName)});
try { global.process.dlopen(module, filePath); }
catch(exception) { throw new Error('Cannot open ' + filePath + ': ' + exception); };
`;
};

module.exports.raw = true;
```

**Comment by calebboyd** [comment]
The issue related to the entrypoint being resolved relative to the current working directory. Which subsequently required all the modules to be resolved in that tree as well. 

fixed via https://github.com/nexe/nexe/commit/c9c9b5a0a31c7ebe6ed4195fecff36b78be8b328

**Comment by simonbuchan** [comment]
Nice, this also results in `__dirname` and `__filename` being set to the exec dir and exec dir + input filename, so `native-ext-loader` amongst others work out of the box as expected.
