### ISSUE TITLE
--rc-* CLI switch

### ISSUE THREAD

**Issue by diwic** [nexe/nexe#550]
Hi,

I'm trying to create an .exe file from the command line, and I'm setting the version info using --rc-* switches, but I can't get it to work. I have two questions:

 1) What is the syntax of setting e g the file version? Is it `--rc-file-version 1.2.3.4` or `--rc-FILEVERSION 1.2.3.4` or `--rc-FileVersion 1.2.3.4` or something else?

 2) Does it work regardless of whether or not the `--build` switch is specified?

**Environment**

- Platform(OS/Version): Windows
- Target Node Version: win32-8.11.4
- Nexe version: nexe@next, i e latest beta (I tried 2.x first but ran into another bug causing me to update to 3.x)

**Comment by stevebaldwin21** [comment]
I was curious about this aswell and I believe this is only for when `--build` is specified.

Looking in the source file `src/patches/node-rc.ts`

```js
 const file = await compiler.readFileAsync('src/res/node.rc')
```

This file is created into a .res file when the solution is built. 

You could resourcehacker for the time being to manipulate the VERSIONINFO manifest.

**Comment by calebboyd** [comment]
@stevebaldwin21 is correct. You'll have to pass the build flag.

@diwic It will depend on the version you're patching. The latest is `--rc-FileVersion 1.2.3.4`

If you change it you'll need to `--clean` and then `--build`. You can also use a post build solution like resourcehacker.

**Comment by diwic** [comment]
@calebboyd @stevebaldwin21 Thanks!

So I tried patching the exe after the packaging (with rc-edit), and my exe ended up going from ~40 MB to 20 MB and nexe saying the exe was corrupt...

So you'll have to patch the exe after it is downloaded but before it is packaged somehow...
