### ISSUE TITLE
Not packaging `locate-path`

### ISSUE THREAD

**Issue by stevebaldwin21** [nexe/nexe#552]
**Is this a BUG or a FEATURE REQUEST?:** 
Bug

**What happened:**
Nexe doesn't package 'locate-path' dependency for 'find-up'.

**What you expected to happen:**
Nexe packages 'locate-path'.

**How to reproduce it (as minimally and precisely as possible):**
Install `yargs` as a dependency and require it

**Anything else we need to know?:**
Nope

**Environment**

- Platform(OS/Version): Windows Server 2012
- Host Node Version: 8.11.3
- Target Node Version: *
- Nexe version: 2.0.0-rc.26
- Python Version: 2.7.9

**Comment by calebboyd** [comment]
Checkout the next version, this should be resolved (`npm i nexe@next`)

**Comment by stevebaldwin21** [comment]
Thanks!
