### ISSUE TITLE
Option for '/SUBSYSTEM:WINDOWS'

### ISSUE THREAD

**Issue by stevebaldwin21** [nexe/nexe#553]
Firstly awesome project!

**Is this a BUG or a FEATURE REQUEST?:** 
Feature Request

Could an option be added for the image type to be Windows Application when the `-build` flag is provided? This can be achieved with the `/SUBSYSTEM:WINDOWS` on the linker options. It would be useful for when applications are used on startup etc or used with libui to not render the console.

**Environment**

- Platform(OS/Version): Windows
- Host Node Version: *
- Target Node Version: *
- Nexe version: *
- Python Version: *

**Comment by calebboyd** [comment]
I'm not familiar with this. Are you referring to an option that can be passed to vcbuild.bat?

**Comment by stevebaldwin21** [comment]
@calebboyd I'm not sure the contents of the vcbuild.bat is that generated from node-gyp?

Do you have an example of it or could tell me where to locate?

Thanks

**Comment by calebboyd** [comment]
vcbuild.bat is a file in the nodejs repo used for building on Windows. Nexe is just a wrapper around the prescribed build steps.

https://github.com/nodejs/node/blob/master/vcbuild.bat

**Comment by stevebaldwin21** [comment]
@calebboyd  

Thanks for this. I took a look and don't believe there is an option.

The same action can be performed in a task by running (developer cmd prompt);

```
editbin /SUBSYSTEM:WINDOWS %nexe-output%.exe
```

**Comment by calebboyd** [comment]
Seems like this might be a bit out of scope then. I'll close it! (correct me if I'm wrong)
