### ISSUE TITLE
Detect running in Nexe

### ISSUE THREAD

**Issue by atmoner** [nexe/nexe#554]
I use nexe to compil my nodejs sources.

Is it possible to define a variable that will be used after compilation with nexe?
Like ifndef with C++

[Here is an example](https://stackoverflow.com/questions/50429180/dynamic-variable-cpp-compilation/50429237#50429237) of what I would like but with nodeJs and nexe

**Comment by calebboyd** [comment]
you could just check to make sure you're not running it with node...


```javascript
const isNode = process.argv[0].replace(/\.exe/g, '').endsWith('node')

if (!isNode) {
  // do stuff...
}
```

**Comment by ricardopolo** [comment]
I dont think this is a safe way, if the user call the "exe" node this method does not work. 
What about having a property that can be check?

In `pkg` there is something like

`````
  if (!process.pkg) {
    logger.writeInConsole('Not running in PKG');
  }

**Comment by calebboyd** [comment]
There is an undocumented property on process called `__nexe` I don't know if it will stick around though.

**Comment by ricardopolo** [comment]
Please keep it! Do you want me a PR documenting it?

**Comment by code-ape** [comment]
Any updates on whether `__nexe` process property was standardized? I'm needing to detect if I'm running in Nexe and could only find this issue.
