### ISSUE TITLE
Node CLI options take precedence in latest Node v10

### ISSUE THREAD

**Issue by hongaar** [nexe/nexe#555]
**Is this a BUG or a FEATURE REQUEST?:** 

A bug

**What happened:**

Passing CLI options to the executable was working fine in Node v8.9.4.

Since upgrading to Node v10.13.0, CLI options (`--x`) seem to be parsed with Node instead of being passed to the application.

**What you expected to happen:**

The application receiving the CLI options, not just arguments.

**How to reproduce it (as minimally and precisely as possible):**

```
$ echo "console.log(process.argv)" | nexe -t 8.9.4 -o test.exe && test.exe test
-> [ 'path\test.exe', '[stdin]', 'test' ]
$ echo "console.log(process.argv)" | nexe -t 8.9.4 -o test.exe && test.exe --test
-> [ 'path\test.exe', '[stdin]', '--test' ]

$ echo "console.log(process.argv)" | nexe -t 10.13.0 -o test.exe && test.exe test
-> [ 'path\test.exe', '[stdin]', 'test' ]
$ echo "console.log(process.argv)" | nexe -t 10.13.0 -o test.exe && test.exe --test
-> test.exe: bad option: --test
```

**Anything else we need to know?:**

**Environment**

- Platform(OS/Version): Windows 10
- Host Node Version: 10.13.0
- Target Node Version: 8.9.4 and 10.13.0
- Nexe version: 2.0.0-rc.34
- Python Version: 2.7.15

**Comment by calebboyd** [comment]
Thanks! I am aware of this issue but haven't had time to alter the patched builds!

**Comment by jaubourg** [comment]
Any idea when you'll find the time. We're kind of hitting a wall with this problem ;) Thanks!

**Comment by calebboyd** [comment]
If you use the node api

You can provide a patch like the following

```javascript

await nexe.compile({
  //...other config
  build: true,
  patches: [
    (compiler, next) => {
      return compiler
        .replaceInFileAsync('src/node.cc', /(?<!void )ProcessArgv\(/g, '//ProcessArgv(')
        .then(next)
    }
  ]
}


```

**Comment by jaubourg** [comment]
Hi there @calebboyd and thank you for your answer.

My latest experience building from source was several hours long : a lot due to setting up all the compilation env on windows, the rest actually building. We also have to build on windows, mac and linux... hence the use of the prebuilds.

If you're telling me it will take weeks to have prebuilds fixed, then I'll get into building from source but I admit I'd rather focus on other things right now ;)

Anyway, I like the way you integrated patches in the compile API. Pretty nifty :)

**Comment by hongaar** [comment]
Looks like a solution is in the making 📦 
 https://github.com/nexe/nexe/commit/7bc3a83667e7683e6533bfc7f6ac4f61c75fd390

**Comment by jaubourg** [comment]
> _oops wrong button.. need more_ ☕️

You and I both ;) Loooooooong days these days 😫

**Comment by calebboyd** [comment]
They're cooking, but the project on AppVeyor appears to be down... Unfortunately it triggers the other builds. Not sure when it will get going again. I've contacted their support team.

**Comment by calebboyd** [comment]
They're there!

**Comment by jaubourg** [comment]
@calebboyd, sorry to bother you again... which version of Node 10? 10.10 doesn't seem to exist:

```
  Fetching prebuilt binary
Error: windows-x64-10.10.0 not available, create it using the --build flag
```

**Comment by jaubourg** [comment]
I tested everything from 10.10 to 10.0, no cigars :(

**Comment by calebboyd** [comment]
Oh, Sorry. The OP mentioned 10.13.0, Which is available now.

It will be several hours from now when 10.10 shows up.

**Comment by jaubourg** [comment]
Ah ok, it's me being late to the party then. I'll install 10.13 ;)
