### ISSUE TITLE
Using --experimental-worker flag

### ISSUE THREAD

**Issue by Jensui** [nexe/nexe#557]
**Is this a BUG or a FEATURE REQUEST?:** 
bug (I think)

**What happened:**
I tried to compile a script of mine into an executable, which uses a node.js experimental flag `--experimental-worker` (added in 10.5.0) which adds a `worker_threads` module and allows it to be required.
Compiling went fine and it generated the executable but when running it I get this error:
`Error: Cannot find module 'worker_threads'`
Is this not a supported flag?

**How to reproduce it (as minimally and precisely as possible):**
Have a file that requires `worker_threads`, compile it with nexe and run it
The cli command I used: `nexe dist/index.js -t win32-x86-10.13.0 -f --experimental-worker`
(maybe I understood the -f flag wrong)
Also tried using `nexe --flags ['--experimental-worker'] -i dist/index.js -t win32-x64-10.13.0`
Executing it normally with `node --experimental-worker dist/index.js` works.

**Environment**

- Platform(OS/Version): Windows
- Host Node Version: 10.13.0
- Target Node Version: win32-x86-10.13.0
- Nexe version: 3.0.0-beta.9
- Python Version:

**Comment by Jensui** [comment]
Small update:
This flag was removed in 11.7.0 ans is now active by default.(https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V11.md#11.7.0)

**Comment by calebboyd** [comment]
Great! I'm probably going to close this for now then.
