### ISSUE TITLE
Fail to bundle dependencies using 3.0.0-beta.x version

### ISSUE THREAD

**Issue by RogerKang** [nexe/nexe#558]
**Is this a BUG or a FEATURE REQUEST?:** 
Should be a bug
**What happened:**
Fail to bundle dependencies using 3.0.0-beta.x version
**What you expected to happen:**
Bundle node modules into executable file, just like 2.0.0-rc.x
**How to reproduce it (as minimally and precisely as possible):**

    const { compile } = require('nexe')
    compile({
      input: './entry.js',
      build: true, 
      target: 'mac-x64-8.9.1',
      patches: [
        async (compiler, next) => {
          await compiler.setFileContentsAsync(
            'lib/new-native-module.js',
            'module.exports = 42'
          )
          return next()
        }
      ]
    }).then(() => {
      console.log('success')
    }).catch(err => {
      console.log('error',  err);
    });

    entry.js:

    let lodash = require('lodash');
    console.log(lodash);

after bundle and remove node_modules, and run ./entry：

    module.js:538
    throw err;
    ^

    Error: Cannot find module 'lodash'
        at Function.Module._resolveFilename (module.js:536:15)
        at Function.Module._load (module.js:466:25)
        at Module.require (module.js:579:17)
        at require (internal/module.js:11:18)

**Anything else we need to know?:**
I use nexe@3.0.0-beta.9 with this issue and it is fine with 2.0.0-rc.34.
**Environment**
Mac with node 8.9.
- Platform(OS/Version):
- Host Node Version:
v8.9.1
- Target Node Version:
- Nexe version:
3.0.0-beta.9
- Python Version:
2.7.10

**Comment by calebboyd** [comment]
I can't replicate this

**Comment by RogerKang** [comment]
Sorry, the root cause is that I used informal npm. After changing to formal npm, it fixed
