### ISSUE TITLE
"JavaScript heap out of memory" during build

### ISSUE THREAD

**Issue by vladikus10** [nexe/nexe#559]
**Is this a BUG or a FEATURE REQUEST?:** 
A question or possible bug?
**What happened:**
When I tried to build my app for windows, I received this error:
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```
**What you expected to happen:**
I expected to complete the build, looking on the web, the issue can be solved in a normal node app by adding a `--max_old_space_size=4096` flag, but when I tried adding this to nexe via `--flags` like so:
```
nexe --flags ['--max_old_space_size=4096'] -i app.js -t win32-x64-8.6.0 -o app-win
```
I still had the same issue.

Is there no way to allocate more memory when building? 
**How to reproduce it (as minimally and precisely as possible):**
Probably the only way to reproduce this is to reproduce the app it self (with other smaller ones the build was successful), but as it is a company project, I cannot share the code. 

**Environment**

- Platform(OS/Version): Linux (debian)
- Host Node Version: v8.12.0
- Target Node Version: win32-x64-8.6.0 
- Nexe version: 3.0.0-beta.9
- Python Version:

**Comment by calebboyd** [comment]
Hmm... Are you including a lot of resources?

Can you run this?

```javascript
const resolveFiles = require('resolve-dependencies').default

const { files } = await resolveFiles('./app.js', { expand: true, loadContent: false })

console.log(Object.keys(files).length, ' files')
```

**Comment by vladikus10** [comment]
Probably yes, we do depend on a lot of external modules.

The code resulted in : 5402 ' files'

After trying to run the build command a couple of times, it started to complete the build again. Not sure why it fails sometimes and sometimes not.
