### ISSUE TITLE
Windows problem when try to complie peerflix

### ISSUE THREAD

**Issue by juliotec** [nexe/nexe#56]
Hi, when im trying to complie "peerflix" project the complie stuck in  v8_base.vcxproj -> ........\build\Release\lib\v8_base.lib, and dont do nothing, i do the same with "torrent-stream" stuck in  v8_base.vcxproj -> ........\build\Release\lib\v8_base.lib too, what is happen? dont show any error or nothing

I have been compiling the examples hellow world and works ok, i have phyton 7 and visual studio 2013

**Comment by RainbowDashDC** [comment]
Hi, thanks for reporting this issue however I'm unclear of what exactly your issue is. Please post screenshots or logs of output and relevant code so we can figure this out!

**Comment by calebboyd** [comment]
Closing - abandoned
