### ISSUE TITLE
fs.readdir incompatible with native nodejs

### ISSUE THREAD

**Issue by RogerKang** [nexe/nexe#560]
**Is this a BUG or a FEATURE REQUEST?:** 
 Should be a bug。
**What happened:**
The second parameter of fs.readdir(fs.readdir(path[, options], callback)): `options` should be optional, but in nexe bundle file it will show: `Calling an asynchronous function without callback is deprecated` if we missing this parameter and fail to get the correct result.
**What you expected to happen:**
Same result as native nodejs.
**How to reproduce it (as minimally and precisely as possible):**

**Anything else we need to know?:**

**Environment**

- Platform(OS/Version):
- Host Node Version: 8.9
- Target Node Version:
- Nexe version: 3.0.0.beta.9
- Python Version:
  2.7

**Comment by RogerKang** [comment]
I have two directories now:
./nexeTest4
./nexeTest5

and create a test.js in nexeTest5:

    let fs = require('fs');
    let path = require('path')
    fs.readdir(path.join(__dirname, '../nexeTest4'), function (err, files) {
      console.log(err, files);
    })

then run: `node test.js`:
output:
`null [ 'bundle.js', 'entry', 'entry.js', 'node_modules', 'test.json' ]` 
// those are files under nexeTest4

bundle test.js: `nexe test.js`:

    ℹ nexe 3.0.0-beta.9
    ✔ Compiling result
    ✔ Entry: 'test.js' written to: test
    ✔ Finished in 0.635s

then run test: `./test`:
output:
`(node:92634) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.`


above issue will be fixed if I change the fs.readdir call to:

    fs.readdir(path.join(__dirname, '../nexeTest4'), {}, function (err, files) {
      console.log(err, files);
    })

 fs.readdir's second parameter is optional according NodeJs's docs:
`fs.readdir(path[, options], callback)`

So I think it is an issue within nexe.

**Comment by calebboyd** [comment]
related to #549

**Comment by bruce-one** [comment]
I actually think this is an issue reassigning the arguments (and not related to #549), as an example:

```
function f(filepath, options, callback) {
  if ('function' === typeof options) {
    callback = options;
    options = { encoding: 'utf8' };
  }
  console.log(arguments)
}
f('path', 'opt', function callback(){})
f('path', function callback(){})
```
Leading to:
```
[Arguments] { '0': 'path', '1': 'opt', '2': [Function: callback] }
[Arguments] { '0': 'path', '1': { encoding: 'utf8' } }
```
Note the second output only contains two values, the third hasn't been set. This becomes an issue with readdir because it calls `.apply` with `arguments`.

https://spin.atomicobject.com/2011/04/10/javascript-don-t-reassign-your-function-arguments/ goes into it in more detail than just that snippet.

I was about to create a PR.
