### ISSUE TITLE
Error: Cannot find module 'ms'

### ISSUE THREAD

**Issue by ofarukcaki** [nexe/nexe#564]
It works without a compiling, but after I compiled it with Nexe it throws this error. I used many times for similar projects but it was never happen before
![image](https://user-images.githubusercontent.com/24359008/49674882-79269980-fa84-11e8-9743-c9663a47649e.png)

**Is this a BUG or a FEATURE REQUEST?:**  BUG

**What happened:**
Error

**What you expected to happen:**
It should have run the compiled program

- Platform(OS/Version): Windows 10 x64
- Host Node Version:  v10.5.0
- Target Node Version: ?
- Nexe version: 2.0.0-rc.34
- Python Version: Python 3.7.0

**Comment by calebboyd** [comment]
Try using `npm I nexe@next`

**Comment by ofarukcaki** [comment]
I already tried using nexe@next too, is there any other temporary solution at least?

**Comment by calebboyd** [comment]
I can't replicate this with `nexe@next`. Please provide a reproduction

**Comment by sidharthmenon** [comment]
I has same issue when using nexe version 2.0.0-rc.34
it was solved by installing version 3.0.0-beta.15

`npm remove nexe -g`

`npm install nexe@3.0.0-beta.15 -g`
