### ISSUE TITLE
Compiled exe works only in original directory

### ISSUE THREAD

**Issue by jasir** [nexe/nexe#570]
**Is this a BUG or a FEATURE REQUEST?:** 

BUG

**What happened:**

compiled .exe (windows) works only in directory where it was compiled. In another path, shows error ``` Cannot find module './client.js'```

**What you expected to happen:**

to just run

**How to reproduce it (as minimally and precisely as possible):**

run nexe --target win-ia32-10.14.1 -i client.js -o client.exe

**Environment**

- Platform(OS/Version): Windows 10
- Host Node Version:

10.14.2

- Target Node Version:
10.14.1

- Nexe version: 3.0.0-beta.11

- Python Version:

**Comment by calebboyd** [comment]
I can't replicate this. Try using `--clean` first

**Comment by jasir** [comment]
--clean does not help.

Reproduction:

create file test.js:

```
console.log('hello world')
```

then ```nexe test.js --target windows-x86-10.14.2```

* move file test.exe to some other directory on another disk (ie from c:\... to d:\...)
* run test.exe from there

output:

```
d:\xxx>test.exe
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './test.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:32:19)
    at d:\xxx\test.exe:320:42
    at Object.<anonymous> (d:\xxx\test.exe:322:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at _third_party_main.js:37:36
    at NativeModule.compile (internal/bootstrap/loaders.js:363:7)
    at Function.NativeModule.require (internal/bootstrap/loaders.js:174:18)
    at internal/bootstrap/node.js:248:22
    at process._tickCallback (internal/process/next_tick.js:61:11)

d:\xxx>
```

**Comment by calebboyd** [comment]
![kap](https://user-images.githubusercontent.com/5818726/50304309-36d26480-0455-11e9-8b5d-03867a85548c.gif)

**Comment by jasir** [comment]
Hello. After lots of hours, I have found ou  that compiled version does not work only when runned from Total Commander activated shell. I am going to close the issue, thanks for cooperation. I have not been able to distinguish differences between TC Shell and normal shell (prompt). Environment variables are ale the same. Thank you very much.

**Comment by aemonge** [comment]
What ?

I'm seeing the same issue. So can you please explain further the TC Shell issue?  I'm seeing this with a powershell and cmd

**Comment by aybhalala** [comment]
I am seing this issue using bash and zsh too

**Comment by calebboyd** [comment]
Please open a new issue and include what you're tried with a minimal reproduction if possible.
