### ISSUE TITLE
nexe binary not working

### ISSUE THREAD

**Issue by viddeshshinde** [nexe/nexe#572]
**What happened:**
I was able to make a binary successfully. I built it it on macOS. While running I get some weird errors related to external required modules (NPMs) in the project.

My project has many external and internal NPMs required in itself. Doesn't nexe support that ?

- Platform(OS/Version): MacOS
- Host Node Version: v8.11.1
- Target Node Version: v8.11.1
- Nexe version: 2.0.0-rc.34
- Python Version: 2.7.15

**Comment by calebboyd** [comment]
Try `npm i nexe@next`
