### ISSUE TITLE
Wrong executable name

### ISSUE THREAD

**Issue by tbhaxor** [nexe/nexe#576]
**Is this a BUG or a FEATURE REQUEST?:** 
BUG Report

**What happened:**
Wrong value of process.argv[1]

Output of same script when made executable
```
$ ./bifrost -h
usage: index.js [-h] [--greet]

First app

Optional arguments:
  -h, --help  Show this help message and exit.
  --greet 
```

**What you expected to happen:**
Correct/Current value of process.argv[1] -_-
```
$ ./bifrost -h
usage: ./bifrost [-h] [--greet]

First app

Optional arguments:
  -h, --help  Show this help message and exit.
  --greet 
```
**How to reproduce it (as minimally and precisely as possible):**

1. Build the following code
```js
const ArgumentParser = require("argparse").ArgumentParser

let parser = new ArgumentParser({ description: "First app" });

parser.addArgument("--greet", {
    type: String,
    metavar: ""
})

console.log("Hi,", parser.parseArgs().greet)
```
2. Now see the output of source `.js` file and executable file

**Anything else we need to know?:**
Nope

**Environment**

- Platform(OS/Version): Arch Linux 2.19
- Host Node Version: 8.15.0
- Target Node Version: 5.15.0
- Nexe version: 2.0.0-rc.34
- Python Version: 3.7

**Comment by calebboyd** [comment]
`./bifrost` is actually `argv[0]`. `index.js` is still being loaded from the internal filesystem and is the correct value for `argv[1]`. If you want to change this you can alter it in your own script at startup. Or set your own usage string in `argparse`.
