### ISSUE TITLE
Steps to Manually Patch NodeJS with NexeFS (Also, Cross Compiling)

### ISSUE THREAD

**Issue by medemi68** [nexe/nexe#577]
Hello everyone!

I'm trying to compile nexe on an unsupported platform (unsupported by nexe). There is a specific toolchain that I have to use in order to compile my executable for the platform. I had a look at the source code of Nexe, and I was wondering if someone could explain how Nexe patches the NodeJS source code before creating the executable so that I can manually create my own version of NodeJS with the Nexe shims (using make and my toolchain), I will figure out a way to pass that executable to Nexe later so that it can bundle the executable binary that i've made.

There are limitations as to what I am able to do (like, I can't run nexe compile on the target device)

What would be helpful is a link to the NodeJS source code that Nexe modifies, or some form of instruction on how to modify the file(s) myself. A fork of the NodeJS project with the modifications in it would also work.

Any help is greatly appreciated.

**Comment by calebboyd** [comment]
The easiest option would be to use a plugin and just overwrite the compiler method used for building.

You can override this method https://github.com/nexe/nexe/blob/c76edb7c0b9870da1125f6bcf4e551241942e85b/src/compiler.ts#L228-L241

like this

```javascript
const nexe = require('nexe')
nexe.compile({
    ...options,
    plugins: [
      async function myToolchainPatch (compiler, next) {
         compiler.build = function myToolchain () { 
           // ensure compiler.nodeSrcBinPath is set to where the built artifact will end up
           // build node with my toolchain           
           // return a Promise<ReadStream> of the executable content
         }
         return next()        
      }
    ]
})


```

**Comment by medemi68** [comment]
That might work actually. I am currently trying to bundle my application for use with [Buildroot](https://buildroot.org/), and I need to be able to use the same toolchain that Buildroot uses to perform the compilation of nodejs. 

I know it **might** be possible to set the environment variables of CC=(c toolchain here) and CXX=(C++ toolchain here) for make, but I know that at some point during the compilation of NodeJS, the host system is required to run some of the executables (specifically ./configure) as part of the compilation process.

I guess I would then be able to change the configure options in nexe to append
`` --dest-cpu=arm64 --cross-compiling --dest-os=linux 
 --with-arm-float-abi=hard --with-arm-fpu=neon``

For example if the architecture was ARM64 Linux?

If this is correct, hopefully it might someone else who is trying to cross compile as well. Ill give it a go when I have a chance.

**Comment by calebboyd** [comment]
Yeah, nexe is a pretty thin wrapper over the regular node compile options.

with the api just do something like

```javascript
nexe.compile({
   ...options,
   target: 'linux-arm64'
   configure: [
     '--dest-cpu=arm64', 
     '--cross-compiling', 
     '--dest-os=linux',
     '--with-arm-float-abi=hard',
     '--with-arm-fpu=neon'
   ]
})
```

**Comment by medemi68** [comment]
Thanks!

I don't have the time to run any builds at the moment, but the explanation has helped quite a bit. Thank you very much.
