### ISSUE TITLE
Acorn struggles with bignum literals

### ISSUE THREAD

**Issue by thalionath** [nexe/nexe#579]
Bug: nexe reports an Acorn error if the input contains a bignum literal.

    const now_ms = process.hrtime.bigint() / 1000000n;
    console.log(`now: ${now_ms}`);

Output with node v10.15.0:

    node bigint.js
    now: 1257989090

Compilation with nexe reports Acorn error:

    nexe bigint.js
    i nexe 2.0.0-rc.34
    Acorn error: Identifier directly after number (1:48)
    File: C:\Users\mg\projects\bignum\bigint.js
    
    1  const now_ms = process.hrtime.bigint() / 1000000n;
    2  console.log(`now: ${now_ms}`);
    
    
    √ Compiling result
    √ Entry: 'bigint.js' written to: bigint.exe
    √ Finished in 0.957s

but nexe does not abort an produces a executable which crashes:

    bigint.exe
    internal/modules/cjs/loader.js:583
        throw err;
        ^
    
    Error: Cannot find module 'default/bigint.js'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
        at Function.Module._load (internal/modules/cjs/loader.js:507:25)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (internal/modules/cjs/helpers.js:22:18)
        at s (bigint.exe:18:1845)
        at c (bigint.exe:18:3124)
        at Function.r.import (bigint.exe:18:4190)
        at bigint.exe:15:15
        at Object.<anonymous> (bigint.exe:18:1)
        at Module._compile (internal/modules/cjs/loader.js:689:30)
    
Is there a way to workaround this an disable Acorn verification?

**Environment**

- Platform(OS/Version): Windows 10 64-bit
- Host Node Version: v10.15.0
- Target Node Version:  v10.15.0
- Nexe version: 2.0.0-rc.34
- Python Version:

**Comment by calebboyd** [comment]
This should work in `nexe@next` if you want to give it a try

**Comment by thalionath** [comment]
Works indeed, thanks!

    npm install nexe@next
    node_modules\.bin\nexe bigint.js
    i nexe 3.0.0-beta.13
    √ Downloading...100%
    √ Entry: 'bigint.js' written to: bigint.exe
    √ Finished in 23.727s
