### ISSUE TITLE
QUESTION : what i am doing wrong to build for windows

### ISSUE THREAD

**Issue by tbhaxor** [nexe/nexe#580]
**Is this a BUG or a FEATURE REQUEST?:** 
QUESTION

**What happened:**
I want to build my express application for windows OS

**What you expected to happen:**
Build an application for windows i.e
```
$ file server.exe
server.exe: PE32+ executable (console) x86-64, for MS Windows
```
**How to reproduce it (as minimally and precisely as possible):**
```
$ nexe server.js --build windows-x64-8.15.0 -o server.exe --python /usr/bin/python2
$ file server.exe
server.exe: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=b3caddbd908a584cc6c87fd681409db714f08e9d, with debug_info, not stripped
```

**Anything else we need to know?:**

**Environment**

- Platform(OS/Version): Arch Linux
- Host Node Version: 8.15.0
- Target Node Version: 8.15.0
- Nexe version: 2.0.0
- Python Version: 2

**Comment by jaredallard** [comment]
@tbhaxor have you tried `nexe server.js -t windows-x64-8.15.0 -o server.exe --python /usr/bin/python2`

`--build` forces it to build node.js, but it looks like you're trying to use a prebuilt which is a no-op when supplying `--build` thus you only supply `-t` (which was no being supplied before).

**Comment by tbhaxor** [comment]
@jaredallard still same file type :unamused:

**Comment by calebboyd** [comment]
I'm having trouble replicating it!
![image](https://user-images.githubusercontent.com/5818726/51440630-c22a5a00-1c8e-11e9-8eed-2a7dc4ec77a7.png)

**Comment by tbhaxor** [comment]
thanks @calebboyd  it worked with `--clean`
