### ISSUE TITLE
what is current version of this projet

### ISSUE THREAD

**Issue by xileftenurb** [nexe/nexe#582]
hello,

on npm, the version published is 2.0.0-rc.34,
but on github, I just saw many issue "resolved in v3", and the lastest release is 3.0.0

Will the v3 be available on npm soon? Is it ready?

thank

**Comment by calebboyd** [comment]
v3 is available via `npm i nexe@next` and y0ou can use this. There are some caveats currently such as executable _size_ due to the new bundling methodology that was created for v3. Until this are made better or more configurable it will not be the `@latest` version.
