### ISSUE TITLE
How does nexe compare to ncc?

### ISSUE THREAD

**Issue by transitive-bullshit** [nexe/nexe#584]
`nexe` seems to have very similar goals as [ncc](https://github.com/zeit/ncc).

Just curious how the two compare and when you may decide to use one versus the other?

Thanks!

**Comment by WebMatrixware** [comment]
It is actually a better comparison to https://github.com/zeit/pkg which also produces an executable (like nexe) whereas ncc just packs all of your code into a single .js file.

I am looking at nexe because zeit/pkg has not had any development in some time and has TONS of open issues that make it impractical to use.

**Comment by calebboyd** [comment]
A quick look, `ncc` looks like a webpack wrapper for node projects. Cool!

Maybe do this if you find nexe's bundling doesn't work for you but ncc's does. 
`ncc build input.js -o dist && cat dist/input.js | nexe -o my-app`

**Comment by transitive-bullshit** [comment]
Thanks!

**Comment by tbhaxor** [comment]
> A quick look, `ncc` looks like a webpack wrapper for node projects. Cool!
> 
> Maybe do this if you find nexe's bundling doesn't work for you but ncc's does.
> `ncc build input.js -o dist && cat dist/input.js | nexe -o my-app`

So instead of configuring webpack for node projects, can we use ncc directly or CAN WE RELY ON NCC ?

**Comment by calebboyd** [comment]
Not sure I understand. If you want to use ncc to provide a bundle to nexe that is up to you!

**Comment by paulocoghi** [comment]
IMHO, [**Rollup**](https://github.com/rollup/rollup) is much better and more efficient than ncc to bundle your node project into one single js file.

I'm using it before generating the binaries with Nexe.
