### ISSUE TITLE
`nexe index.js` error "FuseBox failed to initialize."

### ISSUE THREAD

**Issue by vaidd4** [nexe/nexe#585]
**Is this a BUG or a FEATURE REQUEST?:** Bug

**What happened:**  
On a fresh debian install with node v10.15.1,  
When launching the command `nexe index.js`, I get the following message :  
```
$ nexe index.js
ℹ nexe 2.0.0-rc.34

  FuseBox failed to initialize. Please check that:
      - the TypeScript version installed is >= 3.0

```

**What you expected to happen:** To build a simple exe file.

**How to reproduce it (as minimally and precisely as possible):**  
- Install Debian Stretch 9.7
- Install Node 10 via nodesources
- Create a simple node script `index.js` : `console.log('Hello World')`
- Install nexe globally : `npm install -g nexe`
- Start the command : `nexe index.js`

**Anything else we need to know?:**  
It's a fresh install of debian so I may not have many common packages.

**Environment**

- Platform(OS/Version): Debian 9.7
- Host Node Version: 10.15.1
- Target Node Version: 6.4.1
- Nexe version: 2.0.0-rc.34
- Python Version: none

**Comment by tamasszarka** [comment]
We ran into the same issue last night. The problem is the package.json specifies ^3.1.0 for the version of fuse-box, while they released 3.7.0 yesterday, which explicitly requires typescript 3.0.0< while nexe needs typescript 2.5.3.
My workaround was to force installing fuse-box 3.1.0 instead of ^3.1.0.

**Comment by acg** [comment]
Confirmed workaround. Add this to `package.json`:

```json
  "resolutions": {
    "nexe/fuse-box": "3.1.0"
  }
```

**Comment by RobLoach** [comment]
This worked for me....

```
npm i typescript --save-dev
```

**Comment by ScottWorks** [comment]
I am still having this issue, @tamasszarka @acg are you referring to the package.json belonging to the project or nexe (assuming you cloned your own copy)?

**Comment by tamasszarka** [comment]
No need to clone/modify nexe, the workaround applies to how you specify your dependency to nexe in your own package.json.
Either add a “resolutions” section to it (as in the above answer), or add a direct dependency on fuse-box 3.1.0; both will avoid consuming the incompatible update from fuse-box 3.7.0. And then commit your package-lock.json :)

**Comment by calebboyd** [comment]
Does installing and using `nexe@next` solve your issue?

The next version drops the fusebox dependency

**Comment by fsteff** [comment]
> Does installing and using `nexe@next` solve your issue?

I did have this problem too, using nexe@next works perfectly.

**Comment by tbhaxor** [comment]
> **Is this a BUG or a FEATURE REQUEST?:** Bug
> 
> **What happened:**
> On a fresh debian install with node v10.15.1,
> When launching the command `nexe index.js`, I get the following message :
> 
> ```
> $ nexe index.js
> ℹ nexe 2.0.0-rc.34
> 
>   FuseBox failed to initialize. Please check that:
>       - the TypeScript version installed is >= 3.0
> ```
> 
> **What you expected to happen:** To build a simple exe file.
> 
> **How to reproduce it (as minimally and precisely as possible):**
> 
>     * Install Debian Stretch 9.7
> 
>     * Install Node 10 via nodesources
> 
>     * Create a simple node script `index.js` : `console.log('Hello World')`
> 
>     * Install nexe globally : `npm install -g nexe`
> 
>     * Start the command : `nexe index.js`
> 
> 
> **Anything else we need to know?:**
> It's a fresh install of debian so I may not have many common packages.
> 
> **Environment**
> 
>     * Platform(OS/Version): Debian 9.7
> 
>     * Host Node Version: 10.15.1
> 
>     * Target Node Version: 6.4.1
> 
>     * Nexe version: 2.0.0-rc.34
> 
>     * Python Version: none

Every thing is same  except `Target Node Version` which is **10.15.1**

**Comment by cyyyu** [comment]
Encountered the issue as well, and by using nexe@next it works.

**Comment by tbhaxor** [comment]
> Encountered the issue as well, and by using nexe@next it works.

I got an error while installing nexe@next

```
$ sudo npm i -g nexe@next
npm ERR! code 128
npm ERR! Command failed: git clone --depth=1 -q -b master git://github.com/nexe/globby.git /root/.npm/_cacache/tmp/git-clone-ea731fc1
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-ea731fc1': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-23T11_46_53_456Z-debug.log
```

**Comment by vaidd4** [comment]
Sorry for the late reply,
@calebboyd just tested and yes it does work with the `next` version (`3.0.0-beta.15`).

@tbhaxor your issue seems not to be related with this one. (try installing with root permissions)

**Comment by calebboyd** [comment]
@tbhaxor if you reinstall it should work now

**Comment by subfuzion** [comment]
Confirmed the same issue on a mac, but nexe@next as suggested works fine.
