### ISSUE TITLE
nexe package fail inside docker

### ISSUE THREAD

**Issue by xshadowlegendx** [nexe/nexe#587]
This issue is back, I also tried to create simple script to test this out:

The script

    // index.js
    console.log('hi');

Dockerfile

    FROM alpine:3.8 as builder

    ENV HOME=/opt/app.
    WORKDIR $HOME

    RUN sed -i -e 's/v[[:digit:]]\.[[:digit:]]/edge/g' /etc/apk/repositories &&\
      apk update && apk upgrade &&\
      apk --update add\
      git\
      nodejs-current\
      nodejs-npm\
      python2\
      build-base\
      bash

    ADD . $HOME

    RUN npm install && npm run build

    FROM alpine:3.8
    LABEL maintainer="legend@shadowlegend.me"

    ENV HOME=/opt/app
    WORKDIR $HOME

    COPY --from=builder $HOME/dist/ $HOME

    RUN apk update && apk upgrade &&\
      apk add --no-cache bash &&\
      mkdir /opt/build &&\
      mv $HOME/native_addons/* /opt/build/ &&\
      rm -rf $HOME/native_addons &&\
      addgroup genx &&\
      adduser -D -G genx xuser &&\
      chown -R xuser:genx $HOME

    USER xuser

    CMD ["/opt/app/dist"]

The packing works as normal outside of docker and here is the error:

    - Starting...
    ℹ nexe 3.0.0-beta.15
    - nexe 3.0.0-beta.15
    - Downloading...100%
    events.js:173
      throw er; // Unhandled 'error' event
      ^

    Error: ENOENT: no such file or directory, open '/opt/app/__nexe_stdin.js'
    Emitted 'error' event at:
      at MultiStream.destroy (/opt/app/node_modules/multistream/index.js:64:17)
      at MultiStream.onError (/opt/app/node_modules/multistream/index.js:132:10)
      at Object.onceWrapper (events.js:285:13)
      at MultiStream.emit (events.js:197:13)
      at MultiStream.destroy (/opt/app/node_modules/multistream/index.js:64:17)
      at ReadStream.onError (/opt/app/node_modules/multistream/index.js:132:10)
      at Object.onceWrapper (events.js:285:13)
      at ReadStream.emit (events.js:197:13)
      at /opt/app/node_modules/graceful-fs/graceful-fs.js:207:14
      at /opt/app/node_modules/graceful-fs/graceful-fs.js:258:16

the command the package the app was `nexe -t alpine-x64-10.9.0 --output dist`

_Originally posted by @xshadowlegendx in https://github.com/nexe/nexe/issues/548#issuecomment-464610738_

**Comment by calebboyd** [comment]
Fixed in 3.0.3
