### ISSUE TITLE
[FEATURE REQUEST] No such file or directory

### ISSUE THREAD

**Issue by tbhaxor** [nexe/nexe#590]
**Is this a BUG or a FEATURE REQUEST?:** 
FEATURE REQUEST

**What happened:**
Error: ENOENT: no such file or directory, open '/home/malware-test/program/Commander/bin/linux/x64/commander'

**What you expected to happen:**
It should create the directory recursively if doesnt exists

**How to reproduce it (as minimally and precisely as possible):**
Try pass --output for non existing directory

**Anything else we need to know?:**
No
**Environment**

- Platform(OS/Version): Linux
- Host Node Version: 10.5
- Target Node Version: 10.5
- Nexe version: 3.0.0-beta.15
- Python Version: none

**Comment by tbhaxor** [comment]
Since no one is interested therefore i am closing this issue

**Comment by tbhaxor** [comment]
@calebboyd  is anyone working ?

**Comment by calebboyd** [comment]
PRs welcome!
