### ISSUE TITLE
Missing binaries

### ISSUE THREAD

**Issue by asamuzaK** [nexe/nexe#593]
**Is this a BUG or a FEATURE REQUEST?:** 
Bug?

**What happened:**
[Releases · nexe/nexe](https://github.com/nexe/nexe/releases)
Missing
* linux-x64-10.15.2
* windows-x64-10.15.2

**What you expected to happen:**

**How to reproduce it (as minimally and precisely as possible):**

**Anything else we need to know?:**

**Environment**

- Platform(OS/Version): Windows 10
- Host Node Version: 10.15.2
- Target Node Version: 10.15.2
- Nexe version: 3.0.0-beta.15
- Python Version:

**Comment by calebboyd** [comment]
There is some trouble with the appveyor build. I've contacted their support and the issue should be resolved soon.
