### ISSUE TITLE
Node build not identical to official node

### ISSUE THREAD

**Issue by yasserf** [nexe/nexe#595]
**Is this a BUG or a FEATURE REQUEST?:** 

Bug/ish

**What happened:**

uws (native module) doesn't work

**What you expected to happen:**

For uws to work

**How to reproduce it (as minimally and precisely as possible):**

Build an executable with nexe as a native dependency using a prebuilt nexe package

**Anything else we need to know?:**

The issue seems to be around C++ compiler version

When building using the following docker base it works well:

```
FROM centos/devtoolset-7-toolchain-centos7
RUN yum install -y centos-release-scl
```

**Comment by yasserf** [comment]
Worth also mentioning this issue does not occur with Mac prebuilt versions but does with windows =(

**Comment by calebboyd** [comment]
What version of nexe are you using. Are you using v2 or v3 (nexe@next) v3 doesn't bundle native modules and you have to ship it alongside manually. 

Otherwise...are you expecting to cross compile? Nexe cant do that -- If your package ships with native modules for different platforms you'll have to build on those different platforms. Sounds like you could be building for windows on a mac and expecting your native module (for mac) to be loaded on windows.

It might be possible if the package uses `prebuild`, to then retrieve the correct native addon per platform during the nexe build and ship it alongside the nexe executable (PRs welcome!), or you happen to be running the binary where it has access to the native module...(eg the project directory)

**Comment by yasserf** [comment]
Using V3. Not looking to bundle the files, the issue is just that the built
node bundle doesn’t seem to built with the same flags as the official node
build. Figured that is the case because uws works with normal node and when
I build a custom node with those flags. Basically a very niche issue where
the native module is already prebuilt and doesn’t compile on a node install
😔

**Comment by calebboyd** [comment]
@yasserf 
> "with those flags" 
Which flags in particular? The goal is to be as close to the official node versions (but with appropriate nexe patches) -- So if there are some flags that are missing It might need fixing.

**Comment by yasserf** [comment]
Hey, apologies for the late response! Also for the misleading 'flag' statement.

As mentioned in my first comment, it appears for some of our users (centos 7 and older ubuntu) the native uws 0.15 addon doesn't work. According to the author its because he only supports 'official' node artefact. I managed to get it running on centos7 with help from a user by installing centos-release-scl which apparently allows node to run with older versions of the CPP compiler (which some addons are also built with). I'm not sure if this will work across all platforms but I believe we need to build node on an older system to ensure backwards compatibility.

```
FROM centos/devtoolset-7-toolchain-centos7
RUN yum install -y centos-release-scl
```

**Comment by calebboyd** [comment]
If you know what toolchain versions to set I can look at reverting the toolchain in CI.
Linux builds are currently done with the .travis.yml file.

**Comment by yasserf** [comment]
Cool, I will take a look at what the equivalent for ubuntu is over next couple days and let you know! Thanks

**Comment by calebboyd** [comment]
There is an item in current master requiring rebuilds (the toolchain change would too) If you can figure out the right toolchain we can save some trees by not exercising CI so much 😂

**Comment by yasserf** [comment]
😂 I’ll probably do it via docker on my machine first before trying it out in the cloud 😂

**Comment by yasserf** [comment]
Hey! I haven't managed to get to the bottom of this, so instead just replaced uws with ws as a dependency! 😅😁Closing. Thanks!
