### ISSUE TITLE
Nexe v3 with build and patches options appears to break 'Hello World' app

### ISSUE THREAD

**Issue by derek-groupmail** [nexe/nexe#601]
**Is this a BUG or a FEATURE REQUEST?:** 
BUG

**What happened:**
running the app crashes with the following:-

_third_party_main.js:25
    var _a = binary.layout, resourceStart = _a.resourceStart, stat = _a.stat;
                                               ^

TypeError: Cannot read property 'resourceStart' of undefined
    at shimFs (_third_party_main.js:25:48)
    at _third_party_main.js:308:1
    at _third_party_main.js:308:25
    at NativeModule.compile (bootstrap_node.js:635:7)
    at Function.NativeModule.require (bootstrap_node.js:580:18)
    at bootstrap_node.js:155:22
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**What you expected to happen:**
It should just run!

**How to reproduce it (as minimally and precisely as possible):**
Apologies if this issue has been fixed in v3.0.1 or #600 (I'm not sure if #600 is released yet?) but just in case, I'm logging details of my findings here.

I'm using a gulp task to compile a simple 'hello world' application using nexe v3.0.0.beta.16.

The 'Hello World' app looks like this:-

```
var http = require('http');
http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end(`Hello World on ${Date.now()}\n`);
}).listen(1337, '127.0.0.1');
console.log('Server running at http://127.0.0.1:1337/');
```

(I'm using the build and patch options here as a test case because eventually I will want to sign a real app using the same build process.)

The nexe options I'm using in my Gulp Task are pretty much like that in #466 and look like this:-

```
gulp.task('nexe', () => {
  console.log('Building Executable using nexe...');
  nexe.compile({
    make: ['-j4'],
    input: './experiments/example.js',
    output: './experiments/exampleBin',
    build: true,
    temp: './.temp',
    verbose: false,
    target: 'macos',
    patches: [
      (x, next) => {
        x.code = () => [x.shims.join(''), x.input].join(';');
        return next();
      },
      async (compiler, next) => {
        await compiler.setFileContentsAsync(
          'lib/_third_party_main.js',
          compiler.code(),
        );
        compiler.options.empty = true; // <-- ADDED THIS (hack)
        return next();
      },
    ],
  })
  .then(() => {
    console.log('Nexe completed building Executable.');
  });
});
```

Building the App show this:-

```
dek$ gulp nexe
[14:32:50] Requiring external module babel-register
[14:32:52] Using gulpfile ~/git/hypnos/gulpfile.babel.js
[14:32:52] Starting 'nexe'...
Building Executable using nexe...
ℹ nexe 3.0.0
[14:32:52] Finished 'nexe' after 42 ms
✔ Node source extracted to: /Users/derekmcdermott/git/hypnos/.node/8.15.1
✔ Node binary compiled
✔ Entry: 'experiments/example.js' written to: experiments/exampleBin
✔ Finished in 2658.653s
Nexe completed building Executable.
```

Running the compiled executable gives this:-

```
dek$ ./experiments/exampleBin
_third_party_main.js:25
    var _a = binary.layout, resourceStart = _a.resourceStart, stat = _a.stat;
                                               ^

TypeError: Cannot read property 'resourceStart' of undefined
    at shimFs (_third_party_main.js:25:48)
    at _third_party_main.js:308:1
    at _third_party_main.js:308:25
    at NativeModule.compile (bootstrap_node.js:635:7)
    at Function.NativeModule.require (bootstrap_node.js:580:18)
    at bootstrap_node.js:155:22
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
 
dek$ nexe -v
3.0.0-beta.16
```

I was stuck on this for ages, trying various combinations of options to no avail. Obviously just compiling the 'Hello World' example using nexe without the -build and patches worked perfectly well, it's only when you try to customise the build with a patch that the application cannot run.

Finally, I tried uninstalling nexe v3.0.0 and downgraded to nexe v2.0.0.rc.34 and ran the exact same script above (with some minor fixes for Fusebox dependencies) and lo and behold, the 'Hello World' app ran perfectly!

Using nexe v2.0 is probably not a great long-term fix! For example, I'll need Sqlite native module support etc and that's probably better provided in v3+

So, is this a known issue and has it or will it be fixed soon do you know?

Thanks in advance!

**Anything else we need to know?:**
Nope!

**Environment**

- Platform(OS/Version): MacOS (Mojave) 10.14.3
- Host Node Version: Node v8.15.1
- Target Node Version: v8.15.1
- Nexe version: v3.0.0.Beta.16
- Python Version: v2.7.10

**Comment by derek-groupmail** [comment]
Recent Updates:
- Also tried compiling this with the latest nexe v3.0.1 and still get the same error `TypeError: Cannot read property 'resourceStart' of undefined` as shown above.

- Noticed that this is similar to the issue #578 but note that my 'Hello World' app is not signed and I'm still getting this issue, so signing is not the issue. (Though I do intend to use a similar script to sign my real app.)

- When I actually do try to sign the resulting binary, it can't be signed and I get the usual error `main executable failed strict validation`.

Thanks!

**Comment by calebboyd** [comment]
Here is a hello world example

```
require('nexe').compile({
  mangle: false,
  patches: [
    (compiler, next) => {
      return compiler.setFileContentsAsync(
        'lib/_third_party_main.js',
        `console.log('hello world')`
      ).then(next)
    },
  ],
})
```

**Comment by calebboyd** [comment]
Let me know if you have issues!
