### ISSUE TITLE
JS Code Obfuscation

### ISSUE THREAD

**Issue by tbhaxor** [nexe/nexe#603]
**Is this a BUG or a FEATURE REQUEST?:** 
FEATURE REQUEST

**What happened:**
Nexe compiled applications expose source code

**What you expected to happen:**
It should obfuscate the code

**How to reproduce it (as minimally and precisely as possible):**
Compile any 

**Anything else we need to know?:**
Yes, for obfuscation you can use either one of the 
1. http://www.jsfuck.com/
2. https://obfuscator.io/ 

JS Fuck is recommended as it has its [github](https://github.com/aemkei/jsfuck/blob/master/jsfuck.js) repo

**Environment**

- Platform(OS/Version):
- Host Node Version: `any`
- Target Node Version: `any`
- Nexe version: `any`
- Python Version: `any`

**Comment by calebboyd** [comment]
This isn't in scope of the project goals but, you can provide nexe with obfuscated bundle ahead of time, or just write a plugin to use the tool you want

```JavaScript
const { compile } = require("nexe")
const mangle = require('./obfuscation')
const { map } = require('bluebird')

function shouldMangleFile(filename) {
   return ...
}

nexe.compile({
  plugins: [
    async function (compiler, next) {
      const bundle = compiler.bundle
      await map(Object.keys(bundle.index), async (x) => {
        const absPath = path.resolve(bundle.cwd, x)
        if (shouldMangleFile(absPath)) {
          await bundle.addResource(absPath, await mangle(await readFile(absPath)))
        }
      }, { concurrency: 10 })
      return next()
    }
  ]
})
```

You won't obfuscate filenames this way though. So your best bet it so use a bundle that is obfuscated.
