### ISSUE TITLE
Is there a way to execute bundled Node.js CLI scripts?

### ISSUE THREAD

**Issue by aral** [nexe/nexe#605]
There are various issues related to executing bundled executables where the suggested solution appears to be to extract the executable to the host filesystem and run it there.

My question is: Is there a way to execute bundled node.js script binaries?

__Use case:__ I need to run [pm2](https://github.com/Unitech/pm2)’s _pm2_ binary to make use of the `startup` and `monitor` functionality. e.g., 

```js
  // Launch pm2 monit.
  const options = {
    env: process.env,
    stdio: 'inherit'  // Display output.
  }

  try {
    childProcess.execSync(`sudo ${pm2Path} monit`, options)
  } catch (error) {
    console.log(`\n 👿 Failed to launch the process monitor.\n`)
    process.exit(1)
  }
  process.exit(0)
```

This fails with `node_modules/pm2/bin/pm2` not being found. That file is a Javascript binary:

```javascript
#!/usr/bin/env node
'use strict';

var semver = require('semver');

if (semver.satisfies(process.versions.node, '>= 6.0.0'))
  require('v8-compile-cache');

process.env.PM2_USAGE = 'CLI';
// etc.
```

So if I extract and run it, I would assume it would require Node to be installed (?)

Is there a way I can run this directly without extracting it? Or can such functionality be added?

Thanks in advance + thank you for Nexe; it’s excellent :)

**Comment by calebboyd** [comment]
Nexe works with [child_process.fork](https://nodejs.org/dist/latest-v10.x/docs/api/child_process.html#child_process_child_process_fork_modulepath_args_options) So something like this should do the trick.
```
require('pm2')
require('child_process').fork(require.resolve('pm2/bin/pm2'), ['monit'], { stdio: 'inherit' })
```

**Comment by aral** [comment]
Thanks, Caleb. I did try `fork()` but then I get a `Error: setRawMode EIO` with pm2.

I’m now trying to copy the whole of the `node_modules` folder out to the external file system but my problem now seems to be that __dirname isn’t resolving properly so I cannot find the node_modules directory (which I added as an asset) to copy it.

__dirname (and everything else I‘ve tried) keeps giving me the path of the folder I’m calling the main executable from. Similarly, `require.resolve('pm2/bin/pm2')` resolves to the path of the folder I’m in (e.g., `~/test` when I run the main executable (which is located in `/usr/local/bin/main-executable`) so it resolves to (e.g.) `~/test/node_modules/pm2/bin/pm2`.

**Comment by calebboyd** [comment]
Hmm Yeah. I think this has been brought up before but didn't see the issue clearly until now. The VFS is loaded relative the the cwd instead of relative to the execPath.

**Comment by calebboyd** [comment]
Fixed in https://github.com/nexe/nexe/commit/c9c9b5a0a31c7ebe6ed4195fecff36b78be8b328

**Comment by aral** [comment]
Hey Caleb,

Thanks for the fix for the path issue but I just realised that the path issue was a red herring.

The core issue is that `fs.copyFile` and `fs.copyFileSync` don’t work inside of Nexe binaries for bundled resources. (`fs.readFileSync` _does_ work.)

I will open a separate issue for that.

**Comment by aral** [comment]
Just a quick update: I finally got my app working. A quick overview of how in case it helps anyone else:

1. Zip up the whole app (excluding the .git folder) into my-app.zip
2. Include my-app.zip as a resource using nexe.
3. On first-run, use `fs.readFileSync()` and `fs.writeFileSync()` to copy the app’s source code (my-app.zip) to an external directory (e.g., ~/.my-app)
4. Launch PM2 from that external directory and make it launch the daemon from that directory also.

Related: #607

**Comment by calebboyd** [comment]
If you're going this route, there are options for that!

Something like:
`nexe bootstrap.js -r app-deps.zip`.
If bootstrap depends on your application code you can use `--no-bundle` to prevent analysis (and inclusion) of its dependencies.
