### ISSUE TITLE
fs.copyFileSync does not work for resources bundled in binaries

### ISSUE THREAD

**Issue by aral** [nexe/nexe#607]
## To recreate

1. Create a bundle and add a resource (e.g., 'my-file')
2. In the binary, try to read and/or copy the resource to the external file system

## What should happen

`fs.readFileSync` and `fs.copyFileSync` should both work.

## What actually happens

Only `fs.readFileSync` works.

## Example 

This works:

```js
const myFile = path.join(__dirname, 'my-file')
const contents = fs.readFileSync(myFile)
```

This doesn’t work:

```js
const myFile = path.join(__dirname, 'my-file')
fs.copyFileSync(myFile, someExternalDirectory)
```

Note: This issue follows on from #605

**Comment by TemaSM** [comment]
Confirming. Cannot `fs.copyFileSync` from included file as resource in nexe onto real file system

**Comment by aral** [comment]
Also wondering if the main issue IU had with #605 was that `execSync()` similarly doesn’t work? @calebboyd mentioned that `require('child_process').fork()` does work so perhaps per-command support has to be added? I plan to take a look at the Nexe source when I get a moment in hopes that maybe I can help with this so that including/extracting the full source isn’t necessary to carry out an execSync on an internal Node CLI command.

**Comment by calebboyd** [comment]
copyFileSync is not implemented in the [file system patch](https://github.com/nexe/nexe/blob/master/src/fs/patch.ts#L137) PRs welcome!

**Comment by calebboyd** [comment]
https://github.com/nexe/nexe/commit/75bf6a3dc4bf242a2dd9198617ded07ff76f39b6

**Comment by paulocoghi** [comment]
After the commit https://github.com/nexe/nexe/commit/75bf6a3dc4bf242a2dd9198617ded07ff76f39b6 from @calebboyd, only `fs.copyFileSync()` will be available or `fs.copyFile()` as well?

**Comment by TemaSM** [comment]
@paulocoghi, @calebboyd tested both these functions in production from [current master branch](https://github.com/nexe/nexe/tree/a6ad034336a3af68c01cb78166e089e026b69c1e), works fine as expected 👍

**Comment by paulocoghi** [comment]
I will temporarily use a local build. Thanks everyone for the update! I believe this issue can be closed.

And, if you want, I can publish to **npm** if you authorize my user (paulocoghi).

**Comment by calebboyd** [comment]
https://github.com/nexe/nexe/releases/tag/v3.2.0
