### ISSUE TITLE
spawn C:\Windows\system32\cmd.exe ENOENT

### ISSUE THREAD

**Issue by Sovgut** [nexe/nexe#608]
**Is this a BUG or a FEATURE REQUEST?:** 
BUG

**What happened:**
```
[Nest] 11360   - 2019-04-11 10:45   [ExceptionsHandler] spawn C:\Windows\system32\cmd.exe ENOENT +1368ms
Error: spawn C:\Windows\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

**What you expected to happen:**
That the project will work in any directory without running ```npm i```

**How to reproduce it (as minimally and precisely as possible):**
Just move .exe from project directory and run

**Anything else we need to know?:**
I use NestJS, but I'm sure that such a problem will happen without it

**Environment**

- Platform(OS/Version): Windows 10 x64 
- Host Node Version: v11
- Target Node Version: v11
- Nexe version: 3.1.0
- Python Version: 2.7

**Nexe config**
```
const { compile } = require('nexe');
const path = require('path');

const config = {
  input: path.join(__dirname, 'dist', 'main.js'),
  build: true,
  name: 'service',
};

const success = () => console.log('Success');
const error = error => console.error(error);

compile(config)
  .then(success)
  .catch(error);
```

**Comment by Sovgut** [comment]
I found the dependency of this error, if I move the ```package.json``` file together with the ```.exe``` file and execute ```npm i```, everything will work ...

This means that ```.exe``` cannot work without ```node_modules``` libraries.
Such an approach in my project is not suitable as the application will work where there is ***no Internet*** ...

**Comment by Sovgut** [comment]
How can I solve this?

**Comment by calebboyd** [comment]
What if you include the package.json file with your binary? `-r package.json`

**Comment by Sovgut** [comment]
But even so, why can't it run ```cmd.exe```?
This file exists along this path and works great.
![image](https://user-images.githubusercontent.com/26426861/56020015-c8b8f280-5d0e-11e9-920b-43b5a23968c7.png)


What information should I give you?

**Comment by calebboyd** [comment]
I did the following without issue...
```
npx nest new nest-test
cd nest-test && npm run prestart:prod
npx nexe dist/main.js -o service
./service.exe
```
- open http://localhost:3000 -- see Hello World
- stop server.
```
mv service.exe ~/Desktop/service.exe
cd ~/Desktop
./service.exe
```
- open http://localhost:3000 -- see Hello World
no errors...

My guess is still the same. That you have a dependency, or your own code, using `child_process.exec` on a file that doesn't exist.

**Comment by Sovgut** [comment]
@calebboyd Thank you, I think this [screenshot-desktop](https://www.npmjs.com/package/screenshot-desktop) ... But for some reason he can not run ```cmd.exe```? If he is on the path in which he can not run it.

**Comment by Sovgut** [comment]
> I think this screenshot-desktop...
Yes, this is it!

**Comment by Sovgut** [comment]
@calebboyd If you can help with the screenshot-desktop solution, I would be grateful, otherwise you can close this Issue.

**Comment by calebboyd** [comment]
screenshot-desktop executes a batch file. Just ensure that batch file exists.

```
myapp
  node_modules
    screenshot-desktop
      lib
        win32
          screenCapture_1.3.2.bat
```

**Comment by anmol1432** [comment]
C:\Users\hp\Contacts\Desktop\reacct leaning\first-todo-app>npx create-react-app first-app
'CALL "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (x86)\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.
spawn C:\Windows\system32;c:\python3.8 ENOENT

**Comment by anmol1432** [comment]
can some one help me

**Comment by liuchengts** [comment]
Hi, I'm having the same problem with screenshot-desktop, is there a solution?

**Comment by liuchengts** [comment]
I solved the problem by following https://github.com/bencevans/screenshot-desktop/pull/225
