### ISSUE TITLE
nexe with node 11.4.0 and upx brute on node executable fails in alpine docker

### ISSUE THREAD

**Issue by StevenACoffman** [nexe/nexe#610]
Thank you for a wonderful tool, and for your help in other issues.

**Is this a BUG or a FEATURE REQUEST?:** 

Possibly a bug, but also just maybe this is an FYI.

**What happened:**
Dockerfile:
```
FROM node:11.14.0-alpine as builder

RUN sed -i -e 's/v[[:digit:]]\.[[:digit:]]/edge/g' /etc/apk/repositories &&\
  apk update && apk upgrade &&\
  apk --update add\
  bash \
        libstdc++ \
        binutils-gold \
        curl \
        g++ \
        gcc \
        gnupg \
        libgcc \
        linux-headers \
        make \
        python \
        upx \
        bash
WORKDIR /fake
RUN echo "console.log('hello world')" \
    >> index.js && \
  echo "{\"main\": \"index.js\", \"scripts\": { \"pack\": \"rm -rf dist && nexe --build --logLevel verbose --output dist/app\"}}" \
    >> package.json
RUN npm install nexe -g
RUN rm -rf dist && nexe --build -c="--fully-static, --without-npm" --logLevel verbose --output dist/app
RUN echo done
RUN ls -la /root/.nexe/
RUN ls -la /root/.nexe/11.14.0/out/Release/node
RUN upx --brute /root/.nexe/11.14.0/out/Release/node

RUN nexe --build -c="--fully-static" --logLevel verbose --output dist/app /app/index.js
RUN ls -la /root/.nexe/

RUN chmod a+x /fake/dist/app
RUN ls -la /fake
RUN ls -la /fake/dist/app

FROM alpine:3.9
#  libstdc++
RUN apk add --update --no-cache ca-certificates

WORKDIR /fake/dist
COPY --from=builder /fake/dist/app ./

CMD ["/fake/dist/app"]
```
When I run the docker image, no output returns, and the exit code is 127.
If I comment out upx, things execute normally.
If I change the upx line above to:
```
RUN upx --overlay=copy --strip-relocs=0 --compress-exports=0 --compress-icons=0 --compress-resources=0 --no-align /root/.nexe/11.14.0/out/Release/node
```
Things execute normally (and upx reports File size 45281624 ->  16146320   or 35.66%), and the docker image is executable, printing "Hello World"

I believe the upx defaults are `--overlay=copy --strip-relocs=1 --compress-exports=1 --compress-icons=2`

`--brute` adds M_LZMA compression, and I'm not sure if it otherwise affects the defaults.
I'm not sure which of the upx non-default options is strictly necessary, but thought I'd pass on what I learned here for others.

**What you expected to happen:**
"hello world"
**How to reproduce it (as minimally and precisely as possible):**

**Anything else we need to know?:**

**Environment**
- Platform(OS/Version):
  - alpine linux 3.9 (in container)
  - docker 18.09.2
  - macOs 10.14.3
- Host Node Version:
  - 11.14.0
- Target Node Version:
  - 11.14.0
- Nexe version:
  - 3.1.0 
- Python Version:
  - python2 (2.7.15-r3)

**Comment by StevenACoffman** [comment]
This also works:
```
RUN upx --overlay=copy --lzma /root/.nexe/11.14.0/out/Release/node
```
It should provide similar results to `--brute` (45281624 ->  11733664  or  25.91%).

**Comment by StevenACoffman** [comment]
This also works:
```
RUN upx /root/.nexe/11.14.0/out/Release/node
```
But the results are less impressive (45281624 ->  16146320  or 35.66%).
So I conclude that brute does more than just adding lzma and that breaks things for nexe.

**Comment by calebboyd** [comment]
running `docker build .` with the following produced a final layer that logged `hello world`

Relevant sizes: `38.9M` -> `10.0M`
```Dockerfile
FROM node:10.15.3-alpine
WORKDIR /app
RUN npm i nexe -g
RUN echo "console.log('hello world')" \
    >> index.js
RUN nexe --no-mangle --temp ./temp -t alpine -o out
RUN ls -lh temp
RUN apk add upx && upx --brute ./out
RUN mv out temp/alpine-x64-10.15.3
RUN ls -lh temp
RUN nexe --temp ./temp -t alpine -o out
RUN ./out
```

Cheers!

Also, since this doesn't appear to be an issue with nexe I'm going to close it!
