### ISSUE TITLE
nexe and windows service

### ISSUE THREAD

**Issue by Sovgut** [nexe/nexe#612]
Is it possible to integrate this manifest? Or install Windows Service without this manifest?

**Is this a BUG or a FEATURE REQUEST?:** 
FEATURE REQUEST

**What happened:**
```
An exception occurred while initializing the installation:
System.BadImageFormatException: Failed to load the file or assembly "path/to/file.exe" or one of their dependencies. It was expected that the module contains an assembly manifest ..
```
**What you expected to happen:**
Installed Windows Service using ```InstallUtil``` from ```.NET v4```

**How to reproduce it (as minimally and precisely as possible):**
Just run in cmd:
```
$ cd C:\Windows\Microsoft.NET\Framework\v4.0.30319 
$ .\InstallUtil.exe path/to/file.exe
```

**Anything else we need to know?:**
Make coffee 😃☕

**Environment**

- Platform(OS/Version): Windows 10 x64
- Host Node Version: v11
- Target Node Version: v11
- Nexe version: 3.1.0
- Python Version: 2.7

**Comment by Sovgut** [comment]
Alternatively, you can use [NSSM](https://nssm.cc/), I suggest extending the functionality for compiling js into a compatible file for installation using .NET

**Comment by calebboyd** [comment]
I suggest you use something like NSSM or [WinSW](https://github.com/kohsuke/winsw)
