### ISSUE TITLE
Failing CI

### ISSUE THREAD

**Issue by DanielRuf** [nexe/nexe#614]
https://ci.appveyor.com/project/calebboyd/nexe/builds/23955222

Not sure why Travis CI is not used anymore as they have also Windows support now.
Reference: https://github.com/nexe/nexe/issues/583

**Comment by calebboyd** [comment]
Updated the badge!

**Comment by DanielRuf** [comment]
I did not mean the readme. See the checks on every commit and push.

**Comment by DanielRuf** [comment]
![Screenshot_20190423-233200](https://user-images.githubusercontent.com/827205/56617420-1d6a4080-6620-11e9-965a-0ed7eefa1427.jpg)

**Comment by DanielRuf** [comment]
https://github.com/nexe/nexe/pull/615 at the bottom.

**Comment by calebboyd** [comment]
Appveyor, TravisCI and CircleCI are no longer used.
