### ISSUE TITLE
Executable creation fails on gitlab runner

### ISSUE THREAD

**Issue by defusioner** [nexe/nexe#617]
**Is this a BUG or a FEATURE REQUEST?:** 
- [x] Bug

**What happened:**
When generating an executable with such mechanism as gitlab runner, the process falls to the background (i think the part that checks the existence of the node runner) so the runner won't wait the generation to be finished:

![image](https://user-images.githubusercontent.com/7025961/56888039-5ddc1b00-6a73-11e9-9a06-35a1069d1004.png)

In desktop, Nexe will first try to check if there is an existing runner, then download it, then generate the executable with ~3 additional info lines.

**What you expected to happen:**
The runner should wait for the script to be finished; executable should be generated as on desktop version

**How to reproduce it (as minimally and precisely as possible):**
Create a small nodejs project and generate its executable with gitlab runner.

**Environment**

- Platform(OS/Version): Gitlab default runner (I don't know actually, sorry)
- Host Node Version: 10.15.3
- Target Node Version: linux-armv6
- Nexe version: 3.1.0
- Python Version: ?

**Comment by calebboyd** [comment]
Fixed!

a fresh install should yield 

`npm ls resolve-dependences`

```
`-- nexe@3.2.0
  `-- resolve-dependencies@2.2.3
```
