### ISSUE TITLE
big file

### ISSUE THREAD

**Issue by Wqrld** [nexe/nexe#621]
Hello, what is a normal file size for a nexe .exe? I'm compiling a simple program with one dependency and it takes 30 seconds to build a 150MB executable

Is this normal or is it a issue with my setup

**Comment by Wqrld** [comment]
a hello world program only gives around 23 MB which i can understand if you need to package the node binary

**Comment by Wqrld** [comment]
code used:
```
const client = require('discord-rich-presence')('52594396690074112');

client.updatePresence({
  state: 'Contact me',
  details: 'System Administration',
  startTimestamp: Date.now(),
  endTimestamp: Date.now() + 9999999,
  largeImageKey: 'wq2',
  smallImageKey: 'wq2',
  partyId: "312312312",
  partySize: 1,
  partyMax: 1338,
  joinSecret: "32131212312",
  spectateSecret: "dsasadsad",
  matchSecret: "32123123123123",
  instance: true,
});
console.log("Init")
```

**Comment by calebboyd** [comment]
Hmm Odd. On the mac I get

your code (w/dependency)
39921166 bytes

hello-world
39592206 bytes

**Comment by Wqrld** [comment]
That's more like how it should be, can anyone reproduce on win10?

**Comment by calebboyd** [comment]
Same result on W10 17134.829 (stays right around 23-24)

**Comment by Wqrld** [comment]
Still happening on win10 with the latest nexe and nodejs 8.9.1
went over to using electron since i made this issue but it'd help if anyone can reproduce this

**Comment by marcj** [comment]
nexe 3.2.0 produces for me (macOs 10.14.5) with node 12 with 11mb node_modules and main.js of 800kb a binary of whopping size of 123MB. The whole folder I want to package is 12MB. I mean, placing the node binary next to my source code is significant less. Anything broken lately? Seems like it includes unnecessary stuff and stuff twice.

**Comment by marcj** [comment]
Oh, wow I found it. You need to make sure that the folder you want to build using `nexe` is not inside another npm package, because it searches up all node_modules of parent folders and includes them. My build script for example created a new `build` folder inside the current project (which has a package.json and thus node_modules folder) and nexe was using node_modules from the build folder and its parent folder.

**Comment by Wqrld** [comment]
Could be the same issue for me as i have the program in another folder that contains some other code probably with a node_modules

**Comment by calebboyd** [comment]
@marcj Are you able to make a minimal reproduction for this?

**Comment by marcj** [comment]
@calebboyd no worries, I got it fixed. Do you want to have a reproduction nonetheless?

**Comment by calebboyd** [comment]
@marcj 	That would be super helpful!

**Comment by jasir** [comment]
I have the same issue with latest version. 56MB vs 24MB when building without node_modules in parent folder.

**Comment by liudonghua123** [comment]
I write a simple Hello world program which log hello world, it almost produce 28M executable program. Can we reduce or shrink or compress it.

```
D:\test\hello>cat index.js
console.info("hello");

D:\test\hello>dir
 Volume in drive D is Data
 Volume Serial Number is 08F2-7D08

 Directory of D:\test\hello

2020-02-18  11:28    <DIR>          .
2020-02-18  11:28    <DIR>          ..
2020-02-18  11:28                23 index.js
               1 File(s)             23 bytes
               2 Dir(s)  19,464,675,328 bytes free

D:\test\hello>nexe index.js
i nexe 3.3.2
√ Already downloaded...
√ Compiling result
√ Entry: 'index.js' written to: hello.exe
√ Finished in 2.046s

D:\test\hello>dir
 Volume in drive D is Data
 Volume Serial Number is 08F2-7D08

 Directory of D:\test\hello

2020-02-18  11:29    <DIR>          .
2020-02-18  11:29    <DIR>          ..
2020-02-18  11:29        28,818,840 hello.exe
2020-02-18  11:28                23 index.js
               2 File(s)     28,818,863 bytes
               2 Dir(s)  19,417,882,624 bytes free

D:\test\hello>
```

The installer of nodejs on Windows is no more than 20M.
```
D:\test\hello>curl -I https://nodejs.org/dist/v12.16.0/node-v12.16.0-x64.msi
HTTP/1.1 200 OK
Date: Tue, 18 Feb 2020 03:32:34 GMT
Content-Type: application/octet-stream
Content-Length: 19673088
Connection: keep-alive
Set-Cookie: __cfduid=da0bb3ef627085c017856a7755e74cd8e1581996754; expires=Thu, 19-Mar-20 03:32:34 GMT; path=/; domain=.nodejs.org; HttpOnly; SameSite=Lax
Last-Modified: Tue, 11 Feb 2020 15:36:41 GMT
ETag: "5e42ca09-12c3000"
Cache-Control: max-age=14400
CF-Cache-Status: HIT
Age: 67
Accept-Ranges: bytes
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 566cef456c60d1cf-HKG


D:\test\hello>
```

**Comment by calebboyd** [comment]
28mb is normal. You can use upx if you want to shrink your base executable before using nexe
https://github.com/nexe/nexe/issues/523#issuecomment-421837401
