### ISSUE TITLE
Is a good practive to use webpack with nexe?

### ISSUE THREAD

**Issue by ricardopolo** [nexe/nexe#622]
We build with `nexe` and works like a charm! Thanks for this great project!!!

Do you think implementing `webpack` for our project would make any advantage? Or if a project is going to be compiled with `nexe` using `webpack` would not give any advantage (performance, build size, protect source code, etc.)?

Thanks!!

**Comment by marcj** [comment]
webpack gives always an advantage as you can fine tune the compilation. nexe does not optimize code, but webpack could. If your build using webpack produces smaller .js file (maybe one big one) then nexe has less to bundle and the app starts faster in general.

**Comment by ricardopolo** [comment]
@marcj thanks.
Nexe hides my code so users cant reverse engineer it? Or for that purpose webpack helps?

**Comment by calebboyd** [comment]
All the normal advantages to bundling apply when using webpack (or any bundler) with nexe. 

Code obfuscation/security is not a goal of this project.
