### ISSUE TITLE
Support packaging with start command?

### ISSUE THREAD

**Issue by KarlChow92** [nexe/nexe#623]
Hey, 

I have an API that runs with a command and not an entry point. The entry point is actually in the dependency that I use. So to start the application I just have to do `npm run start` or `npm run dev`. Do you guys support this? Or is an entry point needed?

**Comment by radharajendran** [comment]
I have a task runs with command from package.json. How to run commands from nexe generated binary ?

**Comment by calebboyd** [comment]
@KarlChow92 Start commands can use other binaries. If you don't have a javascript application (run with node) then this probably isn't the project you're looking for. 
If you do you should provide more information.

@radharajendran create a minimal reproduction in a new issue.

**Comment by calebboyd** [comment]
I don't think parsing arbitrary bash commands for npm scripts will be added to this tool. If you think otherwise I'd be willing to review a PR. But I think it would add a lot of unnecessary complexity
