### ISSUE TITLE
Error downloading prebuilt binary: RequestError: connect ETIMEDOUT 203.208.39.104:443

### ISSUE THREAD

**Issue by GonyMaster** [nexe/nexe#624]
![image](https://user-images.githubusercontent.com/14261751/57998309-7c2db780-7b03-11e9-8620-a8d5742dbe1e.png)

**Comment by calebboyd** [comment]
What release?

**Comment by GonyMaster** [comment]
> What version/release of node?

my node version is v10.15.3

**Comment by calebboyd** [comment]
Can you download this normally?
https://github.com/nexe/nexe/releases/download/v3.0.0/windows-x64-10.15.3

**Comment by meteorsnows** [comment]
@calebboyd How to we use it? Like this...assume i have very simple my-app file...

```
const { compile } = require('nexe')

compile({
  input: './my-app.js',
  asset: './windows-x64-10.15.3'

```

asset: string
Provide a pre-built nexe binary asset, this can either be an http or https URL or a file path.

**Comment by calebboyd** [comment]
Thats correct!

There was mapping mistake with the alias `-a` if you were using the CLI but `--asset` would work.
