### ISSUE TITLE
Wrong path separators at Linux/Mac binaries  generated on Windows

### ISSUE THREAD

**Issue by jackens** [nexe/nexe#626]
**Is this a BUG or a FEATURE REQUEST?:** bug

**What happened:**

Building binaries for Linux/Mac on Windows is buggy.

Executing belowe script on Windows

```bash
DISTS='windows linux mac'
for DIST in $DISTS
do
  if [ "$DIST" = windows ]
  then
    OUPTUT=server.exe
  else
    OUPTUT=server
  fi
  nexe server.js -t "$DIST-x64-12.0.0" -o "dist/$DIST/$OUPTUT" \
    --verbose \
    -r 'client/**/*' \
    -r 'node_modules/leaflet/dist/**/*' \
    -r 'node_modules/eva-icons/style/**/*'
done
```

generates invalid `dist/linux/server` and `dist/mac/server` files.
They are invalid because of wrong path separators.

For example, opening file `dist/linux/server` with hex editor we can found something like below:

```
"./node_modules\\leaflet\\dist\\images\\marker-shadow.png":[342449,618],"
```

Running above script on Linux produces valid files `dist/windows/server`, `dist/linux/server` and `dist/mac/server`, however in `dist/windows/server` we can found something like below:

```
"./node_modules/leaflet/dist/images/marker-shadow.png":[339724,618],
```

which runs, but perhaps there should be `\\` instead of `/`.

**What you expected to happen:** valid `dist/linux/server` and `dist/mac/server` files generated on Windows.

**How to reproduce it (as minimally and precisely as possible):** See above.

**Anything else we need to know?:** No.

**Environment**

- Platform(OS/Version): Windows 10 x64/Ubuntu on WSL
- Host Node Version: v12.3.1 (both: Windows and Linux)
- Target Node Version: windows-x64-12.0.0/linux-x64-12.0.0/mac-x64-12.0.0
- Nexe version: 3.2.0 (both: Windows and Linux)
- Python Version: —

**Comment by calebboyd** [comment]
Everything you've described is by design is this causing an issue in your application? 

Specifically, all the keys in that index object you're inspecting are passed through normalization at runtime.

https://github.com/nexe/nexe/blob/a0c8d31f037cea863e8dfe0ccea992cf8f26df9a/src/fs/patch.ts#L103-L105

**Comment by jackens** [comment]
@calebboyd You are right! `nexe` version on Windows was 3.0.0-beta.15 not 3.2.0 as I wrote. Sorry for wasting You time.

PS. `nexe` is great tool!

**Comment by calebboyd** [comment]
You can just use `OUTPUT=server` here, it'll add `.exe` for the windows version.

```
  if [ "$DIST" = windows ]
  then
    OUPTUT=server.exe
  else
    OUPTUT=server
  fi
```
