### ISSUE TITLE
How can I use nexe with this next js boiler plate

### ISSUE THREAD

**Issue by ShintaroNippon** [nexe/nexe#627]
HI there, first of all, thanks by the package, it works on my api.
But if I may I wanna do it in a boilerplate next js
https://github.com/MustansirZia/next-express-bootstrap-boilerplate
I ran
nexe app.js

./true
and in console it stays like this
> Using "webpackDevMiddleware" config function defined in next.config.js.
[ event ] build page: /
[ wait ]  compiling ...

can you help please?

E have removed the babelrc

Thanks in advance
Carlos Vieira

**Comment by jaredallard** [comment]
Hi, there's not much to go off of here. Please provide more information and I suggest you use our issue format in the future.

https://github.com/nexe/nexe/blob/master/issue_template.md
