### ISSUE TITLE
Start .executable in Windows and no showing the CMD

### ISSUE THREAD

**Issue by meteorsnows** [nexe/nexe#631]
I am using following:
`  asset: './windows-x64-10.15.3'`

Want to compile Node.js runtime and Native Tray (https://www.npmjs.com/package/not-the-systray), I am trying to see if could use existing build tools to build desktop framework using CPP or node.js binding. 
See how far it can go...

So I just want to deploy a tray icon ,with node.js capabilities for now, anyway to do this. Simpler example possible add UI Framework like vuido etc , if open a panel is needed.

**Comment by calebboyd** [comment]
An opinion about a UI Framework to use with this is out of scope for this project.

If you launch the process with a service account you can avoid showing the command prompt. 

See nssm or winsw

**Comment by meteorsnows** [comment]
Thanks for info. No knew so much about Windows Mechanism too.
