### ISSUE TITLE
Support for CentOS

### ISSUE THREAD

**Issue by Thiltal** [nexe/nexe#632]
Please add support for CentOS. There are some issues in core libs in package for linux.

**Comment by calebboyd** [comment]
use `-t static`

**Comment by Thiltal** [comment]
I've tried with these errors on app run:

/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by app)
 /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by app)
/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by app)

**Comment by victor0801x** [comment]
you can use `--build` build from source. it will take a long time first build.

**Comment by aral** [comment]
@Thiltal Do you mean you’ve tried with `-t static` and you’re still seeing this error? (I just ran across it too.)

@victor0801x Is the issue that the Nexe Node builds are not built with static libraries?

**Comment by victor0801x** [comment]
@aral I think so, centos 7 using `glibc 2.17` & `libstdc++ 4.8.5` (~3.4.19)
strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX

**Comment by Thiltal** [comment]
@aral sorry I don't remember, but I've spent few hours on research without result so I gues I've tried.

**Comment by brianandrus** [comment]
I tried doing --static, but it throws an error:
Error: https://github.com/nexe/nexe/releases/download/v3.0.0/alpine-x64-10.17.0 is not available, create it using the --build flag

And, indeed, there is no such file in the downloads.

**Comment by Abdulaziz1988** [comment]
is there any update on this?
