### ISSUE TITLE
Node 10.16 support?

### ISSUE THREAD

**Issue by nfrasser** [nexe/nexe#633]
**Is this a BUG or a FEATURE REQUEST?:** BUG

**What happened:** Our build system is set up to create a nexe binary with the latest LTS version of Node, which is 10.16.0 at the time of this writing. When I try to this on Linux or macOS, I get this error:

```
ℹ nexe 3.2.1
✔ Downloading pre-built Node.js
✔ Finished in 2.297s

Error: https://github.com/nexe/nexe/releases/download/v3.0.0/mac-x64-10.16.0 is not available, create it using the --build flag

See nexe -h for usage..
```

**What you expected to happen:**
The binary builds with Node 10.16

**How to reproduce it (as minimally and precisely as possible):**

In the command line, install the latest nexe and run
```
nexe -t darwin-10.16.0 index.js
```

**Anything else we need to know?:**

**Environment**

- Platform(OS/Version): macOS/10.14.5
- Host Node Version: 10.16.0
- Target Node Version: 10.16.0
- Nexe version: 3.2.1
- Python Version: 2.7.10

**Comment by nfrasser** [comment]
If you guys accept binaries from random strangers on the internet, I'm happy to build the latest Node versions locally with `--build` and share them here so you add them as attachments to the `v3.0.0` release!

**Comment by calebboyd** [comment]
It looks like the build is broken. I haven't had time to look at why. (Likely the toolchain on the build system or something similar.

I'd accept a PR that fixes it (but no random binaries sorry 😂)
https://dev.azure.com/nexe-ci/Nexe/_build/results?buildId=125

**Comment by calebboyd** [comment]
These will populate soon. The environment variable contents change.... 😑 azurepipelines...

**Comment by asamuzaK** [comment]
@calebboyd 
No 10.16.0 binaries other than mac yet.
Also, it seems that 10.15.3 binaries are lost?

**Comment by poelstra** [comment]
@asamuzaK I'm having the same issue: we didn't change anything in the code, but our builds starting failing complaining that 10.15.3 binaries aren't available.

They still work fine on my local machine, probably because they are still cached there.

**Comment by poelstra** [comment]
> Also, it seems that 10.15.3 binaries are lost?

Created https://github.com/nexe/nexe/issues/647 for that.
