### ISSUE TITLE
Using nexe to bundle vuejs

### ISSUE THREAD

**Issue by Gaalee** [nexe/nexe#634]
Hi, I'm using nexe to bundle my nodejs server side. It works like a charm.
I use vuejs (CLI+Webpack) for the client side, is it possible to bundle it to an executable as well ? 

If so, how should i do it ?

**Comment by calebboyd** [comment]
I don't know, What did you try?

**Comment by tbhaxor** [comment]
@calebboyd I have explained this in #731
