### ISSUE TITLE
ECONNRESET in fetching nodejs binaries

### ISSUE THREAD

**Issue by alexroat** [nexe/nexe#636]
I'm trying to compile a project with nexe and get this error:

$ nexe app.js

Error: Error downloading prebuilt binary: RequestError: tunneling socket could not be established, cause=read ECONNRESET

I've tryes also to install nexe as dependency and run with cat app.js | node ./node_modeules/nexe/index.js , but the problem remains.

I'm using a CNTLM running on localhost:3128 (without any credential) for preauth to a enterprise proxy.

environmental variable are set to "http://localhost:3128" correctly (both hi and low case http and http_proxy)

I suppose the problem is in the download module ... I see the paramater opts.proxy is not passwed, however also forcing through a direct assignment it does not work.

I could be very useful to have this tool working behind a proxy using ENV variables, cause many companies are using a proxy (and the typical configuration is CNTLM for the development).

Could you fix it or suggest a workaround ?

**Comment by calebboyd** [comment]
Hmm I don't have access or anyway to debug or try this. If you want to try and use `download` and `caw` to handle the web request and potentially provide a PR that would be helpful.

**Comment by calebboyd** [comment]
As a workaround you can aquire an asset from github releases and provide it with `-a`

**Comment by Aymkdn** [comment]
Solution:
1. Go to https://nodejs.org/dist/ and search for the version of Node you want (e.g. v14.16.0)
2. Open the folder and download the `.tar.gz` version (e.g. https://nodejs.org/dist/v14.16.0/node-v14.16.0.tar.gz)
3. Create a folder in your project called `download` and move the downloaded file there
4. Start `nexe ---temp "./download/" --asset "./download/node-v14.16.0.tar.gz" --target "win32-x64-14.16.0"`

**Comment by henjoe** [comment]
Hi, I have the same issue, but I don't see windows-x64-18.0 on the releases. How can I compile my nodejs app since it runs on the version 18 of nodejs?
