### ISSUE TITLE
Can't bundle inside electron app

### ISSUE THREAD

**Issue by oonqt** [nexe/nexe#637]
**BUG** 

**When I try to package a JavaScript file from within an electron app, the executable is created, however it is not compiled correctly and immediately exits as soon as I open it**

**Expected: The packaged app to actually run**

**How to reproduce it (as minimally and precisely as possible):**

**Using electron 5.0.2, i believe the issue may possibly be that nexe doesn't work with Node.js v12, can someone confirm if this is/isn't the case? If not, then can I expect a patch to get nexe to work with electron**

- Windows 10 May 2019 Update
- node: 12.0.0(used by electron):
- Nexe version: 3.2.1
- Python Version: 2.7.16

**Comment by tumeden** [comment]
I ran into this same issue unfortunately...   Working on an application and using electron to display a GUI,  however it immediately closes when using nexe.  It will run the backend stuff fine with electron disabled.
