### ISSUE TITLE
Travis No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

### ISSUE THREAD

**Issue by pascalandy** [nexe/nexe#640]
**BUG** 

**What happened:**

Just like https://github.com/nexe/nexe/issues/573

**What you expected to happen:**

https://travis-ci.org/firepress-org/ghostfire/jobs/543493367#L864

**How to reproduce it (as minimally and precisely as possible):**

https://travis-ci.org/firepress-org/ghostfire/jobs/543493367#L864

**Anything else we need to know?:**

Check the dockerfile

**Environment**

- Platform(OS/Version): travis ubuntu
- Host Node Version: 10
- Target Node Version: 
- Nexe version: 3.2.1
- Python Version: ?

**Comment by calebboyd** [comment]
You might need to periodically log something to keep travis alive. Since building is a relatively long process. Alternatively you could use the verbose flag which will forward the make output. But this will probably fill up the log buffer on travis.

**Comment by pascalandy** [comment]
You are right. Thanks for the answer :)
