### ISSUE TITLE
argv issue when using node 12.4.0

### ISSUE THREAD

**Issue by ledbit** [nexe/nexe#641]
**Is this a BUG or a FEATURE REQUEST?:** 
Bug

**What happened:**
argv[2] gets turned into a path 

**What you expected to happen:**
argv[2] should be preserved 

**How to reproduce it (as minimally and precisely as possible):**
1. create foo.js with just `console.log(process.argv)`
2. `nexe foo.js -t linux-x64-12.4.0 -o foo`
3. `./foo one two three`
4. notice argv[2]
```
[
  '/<snip>/foo',
  '/<snip>/foo.js',
  '/<snip>/one',
 'two',
 'three'
]
``` 

**Anything else we need to know?:**
I only tested 12.4.0 - other 12.x versions would likely suffer from similar issues 

The culprit here could be: https://github.com/nexe/nexe/blob/master/src/patches/third-party-main.ts#L70-L71

which then calls `prepareMainThreadExecution(true)` -  where `true` ==  `expand argv1 (which becomes argv2) by resolving it into a path`
https://github.com/nodejs/node/blob/v12.4.0/lib/internal/main/run_main_module.js#L7

**Environment**

- Platform(OS/Version): Ubuntu 16.04
- Host Node Version: 10.15.3
- Target Node Version: 12.4.0
- Nexe version: 3.3.0
- Python Version: 2.7.12

**Comment by calebboyd** [comment]
Thanks. Fixed via https://github.com/nexe/nexe/commit/1eb44797d07112352241401e18fa8228b81ab674

Builds are running.
