### ISSUE TITLE
Assets scope

### ISSUE THREAD

**Issue by yairmalka06** [nexe/nexe#643]
hey, i wanted to know as you mentiond in ur odcumentation that i can use the --asset scope for asstes. but you also said that it needs to be a nexe binary file or whatever. but how do i build a one like this? i need to use 2 javascript files that i want to compile in to the exe file. but i dont know how to do this. can u help me plz?

**Comment by calebboyd** [comment]
`nexe entryfile.js`

https://github.com/nexe/nexe#usage
