### ISSUE TITLE
Build for linux in windows

### ISSUE THREAD

**Issue by rahbari** [nexe/nexe#644]
When building in windows for linux, the output doesn't work.
I compare windows output vs linux and only difference is resources path:
this is linux output:
**...{"resources":{"./node/views/404.....**
this is windows output:
**...{"resources":{"./node\\\views\\\404...**
Nexe use windows path format even for linux output.

**Comment by calebboyd** [comment]
This is by design. The paths are normalized at runtime. If you have an issue please include a description and reproduction

**Comment by rahbari** [comment]
Windows build for Linux ends as soon as it's started without any errors, but the Linux build works fine. Everything is similar in both builds.

**Comment by rahbari** [comment]
When trying to reproduce the problem I found out i have newer version of nexe on my windows machine than centos, after compiling node with newer nexe in centos, problem got solved.

**Comment by rahbari** [comment]
Sorry to reopen this issue, but the packaged app in windows can't require() files in directories although it work fine for root files.

**Comment by calebboyd** [comment]
Still need more information. Please open a new issue and follow the provided template.
