### ISSUE TITLE
Could not run npm commands from nexe binary

### ISSUE THREAD

**Issue by radharajendran** [nexe/nexe#646]
I have set of npm commands in my package.json

I have generated nexe successfully. Project is running as expected.

But i could not execute npm commands from binary.

Can anyone please help , how to run npm commands from nexe ?

nexe version - 3.1.0

python - 2.7

OS: Windows 
version: Windows 10 Education

**Comment by calebboyd** [comment]
npm commands are shell programs not javascript programs.

If you have a bug or issue please provide a reproduction or some kind of explanation.

**Comment by radharajendran** [comment]
"npm run" command can run javascript files  via package.json .

This can not run via nexe generated binary . Is there any solution to achieve this ?

**Comment by calebboyd** [comment]
npm run executes shell commands, as explained in the documentation
https://docs.npmjs.com/cli/run-script
