### ISSUE TITLE
Node 10.15.3 binaries disappeared for some platforms

### ISSUE THREAD

**Issue by poelstra** [nexe/nexe#647]
**Is this a BUG or a FEATURE REQUEST?:** 
BUG

**What happened:**
Builds for Node 10.15.3 on Linux-64 and Windows-64 stopped working.
Apparently, the binaries have disappeared from https://github.com/nexe/nexe/releases

**What you expected to happen:**
Builds for these versions should still work.

**How to reproduce it (as minimally and precisely as possible):**
```
$ rm -rf ~/.nexe # Clear cached versions
$ nexe -t windows-x64-10.15.3 index.js
ℹ nexe 3.1.0
✔ Downloading pre-built Node.js
✔ Finished in 1.322s

Error: https://github.com/nexe/nexe/releases/download/v3.0.0/windows-x64-10.15.3 is not available, create it using the --build flag

See nexe -h for usage..
```

**Anything else we need to know?:**
It probably broke somewhere between 21 June and 24 June (according to build failures in our pipeline).

**Environment**

- Platform(OS/Version): Windows 10, 64 bit, node:10.15.3 docker image
- Host Node Version: Node 10.15.3
- Target Node Version: Node 10.15.3
- Nexe version: 3.1.0, 3.2.0
- Python Version: 3.6.8

**Comment by calebboyd** [comment]
Hi @poelstra sorry about this. The build scheduled build triggers in Azure Pipelines are very strange...in that they don't work at all...

I'll close this issue when I'm certain the builds have repopulated.

**Comment by poelstra** [comment]
Thanks for the quick response @calebboyd!

Do you have a rough estimate of when the builds will be back (hours, days, weeks)?
(Asking because we may need to create a temporary patch with custom builds in the mean time.)

**Comment by poelstra** [comment]
Thanks @calebboyd! Works like a charm again. 💯 👍

**Comment by ChristianTucker** [comment]
Issue is back, I guess?

**Comment by ChristianTucker** [comment]
Can't edit my previous comment, info: 

```
i nexe 3.3.2
√ Downloading pre-built Node.js
√ Finished in 1.282s

Error: https://github.com/nexe/nexe/releases/download/v3.0.0/windows-x64-10.16.3 is 
not available, create it using the --build flag
```
