### ISSUE TITLE
We should use v2 of Issue and Pull Request templates

### ISSUE THREAD

**Issue by jaredallard** [nexe/nexe#648]
**Is this a BUG or a FEATURE REQUEST?:** Feature Request

**What happened:** n/a

**What you expected to happen:** Should be able to discern between bug and feature requests, as well as have PR templates.

**How to reproduce it (as minimally and precisely as possible):** n/a

**Anything else we need to know?:** 

Related: https://help.github.com/en/articles/about-issue-and-pull-request-templates

---

Assigning this to myself to take on.

**Comment by calebboyd** [comment]
Looks handy :)
