### ISSUE TITLE
Is `nexe` support `yarn workspace` (monorepo)?

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [nexe/nexe#649]
**Is this a BUG or a FEATURE REQUEST?:** 
> FEATURE REQUEST

**What happened:**
I'm now building an monorepo project follow this guide: [`yarn workspace`](https://yarnpkg.com/en/docs/workspaces).
I packed the a package of the project used `nexe`, it succeed and I got an binary-executable file like `xxx.exe`. That looks  good, the `xxx.exe` works well, until I tried to send it to others.
It seems that the local-linked dependence were missing in the packed executable file, so if I move the `xxx.exe` out of the workspace folder, then it could not launched, just throw an error like ` Cannot find module '${my custom package}'`.

**What you expected to happen:**
Is it support monorepo? What should I do?

**How to reproduce it (as minimally and precisely as possible):**
Build an monorepo project using `yarn workspace`, and for one of the package of the project, linked a custom local dependence, then packed the package used `nexe`.

**Anything else we need to know?:**
yarn --version
> 1.13.0

**Environment**

- Platform(OS/Version): Microsoft Windows [版本 10.0.15063]
- Host Node Version: v8.11.3
- Target Node Version:
- Nexe version: ^3.2.1
- Python Version: Python 3.6.1

**Comment by jaredallard** [comment]
This sounds a lot more like a bundler issue, and not really something we should strive to support. Otherwise we open ourself to a class of package manager specific formats that we'd need to emulate.

Thoughts @calebboyd?

**Comment by calebboyd** [comment]
enhanced-resolve might have a solution for this which is what is used when determining the dep tree... I don't know if this setup requires specific configuration for that or not though.

**Comment by zhengxiaoyao0716** [comment]
I found maybe it just caused by system symbol link? The yarn workspace guide said `Please note the fact that /workspace-a is aliased as /node_modules/workspace-a via a symlink`, and it seems the only difference between the custom package dependences and other dependences in the `node_modules` it that they are symlink.

**Comment by zhengxiaoyao0716** [comment]
Is there any progress?

I found that maybe the correctly package has bundled into the `.exe` succeed, but the path of it was incorrect. It seems that `nexe` would track the raw path of the system link created by `npm link`. 

When we see a linked package in the `node_modules` named `xxx` witch is just a system link, it would be packed into the `.exe` file with it true path instead of `xxx` in `node_modules`, so the `.exe` could not found the `xxx` package at launch.

**Comment by sgoll** [comment]
I just stumbled upon this unexpected behavior. I think @zhengxiaoyao0716 is correct: `nexe` seems to pick the wrong path when discovering a symlink inside `node_modules/`.

For what it's worth, my current workaround is to manually include the required module files via the `--resource` flag:

```
--resource ".../node_modules/related-package/package.json"
--resource ".../node_modules/related-package/dist/**/*"
```

(Your paths may vary.)

**Comment by MichaelGatesDev** [comment]
@sgoll thanks for the fix, that worked for me

**Comment by fmatzy** [comment]
I also encountered the same issue on my monorepo project which uses [lerna](https://github.com/lerna/lerna).

[enhanced-resolve](https://github.com/webpack/enhanced-resolve) seems to [provide `symlinks` option](https://github.com/webpack/enhanced-resolve#resolver-options), which determines whether or not to resolve symlinks to its linked path, and default value is `true`.
[resolve-dependencies](https://github.com/nexe/resolve-dependencies) need to set it `false` explicitly or to provide similar option, for supporting symlinks.

**Comment by calebboyd** [comment]
If anyone wants to try this it should work in `nexe@next`
