### ISSUE TITLE
FS readdirSync returning list of "virtual" files, instead of list of the actual files on the file system.

### ISSUE THREAD

**Issue by dbteku** [nexe/nexe#650]
**Is this a BUG or a FEATURE REQUEST?:** 
BUG
**What happened:**
I was trying to list the files and read certain ones and load them into my node.js app. Works fine without packaging but when I package it it reads the binary directory structure and not the actual file system structure.
**What you expected to happen:**
To read and list all the files on the actual file system and not in the packaged binary.
**How to reproduce it (as minimally and precisely as possible):**
```javacript
const fs = require('fs');
const files = fs.readdirSync(process.cwd());
```
**Anything else we need to know?:**

**Environment**

- Platform(OS/Version): Windows 10
- Host Node Version:  10.15.3
- Target Node Version: 10.15.3
- Nexe version: 3.3.2

**Comment by jaredallard** [comment]
Possible duplicate of #613

**Comment by calebboyd** [comment]
closing and tracking there

**Comment by ArashMotamedi** [comment]
`fs.promises.readdir` works
