### ISSUE TITLE
.env file value not reflecting

### ISSUE THREAD

**Issue by jaiyashree** [nexe/nexe#652]
**BUG:** 

**I have a .env files with different environment values (like DB_HOST, DB_URL, etc) set at different systems. I want these variables to be read from the code as process.env**

require(dotenv) to import values from .env and declare any variable like DB_URL=mongo://localhost:20127/test-app and try printing this value from your code as process.env.DB_URL

**Environment**

- Platform(OS/Version): Ubuntu 18
- Host Node Version: 10
- Target Node Version: 10
- Nexe version: 3.3.2
- Python Version: 2.7.15+

**Comment by calebboyd** [comment]
If you want to include additional files in your builds you can use `-r`

eg. `nexe -r .env` will include your .env file. This works if you include the file or ship the file alongside the nexe binary.

**Comment by jaredallard** [comment]
Been awhile without a response, going to close this. @jaiyashree please reopen if you have more information!

**Comment by aravindnc** [comment]
@calebboyd @jaredallard 
can we pass env variables as parameters directly to the output exe file ?
