### ISSUE TITLE
Writing Files to the actual File System

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [nexe/nexe#658]
Hi Guys, very good job you are doing here. I am exited to use nexe to build an exe for a nodejs app I am close to deploy. So far there is a single thing I need nexe to do that I could not figure out how or if it is possible at all: to let me write files to the actual file system. 

I have 2 use cases where I need to write files to the actual file system and not the virtual one:

1) Logs: I need users to be able to check the execution logs of some stuff my app does.
2) Inter execution state: I need to preserve some state between 2 different executions of the resulting .exe, and for that I need to write a file to the actual file system.

So my question is: a) is it possible to write files to the actual file system? b) how c) if not, do you have plans to allow it?

Thanks!

**Is this a BUG or a FEATURE REQUEST?:** 

**What happened:**

**What you expected to happen:**

**How to reproduce it (as minimally and precisely as possible):**

**Anything else we need to know?:**

**Environment**

- Platform(OS/Version):
- Host Node Version:
- Target Node Version:
- Nexe version:
- Python Version:

**Comment by calebboyd** [comment]
Any of the file writing APIs in node will work fine
