### ISSUE TITLE
Error: python ./configure.py --dest-cpu=arm7l exited with code: 2

### ISSUE THREAD

**Issue by bengkoay** [nexe/nexe#661]
Hi all, I am having this issue of compiling nodejs application in Raspberry Pi 3B+, and I met this error. I also tried using other option shown but still give the same error.

`pi@raspberrypi:~ $ nexe -i /home/pi/Documents/helloworld.js -o /home/pi/Documents/hello --build --verbose`
`ℹ nexe 3.3.2`
`✔ Downloading Node.jssource from: https://nodejs.org/dist/v10.16.0/node-v10.16.0.tar.gz`
`✔ Already downloaded...`
`✔ Compiling result`
`  Configuring node build: --dest-cpu=arm7l`
`Usage: configure.py [options]`

`configure.py: error: option --dest-cpu: invalid choice: 'arm7l' (choose from 'arm', 'arm64', 'ia32', 'mips', 'mipsel', 'mips64el', 'ppc', 'ppc64', 'x32', 'x64', 'x86', 'x86_64', 's390', 's390x')`
`✔ Configuring node build: --dest-cpu=arm7l`
`✔ Finished in 7.418s`

`Error: python ./configure.py --dest-cpu=arm7l exited with code: 2`

`See nexe -h for usage..`

Other options I used:

- `nexe -i /home/pi/Documents/helloworld.js -o /home/pi/Documents/hello --build --verbose -c ['arm']`

- `nexe -i /home/pi/Documents/helloworld.js -o /home/pi/Documents/hello --build --verbose -c ['arm64']`

**Comment by wilmardo** [comment]
@mturnshek

**Comment by wilmardo** [comment]
This error seems to come from Node:
https://github.com/nodejs/node/blob/master/configure.py#L48

Might be useful to open a ticket there :)

**Comment by jaredallard** [comment]
This seems to be 100% just a node issue, recommend following @wilmardo's advice and post there. Please reopen if you have more details that suggest it's a `nexe` issue.

**Comment by calebboyd** [comment]
Nexe appears to be passing the wrong argument (arm7l)

**Comment by danawoodman** [comment]
Has this fix been released?

**Comment by wilmardo** [comment]
Doesn't seem so, latest tag is [24 June](https://github.com/nexe/nexe/releases/tag/v3.3.2) and the fix was merged on 22 August. You should install nexe from the master:

```
npm install nexe/nexe#master
or
npm install --save https://github.com/nexe/nexe/tarball/master
```

**Comment by danawoodman** [comment]
@calebboyd can we get a release pweeeeeze? 🤓

**Comment by calebboyd** [comment]
![https://media.tenor.com/images/9222edfb0c81a5bd98e667505494bfec/tenor.gif](https://media.tenor.com/images/9222edfb0c81a5bd98e667505494bfec/tenor.gif)

**Comment by danawoodman** [comment]
💰💵💸 That enough? 😉

**Comment by aemonge** [comment]
Still no money to fix this :( ?

**Comment by SDAdham** [comment]
Hello, I have the same error but `NexeError: python ./configure.py --dest-cpu=x86 exited with code: 1`
