### ISSUE TITLE
Unable to use parallel jobs when building

### ISSUE THREAD

**Issue by gautaz** [nexe/nexe#666]
**What happened**:

I tried to use the `--make` option to pass `--jobs=5` to the NodeJS build process.

**What you expected to happen**:

I expected the NodeJS build to be faster.

**What happened**:

I was unable to pass the jobs options to the NodeJS make command, here is what happened:

```
➤  nexe --build --make --jobs=5
ℹ nexe 3.3.2
✔ Node source extracted to: /home/thibault.hild/.nexe/10.16.3
✔ Compiling Node with arguments: true
✔ Finished in 12.498s

Error: make true exited with code: 2

See nexe -h for usage..
```

**How to reproduce it (as minimally and precisely as possible)**:

```
> index.js
nexe --build --make --jobs=5
```

**Anything else we need to know?**:

It seems that `minimist` is interpreting the `--jobs=5` option as part of the `nexe` options.
This is most probably something I am doing wrong and perhaps this just needs the right documentation.

**Environment**:
- Platform(OS/Version): Linux AMA-LT-4549 4.15.0-55-generic #60~16.04.2-Ubuntu SMP Thu Jul 4 09:03:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Host Node Version: v10.16.3
- Target Node Version: same
- Nexe version: 3.3.2
- Python Version: Python 2.7.12

**Comment by calebboyd** [comment]
`--make="-j4"`

**Comment by gautaz** [comment]
@calebboyd Thank you for the quick answer.
Perhaps you would want this to be documented somewhere?
This could also be part of the `nexe --help`.

**Comment by harsszegi** [comment]
@calebboyd  Just a quick question, is this somehow routed through / converted to appropriate equivalent when building with MSVC in Windows? Thanks,

**Comment by calebboyd** [comment]
Looking in vcbuild.bat I don't see a way to pass in a customized cpu count to msbuild.
It defaults to 2 https://github.com/nodejs/node/blob/master/vcbuild.bat#L354

**Comment by harsszegi** [comment]
@calebboyd Thanks a lot for checking this

**Comment by timarandras** [comment]
This results in the same error.

```bash
nexe --build --make="-j4" index.js 
ℹ nexe 3.3.2
✔ Already downloaded...
✔ Compiling Node with arguments: -j4
✔ Finished in 6.269s

Error: make -j4 exited with code: 2

See nexe -h for usage..
```
Platform(OS/Version): OpenSuSE Tumbleweed Linux 5.5.5-1-default #1 SMP Thu Feb 20 06:00:15 UTC 2020 (5157fff) x86_64 x86_64 x86_64 GNU/Linux
Host Node Version: v13.9.0
Target Node Version: same
Nexe version: 3.3.2
Python Version: Python 2.7.17
