### ISSUE TITLE
Is it possible to run as a background service?

### ISSUE THREAD

**Issue by joaocwd** [nexe/nexe#669]
Hey everyone, Is there any way to create an .exe build that runs in the background as a service? Is there any flag in the execution of the command?

**Comment by ChronSyn** [comment]
It doesn't appear to be possible as a built in option with nexe, but something like this works;

https://www.howtogeek.com/50786/using-srvstart-to-run-any-application-as-a-windows-service/

**Comment by joaocwd** [comment]
Thank you!
Glad to be helped and to know more options than using for my project builds!
I've been searching and found the "nssm" that helped me accomplish this task, a bit like this "srvstart" but managed to do everything through the command line without needing the "sc" command (which is even super powerful to start or stop any windows services).

**Comment by ChronSyn** [comment]
I looked at NSSM too but it didn't seem to fit my use case. I'd love for something like this to be built into nexe (but not above getting native modules working inside exe's first).

**Comment by calebboyd** [comment]
related to #374
