### ISSUE TITLE
Using --asset to with prebuild nodejs

### ISSUE THREAD

**Issue by amarth1982** [nexe/nexe#671]
**What would you like to be added**:

Documentation for --asset doesn't explain the process of creating a prebuild node and using it with  application build. I tried to build nodejs and used it like

nexe -i app.js -o app.exe --asset /tmp/node-10/out/Release/node

but this didnt work.

When I run app.exe, it waits at prompt for node

**Why is this needed**:

I cannot get the prebuild from nexe releases due to proxy issue and compiling the entire nodejs is a long process.

**Comment by calebboyd** [comment]
you can make an asset with `nexe -i app.js -o asset.exe --no-mangle`

You can then use `--asset asset.exe` in subsequent builds

**Comment by amarth1982** [comment]
appreciate your quick response, going to try it now

**Comment by amarth1982** [comment]
Thanks it worked
