### ISSUE TITLE
is it possible to insert externals ? 

### ISSUE THREAD

**Issue by chmod777-R** [nexe/nexe#673]
**What would you like to be added**:

**Why is this needed**:
hello i need insert external json, dll and exe files in my project. is it possible ?

**Comment by insayd10** [comment]
is it ok, im explored --resource parameter but need to help about how can i use child_process with resources ? its not found like exec("xxx.exe")

**Comment by dimitrov-adrian** [comment]
Need to copy it on the host's file system (may be in some cache directory), and then to execute it.
