### ISSUE TITLE
compiler.addResource hangs when passing content

### ISSUE THREAD

**Issue by modeswitch** [nexe/nexe#677]
**What happened**:
I'm trying to add some dynamic data to my bundle:

```
plugins: [
  async (compiler, next) => {
    await compiler.addResource(
      path.resolve(compiler.bundle.cwd, "build.json"),
      JSON.stringify({ id: "some UUID" })
    );
    return next();
  }
],
```

When I run `nexe`, the build hangs on `Writing result to file`.

**What you expected to happen**:
My file `build.json` is added to the bundle with a random UUID.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**: 
- Platform(OS/Version): Linux/Fedora 27
- Host Node Version: v12.10.0
- Target Node Version: v12.10.0
- Nexe version: 4.0.0beta1
- Python Version: 2.7.14

**Comment by cah-calebboyd** [comment]
available via `nexe@next`

**Comment by calebboyd** [comment]
available via `nexe@next`

**Comment by royra** [comment]
@calebboyd still happening for me on nexe@4.0.0-beta.3, and even on the latest master branch.
