### ISSUE TITLE
Error: Error downloading prebuilt binary: RequestError: connect ETIMEDOUT 140.82.118.4:443

### ISSUE THREAD

**Issue by fsmoke** [nexe/nexe#682]
**What happened**:
See the log:

> C:\Program Files\nodejs>nexe test.js
> i nexe 3.3.2
> √ Downloading pre-built Node.js
> √ Finished in 70.746s

> Error: Error downloading prebuilt binary: RequestError: connect ETIMEDOUT 140.82
> .118.4:443

> See nexe -h for usage..

**How to reproduce it (as minimally and precisely as possible)**:
Just install latest version of nodejs, nexe and run nexe with any js file

**Anything else we need to know?**:
I am new in nodejs, i just download latest release of nodejs and nexe(by npm i nexe -g) module, and immediately got this error

**Environment**:
- Platform(OS/Version): Windows 7 x64
- Node JS Version: 12.11.1 
- Nexe version:3.3.2

Added:
I studied the problem: The problem is that I am behind the proxy. And nexe don't handle proxy settings of npm. So npm itself working just fine, but nexe no

**Comment by calebboyd** [comment]
What protocol is your proxy? http or https? 

Right now a proxy tunnel is only created when HTTPS_PROXY is set.
