### ISSUE TITLE
Requiring external files. 

### ISSUE THREAD

**Issue by mabdu11ah** [nexe/nexe#683]
For example, if I want to change details in a file called `config.json` how will I do it as it is bundled in the package?

**Comment by calebboyd** [comment]
What did you try. I don't know what you're trying to accomplish. Maybe post to stackoverflow?

**Comment by mabdu11ah** [comment]
Sorry, my bad. I found the problem to this issue, will post for others. 

Issue: using files outside the package that you want to change. For example, if you do `nexe file.js -r config.json` it will work, but say you want to change `config.json` in the bundled app. You can't. 

Solution: use __dirname and fs instead of require
```
fs.readFileSync((__dirname + "config.json", err, data) => {
    if (err) throw err;
    console.log(data);
  })) )

```
