### ISSUE TITLE
Build error on Raspberry Pi 4

### ISSUE THREAD

**Issue by aral** [nexe/nexe#685]
**What happened**:

While trying to compile a binary for [Site.js](https://sitejs.org) on a Raspberry Pi 4 using Nexe master branch, with the following options:

```sh
pi@raspberrypi:~/small-tech/site.js/app $ node_modules/nexe/index.js bin/site.js --build --verbose -r package.json -r "bin/commands/*" "node_modules/@ind.ie/nodecert/mkcert-bin/mkcert-v1.4.0-linux-arm" -o /tmp/site
```

The following error is received:

```sh
collect2: error: ld returned 1 exit status
make[1]: *** [node.target.mk:190: /home/pi/.nexe/10.16.3/out/Release/node] Error 1
```
Longer stack trace:

```sh
/home/pi/.nexe/10.16.3/out/Release/obj.target/tools/icu/libicustubdata.a /home/pi/.nexe/10.16.3/out/Release/obj.target/deps/v8/gypfiles/libv8_snapshot.a -ldl -lrt -lm -Wl,--end-group
/usr/bin/ld: /home/pi/.nexe/10.16.3/out/Release/obj.target/node_lib/src/bootstrapper.o: in function `node::PromiseRejectCallback(v8::PromiseRejectMessage)':
bootstrapper.cc:(.text+0x400): undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: bootstrapper.cc:(.text+0x498): undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: bootstrapper.cc:(.text+0x4c4): undefined reference to `__atomic_load_8'
/usr/bin/ld: bootstrapper.cc:(.text+0x4dc): undefined reference to `__atomic_load_8'
/usr/bin/ld: bootstrapper.cc:(.text+0x5c8): undefined reference to `__atomic_load_8'
/usr/bin/ld: bootstrapper.cc:(.text+0x5e0): undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
make[1]: *** [node.target.mk:190: /home/pi/.nexe/10.16.3/out/Release/node] Error 1
rm be2d06a58c3fe305182a984ec582b510b672583c.intermediate d3cdd034b7abf9c9ef31d057e448db8b7765e6dc.intermediate 51a815ea246be9b95fe87997bda118c3b1cb7bd3.intermediate
make: *** [Makefile:99: node] Error 2
✔ Compiling Node...
✔ Finished in 8536.109s

Error: make  exited with code: 2

See nexe -h for usage..
```

**What you expected to happen**:

For the Node compilation step to succeed.

**How to reproduce it (as minimally and precisely as possible)**:

On a Raspberry Pi 4 running latest Raspbian:

1. Clone Site.js from https://source.ind.ie/site.js/app.git
2. Run `node_modules/nexe/index.js bin/site.js --build --verbose -r package.json -r "bin/commands/*" "node_modules/@ind.ie/nodecert/mkcert-bin/mkcert-v1.4.0-linux-arm" -o /tmp/site`
3. Wait (a long time)

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version): Raspbian
- Host Node Version: 10.16.3
- Target Node Version:
- Nexe version: master
- Python Version:

**Comment by aral** [comment]
So it looks like `ld` is failing due to the previous error:

```sh
undefined reference to `__atomic_fetch_add_8'
```

Sounds like it might be the same as this issue reported on the OpenCV forums (and the fix there might work for nexe): https://answers.opencv.org/question/215735/make-error-__atomic_fetch_add_8-on-raspberrypi4/

**Comment by calebboyd** [comment]
Is there a nexe issue here? -- For compilation to succeed you'll need to research how to build node in your specific environment. Nexe should allow you to pass the correct parameters to the node build scripts.

I'll reopen if this is actually a bug or feature request!
