### ISSUE TITLE
Question on link to pre-built Node.js releases in readme

### ISSUE THREAD

**Issue by aral** [nexe/nexe#687]
Is it correct that the link to pre-built Node.js executables leads to [github releases](https://github.com/nexe/nexe/releases) (where I can only see Nexe releases) in the [Compiling Node](https://github.com/nexe/nexe/blob/master/README.md#compiling-node) section of the readme or to somewhere like:

https://nodejs.org/dist/

(Which is where Nexe appears to be downloading the releases from as per https://github.com/nexe/nexe/blob/master/src/steps/download.ts#L59)

**Comment by calebboyd** [comment]
Its actually this tag: https://github.com/nexe/nexe/releases/tag/v3.0.0 specifically...

V4 will break this. Hopefully add arm builds too...
