### ISSUE TITLE
how to work with pm2

### ISSUE THREAD

**Issue by guhuangjin** [nexe/nexe#690]
**What happened**:

When I use the PM2 API to start a service, running the packaged exe program crashes.

**What you expected to happen**:

Nexe can be used in combination with PM2

**How to reproduce it (as minimally and precisely as possible)**:

* I use the command "nexe pm2server.js - t x64-6.9.5" to package pm2server.js. Pm2server.js will start an httpserver through the PM2 API, as follows：
```

pm2.connect(function (err) {
  if (err) {
    console.error('pm2 connect err', err);
    process.exit(2);
  }

  console.info('pm2 connected');

  pm2.start({
    script: 'httpServer.js',         // Script to be run
    name: 'httpServer',         // Script to be run
    output: './pm2/out.log',
    error: './pm2/error.log',
    pid: './pm2/httpServer.pid',
    logDateFormat: 'YYYY-MM-DD HH:mm:ss',
    exec_mode: 'cluster', 
    instances: 0,                // Optional: Scales your app, 0：max
    mergeLogs: true,
  }, function (err, proc) {
    console.info('pm2 disconnect err = ', err);
    if (err) {
      throw err;
    }
  });
});
```

**Anything else we need to know?**:

* The "node pm2server.js" command can run normally

**Environment**:
- Platform(OS/Version): Windows 10
- Host Node Version: 6.9.5
- Target Node Version: 6.9.5
- Nexe version: 3.3.2
- Python Version:

**Comment by guhuangjin** [comment]
Through my tests, I found that opening exe executable file packaged by nexe through pm2 would report an error, and no solution was found.
Finally, it was OK to package my project with PKG and run it with pm2.

**Comment by ryandmello1198** [comment]
> Through my tests, I found that opening exe executable file packaged by nexe through pm2 would report an error, and no solution was found.
> Finally, it was OK to package my project with PKG and run it with pm2.
> https://github.com/zeit/pkg

Using pkg instead of nexe is not the answer to the question. Please reopen the Issue
