### ISSUE TITLE
Trying to add a custom icon to my .exe 

### ISSUE THREAD

**Issue by iamnotsrc** [nexe/nexe#694]
**What happened**
I'm trying to add a custom icon to my .exe using nexe. 
I've seen that other people got my same issue.

From my .js file to build the exe:
**const {compile} = require('nexe');

compile({
    input: 'src.js',
    output: 'SRC.exe',
    build: true,
    ico: 'SRC.ico',
    target: {},
    rc: {
        CompanyName: "SRC",
        PRODUCTVERSION: "1",
        FILEVERSION: "1"
    },
}).then(() => {
    console.log('Success')
}).catch(e => {
    console.log(e);
});**

From the prompt: 
i nexe 3.3.2
√ Already downloaded...
√ Configuring node build...
√ Finished in 1.565s
(node:8924) UnhandledPromiseRejectionWarning: Error: spawn python ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:8924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8924) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**HOW CAN I RESOLVE THIS ISSUE?**

**Comment by Bowlingtoolkit** [comment]
just use resource hacker and replace the icon file with ur new pic .

**Comment by calebboyd** [comment]
You don't have python installed or available on the path. See https://github.com/nodejs/node/blob/master/BUILDING.md
