### ISSUE TITLE
module.export TypeError in Meteor app

### ISSUE THREAD

**Issue by Kampflaus** [nexe/nexe#695]
**What happened**:

I'm building a Meteor app with Nexe. Since Meteor 1.8.2 the build cannot be run because it throws the following error:

```
.../output/dist/programs/server/mini-files.js:1
(function (exports, require, module, __filename, __dirname) { module.export({

TypeError: module.export is not a function
    at Object.<anonymous> (/home/vture/workspace/meteor-video-server/output/dist/programs/server/mini-files.js:1:76)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (.../output/dist/programs/server/boot.js:14:15)
    at Object.<anonymous> (.../output/dist/programs/server/boot.js:466:3)
```

**What you expected to happen**:

I'm not sure what the problem is but it seems to be related to the ECMAScript module syntax. Maybe it's possible to fix that in the nexe build process.

**How to reproduce it (as minimally and precisely as possible)**:

meteor node ../../node_modules/nexe/index.js -i main-nexe.js --resource programs/** -o ../dist/app

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version): Win 10 / Ubuntu 18.04
- Host Node Version: 8.16.2
- Target Node Version: 8.16.2
- Nexe version: 3.3.2 / 4.0.0-beta.3

**Comment by luzlab** [comment]
Do you mind sharing the main-nexe.js file?

**Comment by carlo-quinonez** [comment]
When I try `nexe --resource '**/*' main.js` in the bundle, nexe seems to hang. It's been stuck at Including 22927 files for 10+ minutes.

**Comment by Kampflaus** [comment]
Thanks for checking out.

@luzlab
That's just these two lines:
`process.argv.splice(2, 0, 'programs/server/program.json');`
`require('./programs/server/boot.js');`

@carlo-quinonez 
Experienced that as well with newer versions. Older versions like 3.0.0-beta.15 definitely work without being stuck.

**Comment by Kampflaus** [comment]
Problem solved. For more information see:

https://forums.meteor.com/t/meteor-1-9-1-8-2-nexe-not-working-anymore/51717

Cheers.
