### ISSUE TITLE
Support all node command line options when building application

### ISSUE THREAD

**Issue by kaidaguerre** [nexe/nexe#699]
**What would you like to be added**:
I'm not sure is this is a feature request or bug report. It seems not all node command line args are supported by the `--flags` option.

I want to disable deprecation warnings in the build application. I tried running  

`nexe index.js --build --flags ['--no-deprecation']`

However this did not work. Perhaps the flags option only supports the v8 options, not all node command args?

Is there an alternative method to achieve this? Can I set the NODE_OPTIONS env var somehow?

**Why is this needed**:
I want to disable deprecation warnings in the built application.

**Comment by gigouni** [comment]
hi @kaidaguerre 

How did you solve your issue? I'm more or less facing the same one with "--require" flag.
Any news or tips @calebboyd ?

Thanks

**Comment by calebboyd** [comment]
closing in favor of #616
