### ISSUE TITLE
Error when using nexe command !

### ISSUE THREAD

**Issue by Bowlingtoolkit** [nexe/nexe#703]
**i cant use nexe when i run nexe command it shows Error: https://github.com/nexe/nexe/releases/download/v3.0.0/windows-x64-13.1.0 is not available, create it using the --build flag**:

![Screenshot_1](https://user-images.githubusercontent.com/32039975/69984006-18bc2200-1549-11ea-91e5-dd1e1155ca7f.png)

**Environment**:
- Platform(OS/Version): Windows 10
- Host Node Version:13.1.0
- Target Node Version:13.1.0
**-** Nexe **version:3.3.2**

**Comment by Bowlingtoolkit** [comment]
also when i use --build flag ,
i got Error: vcbuild.bat nosign release x64 exited with code: 1

**Comment by ChronSyn** [comment]
Change node version. Not all versions of node are supported by nexe. I've had a lot of success with 10.16.3

**Comment by Bowlingtoolkit** [comment]
didnt work .. i changed the node version to 8 and to 10 and didnt work i tried to reinstall the package 
but didnt work too .

**Comment by Bowlingtoolkit** [comment]
i tried to reinstall the package and use node 12.13.1v and its running now thanks

**Comment by Rajaram54** [comment]
![image](https://user-images.githubusercontent.com/37393244/91559875-76ee2800-e956-11ea-9604-6ce780cf1ee7.png)
Environment:
i am getting this error again. i have tried with node 8 also but same problem
OS: Windows 10
 Node version 10.16.3
 Nexe version:3.3.2

**Comment by Rajaram54** [comment]
![image](https://user-images.githubusercontent.com/37393244/91561459-48258100-e959-11ea-8143-1e042ee9ae83.png)

I am getting this error while building through grunt.
Environment:

OS: Windows 10
node version :10.16.3
Nexe version:3.3.2

**Comment by TomasHubelbauer** [comment]
FYI 14.3.0 seems to work. I was looking for a more recent version and happened to have this one locally, but a different one on the CI which did not work, so I just switched CI to 14.3.0, too.

**Comment by chebotarevmichael** [comment]
`nexe test.js --build --verbose -t windows`

Required to read [ReadME](https://github.com/nodejs/node/blob/master/BUILDING.md#option-1-manual-install).
I solved this problem on Windows with help of the following steps:
1. Install NASM with Admin permissions;
2. Install MS Build Tools with "Desktop development with C++";
3. Install python3.8.5 (it was already)

The first building will be running for about 20 minutes, but others will be momently.

**Comment by 1961pjx** [comment]
6！

**Comment by SalvatoreScalia** [comment]
> `nexe test.js --build --verbose -t windows`
> 
> Required to read [ReadME](https://github.com/nodejs/node/blob/master/BUILDING.md#option-1-manual-install). I solved this problem on Windows with help of the following steps:
> 
>     1. Install NASM with Admin permissions;
> 
>     2. Install MS Build Tools with "Desktop development with C++";
> 
>     3. Install python3.8.5 (it was already)
> 
> 
> The first building will be running for about 20 minutes, but others will be momently.

What it is NASM?
