### ISSUE TITLE
Dynamic variable nexe compilation

### ISSUE THREAD

**Issue by atmoner** [nexe/nexe#705]
Hello and thank you for your program, it works very well!
I have a simple question ...
Is it possible to pass variables at the time of the copilation that modifies the source code?
With c++, it gives that:

```
#ifndef HOST
  #define HOST (char*)"http://localhost/"
#endif
```

At the time of compilation with g++, it is possible to modify the variable like this:
`g++ -o output source.cpp -DHOST='(char *)"http://localhost/"':`

How could I reproduce the same effect with nexe?

**Comment by calebboyd** [comment]
You'd have to do this in a build process for your javascript. Several bundlers support this type of functionality but it is outside the scope of nexe

eg. see https://webpack.js.org/plugins/environment-plugin/
