### ISSUE TITLE
Error with compiling

### ISSUE THREAD

**Issue by krytyYT** [nexe/nexe#707]
I have error
```C:\Users\xxx/xxx/xxx/xxx>nexe app.js --build --ico "icon.ico"
i nexe 3.3.2
√ Already downloaded...
√ Compiling Node with arguments: nosign,release,x64
√ Finished in 24.352s

Error: vcbuild.bat nosign release x64 exited with code: 1

See nexe -h for usage..
```

whats its mean?

**Comment by calebboyd** [comment]
the build process. To make this work on your environment, follow: https://github.com/nodejs/node/blob/master/BUILDING.md

Add the --verbose flag for additional logging through nexe

**Comment by babuilyas** [comment]
Make sure your python version is compliant. For example Node 12 uses python 2.7.
