### ISSUE TITLE
Version 4!

### ISSUE THREAD

**Issue by calebboyd** [nexe/nexe#714]
Version 4!

A new year... time for a new version...

Things that I want to address:

- Code Structure: make more imperative, simpler to grok, update tooling
- ✅ Simplify bundling: rely on NCC (webpack).
- ✅ Emit notes for native nodules (already done in `@next` with `--bundle`
- ✅ Typescript support by default: what even is JavaScript. (done with NCC)
- Fix longstanding windows/linux filesystem bugs. This will be greatly simplified by using ncc and having significantly less files.
- ✅ Allow the use of something like resolve-dependencies since the VFS will still be present.

Meta release things...
- Adopt lerna, because they baked in conventional commits, changelogs, conventional bumps.
- Move to Github Actions. Schedules dont really work on Azure Pipelines. GH actions is basically Azure Pipelines with a github UI so the machines will work the same..
- Only support LTS branches of Node.

Bonuses
- Update Documentation: simplify to level of CLI - have CLI API parity
- Remove RC capabilities defer to rcedit cli tool

CC @bruce-one, @jaredallard

**Comment by Paul75** [comment]
Hello,

I'm interested to this version that can compile Typescript project ? write ?

When it can use ?

Thanks

**Comment by calebboyd** [comment]
Making individual cards and moving this to a milestone
