### ISSUE TITLE
Puppeteer: `Chromium revision is not downloaded. Run "npm install" or "yarn install"`

### ISSUE THREAD

**Issue by sarpik** [nexe/nexe#718]
**What happened**:
I'm trying to create an executable for my script which uses puppeteer.

I used

```sh
npx nexe@next --target 12.9.1
```

and once I run  the executable while `node_modules` are present, everything is fine.

However, once the node_modules aren't there, I get the following error:

```console
(node:388446) UnhandledPromiseRejectionWarning: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at Launcher.launch (/home/kipras/privateprojects/node_modules/puppeteer/lib/Launcher.js:119:15)
    at async latestCarSnitcher (/home/kipras/privateprojects/latestCarSnitcher.js:40:18)
(node:388446) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:388446) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**What you expected to happen**:
I expect the executable to run independently of `node_modules`

**How to reproduce it (as minimally and precisely as possible)**:

```sh
mkdir example
cd example
npm init -y && npm i puppeteer -S

cat <<EOL > index.js
const puppeteer = require("puppeteer");

async function go() {
        const browser = await puppeteer.launch({ headless: false });
}

go();
EOL

npx nexe@next --target 12.9.1

./example # works (close the browser to continue)

rm -rf node_modules

./example # error
```

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version):

```sh
$ uname -a
Linux arch-usb 5.4.11-arch1-1 #1 SMP PREEMPT Sun, 12 Jan 2020 12:15:27 +0000 x86_64 GNU/Linux
```

- Host Node Version:

```sh
$ node --version
v13.6.0
```

keep in mind I used `--target 12.9.1` (the latest 12.x.y target, available from this repo's releases)

- Target Node Version:

`12.9.1`

- Nexe version:

```sh
$ nexe --version
3.3.2
```

- Python Version:

```sh
$ python --version
Python 3.8.1
```

Edit:
See also https://github.com/zeit/pkg/issues/204

**Comment by maheshjukanti** [comment]
you have to have .local-crhomium folder in puppeteer module. or reinstall puppeteer module.

**Comment by calebboyd** [comment]
Or use the executablePath for host chrome
