### ISSUE TITLE
Creating an executable on Windows results in a broken executable - "TypeError: callback is not a function"

### ISSUE THREAD

**Issue by kiprasmel** [nexe/nexe#719]
**What happened**:
I'm trying to build [an installer](https://github.com/sarpik/snitch-latest-car/blob/master/installer.js) for [my application](https://github.com/sarpik/snitch-latest-car) using [this script](https://github.com/sarpik/snitch-latest-car/blob/master/build-installer.sh), powered by nexe.

**What you expected to happen**:
When building on linux, everything builds successfully AND you're able to run the built binary successfully (expected),
On windows, everything still build successfully, BUT you're NOT able to run the built binary - you get the following error:

```console
C:\Users\kipra\Desktop\snitch-latest-car-git\installer.exe:223
                    callback(null, stat);
                    ^

TypeError: callback is not a function
    at C:\Users\kipra\Desktop\snitch-latest-car-git\installer.exe:223:21
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
```

I've chased down where the `callback(null, stat);` code exists, and there seem to be a few candidates:

```sh
$ grep -Hr "callback(null, stat);"
Binary file installer.exe matches
node_modules/fast-glob/node_modules/@nodelib/fs.stat/out/providers/stat.js:            callback(null, stat);
node_modules/nexe/lib/fs/patch.js:                    callback(null, stat);
node_modules/nexe/lib/steps/shim.js: <long verbose string which also has callback(null, stat);>
```

**How to reproduce it (as minimally and precisely as possible)**:

v1: Be on windows (errors)

```sh
git clone https://github.com/sarpik/snitch-latest-car.git
# or:   git clone git@github.com:sarpik/snitch-latest-car.git

cd snitch-latest-car

yarn

./build-installer.sh
./installer.exe

# errors
```

v2: Be on linux (works)

Do the same as above, just replace `./installer.exe` with `./installer`. Should work fine.

**Anything else we need to know?**:
Yes! I've made this work via https://github.com/zeit/pkg/

I've tried to do the same packaging through https://github.com/zeit/pkg/, but ran into an issue.
Later, however, I found https://github.com/zeit/pkg/issues/522,
and after applying the work-around, **everything worked**.

**Environment**:

Windows:

- Platform(OS/Version):
Windows 10 Home
Version 1903
Installed on 2019-07-29
OS build 18362.592
- Host Node Version: v12.14.1
- Target Node Version: windows-x64-12.14.1
- Nexe version: 3.3.2
- Python Version: Python 2.7.17

---

Maybe related: #137 #213 #410 #514

**Comment by nmarus** [comment]
I had this exact issue with the node-js library (fs-extra.copy) that had functions that allowed it to be called with either a callback or would return a promise. I didn't go into the lib to see exactly how this was being done, but rather my fix was to remove the library and create the functionality myself. Everything would work fine when the app was ran outside of nexe.

**Comment by slyadams** [comment]
I am having the same proboem using fs-extra/copy. I think I've tracked the problem down. Inside src/fs/patch.ts there is a shim for the fs module. On line 264 it calls

On line 260 there is a function:
` 
stat: function stat(filepath: string | Buffer, callback: any) {

      const stat = ownStat(filepath)
      if (stat) {
        process.nextTick(() => {
          callback(null, stat)
        })
      } else {
        return originalFsMethods.stat.apply(fs, arguments)
      }
    }
`
I can't quite follow this through, but the current node FS stat function's prototype signature is:

>  fs.fstat(fd[, options], callback)

Wheras in the past (and the call signaure in the nexe patch) is:

> fs.stat(path, callback)

So I believe the problem is that if code being compiled uses the new signature with options as the second parameter, nexe is trying to use that as a callback.

**Comment by nmarus** [comment]
I agree. I looked into this a bit further and commented on another issue that this is a symptom of too. Like you said, it is related to the way the the call signatures have changed in node/fs vs the overridden nexe/fs methods. https://github.com/nexe/nexe/issues/711#issuecomment-581144641

**Comment by FinlayDaG33k** [comment]
Did you ever manage to find a working solution for this?
I've also run into this just now and it made my entire project come to a dead stop D:

**Comment by kiprasmel** [comment]
@FinlayDaG33k I've switched to https://github.com/vercel/pkg, lol

**Comment by FinlayDaG33k** [comment]
oh D:

I did manage to _somewhat_ work by using the latest beta, but it's not perfect.

**Comment by slyadams** [comment]
I also switched tbh.
