### ISSUE TITLE
windows-x64-13.6.0 is not available

### ISSUE THREAD

**Issue by rainb3rry** [nexe/nexe#720]
Hi team, When I try this `nexe -i main.js -o test.exe` I got an error like `Error: https://github.com/nexe/nexe/releases/download/v3.0.0/windows-x64-13.6.0 is not available, create it using the --build flag` could you help me ? Thanks.

**Comment by cat-ninja** [comment]
Hey @rainb3rry I was able to successfully build it after I downgraded my node to the LTS version. Don't know if that's the option for you.

**Comment by rainb3rry** [comment]
Hei @cat-ninja thanks for your recommend, actually I solved my problem with usage on readme.
