### ISSUE TITLE
Swap file inside executable

### ISSUE THREAD

**Issue by elpaxel** [nexe/nexe#722]
**What would you like to be added**:
Some sort of swap file. When I pack my script, nexe will add 100mb of free space inside executable where I will be able to store "future" created files from my script.
**Why is this needed**:
Cause I want trully single executable without any assets even in the future :)

**Comment by jaredallard** [comment]
I'm not entirely sure this is possible, Inna cross platform way anyways.
Windows doesn't let you modify the running executable. I may be wrong
though.

**Comment by calebboyd** [comment]
Regarding this, you are able to rename the running executable on windows and linux I believe. But as far as modifying the file, I do not think it is possible. You'd want your application to 

- Download a new version
- Rename the running version (istelf)
- Name the new version its previous name
- Restart the way it was running (eg. a daemon or something)

In general, this behavior is outside the scope of this project.
