### ISSUE TITLE
Disabling node cli produces nasty bug

### ISSUE THREAD

**Issue by m44-io** [nexe/nexe#725]
### Problem
Generally, when passing in flags/args from the cli, they are accessed via `process.argv`.  Nexe has a patch that disables the default node flags, but produced a bug using that approach.

If you are passing in an argument that has spaces in it (wrapped in quotes obviously) then it does not recognize them as being grouped together as a single argument. The problem is actually much deeper in that the internal parser doesn't recognize the quotes at all, which then in turn causes the parser to treat them as separate items in the array. 

### Source
In your patches you are disabling the node cli flags in the *node.cc file* by replacing 
```javascript 
argv[index][0] == '-' 
```
with
```javascript 
argv[index][0] == ']'
 ```

While this effectively does a good job of preventing the traditional node flags from affecting the application, it comes with a very nasty side effect that took a very long time to trace it back to this source.

### Example
```shell
myapp --flag1 option --flag2 "a string with spaces"
```
should produce
```javascript 
process.argv[ '--flag1', 'option', '--flag2', 'a string with spaces' ]
```
but Instead produces
```javascript 
process.argv[ '--flag1', 'option', '--flag2', 'a', 'string',  'with', 'spaces' ]
```
### Confirmation
After the painful discovery, it had been confirmed 100% when I simply omitted just this patch mentioned above from the `node.cc` file that the flags/args had been interpreted properly. Of course this brought back the original behavior and allowed node flags to influence the app, so it's not really a solution.

### Resolution
Is there perhaps a better strategy in disabling the node flags while still preserving the integrity of the remaining flags so that they are not compromised?

**Comment by calebboyd** [comment]
Was this a differ issue?
