### ISSUE TITLE
nexe Built window x64 executable program can not run ，dependencies not found.

### ISSUE THREAD

**Issue by lsunflower** [nexe/nexe#726]
Hi. In my project , I used typeorm and oracledb to connect the database, run with "node index.js", it is ok, But when i builded too executable program and run it, then i got  wrong infomation:
"(node:16720) UnhandledPromiseRejectionWarning: DriverPackageNotInstalledError: Oracle package has not been found installed. Try to install it: npm install oracledb --save" , what can i do?
Forgive me for bad english！

"oracledb": "4.2.0"
"typeorm": "^0.2.22"
"nexe": "4.0.0-beta.3"

![image](https://user-images.githubusercontent.com/5770394/74157734-bfacf080-4c53-11ea-9d53-09fd1476d47a.png)

**Comment by calebboyd** [comment]
oracledb is a native module, so the accompanying linked library (native module) must be shipped alongside the executable built with nexe.

**Comment by lsunflower** [comment]
> oracledb is a native module, so the accompanying linked library (native module) must be shipped alongside the executable built with nexe.
Could you please tell me some details and what should I do，think you very much!

**Comment by calebboyd** [comment]
Extra executables and linked libraries will have to be installed alongside the binary you generate with nexe. So the directory where you install your program might look like

```
|-my-exe.exe
|-node_modules
  |-oracledb
    |-...
```

**Comment by lsunflower** [comment]
awesome！

> Extra executables and linked libraries will have to be installed alongside the binary you generate with nexe. So the directory where you install your program might look like
> 
> ```
> |-my-exe.exe
> |-node_modules
>   |-oracledb
>     |-...
> ```

awesome ！！！

**Comment by Abhishek150995** [comment]
> Extra executables and linked libraries will have to be installed alongside the binary you generate with nexe. So the directory where you install your program might look like
> 
> ```
> |-my-exe.exe
> |-node_modules
>   |-oracledb
>     |-...
> ```

I tried to implement the same but it gave a new error that
**Error: Module did not self-register.**

Please suggest! Thanks in advance
