### ISSUE TITLE
Error with compile

### ISSUE THREAD

**Issue by OtisGoodman** [nexe/nexe#728]
**What happened**:
I get this error and my app does not compile. 
`(node:11076) UnhandledPromiseRejectionWarning: Error: vcbuild.bat nosign release x64 exited with code: 1
`
**What you expected to happen**:
My file was supposed to compile.
**How to reproduce it (as minimally and precisely as possible)**:
Use this code.
https://gist.github.com/OtisGoodman/88765eed5f9d63fb05b22753874cb221
**Anything else we need to know?**:
The build works just fine if I use the terminal to build.
A link to an image of my file setup: https://i.imgur.com/wjhrWlR.png
**Environment**:
- Platform(OS/Version):Win-10
- Host Node Version:12.3.1
- Target Node Version:12.3.1
- Nexe version:3.3.2
- Python Version: 2.7

**Comment by calebboyd** [comment]
Please refer to https://github.com/nodejs/node/blob/master/BUILDING.md
