### ISSUE TITLE
cjs/loader.js error when running executable with node v13.9.0

### ISSUE THREAD

**Issue by rafabenmar-te** [nexe/nexe#729]
**What happened**: Built nexe example with the latest node release (v13.9.0) but the executable is corrupt. I had to download nodejs code from GitHub repository because of missing dependency & copy the directory deps/zlib/contrib into .nexe/v13.9.0 directory. I'm using Ubuntu Xenial, but also happens in macOS Catalina.

**What you expected to happen**: Generated executable should run without any issues with target 
 version = v13.9.0

**How to reproduce it (as minimally and precisely as possible)**:
`user@user-VirtualBox:~/Documents/projects/nexe-example$ cat index.js 
console.log('Hello world', process.version);
user@user-VirtualBox:~/Documents/projects/nexe-example$ node index.js 
Hello world v13.9.0
user@user-VirtualBox:~/Documents/projects/nexe-example$ nexe index.js -t linux-x64-13.9.0 -o out/index --build --enableNodeCli
ℹ nexe 3.3.2
✔ Already downloaded...
✔ Compiling result
✔ Entry: 'index.js' written to: out/index
✔ Finished in 0.965s
user@user-VirtualBox:~/Documents/projects/nexe-example$ ./out/index 
internal/modules/cjs/loader.js:1091
  callbackMap.set(compiled.cacheKey, {
              ^

TypeError: Cannot read property 'set' of undefined
    at wrapSafe (internal/modules/cjs/loader.js:1091:15)
    at Module._compile (internal/modules/cjs/loader.js:1115:27)
    at internal/bootstrap/pre_execution.js:118:36
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:119:3)
    at internal/main/run_main_module.js:7:1
`

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version): Ubuntu Xenial & macOS Catalina
- Host Node Version: 13.9.0 & 10.16.0
- Target Node Version: 13.9.0
- Nexe version: 3.3.2
- Python Version: 2.7.12

**Comment by gautaz** [comment]
Hello,

Same exact  issue here with node v13.11.0:
```
test-config_1     | internal/modules/cjs/loader.js:1087
test-config_1     |   callbackMap.set(compiled.cacheKey, {
test-config_1     |               ^
test-config_1     | 
test-config_1     | TypeError: Cannot read property 'set' of undefined
test-config_1     |     at wrapSafe (internal/modules/cjs/loader.js:1087:15)
test-config_1     |     at Module._compile (internal/modules/cjs/loader.js:1111:27)
test-config_1     |     at internal/bootstrap/pre_execution.js:118:36
test-config_1     |     at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:119:3)
test-config_1     |     at internal/main/run_main_module.js:7:1
```

**Environment:**

- Platform(OS/Version): Docker image debian:buster-20200224-slim
- Container Node Version: 13.11.0
- Target Node Version: 13.11.0
- Nexe version: 3.3.2
- Python Version: 2.7.16-1

**Comment by calebboyd** [comment]
closing since node 13 is not supported
