### ISSUE TITLE
NEXE compiling with wrong version of node?

### ISSUE THREAD

**Issue by YoussefExplicit** [nexe/nexe#746]
**What happened**: I use `nexe -t x86-8.0.0` to compile the files, and I get `ReferenceError: URL is not defined`, when I run the file normally through index.js it works fine. I assume there's an issue with the node version as to use the URL class, you need node version 10 and above.

**What you expected to happen**: The exe to run.

**How to reproduce it (as minimally and precisely as possible)**: Use the URL class, compile the file, and use cmd to run the exe to see the output.

**Anything else we need to know?**: No

**Environment**: ?
- Platform(OS/Version): Windows
- Host Node Version: 12.16.1
- Target Node Version: ?
- Nexe version: 3.3.2
- Python Version: ?

**Comment by calebboyd** [comment]
You're specifying 8.0.0 which doesn't have whatwg url object available globally. You can access it that way in version 10.

with node 8 I get
```
> console.log(process.version) ||  URL
v8.17.0
ReferenceError: URL is not defined
```

**Comment by YoussefExplicit** [comment]
ah is that what the 8.0.0 does, thanks
