### ISSUE TITLE
cannot create icon

### ISSUE THREAD

**Issue by TheUnsaid** [nexe/nexe#747]
I'm trying to build a node program using an icon file. 
I'm using npm run build, and inside of my package.json file I have build:"nexe"
I've edited it too like build:"nexe -i [inputname] -o [outputname]"
So I know that some variables actually do work!
As soon as I try build:"nexe --icon [iconname]" though, this variable is completely ignored. The application is still built completely fine. The icon isn't changing nor is it throwing an error. 
"nexe --build --icon [iconname]" will always throw an error. Actually --build ALWAYS throws an error.

I've ran nexe --clean before each build.

My thought process was... maybe I should try building through javascript? So I copy-pasted the example and put it into a separate json file.

```
const { compile } = require('nexe')

compile({
  input: './my-app.js',
  build: true, //required to use patches
  patches: [
    async (compiler, next) => {
      await compiler.setFileContentsAsync(
        'lib/new-native-module.js',
        'module.exports = 42'
      )
      return next()
    }
  ]
}).then(() => {
  console.log('success')
})
```

This threw an error of cannot find requirement nexe
Turns out require('nexe') was the problem.
Whether it's a constant or var. Whether it's in curly braces or not. This will 100% throw an error when the JS file is run.

I will add that building through nexe is perfectly fine. I just cannot modify the icon of the created file no matter what.

**Environment**:
- Platform(OS/Version): Windows 10
- Host Node Version: 12.16.2
- Target Node Version: 12.16.2
- Nexe version: 3.3.2
- Python Version: ???

**Comment by Ayzrian** [comment]
Hey, @TheUnsaid 
If you want to change the icon or the executable descriptors you need to build it locally with `compile` function exposed by `nexe`.
```typescript
    await compile({
        build: true,
        name: 'AppName',
        input: './bundle/index.js',
        output: 'AppName.exe',
        resources: [YOUR RESOURCES],
        ico: 'PATH TO YOUR ICON',
        targets: [`YOUR TARGET PLATFORM`],
    });
```
