### ISSUE TITLE
Stuck at Node Compilation Step

### ISSUE THREAD

**Issue by a-y-u-s-h** [nexe/nexe#751]
**What happened**: 

I'm trying out Nexe for the first time, so not sure whether it should do this. When I run `nexe` it tells me that pre-built Node is not available. And that I should create it using --build flag. 

![2020-04-21_12-42-28_screenshot](https://user-images.githubusercontent.com/19586719/79836429-bd8ead00-83cd-11ea-9cbe-d1b8489ce1c8.png)

And after I do that like so, it gets stuck in this step forever: 

![2020-04-21_12-44-59_screenshot](https://user-images.githubusercontent.com/19586719/79836570-ef077880-83cd-11ea-8b23-4917c1dc14c7.png)

(Node compilation step takes forever, tried this several times in last one week)

**What you expected to happen**:

I expect Node to compile faster.

**How to reproduce it (as minimally and precisely as possible)**:

I installed `nexe` locally with `yarn add nexe` and then added a script: `"package": "nexe --build",` to my package.json and then ran `yarn package`. "main" key in my package.json points to `src/index.js`

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version): Arch Linux x86_64  5.6.4-arch1-1 
- Host Node Version: v13.13.0
- Target Node Version: (have no idea what this means)
- Nexe version: 3.3.2
- Python Version: 3.8.2 (for some reason `python` and `python3` maps to `3.8.2` and `python2` maps to `2.7.17`). Not sure whether this is the problem.

**Comment by giacomoratta** [comment]
I have the same problem (but exit error 2). Before someone answers you, I suggest to run again by using --verbose option, in order to provide more info.

**Comment by a-y-u-s-h** [comment]
Yeah, same. Adding screenshot as well here after `verbose`:

![2020-04-22_23-55-53_screenshot](https://user-images.githubusercontent.com/19586719/80019334-faa18f00-84f4-11ea-8b5e-899655ac7c40.png)

**Comment by calebboyd** [comment]
You can refer to https://github.com/nodejs/node/blob/master/BUILDING.md
In order to build not-yet-or-unsupported versions.
