### ISSUE TITLE
Nexe with create react app

### ISSUE THREAD

**Issue by ldevalbray** [nexe/nexe#753]
**What would you like to be added**:
I was wondering if it was possible to bundle a whole react application with nexe ? If so, how ?
This is because I would like to build a user interface on top of my application

**Why is this needed**:
If not, it would be amazing :)

Thank you for your answer !

**Comment by s-a** [comment]
This is currently possible. Add static files with build options.
```javascript
resources: [
			'./package.json',
			'public/**/*'
		],
```
