### ISSUE TITLE
mac-x64 builds missing for Node 12.16.x

### ISSUE THREAD

**Issue by aral** [nexe/nexe#757]
## Summary

Windows and Linux builds exist for Node 12.16.x (12.16.1 and 12.16.2) but a Mac build doesn’t. The last Mac build is for version 12.15.0 (although there is also a 14.0.0 build for Mac and Windows, but not Linux).

https://github.com/nexe/nexe/releases?after=v3.0.3

**Comment by aral** [comment]
I just built 12.16.2 for Mac. If you’d like to use it, please do:

https://sitejs.org/nexe/mac-x64-12.16.2

**Comment by calebboyd** [comment]
Oh!

```
~ > nexe -h
...
  -a   --asset   -- alternate asset path, file or url pointing to a base  (nexe) binary
```

**Comment by tanviShah29** [comment]
@aral Have you tested this solution on Mac? It's not working for me. Please provide more inputs on this

**Comment by aral** [comment]
@tanviShah29 Hi there. I have, yes. What’s the error you’re getting?

**Comment by tanviShah29** [comment]
@aral I have downloaded your file after trying to open it, I get an attached error @ 
<img width="422" alt="Screenshot 2020-06-08 at 5 42 55 PM" src="https://user-images.githubusercontent.com/55585010/84029260-ba687400-a9af-11ea-89e7-c9c934455f8a.png">

**Comment by s-a** [comment]
let' close this in favor of #777 ?
