### ISSUE TITLE
nexe@next regression: pkg → assets in package.json of modules being ignored

### ISSUE THREAD

**Issue by aral** [nexe/nexe#758]
## Summary

In 3.3.2, if Module A loads Module B and Module B has a `pkg` object specified in its package.json with an `assets` property ([example](https://source.small-tech.org/site.js/lib/auto-encrypt-localhost/-/blob/master/package.json#L59), those assets are included in the build by Nexe.

In nexe@next, they are not.

## Workaround

Include any assets required by submodules manually while compiling ([example](https://source.small-tech.org/site.js/app/-/blob/master/bin/build.js#L116)).

If the issue isn’t immediately clear from the description, please let me know and I will try to create an isolated example. (I just wanted to open an issue so that I didn’t forget to.)

**Comment by calebboyd** [comment]
Thanks, I didn't know about those properties.

https://github.com/nexe/resolve-dependencies/issues/4

The change I made in v3 of resolve-dependencies was to 
add the "expand"  option.. https://github.com/nexe/resolve-dependencies#options
v2 treated it as "all" and nexe v4 uses "variable" - which expands node modules that use variabe/not statically analyzable require statements.

It seems like I can keep that and just include those fields by default if they're present.

**Comment by calebboyd** [comment]
beta.9 should have this fixed!

**Comment by calebboyd** [comment]
Now with tests 🤦 resolve-dependencies@4.2.1
https://github.com/nexe/resolve-dependencies/blob/3db238eb47b05f75b60c5a0a41a0268f242762ef/src/resolve.spec.ts#L23-L36
