### ISSUE TITLE
Feature: third-party remote

### ISSUE THREAD

**Issue by aral** [nexe/nexe#760]
## Use case

You are cross compiling your binary for multiple platforms but the official Nexe release for the version of Node you want either isn’t ready or missing.

## Proposed solution

It would be handy to have the ability to specify a remote that is used instead of the official Nexe releases URL on Github.

I propose that we add it to the options object.

e.g.,

```js
    const { compile } = require('nexe')
    // ...
    const remote  = 'https://sitejs.org/nexe/'
    // ...
    await compile({
      input,
      remote,
      output    : linuxX64BinaryPath,
      target    : linuxX64Target,
      resources
    })
```

I just hacked Nexe in my node_modules to implement/test it and use it for myself. Will issue a PR once I’ve added it to Nexe properly.

**Comment by calebboyd** [comment]
Meant for that comment to be here.https://github.com/nexe/nexe/issues/757#issuecomment-620247575

**Comment by aral** [comment]
Ah, that’s very neat (I hadn’t realised it had a stream interface).

Not sure it would help me in this case, though, as [my build script](https://source.small-tech.org/site.js/app/-/blob/master/bin/build.js) does a few other things and I’d rather keep it in Node than in a shell script. (Note: I haven’t pushed the changes I mentioned in the issue yet so the script is looking a bit different. Previously I was building on a Raspberry Pi as that was the only platform I could build the ARM version on.)

By the way, I did initially misread the code and try setting it as an asset but it just ended up bundling the current platform/architecture’s Node. Not sure if I missed something.

Totally cool with using it from my fork if you feel this is too niche a use case to include and/or you’d rather have people use a shell script for that use case.

**Comment by calebboyd** [comment]
Oh, I see, you're still rendering the target with nexe
```
remoteAsset = `${remote}/${target}`
```
Am I understanding correctly?

**Comment by aral** [comment]
Thanks, appreciate it. (And I realised that I’d misunderstood what the pipe was doing in your comment also. It generated a Linux executable on my machine that embedded the Nexe Mac binary from the site. Which is, of course, is exactly what the API does. For a moment there I thought you could just pipe JS code to a Nexe binary and get a wrapped binary and I was a little in awe.)  

The `remote` option: yes, that’s it. Will prep a PR request today (no pressure to merge it, I need to do it anyway) :)

**Comment by aral** [comment]
Ah, wait a minute… I just read the description of `--asset` in the CLI help in _options.ts_. Am I right in that it sounds like it should be doing what I originally thought it should be doing but it isn’t.

Current behaviour: does not build using the Nexe binary at the specified URL. Should it? (e.g., for your Mac example, it builds it using the Linux Nexe binary on my machine and I can launch it on Linux.)

I’m almost done implementing the remote option and will issue the PR anyway but perhaps the problem is that `--asset` isn’t doing what it should.

**Comment by calebboyd** [comment]
> For a moment there...

That would be a fun interface 😂 

> should be doing but it isn’t?


Looks like it requires the `target` to be set as well 🤦🏻‍♂️

**Comment by calebboyd** [comment]
specifically... retrieves cached value assumed by `target` and then bombs trying to build because there is no source.. Shoot

![image](https://user-images.githubusercontent.com/5818726/80487118-e826bb80-8921-11ea-9026-dfbc2a1067cf.png)

**Comment by aral** [comment]
Ah, I was wondering.

Are you married to the ‘--asset’ flag? Just about to have a spot of lunch and then test my changes and will issue a PR with --remote. Let me know what you think and whether you’d be up for replacing asset with that :)

**Comment by calebboyd** [comment]
Nah, I'm not tied to it. Your implementation or remote sounds like it satisfies the usecase I had for asset, while broadening and fixing it 🙃
