### ISSUE TITLE
Cant use Child Proccess

### ISSUE THREAD

**Issue by ScriptsByMe** [nexe/nexe#764]
**What happened**:
I`ve tried to use child proccess to exec an attached file with "nexe -r ./bot.js" but when I try, I got this error: 
```
Error: Cannot find module 'C:\Users\Santana-Itabatan\Documents\bot.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Child process exited with exit code 1
Error: Command failed: node ./bot.js
internal/modules/cjs/loader.js:983
  throw err;
  ^

```
**What you expected to happen**:
					
```
function starter() {
					const ls = exec('node ./bot.js', function (error, stdout, stderr) {
					  if (error) {
					    console.log(error.stack);
					    console.log('Error code: '+error.code);
					    console.log('Signal received: '+error.signal);
 					 }
					  console.log('Child Process STDOUT: '+stdout);
					  console.log('Child Process STDERR: '+stderr);
					});

					ls.on('exit', function (code) {
  					console.log('Child process exited with exit code '+code);
					starter();
					});
					};
					starter();

```
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version): Windows 10
- Host Node Version: 11.2.3
- Target Node Version: 11.2.3
- Nexe version: Actual
- Python Version: 2.7

**Comment by calebboyd** [comment]
If you want to `exec`ute a file with node, that file has to exist.

**Comment by ScriptsByMe** [comment]
But the file exists and It is attached to the executable as a resource with 
```
nexe -r "./**"
```

**Comment by calebboyd** [comment]
The **file** is _in_ the executable, it doesn't exist by itself,

Youre using `exec` to run node, which says "use the _node_ executable in the hosts PATH to evaluate the **file**"

Where using `fork` says, "use the current executable (nexe'd app with access to the **file**) to evalate the **file**"

**Comment by ScriptsByMe** [comment]
Thanks! :)
(and Sorry for waste your time)
