### ISSUE TITLE
Error cannot find module using obfuscate code

### ISSUE THREAD

**Issue by juancampuzano** [nexe/nexe#765]
**What happened**:

Unable to build a single executable when using obfuscate code.  I am using [Javascript Obfuscator](https://github.com/javascript-obfuscator) tool because I want to enhance the security of my app. 

When I run my app with the obfuscated code It works fine, but when I want to create an executable with nexe It does not work.

**What you expected to happen**:

Create executable when using obfuscated code.

**How to reproduce it (as minimally and precisely as possible)**:

I am having problems when requiring local files and using relative paths.

**Example:**
 `const cleanup = require('./someModule')();`
**Error:**
> internal/modules/cjs/loader.js:638
    throw err;
    ^
> Error: Cannot find module './someModule'

**Environment**:
 - Platform(OS/Version):  macOS Catalina version: 10.15.4 
 - Host Node Version: 10.16.1
 - Target Node Version:
 - Nexe version: 3.3.2
 - Python Version: 2.7

**Comment by juancampuzano** [comment]
@calebboyd  What other information do you need?

**Comment by calebboyd** [comment]
A reproduction of some kind, I can't reproduce your issue based on the information you've provided.
If I create a file main.js with the contents `const cleanup = require('./someModule')();`
Where `someModule` is an obfuscated file, I have no issues.

**Comment by juancampuzano** [comment]
In this example project [NexeObfuscated](https://github.com/juancampuzano/NexeObfuscated) you will see the error. 

I'm trying to run executable in a MacBook Air. 

Firstly I obfuscate my code and then I create the executable with a [ build.js](https://github.com/juancampuzano/NexeObfuscated/blob/master/build.js) file. Finally, when I try to run the executable I get the following error. 

![Screen Shot 2020-05-08 at 11 47 36 AM](https://user-images.githubusercontent.com/52759609/81428769-62292280-9122-11ea-81a8-657c8266e00b.png)

**Comment by calebboyd** [comment]
npm run javascript:obfuscate errors when I run it
`[javascript-obfuscator-cli] Error in file: node_modules/charenc/README.js... `

**Comment by juancampuzano** [comment]
I am not obfuscating the `node_modules` libraries I am just looking to obfuscate the main code of the application.

So what I do is run the obfuscation before the n`ode_modules` folder has been created.

**Comment by calebboyd** [comment]
Since you're obfuscating the code, nexe can't perform static analysis on it and find your dependencies. If you bundle your code first with a tool like webpack or rollup you can then obfuscate that and just use nexe's stdin interface for generating a binary.
