### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by TazzerSZN** [nexe/nexe#766]
TypeError: Cannot read property 'set' of undefined
[90m    at Object.compileFunction (vm.js:375:17)[39m
[90m    at wrapSafe (internal/modules/cjs/loader.js:1106:15)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1140:27)[39m
[90m    at internal/bootstrap/pre_execution.js:118:36[39m
[90m    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:119:3)[39m
[90m    at internal/main/repl.js:18:1[39m

It compiles the file but then hits this on run. :/
nexe 3.3.2
Node v14.2.0

**Comment by TazzerSZN** [comment]
Ok solved by adding -t windows-x64-12.16.3 as it doesnt seem to like the latest version of node.

**Comment by calebboyd** [comment]
Hmm Thanks, I'll take a look

**Comment by TazzerSZN** [comment]
its on the latest node version.

**Comment by vectronic** [comment]
#768 looks do be a duplicate of this.
