### ISSUE TITLE
koa2 static assets Prompt after compilation 404

### ISSUE THREAD

**Issue by ShareQiu1994** [nexe/nexe#767]
1. 
Compiling binaries...
i nexe 3.3.2
√ Included 49 file(s). 0.049 MB
√ Already downloaded...
√ Compiling result
√ Entry: 'bin\www' written to: build2\gis_server2.exe
√ Finished in 43.691s
Finished compiling binaries

2.

my nexe.js file

```
const { compile } = require("nexe");
console.log("Compiling binaries...");
compile({
  input: "bin/www",
  output: `build2/gis_server2`,
  resources: [
    "public/**/*",
    "template/*",
    "controllers/**/*",
    "model/**/*",
    "config/**/*",
    "routes/**/*"
  ],
  targets: ["windows-x64-12.16.2"],
})
  .then(() => {
    console.log("Finished compiling binaries");
  })
  .catch((error) => {
    console.error(error);
  });
```

3. After compiling, I visited my project and found that my static resources could not be loaded.
But I've already set "public"/**/*

 
` http://localhost:8053/index.css net::ERR_ABORTED 404 (Not Found)`

But it's all right in the development environment.I want to know where I've got a problem with the configuration. Thank you

**Comment by calebboyd** [comment]
I can't replicate this, Please open a new issue with a reproduction if you're still having problems!
