### ISSUE TITLE
Run without nodejs?

### ISSUE THREAD

**Issue by Alexander9673** [nexe/nexe#771]
Is it possible to run this without nodejs installed on the system?

**Comment by AldieNightStar** [comment]
Hi Alexander9673 :) No. Cause if you developing self-contained app in nodeJS, and wanted to pack it, you need this NodeJS app with all the NodeJS environment to make it work on computer, without NodeJS then.
Thank you :)

**Comment by calebboyd** [comment]
I'm tracking this here: 
Duplicate of https://github.com/nexe/nexe/issues/543
