### ISSUE TITLE
Missing node versions for linux, mac and alpine

### ISSUE THREAD

**Issue by Barkole** [nexe/nexe#777]
It looks like only windows has for example the current node version 12.18.0

https://github.com/nexe/nexe/releases/tag/v3.0.0

**Comment by MichaelLeeHobbs** [comment]
Would it be possible to have builds for matching versions  https://hub.docker.com/_/node/ ?

**Comment by baparham** [comment]
Is there any update on when this will be fixed?

**Comment by calebboyd** [comment]
#754
