### ISSUE TITLE
Can´t start electron app

### ISSUE THREAD

**Issue by ScriptsByMe** [nexe/nexe#778]
**What happened**:
I´ve tried to use electroner to start my electron app, but when I start the app, this just don´t show the app screen.

**What you expected to happen**:
Show the html project screen when opened.

**How to reproduce it (as minimally and precisely as possible)**:
-Create an electron project
-Start with electroner
-compile with nexe
- get the error

**Environment**:
- Platform(OS/Version): win64
- Host Node Version: 10
- Target Node Version: 10
- Nexe version: Last Stable Version

**Comment by Monsupito** [comment]
Why want to compile an Electron application with Nexe? Electron can already be compiled, I think that if you want to compile an Electron application other than with the official Electron modules, you will have errors An Electron application can be compiled with [electron-build](https://www.electron.build/) or [electron-forge](https://www.electronforge.io/)

**Comment by ScriptsByMe** [comment]
@Monsupito cause I need to protect my source code.

**Comment by calebboyd** [comment]
Source code obfuscation is a non-goal of this project. Any code associated with a nexe build can easily be found/observed.

**Comment by calebboyd** [comment]
Closing because electron and nexe are mutually exclusive solutions.

**Comment by Monsupito** [comment]
@ScriptsByMe use gulp and gulp-javascript-obfuscator

**Comment by ScriptsByMe** [comment]
thanks! @Monsupito
