### ISSUE TITLE
'rc: object' don't change anythings

### ISSUE THREAD

**Issue by Monsupito** [nexe/nexe#780]
**What happened**:
When the exe file is created, file details is not modified : https://imgur.com/a/YUJecMx

**What you expected to happen**:
That the details of the file be changed

**How to reproduce it (as minimally and precisely as possible)**:
Create a file, and enter this code (for me is this) : 
```javascript
const { compile } = require('nexe');

compile({
    input: './index.js', // Input bundle file path
    output: './dist/test-rpc', // Output executable file path
    target: 'windows', // An object or string describing platform-arch-version
    resources: [
        './node_modules/**/*'
    ],
    rc: {
        CompanyName: "FellGill",
        ProductName: "Test RPC",
        FileDescription: "A NodeJS integration of Test for Discord",
        FileVersion: "0,0,1",
        ProductVersion: "0,0,1",
        OriginalFilename: "test-rpc.exe",
        InternalName: "test-rpc",
        LegalCopyright: "Copyright FellGill. Apache 2.0 license."
    } // Settings for patching the node.rc configuration file
})
```

**Environment**:
- Platform(OS/Version): Windows v1909
- Host Node Version: 12.14.1
- Target Node Version: 12.14.1
- Nexe version: 3.3.2
- Python Version: 3.8.3

**Comment by s-a** [comment]
As far as I understand you need you need to pass parm to rebuild from source. Unfortunately this seems to be broken function at the moment

**Comment by s-a** [comment]
I can confirm that this works when you build node from source. I can't tell if this is how the original artist imagined it.

**Comment by Monsupito** [comment]
Mhhh I see, I'll see if I can't do a few things

**Comment by calebboyd** [comment]
This is by design. rc settings will only apply if build:true is set.

If you want to modify the binary prior to building you can operate on the temporary artifact downloaded to `~/.nexe/<target>` using the rcedit package

**Comment by Monsupito** [comment]
Thanks !
