### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HideakiAtsuyo** [nexe/nexe#781]
HP@Windobe MINGW64 ~/Desktop/Midorya-master/a
$ nexe index.js --build -f
i nexe 3.3.2
√ Already downloaded...
√ Compiling Node with arguments: nosign,release,x64
√ Finished in 1.493s

Error: vcbuild.bat nosign release x64 exited with code: 1

See nexe -h for usage..

**Comment by calebboyd** [comment]
See https://github.com/nodejs/node/blob/master/BUILDING.md and ensure your environment is setup correctly. See additional logs with `--verbose`
