### ISSUE TITLE
How to achive build from source once?

### ISSUE THREAD

**Issue by s-a** [nexe/nexe#785]
**What happened**:
nexe always recompiles node from source code when I change the temp folder. When I do not change temp folder nexe uses previous build to create exectable. Which is much faster!

**What you expected to happen**:
nexe should use previous builds .

**How to reproduce it (as minimally and precisely as possible)**:
add temp to compile config.

**Anything else we need to know?**:
I tried snapshot config property but not sure how to use it.

Is snapshot responsible settings for this purpose?

**Comment by calebboyd** [comment]
You deleted the template and this feature is different across versions, Please indicate what version you're using.

**Comment by s-a** [comment]
@latest 3.3.3

**Comment by calebboyd** [comment]
Do you have a reproduction? I can't reproduce the issue.
```
code/test > echo "console.log('hello world')" | nexe --temp my-temp-dir --build -t 12.14.0 --make="-j8" -o hi
ℹ nexe 3.3.3
✔ Already downloaded...
✔ Compiling result
✔ Entry: '[stdin]' written to: hi
✔ Finished in 0.098s
code/test > ./hi
hello world
code/test > ls | grep my-temp
my-temp-dir
```

**Comment by s-a** [comment]
I can confirm that this works as expected for x64 builds. Seems the problem occurs in 32bit mode.
 Here my config. 
```javascript
{
  input: 'C:\\src\\my-app\\lib\\index.js',
  output: 'C:\\src\\my-app\\dist\\my-app-win32-x86.exe',
  target: 'win32-x86-12.13.1',
  build: true,
  vcBuild: [ 'nosign', 'release' ],
  ico: 'C:\\src\\my-app\\resource\\icon\\icon-set.ico',
  resources: [ './package.json', 'public/**/*' ],
  rc: {
    ...
  },
  temp: 'C:\\src\\my-app\\.build\\win32-x86'
}
```

Can you explain the snapshot property? [docs](https://github.com/nexe/nexe#snapshot-string) does not tell so much about functionality but I feel it could help. 

I figured out that in my temp folder for x64 is as file called `windows-x64-12.13.1`. in x86 the does not exist. I think this could be the problem.

**Comment by calebboyd** [comment]
Snapshot refers to a v8 snapshot https://v8.dev/blog/custom-startup-snapshots
Removing the artifact `C:\\src\\my-app\\.build\\win32-x86\\12.13.1\\Release\\node.exe` before building nexe will speed up your builds

**Comment by s-a** [comment]
Well this does not realy make a difference. maybe depends on x86 arch, but I think it should work for precompiled binaries without `--build`? For that reason I would leave issue open otherwise would close it. Anyway thank! you for the support. This means a lot.

**Comment by calebboyd** [comment]
You can use [rcedit](https://www.npmjs.com/package/rcedit) module in a plugin
this is editing the downloaded (not built) binary before its being written to your specified output.

```javascript
compile({
  ...
  plugins: [
    async (compiler, next) => {
      location = compiler.getNodeExecutableLocation(compiler.target);
      await rcedit(location, { ico: '...' })
      return next();
    }
  ]
})
```
