### ISSUE TITLE
vcbuild error

### ISSUE THREAD

**Issue by calebboyd** [nexe/nexe#787]
Any workaround on that? When I try: nexe -t windows-x64-12.16.3 or nexe -b windows-x64-12.16.3, I'm getting the error:
```
i nexe 3.3.2
√ Already downloaded...
√ Compiling Node with arguments: nosign,release,x64
√ Finished in 2.089s

Error: vcbuild.bat nosign release x64 exited with code: 1
```

_Originally posted by @Krzysztof-Dziardziel in https://github.com/nexe/nexe/issues/768#issuecomment-648798185_

**Comment by calebboyd** [comment]
See the documentation on using `-b` and compiling node.

**Comment by Krzysztof-Dziardziel** [comment]
`nexe --build x64-12.16.3`
Also yields an vcbuild error.

**Comment by calebboyd** [comment]
`--verbose` will indicate what the error is from that build script.

Here is the documentation: https://github.com/nexe/nexe#compiling-node, follow the link on how to "build node"

**Comment by Krzysztof-Dziardziel** [comment]
Even after BoxStarter installation and installation of nodejs bootstrap package build still fails.
`i nexe 3.3.2
√ Already downloaded...
√ Compiling Node with arguments: nosign,release,x64
√ Finished in 1382.541s

Error: vcbuild.bat nosign release x64 exited with code: 1`

**Comment by calebboyd** [comment]
Please use the verbose flag and then follow the directions indicated in the error.
https://github.com/nexe/nexe/issues/787#issuecomment-648868296
