### ISSUE TITLE
Output program won't run when npm package sharp is installed.

### ISSUE THREAD

**Issue by NomisIV** [nexe/nexe#790]
**What happened**:

When trying to start the compiled program, I get the following error:

```
Error:
Something went wrong installing the "sharp" module

Module did not self-register.

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues
```

**What you ~expected~ hoped to happen**:

It would just work

**How to reproduce it (as minimally and precisely as possible)**:

Build a project which requires sharp, and try to start it.

**Anything else we need to know?**:

Sharp relies on external libraries. I tried to include `node_modules/sharp/**/*` as a resource to nexe without success. I suspect nexe might mess up the file path of the libraries, and thus confuse sharp to the point of failure.

Link to the repo and npm page:
* [github](https://github.com/lovell/sharp)
* [npm](https://www.npmjs.com/package/sharp)

**Environment**:

Not sure if this matters, but I filled it out anyway:

- Platform(OS/Version): GNU/Linux (Arch Linux) 5.7.7-arch1-1
- Host Node Version: v14.5.0
- Target Node Version: v12.14.0
- Nexe version: 3.3.7
- Python Version: 3.8.3

**Comment by baparham** [comment]
Sharp compiles it's primary dependency into a native `sharp.node` library because it depends on `libvips` Did you bundle the .node file alongside your executable for `sharp` to work from? It's likely in `./node_modules/sharp/build/Release/sharp.node` and should be handled like described in #811 or #639.

**Comment by NomisIV** [comment]
Thanks for the reply, but I'm not working on that project anymore, so I'll go ahead and close this for now
