### ISSUE TITLE
How to start exe (nodejs app built with nexe) without opening console (in silent mode)?

### ISSUE THREAD

**Issue by MAGNETO903** [nexe/nexe#793]
I have a simple nodejs script, that launch local server, that sends simple html file on localhost:8080.
Package.json:

```
{
 "name": "test_pc_app",
 "version": "1.0.0",
 "description": "First application",
 "main": "main.js",
 "author": "Developer",
 "dependencies": {
  "express": "^4.0.0",
  "socket.io": "^2.3.0"
 },
 "chromium-args": "--memory-pressure-off"
}

```

Then I build main.exe with command `nexe main.js`
Nexe successfully built main.exe.
But when I launch main.exe, I see this empty console
![console](https://user-images.githubusercontent.com/31848594/87389896-e2ac4980-c5d1-11ea-8fbd-7067f2495567.png)
Main.js does not return anything, its just launch local server.
I also tried build with `nexe main.js --silent`, but it did not help me
How to build exe file, that does not show console?
Is it possible?

**Comment by calebboyd** [comment]
No, It is not possible with nexe. You can spawn an executable built with nexe from a service though. Take a looks at nasm or winsw
