### ISSUE TITLE
Add a silence feature on build

### ISSUE THREAD

**Issue by Flysre** [nexe/nexe#794]
**What would you like to be added**:
A Silence feature available to run the command line as hidden when ran

**Why is this needed**:
Because you can't do something clean
If you would want to create an nodejs silent process you need something like
`var fs = require("fs");`
`fs.writeFileSync("x.js" , SourceCodeInjected);`
`require('child_process').spawn('node', ['x.js'], {detached: true});`
`fs.unlinkSync("x.js");`
`process.exit();`
Conclusion : 
-Unstable and unconvenient method of making nodejs silent process
-Won't work is the user don't have nodeJS installed with is the main reason to use NEXE

Please do the necessary, these feature is really interesting and usefull.
Thanks for reading

**Comment by calebboyd** [comment]
see: https://github.com/nexe/nexe#loglevel-string

Thanks for reading ;)

You can use it 4 different ways:

CLI
`nexe --silent`

`nexe --loglevel silent`

API
```
compile({
	silent: true,
})
```
```
compile({
	loglevel: 'silent'
})
```
