### ISSUE TITLE
[win32]- launch as windowless

### ISSUE THREAD

**Issue by xPythh** [nexe/nexe#795]
SEE <https://github.com/nexe/nexe/issues/794>

This is not what we wand, but a silent console, no console visible when starting the program, everything runnning in a background without the console visible.

+ The The fact that using service as a method is not convenient. The objective is to make nodeJs silent by the .exe itself.

**Comment by calebboyd** [comment]
If you'd like to add a PR to support this that would be welcomed, As of now it is not something that node core has supported, so it would likely be a large undertaking and difficult to maintain.

You can see from the previous issues that have been opened that this has been solved in other ways

https://github.com/nexe/nexe/issues/133#issuecomment-143292126
https://github.com/nodejs/node/issues/556#issuecomment-538060415

**Comment by Flysre** [comment]
I mean im not gonna talk for nothing but i remember 1000% found in the past a nodejs module that did that,, and it was also working with nexe or PKG modules..
Its sad that its not even possible to hide the console.

**Comment by calebboyd** [comment]
Yeah, I just linked the comment with that module
https://www.npmjs.com/package/create-windowless-app

That project uses this project to make your executable windowless.

**Comment by Flysre** [comment]
These kind of modules are like really big and have many dependencies, if this package is able to hide the window, maybe it would be worth it to look about it :+1:

**Comment by ChronSyn** [comment]
If windowless is a game-breaker for you, the best solution is to run it as a service. There are numerous solutions out there that will allow you to install and run any exe as a service, whether it's node or not.

There's only 1 limitation I've found with this, and that is launching a GUI program will not work correctly as services are run under their own user. A workaround to this is to write a separate program which can launch the GUI program under a different user account (I built a small solution in C# to get past this exact limitation). If you're not in need of launching a GUI program from the nexe app, then there's not much you can't do.

**Comment by calebboyd** [comment]
related to #374

**Comment by eladkarako** [comment]
<blockquote> * The The fact that using service as a method is not convenient. The objective is to make nodeJs silent by the .exe itself.<sup><a href="https://github.com/nexe/nexe/issues/795#issue-657110431">1</a></sup></blockquote>

1. get `node.exe` 
<sub>(for example: https://nodejs.org/download/nightly/v18.0.0-nightly20220209bd86e5186a/win-x86/node.exe)</sub>
2. patch it: `editbin.exe /NOLOGO /SUBSYSTEM:WINDOWS "node.exe"`.
<sub>(note: `console.log` won't work, for obvious reasons.. instead - write logs to files).</sub>
3. use that `node.exe` for your scripts.

<sub>source: <a href="https://github.com/eladkarako/NodeJSW" title="https://github.com/eladkarako/NodeJSW">github.com/eladkarako/NodeJSW</a></sub>
