### ISSUE TITLE
Always shows the node.js REPL

### ISSUE THREAD

**Issue by Esporia** [nexe/nexe#797]
My environnement:
os : windows 10
node.js : 14.5.0
nexe :  3.3.7 
nvm-windows : 1.1.7

Every time I create a new executable file (with command `nexe index.js`) for example, with this project : https://github.com/nexe/nexe/tree/master/examples/express-app and then i execute the created file, it always shows the node.js REPL in a cli

```
Welcome to Node.js v14.5.0.
Type ".help" for more information.
>  
```   

How can I fix that ? What was wrong ?

**Comment by calebboyd** [comment]
This will be resolved with #754
