### ISSUE TITLE
Linux pre-build packages missing after 12.16.2, cannot compile 12.18.2

### ISSUE THREAD

**Issue by Corben78** [nexe/nexe#798]
**What happened**:
Using nexe to build binary on Linux fails:
```
Error: https://github.com/nexe/nexe/releases/download/v3.3.3/linux-x64-12.18.2 is not available, create it using the --build flag
```

**What you expected to happen**:
Either downloading pre-build package succeeds, or local compilation works

**How to reproduce it (as minimally and precisely as possible)**:
Having any nodejs project with an entry for building with nexe:
```
"scripts": {
    "build": "nexe"
}
```
And running `npm run build` will result in the error above.

**Anything else we need to know?**:
Trying to build nexe manually fails, looks like the generated `node.cc` file contains errors with comments, e.g. line 765:
```
    const int exit_code = 0;//ProcessGlobalArgs(&env_argv,
                                            nullptr,
                                            errors,
                                            kAllowedInEnvironment);
```
And line 773:
```
  const int exit_code = 0;//ProcessGlobalArgs(argv,
                                          exec_argv,
                                          errors,
                                          kDisallowedInEnvironment);
```

**Environment**:
- Platform(OS/Version): Ubuntu 18.04.4 LTS
- Host Node Version: v12.18.2
- Target Node Version: v12.18.2
- Nexe version: 3.3.7
- Python Version: 2.7.17

**Comment by Corben78** [comment]
My current workaround is now to use a special build entry for Linux with the currently last existing pre-build version:
```
"scripts": {
    "build": "nexe",
    "buildlnx": "nexe -t 12.16.2"
}
```
Just saw #777 which has a similar topic, except that meanwhile it seems the Windows and Mac pre-build packages up to 12.18.2 are there. It doesn't mention the compilation error for 12.18.2 on Linux though.

**Comment by baparham** [comment]
I can build node `v12.18.3` from the source, so what's different about the nexe specific source that is checked out for building with nexe?

building 12.18.3 via nexe fails for me in the same way as the OP.

**Comment by alxproject** [comment]
the build works for me on windows and linux for node 12.18.2 but with nexe@beta (nexe@4.0.0-beta.14), for node 12.18.3 the build success but the binary fails to load any external node module

**Comment by rahbari** [comment]
building 14.12.0 fails with the same problem.

**Comment by calebboyd** [comment]
Closing in favor of #754
