### ISSUE TITLE
unable to compile with @aspnet/signalr module

### ISSUE THREAD

**Issue by Granaat** [nexe/nexe#801]
When compiling nexe refuses to include the @aspnet/signalr module in the build.

A workaround is placing the module in a nodemodules folder next to the exe, but this isn't very user friendly

**Comment by calebboyd** [comment]
Please provide the information requested in the issue template so that this issue can be reproduced.

**Comment by Granaat** [comment]
**What happened**: 
When compiling nexe refuses to include the @aspnet/signalr module in the build.

**What you expected to happen**:
SignalR to work when the exe runs

**How to reproduce it (as minimally and precisely as possible)**:
- new node project
- start new thread in a worker
- use @aspnet/signalr in worker
- create exe through nexe

**Anything else we need to know?**:
/

**Environment**:
- Platform(OS/Version): Win Server 2016 (+ other versions)
- Host Node Version: v12.8.0
- Target Node Version: v12.8.0
- Nexe version: 3.3.2
- Python Version: na

**Comment by calebboyd** [comment]
You may need to include your worker entrypoint with the `-r` option if it isn't staticaly analyzable.

**Comment by AndyClausen** [comment]
I think I'm having a similar problem - I'm creating a CLI that uses `googleapis`, which in turn uses `google-gax`. When running the application, I get:
```
Error: error reading first path in the walk C:\<path where exe is>\node_modules\google-gax\protos
Error: ENOENT: no such file or directory, lstat 'C:\<path where exe is>\node_modules\google-gax\protos'
at EventEmitter.<anonymous> (C:\<path where exe is>\node_modules\walkdir\walkdir.js:265:28)
[more stacktrace omitted]
```

@Granaat Can you post your error message? It seems like mine is related to reading files, and it seems like it can't find some non-js in my case - maybe it's the same for you.

@calebboyd Is nexe supposed to be able to find non-js files in indirect dependencies? I even tried running with `-r ./node_modules/google-gax/protos/**/*` to make sure it's getting packaged, but still getting the error. It works when I run it in my project folder (where `node_modules` is).

I'm on nexe v3.3.7 on Windows 10 (using git bash, hence the forward slashes).
