### ISSUE TITLE
Node .exe not working.

### ISSUE THREAD

**Issue by hackermondev** [nexe/nexe#807]
**What happened**:
So I have a program that has some node_modules and I wanted to package it into a .exe file so I did ``nexe -r "./node_modules/**/*"`` that worked perfectly but now I have another problem. When I run the file it just opens my ``Command Prompt`` and closes it and the program doesn't work. The program is supposed to console.log something and then run some things.

**What you expected to happen**:
I expect my program to open a Command Prompt and run the program in the Command Prompt then close when done.

**How to reproduce it (as minimally and precisely as possible)**:
The repo isn't public so no.

**Anything else we need to know?**:

Not really.

**Environment**:
- Platform(OS/Version): Windows
- Host Node Version: v12.18.0
- Target Node Version: v12.18.0
- Nexe version: 3.3.7
- Python Version:

**Comment by calebboyd** [comment]
What happens if you run your program from an existing command prompt?

**Comment by NoobKeksTV** [comment]
similar issue here. it opens the prompt and then stops it instantly.
