### ISSUE TITLE
Generating error while interacting with C# DLL

### ISSUE THREAD

**Issue by Abhishek150995** [nexe/nexe#810]
I have an application that interacts with C# Dll using 'edge-js'. Earlier I used electron to package the application so I used 'electron-edge-js' node modules, it worked perfectly fine. But now I want to switch to nexe packaging, but its generating error that it cannot find the 'edge-js' module at a particular location

**_Error: The specified module could not be found.
\\?\C:\Users\..\Desktop\...\....\..\....\xyz\node_modules\edge-js\lib\native\win32\x64\12.13.0\edge_nativeclr.node_**

And when I explicitly place the node_modules at the location it generates different error

**_Error: Module did not self-register._** 

Please suggest!

**Comment by Abhishek150995** [comment]
@calebboyd  Please Suggest. Thanks in advance

**Comment by calebboyd** [comment]
Are you building for target win32-x64-12.3.0? Please include the information from the template so we can help!

**Comment by Abhishek150995** [comment]
I am using the following command

**call nexe -i %~dp0AbcModule/"index.js" --resources %~dp0AbcModule/**/* -o %~dp0Abc\ExeName --vcBuild x64**

same issue occurs even if I try with 

**call nexe -i %~dp0AbcModule/"index.js" --resources %~dp0AbcModule/**/* -o %~dp0Abc\ExeName**

**Comment by Abhishek150995** [comment]
Also

During debug require('edge-js') refers to:
"C:\Users\...\Desktop\....\node_modules\edge-js\edge-js.d.ts" file 

but after creating exe it tries to find the following file
?\C:\Users..\Desktop.............\xyz\node_modules\edge-js\lib\native\win32\x64\12.13.0\edge_nativeclr.node

Why is this so. Please help

**Comment by calebboyd** [comment]
see #639
