### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by s-a** [nexe/nexe#816]
**What happened**:
via `cmd.exe`

```bash
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '[HIDEN_PATH].\lib\index.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:690:27)←[39m
←[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)←[39m
←[90m    at internal/main/run_main_module.js:17:11←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}
``` 
**Anything else we need to know?**:
If i run the executable within powershell everything works as expected

**Environment**:
- Platform(OS/Version): windows 10
- Host Node Version: 12.13.1
- Target Node Version: 12.13.1
- Nexe version: 3.3.2
- Python Version: 2.7.15

**Comment by JacobNorlin** [comment]
I have noticed this issue as well but when running a linux executable. It seemed related to requiring in files from subfolders.
A minimal example I used to test this:
```
+--lib/
|   +--library.js
+--index.js
```
```
library.js
--
function foo(){
    console.log('bar');
}

module.exports = {foo};
```
```
index.js
--
var {foo} = require('./lib/library.js);

foo();
```
```
build.js
--
var {compile} = require('nexe');

compile({
    input: 'index.js',
    output: 'dist/test',
    target: 'linux-x64-12.16.2',
    loglevel: 'verbose'
});
```

When moving library.js to the same folder as index.js the executable works as expected.

**Comment by calebboyd** [comment]
closing in favor of #841
