### ISSUE TITLE
Node goes to CLI without argument

### ISSUE THREAD

**Issue by rahbari** [nexe/nexe#817]
I used nexe master branch to build node 14.12 on Centos 7.
When I run packaged app as usual it goes to Node CLI, but when any arguments like 1 is passed it works as expected.
```
./app  # goes to Node CLI
./app 1 # everything works
```

**Environment**:
- Platform(OS/Version): Centos 7
- Host Node Version: 14.12
- Target Node Version: 14.12
- Nexe version: Master Branch

**Comment by pundoo** [comment]
Same issue on Windows. Only Node-14.x builds are causing this!

**Comment by misterkoko** [comment]
Anyone perhaps found any solutions or a workaround? On Windows it doesn't even work if you pass arguments.

Contrubitors don't seem to be very active with helping issues here.

**Comment by calebboyd** [comment]
I think @bruce-one (THANKS) fixed this one

**Comment by ebw44** [comment]
This bug still seems to be present with:
- Platform(OS/Version): Windows 11
- Host Node Version: 16.17.0
- Target Node Version: 14.5.0 (prebuilt)
- Nexe version: 4.0.0-rc.1
