### ISSUE TITLE
Literal notation RegExp fail when output is not in current folder

### ISSUE THREAD

**Issue by yoavain** [nexe/nexe#818]
**What happened**:
```
Error: Cannot find module 'C:\Dev\nexe-test\dist\_compile\index.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:842:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}
```

**Took me a while to find the line causing the error...**

**How to reproduce it (as minimally and precisely as possible)**:
Running nexe with the following code:
```js
const regex = /abc/mgs;
const str = "abc\ndabce";
const matches= str.match(regex);
```
With the following command:
```
nexe -t windows-x64-12.18.2 -o dist/nexe-test.exe
```

**Workaround 1**:
Changing the line:
```js
const regex = /abc/mgs;
```
To:
```js
const regex = new RegExp('abc', 'mgs');
```

**Workaround 2**:
Setting output to the same folder
```
nexe -t windows-x64-12.18.2 -o nexe-test.exe
```

**Environment**:
- Platform(OS/Version): Windows 10
- Host Node Version: 14.13
- Target Node Version: 12.18.2
- Nexe version: 3.3.7

**Comment by calebboyd** [comment]
Works in the latest version (nexe@next).

I have to assume this was probably a parser bug.
