### ISSUE TITLE
How to use --resource with mutilple folders?

### ISSUE THREAD

**Issue by tracer8** [nexe/nexe#819]
Hi,
I tried to use --resource with mutilple folders, but nothing work, can you show me correct command?
What i tried:
```
nexe app.js --resource ["scripts/*", "assets/*"]
nexe app.js --resource "scripts/*" "assets/*"
nexe app.js --resource "scripts/*" --resource "assets/*"
```

I understand it can use string array, but did't said how to use string[] in cmd
```
resources: string[]
Array of globs with files to include in the build
Example: ['./public/**/*']
default: []
```

**Comment by calebboyd** [comment]
Its a regular glob pattern eg. `"{scripts,assets}/**/*"`

**Comment by tracer8** [comment]
Oh, thank you so much, now i got it!
