### ISSUE TITLE
Missing node versions

### ISSUE THREAD

**Issue by Denisiums** [nexe/nexe#821]
2020-10-06 new node version was released.

https://github.com/nexe/nexe/releases has only 12.18.2 and nothing later.

**Comment by Kampflaus** [comment]
It would be awesome if @calebboyd adds some newer versions (12.18.3, 12.18.4, 12.9.0). I was having trouble to build them myself in my nexe script.

**Comment by alxproject** [comment]
the build not working for this version either

**Comment by Kampflaus** [comment]
Still having problems with node 12.18.4 and the latest nexe version (4.0.0-beta15):

C:\path\binary.exe:1
♠
^

SyntaxError: Invalid or unexpected token
←[90m    at wrapSafe (internal/modules/cjs/loader.js:1053:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1101:27)←[39m
←[90m    at internal/bootstrap/pre_execution.js:133:36←[39m
←[90m    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:134:3)←[39m
←[90m    at internal/main/run_main_module.js:7:1←[39m

Any ideas?

**Comment by calebboyd** [comment]
closing in favor of #754
