### ISSUE TITLE
Next Major Version

### ISSUE THREAD

**Issue by calebboyd** [nexe/nexe#823]
Going to be using this issue as a template for the next major version TODOs/Roadmap. Requests welcomed.

**What would you like to be added**:

 - [ ] Drop Node 10 Support
 - [ ] Drop Multiple current versions of never LTS builds (11,13,15..etc)
 - [ ] Documentation for supported versions
 - [ ] Documentation for native module usage
 - [ ] Generate signable (pre-built) binaries, quickly, with javascript (Browser compatible)
 - [ ] Refactor codebase and reduce dependencies
 - [ ] Warn on implicit CLI behavior, name, version, input etc.
 - [ ] Add bytecode support
 - [ ] Improved (maintained) filesystem shim

**Comment by luffs** [comment]
It would be great to have ESM support.
I have a backend that uses [standard-things/esm](https://github.com/standard-things/esm), and I'm trying to figure out how I can run it with nexe at the moment. Maybe compile to CommonJS before bundling or something.
