### ISSUE TITLE
Increasing max-old-space-size in node.js app running as Windows service

### ISSUE THREAD

**Issue by theoremme** [nexe/nexe#825]
I'm relatively new to node.js and have built an app that is designed to be deployed as a windows service (via node-windows) using a standalone application without the need to install node.js or any of its dependencies.

I'm running into an issue where in specific, not easily reproducible instances, the app crashes and the I get a "Javascript heap out of memory" error.

While I'm debugging the root cause, I'm trying to increase the heap size. I've tried a great number of things I've found in other forum responses including:

- Various version of Python 2x & 3x
- Running "build": "nexe --enableNodeCli --build" in the build script and adding --max-old-space-size=4096 to the shortcut target
- Ugrading (and eventually rolling back) Node.js
- Adding --max-old-space-size=4096 to NODE_OPTIONS in Windows environment variables
- Adding nodeOptions: ['--max-old-space-size=4096'] into the service options

..among others. These just seem to be the most common solutions suggested.

Some of these solutions resulted in an inability to run the build. Others run, however the memory remains at around 1.42 GB according to v8.getHeapStatistics.
......

OS: Windows 10
Node: 10.22.1 (have also tried 12.19.0)
Nexe: 3.3.7
Python: 2.7.17 (have also tried 2.7.16, 2.7.14, 3.7, 3.8 & 3.9)
......

```
const fs = require('fs');
const v8 = require('v8');

const Service = require('node-windows').Service
var svc = new Service({
    name: 'VDE',
    description: 'VDE',
    script: __dirname + '/index.js',
    execPath: __dirname + '/VDE.exe',
    abortOnError: false,
    nodeOptions: [
        '--max-old-space-size=4096'
    ],
    env: {
        name: 'NODE_OPTIONS',
        value: '--max-old-space-size=4096'
    }
})

var EventLogger = require('node-windows').EventLogger;
var log = new EventLogger('VDE Event Log');

checkUsage()
 
svc.on('install',function(){
    svc.start();
});

svc.on('start',function(){
    log.info(`VDE is running.`);
    
})

svc.on('error',function(err){
    log.error(`Error: ${err}`);
})

svc.on('stop',function(){
    log.warn(`Service has stopped.`);

    svc.start();
})

if (svc.exists == false){
    svc.install();
    log.info(`Windows service for VDE does not exist. Installing now....`);
}else{
    log.info(`Windows service for VDE already exists!`);
    svc.start();
};

function checkUsage(){
    let heapSize = (v8.getHeapStatistics().heap_size_limit / 1024 / 1024 / 1024).toFixed(2);

    log.info(`Heap: is ~${heapSize} GB`);
}
```

**Comment by calebboyd** [comment]
Does the high memory usage occur when you run you app without nexe?

**Comment by theoremme** [comment]
Through command line? Short answer: I don't know because I haven't tried.

Long answer: My production environment is quite different from my dev environment and comes with a much higher volume of chatter. The app monitors TCP socket communication, filters out particular reports and then reacts to them.

I haven't installed node.js in the production environment - the app/service is meant to be standalone with no internet access or prerequisites required. This is because the machines as a whole are a complicated multi-step process to set up and we're trying to limit the complexity as much as possible for scalability.

If it's helpful though, I may be able to set up one of the systems in the network strictly for debugging purposes and run the app through cli.

**Comment by theoremme** [comment]
Side note: I am able to increase max-old-space size when adding it as a parameter and running from command line:

`node --max-old-space-size=4096 index.js`

`Heap is: ~4.10 GB`

**Comment by tony-gutierrez** [comment]
It looks like you are using node-windows to launch a nexe app (VDE.exe) instead of node, which will then take index.js as an argument? 

Node-windows is not designed to wrap an executable, it's designed to wrap a script. They specifically mention not using it to make a self contained exe into a service.

**Comment by calebboyd** [comment]
For Windows services that are nexe executables, I've run the following (pseudo code) for their install scripts.

```
  async installAsync(appName, installDir) {
    await this.extractWinswConfig(installDir)
    await this.winswInstall(installDir)
    await this.startAsync(appName, installDir)
  }
```

[winsw](https://github.com/winsw/winsw) can be configured for logging/rotation self restart etc.

I think last time I looked this was also what node-windows used under the hood.

**Comment by theoremme** [comment]
@tony-gutierrez I removed the execPath line and it seems to have fixed that portion of my issue. When I run the install script in command line it logs a heap size of about 4 GB. However I still have the issue that I need this to run in a nodeless environment. I'm currently trying to package the install script itself as an exe (although I may be misunderstanding the mechanics behind this.) 

@calebboyd I'll take a look at winsw as an alternative.

Thank you both for you help - I'll let you know how it goes.

**Comment by theoremme** [comment]
@tony-gutierrez So far I haven't made much progress with this. When I run node install-service.js it works perfectly. However I can't do this in a nodeless environment. (Right? Again, still a little green here.)

When I try and package install-service.js into an executable using nexe, I can't seem to get it to run index.js when it starts, it just wants to run install-service.js. When I combine index.js and install-service.js it runs fine but again, I lose control of --max-old-space-size.

@calebboyd I'm not totally understanding where I can use that script to install the service in a nodeless environment. Can you please elaborate some?

**Comment by calebboyd** [comment]
Closing in favor of #616
