### ISSUE TITLE
Exe can be paused if running in an interactive command prompt?

### ISSUE THREAD

**Issue by tony-gutierrez** [nexe/nexe#826]
**What happened**:
Compiled exe with nexe. Launched a cmd prompt with "cmd". Launched exe inside command prompt. Exe starts outputting console messages. Scroll up and click cursor on an old console message. Exe functionality pauses (no more output, web server wont respond, etc). Scroll to bottom and hit enter, exe resumes functionality.

**What you expected to happen**: Expect exe to ignore cmd prompt cursor and mouse interaction.

**How to reproduce it (as minimally and precisely as possible)**: See above.

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version): win 10
- Host Node Version: 12
- Target Node Version: 12
- Nexe version: latest
- Python Version:

**Comment by calebboyd** [comment]
You're likely in quick edit mode which will indefinitely pauses your program when you make selections

https://stackoverflow.com/questions/30418886/how-and-why-does-quickedit-mode-in-command-prompt-freeze-applications/30517482#30517482

**Comment by tony-gutierrez** [comment]
Thanks. Not nexe specific then. Closing
