### ISSUE TITLE
child_process.fork() fails when passing execArgv

### ISSUE THREAD

**Issue by tsmaeder** [nexe/nexe#831]
**What happened**:
Running the vscode typescript extension from a nexe'd plugin host in Eclipse Theia fails: it turns out the spawned typescript language server crashes upon startup. Analysis showed that when using child_process.fork(), node tried to execute the first argument from options.execArgv

**What you expected to happen**:
It works when using node, I would expect the behavior to be the same.

**How to reproduce it (as minimally and precisely as possible)**:
Run nexe 3.7.3 on this script (main.js)
```
var cp = require("child_process");
console.log('executing sub');
cp.fork('sub.js', ['subarg'], {
    silent: false,
    execArgv: ['--max-old-space-size=3072', '--use-bundled-ca']
});
```

Running the resulting binary produces the following error:

``` 
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module '--max-old-space-size=3072'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
``` 

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version): Windows 10, Linux
- Host Node Version: 12.18.2
- Target Node Version: 12.18.2
- Nexe version: 3.7.3
- Python Version: ?

**Comment by tsmaeder** [comment]
Generally, the argv seems to be quite different when running a nexe'd script vs running the same script in node.

**Comment by tsmaeder** [comment]
I tried `nexe -i main.js --enableNodeCli` but that did not change the outcome.

**Comment by tsmaeder** [comment]
Noticed that `--enableNodeCli` probably needs -build to work. Doh!

**Comment by tsmaeder** [comment]
so after doing `nexe main.js --build --enableNodeCli` I get a new error when running main.exe:
```
internal/modules/cjs/loader.js:1078
  callbackMap.set(compiled.cacheKey, {
              ^

TypeError: Cannot read property 'set' of undefined
[90m    at wrapSafe (internal/modules/cjs/loader.js:1078:15)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1102:27)[39m
[90m    at internal/bootstrap/pre_execution.js:118:36[39m
[90m    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:119:3)[39m
[90m    at internal/main/run_main_module.js:7:1[39m
```

**Comment by tsmaeder** [comment]
Hmh...even without --enableNodeCli, the built executable fails with the above error.

**Comment by tsmaeder** [comment]
found https://github.com/nexe/nexe/issues/768

**Comment by tsmaeder** [comment]
Turns out this works when combining the right version of node with the right version of nexe. It would be helpful to know which version of node can be used with "--build" for each nexe version.

**Comment by JeffJassky** [comment]
Can you share which version of node and nexe you got this to work with? I'm having the same issue.
