### ISSUE TITLE
Nexe's exe doesnt emit process.on('exit') when i close it 

### ISSUE THREAD

**Issue by vorpax** [nexe/nexe#836]
Hello, when i close the exe that i've generated with node, it doesn't emit process.on('exit'). 

The thing is that i need to do a call to an api when someone is closing my exe.

**Comment by calebboyd** [comment]
Please fill out a new issue with steps that you have tried. I can't reproduce this

eg:
```
code/test > echo "console.log(process.version); process.on('exit', () => console.log('exiting'))" | nexe -o out -t 14.15.3
ℹ nexe 4.0.0-beta.15
✔ Already downloaded...
✔ Compiling result
✔ Entry: '[stdin]' written to: out
✔ Finished in 0.115s
code/test > ./out
v14.15.3
exiting
```
