### ISSUE TITLE
Build error 12.16.2

### ISSUE THREAD

**Issue by wiseguysby** [nexe/nexe#838]
**What happened**:
Error build with syntaks
nexe soft.js -t linux-x64-12.16.2 --build --verbose

**Environment**:
- Platform(OS/Version): CentOS Linux release 7.9.2009 (Core)
- Host Node Version:  14.15.1
- Target Node Version: 12.6.2
- Nexe version: 3.3.7
- Python Version: 2.7.5
- Gcc : 8.4.0

Error message :
../src/node.cc: In function ‘int node::InitializeNodeWithArgs(std::vector<std::__cxx11::basic_string<char> >*, std::vector<std::__cxx11::basic_string<char> >*, std::vector<std::__cxx11::basic_string<char> >*)’:
../src/node.cc:762:45: warning: left operand of comma operator has no effect [-Wunused-value]
                                             errors,
                                             ^~~~~~
../src/node.cc:763:45: warning: right operand of comma operator has no effect [-Wunused-value]
                                             kAllowedInEnvironment);
                                             ^~~~~~~~~~~~~~~~~~~~~
../src/node.cc:763:66: error: expected ‘;’ before ‘)’ token
                                             kAllowedInEnvironment);
                                                                  ^
                                                                  ;
../src/node.cc:763:67: warning: right operand of comma operator has no effect [-Wunused-value]
                                             kAllowedInEnvironment);
                                                                   ^
../src/node.cc:770:43: warning: left operand of comma operator has no effect [-Wunused-value]
                                           errors,
                                           ^~~~~~
../src/node.cc:771:43: warning: right operand of comma operator has no effect [-Wunused-value]
                                           kDisallowedInEnvironment);
                                           ^~~~~~~~~~~~~~~~~~~~~~~~
../src/node.cc:771:67: error: expected ‘;’ before ‘)’ token
                                           kDisallowedInEnvironment);
                                                                   ^
                                                                   ;
../src/node.cc:771:68: warning: right operand of comma operator has no effect [-Wunused-value]
                                           kDisallowedInEnvironment);

Error: make  exited with code: 2

**Comment by bruce-one** [comment]
The latest beta release has a fix for this :-)

**Comment by wiseguysby** [comment]
oh..greatttt...thanks for your support
