### ISSUE TITLE
Different result between centos and windows 7 x64

### ISSUE THREAD

**Issue by wiseguysby** [nexe/nexe#839]
**What happened**:
I have a project, when running nexe in centos with -t windows-x64-10.15.3 --r node_modules/**/**, file result can running well at windows 7 x64, but when running nexe --r node_modules/**/** in windows 7 x64, file result cannot running well, still looking file node_modules

**What you expected to happen**:
should be running well without node_modules directory

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I have delete node_modules and npm install again, but still problem. 

**Environment**:
- Platform(OS/Version): Centos 7 / Windows 7 x64
- Host Node Version: Centos ( 12.16.2) / windows  ( 10.15.3)
- Target Node Version: windows-x64-10.15.3
- Nexe version: 3.3.7
- Python Version: 2.7.15

**Comment by calebboyd** [comment]
Are there specific packages you're using that seem to not be included when you build from windows?
