### ISSUE TITLE
Ease of decompilation

### ISSUE THREAD

**Issue by inian** [nexe/nexe#84]
Hi,

I would like to know how easy it is for someone to decompile the binary back into the source files. Is this a secure way of distributing your Node.js code?

Thanks!

**Comment by bayucandra** [comment]
What about this discussion, is that correct: https://reverseengineering.stackexchange.com/questions/23186/how-to-reverse-engineer-an-exe-built-using-nexe ? Not hex editor expert though :)

**Comment by calebboyd** [comment]
Yes, obfuscation of the source code has been a non-goal of this project.
