### ISSUE TITLE
Can not build Node.js v14.15.1

### ISSUE THREAD

**Issue by Ayzrian** [nexe/nexe#840]
**What happened**:
During the build of Node.js it fails to build with following message.
```
 NexeError: vcbuild.bat nosign release x86 exited with code: 1
 at new NexeError (C:\Application\node_modules\nexe\lib\compiler.js:83:28)
at ChildProcess.<anonymous> (C:\Application\node_modules\nexe\lib\compiler.js:274:28)
at Object.onceWrapper (events.js:422:26)
at ChildProcess.emit (events.js:315:20)
at maybeClose (internal/child_process.js:1048:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```
**What you expected to happen**:
It should not fail during the build.
**How to reproduce it (as minimally and precisely as possible)**:
Install all the build dependencies for Node v14.15.1
build Node.js using nexe.
**Anything else we need to know?**:
Building original repo with the same setup works as expected.
**Environment**:
- Platform(OS/Version): Windows
- Host Node Version: 14.15.1 x86
- Target Node Version: 14.15.1 x86
- Nexe version: 3.3.7
- Python Version: 3.7.0

**Comment by wiseguysby** [comment]
In my case, problem solved with :
 
npm install --global --production windows-build-tools node-gyp
PYTHON='C:\\Users\\[YOUR USER]\\.windows-build-tools\\python27\\python.exe'
export PYTHON
npm config set PYTHON

if still problem install visual studio 19/

**Comment by calebboyd** [comment]
Should be fixed with `nexe@next`
