### ISSUE TITLE
Invalid Nexe binary - linux-x64-12.16.2 - pre_execution.js

### ISSUE THREAD

**Issue by arteze** [nexe/nexe#845]
Index.js

```js
console.log("Hola mundo")
```

Nexe command:
```sh
linux-x64-12.16.2 index.js -o executeableFile
```

Error:

```sh
internal/bootstrap/pre_execution.js:83
    throw 'Invalid Nexe binary';
    ^
Invalid Nexe binary
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

**Environment**:

```sh
# uname -a
Linux puppypc6873 5.7.2-lxpup64 #1 SMP Sat Jun 13 11:12:52 BST 2020 x86_64 Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz GenuineIntel GNU/Linux

# node -v
v15.3.0
```

- Nexe version: linux-x64-12.16.2
- Python Version: 2.7.18

**Comment by wiseguysby** [comment]
have u install nexe ? the syntaks should be nexe index.js -o executableFile

**Comment by arteze** [comment]
I have downloaded the release... In x64 I get that error, but in x86 it does not find the executable directly. If I rename linux to nexe, and copy it to `/usr/bin`, I have the same problem.

**Comment by calebboyd** [comment]
Nexe is a package hosted on NPM (npm i nexe@next -g) Please refer to the readme for usage help.

It uses assets hosted in github to operate, but those assets themselves are not the tool
