### ISSUE TITLE
Is there anyway to build up a native module?

### ISSUE THREAD

**Issue by qengineer** [nexe/nexe#846]
I'd like to be able to build a native module like

test.js -> test.node

```
call_native_fnc = () => {
	return "native_str";
};

module.exports = {
	call_native_fnc
};
```

app.js

```
const i = require('test.node');

i.call_native_fnc();
```

**Comment by calebboyd** [comment]
Hmm, what do you mean by test.js -> test.node?

It is currently possible to require any `.node` file that is shipped alongside your binary, built for the version of node you're using.

It is not possible (currently) to include the .node dll embedded alongside the js in a nexe binary.

**Comment by qengineer** [comment]
Thanks for the quick response, but no, I was meaning about to produce a `dll` if you wanna call it like that or a `.node`, through `nexe`. Let's to say I wrote a library in node, and I'd like to distribute it, Can `nexe` produce that library?

**Comment by calebboyd** [comment]
Ahh okay, No - You'll have to use [node-gyp](https://nodejs.org/api/addons.html#addons_building) for that, though you wouldn't be able to do that with js.

**Comment by qengineer** [comment]
Yes, I just need to produce the obj files, so I'd link it with any C/C++ compiler. Pretty bad you can't build directly to machine code objects with just js files.

**Comment by calebboyd** [comment]
Gotcha, Nexe's goal is to include the node runtime with your node application.

There are projects like nectarjs and quickjs who's goal is compiling javascript to machine code. I suggest you take a look at one of those 💯
