### ISSUE TITLE
try to build please help

### ISSUE THREAD

**Issue by mdimranpatel250** [nexe/nexe#847]
python configure exited with code: 9009

**Comment by mdimranpatel250** [comment]
python configure exited with code: 9009
error
 how to solve

**Comment by jaredallard** [comment]
Hi @mdimranpatel250. Can you please edit your message to [follow the issue template you deleted](https://github.com/nexe/nexe/blob/master/.github/ISSUE_TEMPLATE/bug-report.md)? Thank you!

**Comment by Chintan8169** [comment]
How to add multiple resources in form of array???
--resources ['favicon.ico','logo.png','musicPlayer.html','musicPlayer.js','musicPlayer.css','vanilla-tilt.js']
I am doing this but 0 file included is displayed.
nexe server.js --output MusicPlayer.exe --resources ['favicon.ico','logo.png','musicPlayer.html','musicPlayer.js','musicPlayer.css','vanilla-tilt.js']

**Comment by pjalsGit** [comment]
is this just a place where people dump there issues which dont follow templates?

**Comment by calebboyd** [comment]
Closing, no response from the OP
