### ISSUE TITLE
How and where are pre-built binaries generated?

### ISSUE THREAD

**Issue by cspotcode** [nexe/nexe#850]
I see a ton of binaries here: https://github.com/nexe/nexe/releases/tag/v3.3.3

Are they generated via the [Azure Pipelines](https://dev.azure.com/nexe-ci/Nexe/_build/results?buildId=1108&view=logs&jobId=37db2d02-2788-5f6e-3e9e-d0a7f43d4fb8&j=37db2d02-2788-5f6e-3e9e-d0a7f43d4fb8&t=c22303c6-875f-5945-3d9e-f3ce868c97e9)?  Is their generation automated?  Not a bug or feature request; just a question to better understand the project.

**Comment by calebboyd** [comment]
https://github.com/nexe/nexe/blob/cf8e6ff39383535c93c3cb454c4682bcc8628d67/tasks/build.ts#L29

**Comment by cspotcode** [comment]
Ok, thanks, closing as answered.
