### ISSUE TITLE
Get all the code when running strings ./binary

### ISSUE THREAD

**Issue by hatembentayeb** [nexe/nexe#852]
**What happened**:
I want to hide my nodejs code inside my container so i used nexe to build a binary but when i test the binary with 
 i got all the js code, it's much like a single js file without .js extention

**What you expected to happen**:
i expected to not see any js word in the binary, is there any thing i can do with the current version ?
**How to reproduce it (as minimally and precisely as possible)**:
```
strings ./mybinary
```

**Environment**:
- Platform(OS/Version): alpine
- Host Node Version: 12.2.0
- Target Node Version: 12.2.0
- Nexe version: 4.0.0-beta.16
- Python Version: 3.7.8

**Comment by calebboyd** [comment]
Nexe doesn't make an effort to obfuscate your code - If you look closely you'll also find all of the nodejs internals (js) in there too!
