### ISSUE TITLE
[ERR_INTERNAL_ASSERTION] runtime error

### ISSUE THREAD

**Issue by H-s-O** [nexe/nexe#856]
**What happened**:
Building a simple script file results in a runtime error with the built executable.

**What you expected to happen**:
The executable runs correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Create an `index.js` file with contents:
```
console.log("Hello World")
```
Run  `nexe index.js`; outputs:
```
i nexe 3.3.7
√ Already downloaded...
√ Compiling result
√ Entry: 'index.js' written to: test_nexe.exe
√ Finished in 0.32s
```
The build succeeds, but running the executable results in:
```
internal/assert.js:14
    throw new ERR_INTERNAL_ASSERTION(message);
    ^

Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

    at assert (internal/assert.js:14:11)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:129:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'ERR_INTERNAL_ASSERTION'
}
```

**Environment**:
- Platform(OS/Version): Windows 10 (20H2)
- Host Node Version: 12.16.0
- Target Node Version: not specified in build command
- Nexe version: 3.3.7
- Python Version: 2.7.15

**Comment by bruce-one** [comment]
I'd suggest trying the latest beta of Nexe (4.0.0-beta.17) - I can't quite remember but I don't _think_ 12.16.0 is supported by Nexe 3.3.7 (although I haven't tried on Windows (and my memory might be bad))

**Comment by H-s-O** [comment]
I tried with `4.0.0-beta.17` (still with Node 12.16.0) and the result is the same:

```
i nexe 4.0.0-beta.17
√ Downloading...100%
√ Compiling result
√ Entry: 'index.js' written to: test_nexe.exe
√ Finished in 15.032s
```

```
internal/assert.js:14
    throw new ERR_INTERNAL_ASSERTION(message);
    ^

Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

    at assert (internal/assert.js:14:11)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:129:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'ERR_INTERNAL_ASSERTION'
}
```

**Comment by H-s-O** [comment]
Apparently, something was messed up in my shell and/or environment, but it's working now.
