### ISSUE TITLE
Updated nexe v3 Release Assets (to be able to use latest NodeJS versions with apps bundled with nexe)

### ISSUE THREAD

**Issue by ceisele-r** [nexe/nexe#857]
**What would you like to be added**:
The nexe v3 Release assets here https://github.com/nexe/nexe/releases/tag/v3.3.3 seem outdated, e.g. there are no node 12.20.1 versions so these can currently be bundled with nexe.

I've read through https://github.com/nexe/nexe/issues/843 and it reads to me that with v4 there is maybe another approach but for v3, is there any solution/update planned for the provided Node releases?
Or is there any specific reason why newer Node releases are not provided (besides the manual work of copying the images to the v3.3.3 assets)?

**Why is this needed**:
To be able to use updated, secure node versions with applications bundled with nexe, it's important to have the latest node releases available to bundle with nexe.

**Comment by ceisele-r** [comment]
Is there any update on this as there is another batch of security updates for node?
See https://nodejs.org/en/blog/vulnerability/february-2021-security-releases/

**Comment by ceisele-r** [comment]
Unfortunately, again nexe is falling back behind node security releases:
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#2021-08-11-version-14175-fermium-lts-bethgriggs

The last build here is more than half a year old.
Is there any way how we could make more recent (security) releases available?

**Comment by calebboyd** [comment]
Duplicate of #754
