### ISSUE TITLE
[Feature Request] Allow caching node binaries outside of creating a build

### ISSUE THREAD

**Issue by andrewmackrodt** [nexe/nexe#858]
**What would you like to be added**:
I would like to be able to specify a build target(s) via the CLI and have nexe fetch the pre-compiled binaries (or build from source) without having to specify a project to compile.

**Why is this needed**:
This feature would allow for caching the nexe node binary e.g. in a multi-stage docker pipeline. While the pre-built binaries are relatively small, it's possible that github rate limits could be encountered in a CI pipeline. This can be worked around somewhat by downloading the binaries manually ahead of time, e.g. [as in this multi-stage build](https://github.com/andrewmackrodt/ts-express-template/blob/master/Dockerfile#L13) but it would be preferred to not have to hardcode the release URLs.

**Comment by calebboyd** [comment]
You can generate source binaries at the location specified with `-o` in combination with `--no-mangle`

I just added [(diff)](https://github.com/nexe/nexe/commit/9f22309949bf8207cb9e4566f917d5bdd0324a01#diff-041bb58b49fbc5e7fdf9b8d09f0f0ae8d524d727947bcfa3e3d1c91b8a35aeeeR195-R197) the `--asset` flag that will allow you to pass a path.

For example, 

Early on in your build process, or maybe just whenever your node build needs to change

`nexe -i index.js -t 14.7.0 --no-mangle -o ./base-build`

...later

`nexe -a ./base-build -i index.js -o ./my-app`

Note: `--remote` is also an option that can be used to change where builds are retrieved.
It behaves by requesting the asset (https?) from `${remote}/${target}`

**Comment by calebboyd** [comment]
@andrewmackrodt Did you get a chance to try this out?

**Comment by andrewmackrodt** [comment]
@calebboyd thanks for getting back to me. I may not have understood correctly but this looks like I would still need an "app" to compile. Although I could create an empty `index.js` which I hadn't thought of before, so that is a useful workaround.

My use case is to download the desired next node binary as the first stage of a docker multi-stage build; by doing so, the download only happens a single time and is cached for subsequent rebuilds. Currently I am doing this by hardcoding the desired releases download link and placing it in `~/nexe`.

If I were to omit this stage, the node binary would be downloaded (or built from source) every time as docker build is in effect a "clean" filesystem.

**Comment by calebboyd** [comment]
Great! I'm glad you found a solution
