### ISSUE TITLE
spawn make enoent error?

### ISSUE THREAD

**Issue by Fyse** [nexe/nexe#859]
**What happened**:
Trying to compile js and come across error:
✔ Including file: node_modules/uri-js/dist/esnext/schemes/wss.d.ts              ✔ Including file: node_modules/uri-js/dist/esnext/schemes/wss.js                ✔ Including file: node_modules/uri-js/dist/esnext/schemes/wss.js.map            ✔ Included 1730 file(s)                                                         
✔ Downloading Node.jssource from: https://nodejs.org/dist/v14.15.3/node-v14.15.3.tar.gz                                                                         ✔ Already downloaded...                                                         
✔ Compiling result                                                                
Configuring node build: --dest-cpu=x64                                        
INFO: configure completed successfully
✔ Configuring node build: --dest-cpu=x64                                          Compiling Node...                                                             
✔ Compiling Node...                                                             
✔ Finished in 5.71s                                                             
Error: spawn make ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:276:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)

**What you expected to happen**:
exe file output
**How to reproduce it (as minimally and precisely as possible)**:
nexe download.js -r "node_modules/**" -t windows-x64-14.15.3 --ico icon.png --build --verbose
**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version): Ubuntu 20.04
- Host Node Version: 15.5.0
- Target Node Version: 14.15.3
- Nexe version: latest
- Python Version: 2.7

**Comment by koooge** [comment]
Maybe `nexe --build --python=$(which python3)` resolves it. https://github.com/nexe/nexe#compiling-the-nexe-executable

**Comment by Fyse** [comment]
ah thanks, didn't see that
bit late though 😅
