### ISSUE TITLE
When the exe is moved the app does nothing even with the -r tag

### ISSUE THREAD

**Issue by MathiewMay** [nexe/nexe#884]
Simple, i did "nexe index.js --build -r './*'" and the program just closes when started from another location. my app is 2 lines and 1 dependencie so i have no idea why this is not working?

The app:
`var processWindows = require("node-process-windows");
processWindows.focusWindow("Discord");`

it works fine when not moved.

**Comment by MathiewMay** [comment]
> `node-process-windows` is a child process wrapper around a .net executable.
> 
> In order to exec that .net executable it has to be on the filesystem in the spot its expected relative to your built nexe executable.
> 
> eg, here: https://github.com/bryphe/node-process-windows/blob/7dab701fd2bc6032b7862e89f3ca5930a5966371/index.js#L4

I have no idea what that means

**Comment by MathiewMay** [comment]
I see, so i need the node_modules with the nexe output file at all time unless i edit how the depencie works.

**Comment by calebboyd** [comment]
Pretty much, That dependency isn't "bundle-able".
