### ISSUE TITLE
virus total / zyllia reports windows executable as a trojan

### ISSUE THREAD

**Issue by vexorian** [nexe/nexe#886]
This looks like a false positive, but it is affecting both executables built using this executable and the executable provided by nexe itself.

File: https://github.com/nexe/nexe/releases/download/v3.3.3/windows-x64-12.18.2

Virus total report : https://www.virustotal.com/gui/file/8c81215eda812eeed279aed393133cd77e3450741e320ef5abe55d6e6c858922/detection

" I advise that you contact Zillya! Support (https://zillya.com/support) and provide Feedback related to this -- your name, email, telephone, a message about the issue, and upload the most current Windows x64 file version.  It would be good for you to work with them to fix or whitelist this malicious detection related to your product to remove this bad mark from its security reputation. "

**Comment by jaredallard** [comment]
Does this also impact stock node releases?

**Comment by calebboyd** [comment]
@jaredallard It shouldn't because they're signed.

**Comment by vexorian** [comment]
Are there any news regarding this?

**Comment by recontrapablo** [comment]
Happened to me trying to build windows-x64-16.13.1 using node@4.0.0-beta.19. Uploaded it to google drive and while trying to download I got a "your file is malicious" message. I uploaded it to virus total and got the same Zillya report.

**Comment by calebboyd** [comment]
If you're shipping a binary to end users it should be signed first. 

Closing as #945 is a more recent conversation
