### ISSUE TITLE
I Can't use it properly.

### ISSUE THREAD

**Issue by BrownMountain** [nexe/nexe#891]
**When I tried running npm run build it didn't work and gave me this error: "Error: https://github.com/nexe/nexe/releases/download/v3.3.3/windows-x64-16.0.0 is not available, create it using the --build flag

See nexe -h for usage.."**

**I expected it to turn into an executable but instead it gave me this error.**:

- Windows 10 64bit
- Nexe 10.0.0

**Comment by OmgImAlexis** [comment]
What command are you using?

**Comment by davidzwa** [comment]
You seem to be running Node 16 on Windows. This is not going to work as Node 16 is not prebuilt for `nexe`.
Find the list of prebuilt node versions and OS combinations here:
https://github.com/nexe/nexe/releases/tag/v3.3.3

14.15.3 is the latest available (prebuilt for your ease) so the following command should work:
`nexe -t x64-14.15.3 app.js` where you have to replace `app.js` with your entrypoint.

Consider for yourself if you require Node 16 or if Node 14 is good enough. For me it is.

**Comment by calebboyd** [comment]
Duplicate of #754
