### ISSUE TITLE
place native modules within the same app directory?

### ISSUE THREAD

**Issue by crcn** [nexe/nexe#9]
kinda like DLL's

**Comment by unbalanced** [comment]
Bump, as i'm currently looking into nexe, is this solved or planed to be solved?
Many thanks.

**Comment by calebboyd** [comment]
@unbalanced We needed some native modules too --- ended up with our own node build wrapper -- might fit your needs https://github.com/calebboyd/xbin

**Comment by calebboyd** [comment]
see [example](examples/native-build)
