### ISSUE TITLE
error with nexe --build

### ISSUE THREAD

**Issue by henpett1** [nexe/nexe#900]
i have a issue where when i do `nexe --build` i get this error: `Error: vcbuild.bat nosign release x64 exited with code: 1` ive been trying to fix it but nothing ive tried works, ive tried `npm i windows-build-tools -g` but it just gets stuck aswell so im not sure what to do

**Comment by 7Lycolt** [comment]
Please see issue #799 here: https://github.com/nexe/nexe/issues/799

My fix is up there.

**Comment by calebboyd** [comment]
If you're still having issues please add the error information that is show from running nexe with the `--verbose` flag

**Comment by henpett1** [comment]
ive managed to ish resolve it, instead of using the command line utility i just made a js file
