### ISSUE TITLE
Issue with fs.chmodSync and childProcess.execSync functions when used with files in packaged environment

### ISSUE THREAD

**Issue by kamesh95** [nexe/nexe#906]
**What happened**:
1. When I try to modify the permissions of a file that is included in the executable with-r flag, it fails with ENOENT error even though the file is present in there. I have verified that file is present using fs.existsSync and it does return true. With the same path in fs.chmodSync it throws error.
2. Similar thing happens when I try to execute a .bat file that is part of executable, the childProcess.execSync method throws error ENOENT. Verified that the .bat file is present in the expected directory which is passed to childProcess cwd options.

**What you expected to happen**:
1. File Permissions should be modified successfully even if they are part of the executable.
2. Child Process should be executed successfully and returned output should be captured in the variable.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an executable with nexe that contains few files including the main script. In the main script file, write a function to modify permissions of one of the files in executable. Eg:
```
const fse = require("fs-extra");
const path = require("path");

const filePath = path.resolve(path.join(__dirname, "lib/run.sh"));

fse.chmodSync(filePath, "755");
```
Copy the generated .exe file to different directory and run. It will fail with error:
```
...\node_modules\graceful-fs\polyfills.js:254
        if (!chownErOk(er)) throw er
                            ^

Error: ENOENT: no such file or directory, chmod '...\lib\run.sh'
    at Object.chmodSync (fs.js:1115:3)
    at Object.chmodSync (node_modules\graceful-fs\polyfills.js:252:21)
    at Object.<anonymous> (...index.js:6:5)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -4058,
  syscall: 'chmod',
  code: 'ENOENT'
}
```
Command I ran to generate executable - `nexe index.js -o index.exe -a windows-x64-12.11.1 -r "lib/run.sh"`

2. Create an executable with nexe that contains a batch file including the main script. In the main script file, write a function to execute that batch file. Eg:
```
const childProcess = require("child_process");
const path = require("path");

const pmdCommand = "pmd.bat";

childProcess.execSync(pmdCommand, {
    cwd: path.resolve(path.join(__dirname, "lib")),
    stdio: "pipe"
});
```
Copy the generated .exe file to different directory and run. It will fail with following error:
```
child_process.js:660
    throw err;
    ^

Error: spawnSync C:\Windows\system32\cmd.exe ENOENT
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:607:24)
    at Object.execSync (child_process.js:652:15)
    at Object.<anonymous> (...index.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at internal/main/run_main_module.js:17:11 {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawnSync C:\\Windows\\system32\\cmd.exe',
  path: 'C:\\Windows\\system32\\cmd.exe',
  spawnargs: [ '/d', '/s', '/c', '"pmd.bat"' ],
  error: [Circular],
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
```
Command I ran to generate executable - `nexe index.js -o index.exe -a windows-x64-12.11.1 -r "lib/pmd.bat"`

**Environment**:
- Platform(OS/Version): Windows
- Host Node Version: 12
- Target Node Version: 12
- Nexe version: 4.0.0-beta.18

**Comment by calebboyd** [comment]
Hmm.. Bundled resources become readonly files. There is no way to execute or chmod a file that is a part of that bundle. Those methods operate on the actual filesystem, since those files are missing from the filesystem ENOENT is being thrown

**Comment by kamesh95** [comment]
@calebboyd Oh okay, but if someone wants to execute a script via their executable then they can’t bundle it in such use case? Or is there a workaround possible for this? Thanks.

**Comment by calebboyd** [comment]
To execute or modify they'd have to have the file written to the actual file system.
So you could write it out from the executable to a temp directory and execute/modify it from there if you wanted.

**Comment by kamesh95** [comment]
@calebboyd Okay thanks for your inputs. I will close this issue.
