### ISSUE TITLE
Error on to compile node 14

### ISSUE THREAD

**Issue by henriquegmatos** [nexe/nexe#912]
Hello dear. 

I was using nexe with node 10.x.x without problem. Now I need upgrade node to LTS 14.x.x but I got error to compile a simple hello world code. Please see the screenshot.

![72DD86D0-7A0A-4E2C-A434-677D0E6F37FE](https://user-images.githubusercontent.com/57631301/126053653-0dd8e0c7-c471-4410-93f2-35b5c4c8c7ad.jpeg)

best regards

Henrique Matos

**Comment by pjalsGit** [comment]
i think you need python

**Comment by henriquegmatos** [comment]
> i think you need python

Hi. 
Maybe, but I dont think so because it is posible compile just using node version 10.17 in this same computer.

In the screenshotin the orginal post is posible to see nexe compiling using node 10 with no problem, and after when  I change the node version using "nvm use 14" command when I gettig troubble. I guess the python is there to both node version.

best regards.

**Comment by calebboyd** [comment]
If you're still having issues please provide the information from running a build with the `--verbose` flag
