### ISSUE TITLE
Problem when compiling with build

### ISSUE THREAD

**Issue by caiospimentel** [nexe/nexe#915]
Hello!
I'm trying to compile with the following code, in a file called compiler.js:
`const { compile } = require('nexe')

const fileConfig = {
    CompanyName: "Dummy",
    PRODUCTVERSION: "1.0.0.0",
    FILEVERSION: "1.2.3.4"
}

compile({
    input: './run.js',
    rc: fileConfig,
    name: 'test',
    clean: false,
    build: true,
    ico: "./public/favicon.ico",
  }).then(() => {
    console.log('success')
  }).catch(err=>{
    console.log(err)
  })`

And i get the following error:

> 
mycomputerpath>node compiler
i nexe 4.0.0-beta.18
√ Already downloaded...
√ Configuring node build...
√ Finished in 3.648s
Error: python configure.py exited with code: 1
    at ChildProcess.child_process_1.spawn.once.once mycomputerpath\node_modules\nexe\lib\compiler.js:178:28)     
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  
> 

The command I'm using is node compiler
I've tried to reinstall node, install python, install node globally

If I remove build the compilation runs normally, but as I understand, I need it to set the icon and rc. 
How can I solve this?

**Comment by calebboyd** [comment]
If this is still an please comment here and I can reopen, You can try running nexe with the `--verbose` flag set to get a more detailed error
