### ISSUE TITLE
Struggling to include a .py file inside of build to later run it via a child process

### ISSUE THREAD

**Issue by justkamiii** [nexe/nexe#916]
Hello there! I've been struggling to try and include a py file in my nexe build to later be able to run it via a child process shell command. The .py file is on the root of the project, and it's executed on my main .js file by making a child process and running it by making "py package-manager.py". The only issue is, I don't know if this is possible or how. The project I'm worked on is a fork of another project that includes a build.js file on it, which contents are the following:

 ```const { compile } = require("nexe");
const pack = require("./package.json");
const fs = require("fs");
const util = require("./util");
util.mkdir("nexe-conf");
fs.copyFileSync("config/default.json", "nexe-conf/default.json");
["linux", "alphine", "windows"].forEach((os) => {
	["x86", "x64"].forEach((arch) => {
		build(`${os}-${arch}`);
	});
});
build("macos-x64");

function build(platform) {
	compile({
		input: "cli.js",
		resources: ["webserver/index*", "nexe-conf", "node_modules/discord.js/src", "node_modules/particles.js/particles.js", "node_modules/particles.js/demo/js/app.js", "package-manager.py"],
		name: `build/2bored2wait-${platform}-${pack.version}`,
		target: `${platform}-14.15.3`
	});
}
```

I tried including the file in the resources parameter, but it just won't be included and therefore, won't be executed and it will just throw an error on my nodejs terminal saying that the file doesn't exist. How can I possibly achieve this? Thanks

**Comment by calebboyd** [comment]
You'll have to write the py file out to a temporary file in order to have another (child) process access it.
