### ISSUE TITLE
[Question]: Filesystem access

### ISSUE THREAD

**Issue by armenr** [nexe/nexe#917]
Just a quick and direct question -

Is it possible for a nexe-packaged NodeJS app to have access to the "outer" filesystem, on the host where you run the executable?

That is to say - if I wanted to package an app within nexe that can "share" files with the host, in the directory where it runs, would that be possible?

Also - thank you for all of the wonderful work you do! I love this tool. It's helped us simplify a great deal of microservices and deployment architecture/strategy. :)

**Comment by calebboyd** [comment]
Hey @armenr, Generally you can accomplish this by reducing the number of included directories/files. There shouldn't be any issue reading the real fs if the target directory/file names are are not included at build time.

**Comment by armenr** [comment]
@calebboyd - Thanks for the quick reply. When you mention "real fs," do you mean at compile time, or when running the compiled/bundled binary?

That is to say, I want my binary to have access to files on the filesystem where the binary is going to be downloaded and executed.+

Example:

### Binary/NodeJS server
- I build a nexe binary with NodeJS + an express server, named `my_nexe_binary`
- The purpose of this server is to parse CSV files from the host filesystem (not the files that are included at build/compile time) and write new CSVs back to the filesystem, wherever it runs

### Intended use
- I download this nexe-compiled binary
- I take the compiled binary and I move it to `/home/armenr/testApp/my_server_binary`
- In this same directory, I place a new CSV file next to the binary file --> `/home/armenr/testApp/my_test_file.csv`
- I run the binary `./my_server_binary` and it is able to access and read the `my_test_file.csv`

### Objective
- I want the downloaded server executable to read the files in the directory where the binary is being executed, and have access to `my_test_file.csv`
- Server executable can READ `my_test_file.csv` on the host filesystem, in the directory where it runs
- Server executable can WRITE a NEW file called `my_parsed_test_file.csv` into `/home/armenr/testApp/`

**Comment by calebboyd** [comment]
Yep, That should work if you give it a try!
