### ISSUE TITLE
Build with Window 10 21H1 got error.

### ISSUE THREAD

**Issue by tracer8** [nexe/nexe#919]
Hi, 
When build app with Window 10 21H1, i have this error:
Error: https://github.com/nexe/nexe/releases/download/v3.3.3/windows-x64-14.17.4 is not available
Seem Nexe not support Window10 21H1 for now?

**Comment by io-dine** [comment]
Same here

**Comment by wonox** [comment]
It is working:
'nexe -t windows-x64-14.15.3 hoge.js'
I'm see: https://github.com/nexe/nexe/releases/tag/v3.3.3

**Comment by calebboyd** [comment]
Duplicate of #754
