### ISSUE TITLE
how to build an executable with no dependencies on external libraries?

### ISSUE THREAD

**Issue by dtenenba** [nexe/nexe#938]
Hello,

I'm running nexe 4.0.0-beta.19 with node v17.0.1.

Given this code:

```
$ cat index.js
console.log("howdee");
```

and building it as follows:

```
 ./node_modules/nexe/index.js --build
```

I end up with an executable that works on the system where I built it (which is a node docker container). If I then run that executable in a different container (say ubuntu:18.04), I get this:

```
$ ./work2
./work2: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./work2)
./work2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./work2)
./work2: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./work2)
```

Is there a way to avoid that so I end up with a truly portable executable that can be run on any linux x64 system without assuming any libraries are present?

**Comment by bruce-one** [comment]
One option is to build a statically linked executable, e.g.:

```bash
npx --package=node-musl musl-env npx nexe --configure=--fully-static --make=-j9 --build --verbose index.js
````

(`node-musl` is a package that provides a musl toolchain)

The prebuilt `alpine` artefacts are statically linked, afaik

**Comment by donthijackthegit** [comment]
Don't be stupid like me, you have to exclude "node-musl" in your resource, or you will have deserialization issue.
![image](https://user-images.githubusercontent.com/53329142/143469529-cac6b069-64f5-41aa-8f22-d87c1ad88af5.png)

**Comment by donthijackthegit** [comment]
In case anyone who have problem to write the glob pattern
` -r "node_modules/!(node-musl)/**/*"`
