### ISSUE TITLE
Error: vcbuild.bat nosign release x64 exited with code: 1

### ISSUE THREAD

**Issue by Default-01** [nexe/nexe#942]
I get this error when i run nexe --build:

![image](https://user-images.githubusercontent.com/55616945/143258094-c7a213ba-152d-43d6-a932-08f5707bd96d.png)

**Comment by calebboyd** [comment]
Take a look at the [troubleshooting](https://github.com/nexe/nexe#troubleshooting) section of the readme

**Comment by Default-01** [comment]
I can see that the python file path is wrong, how can I change that?

![image](https://user-images.githubusercontent.com/55616945/143266988-969d3347-26bf-4c95-8c20-1ff907ba9f4f.png)

The path should be `C:\Users\jrehm\AppData\Local\Microsoft\WindowsApps\python.exe`
