### ISSUE TITLE
spamming g++ command without compiling

### ISSUE THREAD

**Issue by Stanley-GF** [nexe/nexe#943]
System: Ubuntu (`Linux localhost 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`)
Nexe Version: 4.0.0-beta.19

![image](https://user-images.githubusercontent.com/66573599/143295253-0f854ea4-90c5-4914-8f7f-a80bd2c2c14e.png)

```terminal

creating icu_config.gypi
* Using ICU in deps/icu-small
WARNING: Using floating patch "tools/icu/patches/64/source/common/putil.cpp" from "tools/icu"
WARNING: Using floating patch "tools/icu/patches/64/source/i18n/dtptngen.cpp" from "tools/icu"
creating icu_config.gypi
```

**Comment by calebboyd** [comment]
Sorry, I'd love to help, but there isn't enough information in this issue to do so.
