### ISSUE TITLE
Virus detected on exe startup

### ISSUE THREAD

**Issue by Default-01** [nexe/nexe#945]
When i try to run my exe my windows warns me that the file could damage mu computer. How can i prevent this from showing?

Like can i change the exe file so that other users dont get this warning when they download the exe

**Comment by Stanley-GF** [comment]
You can fix by signing your exe ;)

**Comment by Default-01** [comment]
how can i do that?

**Comment by Default-01** [comment]
Anyone that can help me?

**Comment by nytamin** [comment]
A bit late to the party, but this thread sums it up pretty well: https://stackoverflow.com/questions/252226/signing-a-windows-exe-file

**Comment by calebboyd** [comment]
The base binaries are intentionally unsigned. If shipping an executable to an end user, it will need to be signed to avoid false positives, from the OS or AV software.

**Comment by emcodem** [comment]
Signing exe files can afaik only be done by paying a yearly fee which automatically implies that i cannot distribute free software that is signed. Does nexe really target only to be used in commercial software?
