### ISSUE TITLE
Use native library wrapper

### ISSUE THREAD

**Issue by dj-fiorex** [nexe/nexe#947]
Hello, first of all thanks for your hard work! Very helpfull tool!
In my app i use a library called [systray2](https://www.npmjs.com/package/systray2), it can display a systray icon on every platforms. When i build my simple js file with 
`nexe index.js` and then try to start my app i receive an error: "systray failed to start: spawn C:\Users\carme\Documents\Haptica\Gabaldini\node_modules\systray2\traybin\tray_windows_release.exe ENOENT"
if i undestand correctly the package systray is trying to load a file but of course this file does not exists. i then tried to build with this command:  `nexe index.js -r "node_modules\systray2\traybin\tray_windows_release.exe"` but never changed, same error. Could you help me to find a solution?

Thanks!

**Comment by calebboyd** [comment]
To get an additional binary to work you have to have that additional binary present on the host's file system. So if you've installed your application it might have the following folder structure:

`C:\Users\Me\Program Files\MyApp\app.exe`
`C:\Users\Me\Program Files\MyApp\node_modules\systray2\traybin\tray_windows_release.exe`

You may find that you can use a bundler like [ncc](https://github.com/vercel/webpack-asset-relocator-loader#how-it-works) and relocate those assets to a more ergonomic path.
