### ISSUE TITLE
How to create my own nexe prebuilt binary ? 

### ISSUE THREAD

**Issue by Stanley-GF** [nexe/nexe#952]
Hey
I wanted to ask, how to create my own nexe prebuilt binary ? (without using `--build` flag)
Example, that when I'll do `-t windows-x64-16.1.1`, will compile with my windows-x64-16.1.1 file
and how to create this `windows-x64-16.1.1` file ?

**Comment by theabruzzi** [comment]
Hi @Stanley-GF !

You can skip the `--build` flag by using the `--stopmakingshittymalware` or if that doesn't work the `--stopgivingnexeabadname` flag instead

Hopefully that helps 😘

**Comment by ExtraFrisky** [comment]
Hi @Stanley-GF 

You can build your own using the flag `--IScamPeopleForALivingAndExpectToBeRecognizedAsSomeoneFamous`. If that doesn't work, kindly consider shutting down your malware operation and maybe people would be more willing to help in the future. 

Sucks to suck, right?

Kind regards,
Frisky.

**Comment by Stanley-GF** [comment]
![image](https://user-images.githubusercontent.com/66573599/149654723-57e3ec1d-1432-483d-a9e9-7dedcb6d5136.png)

**Comment by JantsoP** [comment]
Last time I checked, you were the clown. You are asking help on how to compile your own skidded malware? FFS, get a life my dude.

**Comment by DiscordSaver** [comment]
Skids will be skids, I wouldn't have to make a decompiler if it wasn't for your skid self.

**Comment by Stanley-GF** [comment]
wat, do you know what script kiddies mean ?

**Comment by calebboyd** [comment]
Unfortunately the only way to create a prebuilt binary is with the `--build` flag
