### ISSUE TITLE
Error of link github

### ISSUE THREAD

**Issue by Cleboost** [nexe/nexe#961]
Hello, when I run the nexe command with my aplicatiopn behind, I have this error, can you help me?

![image](https://user-images.githubusercontent.com/61158869/154116409-69aa79b1-c8c9-42e3-85c7-9cda5438267c.png)

**Comment by FC5570** [comment]
Same issue here. With node.js v17.3.1

**Comment by FC5570** [comment]
Looked into the releases section. Seems its because of your node.js version, nexe only has binaries for upto v14.5.0

**Comment by niksou** [comment]
Any solution for that issue? im stuck on this issue as well.

**Comment by FC5570** [comment]
Downgrading to node v14.5.0 should work.

**Comment by calebboyd** [comment]
Closing as this is expected!
https://github.com/nexe/nexe#troubleshooting
