### ISSUE TITLE
exe file take long time to start

### ISSUE THREAD

**Issue by hungpham92uns** [nexe/nexe#974]
I only test with an index file with a simple console log.

I run **nexe index.js -t windows-x64-14.15.3** and it complete sucessfully.

But when I run exe file, it take very long time to see the console log (15-20 sec).
With my bigger main project, it's take very long time to show the initial console log (1-2 minutes).

Can someone help me please? Thank you.

Platform(OS/Version): Windows 10 x64
Host Node Version: 10.14.2 / 14.15.3 / 16.14.2
Target Node Version: 10.14.2 / 14.15.3
Nexe version: 4.0.0-beta.19

**Comment by calebboyd** [comment]
I cannot replicate this. Perhaps you have an antivirus software that is sandboxing the executable.

**Comment by WenWu5** [comment]
I am also getting same behavior as OP @hungpham92uns. Any suggestions?

Nexe version: 4.0.0-beta.18
windows-x64-14.15.3
Platform: Windows10 x64
Host Node Version: 16.15.1
Target Node Version: 16.15.1
