### ISSUE TITLE
TypeError: r.replace is not a function

### ISSUE THREAD

**Issue by thecowmilk** [nexe/nexe#978]
I wanted to build a nodejs app into a single file following the command line: `nexe -i app.js -o dist -t node16 --resource` but I got this full error:
```
TypeError: r.replace is not a function
    at C:\Users\thecowmilk\AppData\Roaming\npm\node_modules\nexe\lib\steps\resource.js:25:68
    at Array.map (<anonymous>)
    at Generator.next (<anonymous>)
    at C:\Users\thecowmilk\AppData\Roaming\npm\node_modules\nexe\lib\steps\resource.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\thecowmilk\AppData\Roaming\npm\node_modules\nexe\lib\steps\resource.js:4:12)
    at resource (C:\Users\thecowmilk\AppData\Roaming\npm\node_modules\nexe\lib\steps\resource.js:16:12)
    at Executor.tryInvokeMiddleware (C:\Users\thecowmilk\AppData\Roaming\npm\node_modules\nexe\node_modules\app-builder\lib\cjs\compose.js:21:43)                                                                                                                                           43)
    at C:\Users\thecowmilk\AppData\Roaming\npm\node_modules\nexe\node_modules\app-builder\lib\cjs\compose.js:30:25
```

This error also when trying with `--build` flag:
```
nexe -i bot.js -o dist -t node16 --build
i nexe 4.0.0-beta.19
√ Already downloaded...
√ Compiling Node with arguments: nosign,release,x64
√ Finished in 3.634s

Error: vcbuild.bat nosign release x64 exited with code: 1

See nexe -h for usage..
```
How can I fix this?

**Comment by calebboyd** [comment]
Does providing a valid target solve the issue? See: https://github.com/nexe/nexe#target-string--object

**Comment by thecowmilk** [comment]
@calebboyd yepp, I tried it even with the valid target and I got the same issue all the time.

**Comment by bruce-one** [comment]
It looks like you're missing the second argument for `--resource` -> it needs a resource string to include, e.g. `nexe -i app.js -o dist -t node16 --resource some_resource_file.txt` (or, omit `--resource` if it's no required)

Not sure about the build issue -> perhaps try something like `nexe -i app.js -o dist -t windows-x64-16.14.2 --verbose --build --make 'V=2'` to see if it gives you extra log information?

**Comment by thecowmilk** [comment]
> It looks like you're missing the second argument for `--resource` -> it needs a resource string to include, e.g. `nexe -i app.js -o dist -t node16 --resource some_resource_file.txt` (or, omit `--resource` if it's no required)
> 
> Not sure about the build issue -> perhaps try something like `nexe -i app.js -o dist -t windows-x64-16.14.2 --verbose --build --make 'V=2'` to see if it gives you extra log information?

@bruce-one sure I will recompile today as you suggested and give feedback!

**Comment by grahamgraham** [comment]
@thecowmilk I fixed the `Error: vcbuild.bat nosign release x64 exited with code: 1` by installing NASM. Do you have NASM installed?
