### ISSUE TITLE
Standing behind the ”Compiling Node“ progress after 30 minutes

### ISSUE THREAD

**Issue by rico0808** [nexe/nexe#981]
MacOS：12.2.1
NodeJS：v14.19.1
Nexe：4.0.0-beta.19

```
[~/Desktop/demo/nexe]$ nexe -i index.js --build
ℹ nexe 4.0.0-beta.19
✔ Already downloaded...
⠏ Compiling Node...
```

How to deal with this problem

**Comment by calebboyd** [comment]
You can pass `--make="-j8"`  (where 8 is the number of CPUs you have available)

**Comment by Code2Life** [comment]
Could there be more prebuilt binaries of newer node.js version ? It would be very helpful.
