### ISSUE TITLE
Dynamic value in node file

### ISSUE THREAD

**Issue by FarzadShamriz** [nexe/nexe#982]
Hi, 
I'm running a local server with a specific port in node js and using nexe to compile it as an exe file.
I want to read the port number from a js file. It's working properly in the node js. (It will change the port if I change the js file)
However, if I use the compiled exe file (compiled from the same code) it's not changing the port at all.
Do you have any solution for this issue?

Thank you for your help in advance.

Here is the code in my js file:

```javascript
const httpServer = require("http-server");
const proc = require("child_process");
const porttxt = require('./port.js');
let port = 7711;
 
if (myport != undefined){
    port = myport;
    console.log("Customer specified port "+myport);
}


 
let server = httpServer.createServer({ root: "./", gzip: true, o: "test.htm" });
server.listen(port);
 
var url = 'http://localhost:' + port + '/test.htm';
var start = (process.platform == 'darwin'? 'open': process.platform == 'win32'? 'start': 'xdg-open');
proc.exec(start + ' ' + url);
```

**Comment by FarzadShamriz** [comment]
Can anyone help?
Any solution?

**Comment by calebboyd** [comment]
`port.js` is bundled, it can't be read from the filesystem at runtime. If you want to read a dynamic/ user defined JS file you can use `fs.readFileSync` and either `new Function` or the `vm` module to execute it, Though, I'd explore using a configuration file like an ini or json file (instead of a js file)

**Comment by FarzadShamriz** [comment]
Thank you so much for your help.
