### ISSUE TITLE
Help building windows-x64-18.1.0 - Cherow SyntaxError: Line 279, column 38: Unexpected token '?'

### ISSUE THREAD

**Issue by misterkoko** [nexe/nexe#987]
Hello!

I'm getting the Cherow syntax errors when trying to --build. I saw that Cherow is getting replaced with meriyah but I guess that's not merged with the master branch yet?

Could anyone point me in the right direction as to how to build the latest versions on Windows?

I can succesfully build up to node version 16.9.1, everything above that I get the cherow syntax errors.

I installed all the prerequisites with the automated boxstarter install, my python version is 3.9.5

I'd be really greatful if somebody would point me in the right direction to build 18.1.0.

**Comment by misterkoko** [comment]
Nevermind, already found the solution. I saw that I need to use nexe@next in issue#985, now 18.1.0 builds without a problem. 

It was user error :)

**Comment by amiralam0** [comment]
how did you fixed this issue?
