### ISSUE TITLE
Is there a way to check app version based on package.json

### ISSUE THREAD

**Issue by xiaoweiliu945** [nexe/nexe#989]
I was able to use nexe to build my app into a single execuble.

But how to identify the app version based on it's package.json.

I tried something like: 
```
const version = require('./package.json').version
console.log(version)
```

but it doesn't work since it was a single .exe, unless we release with package.json?

**Comment by serhii-filippov** [comment]
Hi @xiaoweiliu945, you're able to add on 'rc' field to compilerOptions you're passing as an argument to nexe.compile() method.

```
await compile({
...
  rc: {
    ProductVersion: 'any computable string',
    FILEVERSION: 'whatever you need',
  };
})
```

**Comment by calebboyd** [comment]
The `package.json` file is included in the binary. I can't replicate any issues with what you've shared here. Do you have any other information?
