### ISSUE TITLE
spawn python ENOENT

### ISSUE THREAD

**Issue by vinnitu** [nexe/nexe#993]
Hi.

I my ubuntu I have only python3.8 (and don't plan use 2.7 because it doesn't support more).
Can we use python3?

**Comment by calebboyd** [comment]
Yeah, you can use the option `--python=$(which python3)`

**Comment by vinnitu** [comment]
Freezen on Comping Node...

```
$ nexe app.js --build --python=$(which python3)
ℹ nexe 4.0.0-rc.1
✔ Already downloaded...
⠧ Compiling Node...
```

**Comment by calebboyd** [comment]
If its taking a long time (initial build only) you can use more tasks/jobs by passing `--make="-j8"` (where 8 is the number of cpus you have)

**Comment by matt-curtis** [comment]
Dealing with the same situation as @vinnitu, "compiling node" is taking quite some time — it'd be nice if there was some way to know if it's frozen vs. progressing slowly

**Comment by waytoviva** [comment]
> Freezen on Comping Node...
> 
> ```
> $ nexe app.js --build --python=$(which python3)
> ℹ nexe 4.0.0-rc.1
> ✔ Already downloaded...
> ⠧ Compiling Node...
> ```
I got the same resut too

**Comment by bao-io** [comment]
> --make="-j8"

today is 2024-01-05, I got the same resut too

**Comment by bao-io** [comment]
> Freezen on Comping Node...
> 
> ```
> $ nexe app.js --build --python=$(which python3)
> ℹ nexe 4.0.0-rc.1
> ✔ Already downloaded...
> ⠧ Compiling Node...
> ```

today is 2024-01-05, I got the same resut too
