### ISSUE TITLE
Cannot find module ... imported from ... did you mean to import....

### ISSUE THREAD

**Issue by grahamgraham** [nexe/nexe#994]
I am having an issue compiling a very simple app into an exe. 

JS code:

> `import chalk from 'chalk'
> import clipboardy from 'clipboardy'
> 
> const clearConsole = () => {
>     console.clear()
>     console.log('\n\n\n\n')
>     }
> const error = chalk.bold.red    
> const sleep = (waitTimeInMs) => new Promise(resolve => setTimeout(resolve, waitTimeInMs));
> const exitPermission = () => {
>   console.log(chalk.cyan('\n     Press any key to exit \n\n\n'));
>     
>   process.stdin.setRawMode(true);
>   process.stdin.resume();
>   process.stdin.on('data', process.exit.bind(process, 0));
> }
> 
> const cancelCrap = () => {
>   clearConsole()
>   console.log(error('    Please start over'))
>   exitPermission();
>   return false;
> }
>     
> clearConsole()
> 
> 
> var today = new Date();
> var dd = String(today.getDate()).replace('0','')
> var mm = String(today.getMonth() + 1).replace('0',''); //January is 0!
> var yyyy = String(today.getFullYear()).replace('0','');
> let hh = String(today.getHours()).padStart(2, '0');
> let min = String(today.getMinutes()).padEnd(4, '0');
> let timeStr = hh + min
> today = dd+'/'+mm+'/'+yyyy;
> var todayStr = dd+mm+yyyy
> 
> var dayTimes3Plus10 = ((dd*3)+10)
> let masterPass = todayStr+dayTimes3Plus10
> clipboardy.writeSync(masterPass)
> console.log(chalk.green(`\n\n     Today's password is:`))
> console.log(chalk.cyan(`     ${masterPass}`))
> console.log('\n')
> console.log(chalk.yellow('     The password has been saved to your clipboard'))
> console.log('\n\n\n')
> exitPermission()`

When running the exe outside the same folder, I get this error:

> `C:\Users\cgrah\Downloads\PassGen2\PassGen>C:\Users\cgrah\Desktop\passgen.exe
> node:internal/process/esm_loader:94
>     internalBinding('errors').triggerUncaughtException(
>                               ^
> 
> Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\cgrah\Desktop\passgen.js' imported from C:\Users\cgrah\Downloads\PassGen2\PassGen\
> Did you mean to import C:/Users/cgrah/Desktop/passgen.js?
> ←[90m    at new NodeError (node:internal/errors:372:5)←[39m
> ←[90m    at finalizeResolution (node:internal/modules/esm/resolve:404:11)←[39m
> ←[90m    at moduleResolve (node:internal/modules/esm/resolve:963:10)←[39m
> ←[90m    at defaultResolve (node:internal/modules/esm/resolve:1172:11)←[39m
> ←[90m    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)←[39m
> ←[90m    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)←[39m
> ←[90m    at ESMLoader.import (node:internal/modules/esm/loader:380:22)←[39m
> ←[90m    at node:internal/modules/run_main:54:28←[39m
> ←[90m    at loadESM (node:internal/process/esm_loader:88:11)←[39m
> ←[90m    at async handleMainPromise (node:internal/modules/run_main:61:12)←[39m {
>   code: ←[32m'ERR_MODULE_NOT_FOUND'←[39m
> }
> 
> Node.js v17.7.2`

_Originally posted by @grahamgraham in https://github.com/nexe/nexe/issues/920#issuecomment-1145384767_

**Comment by idk-pixel** [comment]
Make sure you have downloaded https://www.nasm.us/pub/nasm/releasebuilds/2.15.04/win64/
Also this does not seem like a JS project. More like TS. Does your package.json file have it as module type?
Also is there a passgen file in there? 
Please provide more detail
