### ISSUE TITLE
Error: make  exited with code : 2

### ISSUE THREAD

**Issue by AnAveragePerson** [nexe/nexe#997]
![Screenshot_20220611_105100.jpg](https://user-images.githubusercontent.com/107243645/173178909-bafe43d8-1de4-491e-87e0-39bd8be34d5a.jpg)

**Comment by calebboyd** [comment]
What's the error if you pass `--verbose`?

**Comment by AnAveragePerson** [comment]
> What's the error if you pass `--verbose`?

![Screenshot_20220611-163443.jpg](https://user-images.githubusercontent.com/107243645/173190165-127e6659-9231-4488-bf01-1ac8b68216ad.jpg)

**Comment by calebboyd** [comment]
There isnt much to go off here since the issue template was removed. I'd start here though as it looks like the missing file is related to ICU support

* [`Intl` (ECMA-402) support](https://github.com/nodejs/node/blob/master/BUILDING.md#intl-ecma-402-support)

**Comment by AnAveragePerson** [comment]
> There isnt much to go off here since the issue template was removed. I'd start here though as it looks like the missing file is related to ICU support
> 
> * [`Intl` (ECMA-402) support](https://github.com/nodejs/node/blob/master/BUILDING.md#intl-ecma-402-support)
> 

![Screenshot_20220612-102704.jpg](https://user-images.githubusercontent.com/107243645/173222310-2bfca277-0b33-4fe3-b089-17f8b62a0075.jpg)
