### ISSUE TITLE
Compiling node takes way too much time

### ISSUE THREAD

**Issue by AnAveragePerson** [nexe/nexe#998]
I tried letting nexe compile my nodejs file into an executable
but for some reason
its taking alot of time to compile node
like
it has been around 2 hours since I let it compile, and its still stuck on compiling node ![Screenshot_20220611-213123.jpg](https://user-images.githubusercontent.com/107243645/173200729-ea0d744f-21d3-4596-9e61-13db14f6c936.jpg)
what's the issue here?

**Comment by h2Entwicklung** [comment]
When I print all logs with --verbose I get a list of hundreds of dependencies. But it is so slow.. I run nexe in a docker environment.
